### ISSUE TITLE
Missing send button labels in campaigns

### ISSUE THREAD

**Issue by Jason-Dang** [salesagility/SuiteCRM#4625] opened 2017-12-05 12:06 UTC
Campaign send button is missing a label and title. 

#### Issue

When a user clicks 'Send Test' or 'Send Emails' in the actions drop-down of a campaign record's detail view, the send button displayed there is missing a label and title. 
#### Expected Behavior

There should be a value and title for the send button.
#### Actual Behavior

There is no value or title for the send button.
#### Possible Fix

Add the following to Email Marketing mod strings:
'LBL_SCHEDULE_BUTTON_LABEL' => 'Send',
'LBL_SCHEDULE_BUTTON_TITLE' => 'Send',

#### Steps to Reproduce

1. Create a campaign or open an existing one.
2. In the detail view click either 'Send Test' or 'Send Emails'.
3. The view you are presented contains a send and cancel button, the send button has no label/value

#### Context

Medium - High priority

#### Your Environment

* SuiteCRM Version used: 7.9.6

**Comment by Mausino** [comment] 2017-12-05 13:28
I think, that is duplicate of issue #4364 and solution you're able to find in this patch

**Closed** 2017-12-07 11:00 UTC
