### ISSUE TITLE
DB error in Activities subpannel

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#7478] opened 2019-06-26 18:18 UTC
I am using SuiteCRM 7.10.17.

https://github.com/salesagility/SuiteCRM/commit/50de8b26b1668909a8721f3677b7bf95b08d03da#diff-8f5a5e8aa91f22a82caa390f4b85f15b changed "date-start" to "date-end". There is no field "date-end" in the table tasks. Displaying i.e. a lead will result in a database error:

...

 AND jt0.deleted=0 JOIN (select DISTINCT email_id from emails_email_addr_rel eear

        join email_addr_bean_rel eabr on eabr.bean_id ='81554f9c-f6f7-aeea-f71e-5cebf8986588' and eabr.bean_module = 'Leads' and
        eabr.email_address_id = eear.email_address_id and eabr.deleted=0
        where eear.deleted=0 and eear.email_id not in
        (select eb.email_id from emails_beans eb where eb.bean_module ='Leads' and eb.bean_id = '81554f9c-f6f7-aeea-f71e-5cebf8986588')
        ) derivedemails on derivedemails.email_id = emails.id  where emails.deleted=0 ) ORDER BY date_entered desc LIMIT 0,100: MySQL error 1054: Unknown column 'tasks.date_end' in 'field list'
Wed Jun 26 19:04:48 2019 [64845][1][FATAL] Exception handling in /var/www/html/include/MVC/Controller/SugarController.php:400
Wed Jun 26 19:04:48 2019 [64845][1][FATAL] Exception in Controller: Datenbank Fehler. Bitte sehen Sie in der Datei suitecrm.log nach.
Wed Jun 26 19:04:48 2019 [64845][1][FATAL] backtrace:
#0 /var/www/html/include/database/DBManager.php(353): sugar_die('Datenbank Fehle...')
#1 /var/www/html/include/database/DBManager.php(328): DBManager->registerError('Error retrievin...', 'Error retrievin...', true)
#2 /var/www/html/include/database/MysqliManager.php(179): DBManager->checkError('Error retrievin...', true)
#3 /var/www/html/include/database/MysqlManager.php(285): MysqliManager->query('(SELECT meeting...', true, 'Error retrievin...')
#4 /var/www/html/data/SugarBean.php(1284): MysqlManager->limitQuery('(SELECT meeting...', 0, 100, true, 'Error retrievin...')
#5 /var/www/html/data/SugarBean.php(1016): SugarBean->process_union_list_query(Object(Lead), '(SELECT meeting...', 0, 100, 100, '', Object(aSubPanel), '( SELECT count(...', Array)
#6 /var/www/html/include/ListView/ListView.php(1141): SugarBean::get_union_related_list(Object(Lead), 'date_entered de...', 'desc', '', 0, -1, 100, '', Object(aSubPanel))
#7 /var/www/html/include/ListView/ListViewSubPanel.php(142): ListView->processUnionBeans(Object(Lead), Object(aSubPanel), 'history_CELL', false)
#8 /var/www/html/include/SubPanel/SubPanel.php(220): ListViewSubPanel->process_dynamic_listview('Leads', Object(Lead), Object(aSubPanel), false)
#9 /var/www/html/include/SubPanel/SubPanelTiles.php(357): SubPanel->ProcessSubPanelListView('include/SubPane...', Array)
#10 /var/www/html/include/MVC/View/SugarView.php(1167): SubPanelTiles->display()
#11 /var/www/html/include/MVC/View/SugarView.php(240): SugarView->_displaySubPanels()
#12 /var/www/html/include/MVC/Controller/SugarController.php(435): SugarView->process()
#13 /var/www/html/include/MVC/Controller/SugarController.php(375): SugarController->processView()
#14 /var/www/html/include/MVC/SugarApplication.php(113): SugarController->execute()
#15 /var/www/html/index.php(52): SugarApplication->execute()
#16 {main}

Please also see https://github.com/salesagility/SuiteCRM/issues/7423; same problem in 7.10.17

**Comment by Dillon-Brown** [comment] 2019-06-28 15:38
Duplicate of #7267.

**Closed by Dillon-Brown** 2019-06-28 15:38 UTC
Labels: Duplicate
