### ISSUE TITLE
Can't use user primary email as main email address  in compose email

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#6812] opened 2019-01-23 13:55 UTC
#### Issue

In user profile i set email account as primary (mikolaj@something.com + set up as default SuiteCRM client. In SMTP setting i set that users can use this SMTP account info@something.com

Now if compose email and FROM dropdown i choose my name where is mikolaj@something.com on send action i got error "Error Sending Email. Please contact your administrator for assistance." but if i choose the system email from SMTP info@something.com, the email was sent without any issue.

Only for sure. If you set up the SMTP and allow user to sent emails from this you will see in compose email in row FROM the dropdwon with 2 email options.... with your primary email of your user account and SMTP default email account. Before upgrade to 7.11 both worked.. now only default SMTP.

#### Actual Behavior

If i want send email as mikolaj@something.com i must create personal emial account. Can't use primary setted email address in user settings.

#### Your Environment

* SuiteCRM Version used: 7.11
* Browser name and version Chrome 71.x
* Environment name and version PHP 7.3, MySQL 5.6

**Comment by pstevens71** [comment] 2019-07-03 18:27
This is a duplicate of this one (I'm pretty sure).

[https://github.com/salesagility/SuiteCRM/issues/7407](url)

**Closed** 2019-07-04 11:12 UTC
Labels: Duplicate

**Comment by Dillon-Brown** [comment] 2019-07-04 12:12
Fix here: #7518
