### ISSUE TITLE
Role Management - Header change doesn't update entire column

### ISSUE THREAD

**Issue by michelhcote** [salesagility/SuiteCRM#6778] opened 2019-01-17 19:02 UTC
#### Issue
When changing the header of a column in Role Management , the entire column is not updated

#### Expected Behavior
Entire culomn should be updated with the value entered in the header of the column

#### Actual Behavior
Nothing is updated in the column

#### Steps to Reproduce
1. Select value in header
2. change column
3. save
4. Data is not updated

#### Your Environment

* SuiteCRM Version used: Version 7.10.12
Sugar Version 6.5.25 (Build 344)
* Browser name and version  Chrome 
* Environment name and version MySQL: 10.2.19-MariaDB-cll-lve
* Operating System and version :

**Comment by pgorod** [comment] 2019-01-22 11:19
I can reproduce this in 7.11. I am not sure if the changes are not being made, or simply if they are not updated on screen. Because, after you change the header to `owner`, for example, apparently nothing happens, but then if you then click on one of the items in that column, you see it shows `owner`.

There were recent commits around this part of the code

https://github.com/salesagility/SuiteCRM/commit/684c08419ab71500868d0f53af79e2c407ae9690#diff-87bfc2fbbed017ab9b98568a2ae08001

https://github.com/salesagility/SuiteCRM/commit/b4d3b23f011d076007bc7791a9a4df10feee29dd#diff-87bfc2fbbed017ab9b98568a2ae08001

**Comment by pgorod** [comment] 2019-02-11 17:39
There is a proposed fix in a duplicate of this, #6928

**Closed** 2019-02-20 16:50 UTC
Labels: Fix Proposed, Medium Priority, Resolved: Next Release, bug
