### ISSUE TITLE
Issue with Date fields and Inline Edit

### ISSUE THREAD

**Issue by Polareious** [salesagility/SuiteCRM#2110] opened 2016-09-01 22:13 UTC
#### Issue
When you edit any date field with the inline editing it defaults the date immediately to todays date, then when you save any changes it changes the format to YYYY-MM-DD, instead of the default mm/dd/yyyy

#### Expected Behavior
When you double click to edit, the date should remain as whatever value is already in that field.  Once saved, it should stay the same format MM/DD/YYYY.

#### Actual Behavior
When you inline edit, it sets todays date (regardless of what is in the field), then when you save it changes the format to YYYY-MM-DD

#### Steps to Reproduce

1. Double click a date field

#### Context
This is an annoyance to many clients I have currently using the SuiteCRM, I have seen this issue in all of V7, including 7.7.4

#### Your Environment

* SuiteCRM Version used: 7.7.1,7.7.3,7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):chrome and firefox
* Environment name and version (e.g. MySQL, PHP 7): mariadb, php 5
* Operating System and version (e.g Ubuntu 16.04): opensuse 13.1

**Comment by ijdavie** [comment] 2016-09-02 13:13
HI @Polareious, 

This appears to be a duplicate of #1042

**Closed by ijdavie** 2016-09-02 13:13 UTC

**Comment by rholighaus** [comment] 2016-12-08 16:03
Not a duplicate of #1042 in my opinion - and still not fixed in Version 7.7.8.
Still resets the date to today's date when trying to inline edit - at least with German date format in use (dd.mm.yy)

**Comment by Szellszi** [comment] 2016-12-14 16:40
Hey,

added a fix for the issue I've created for @rholighaus
