### ISSUE TITLE
Emails behavior

### ISSUE THREAD

**Issue by fcorluka** [salesagility/SuiteCRM#6436] opened 2018-10-19 14:55 UTC
This is a merge of all issues (emails related) I have seen on GitHub because I have seen it all in last week of my own implementation.

A simple task I cannot do is: Implement support center for my company
Support center requires:
3 inbound mail accounts - 2 of them have auto import, auto case creation, auto mail response to sender, 3rd have only auto import
2 security groups for assigning emails and cases, but not restrict each other to view emails and cases

#### Issue
I have been trying for past week to implement this, on several CRM instances, with several emails and no luck.

All issues I have seen:
1. Set up INBOUND GROUP mail, checked create cases, but cases are not created (another try with setting INBOUND MAILS cases are created ?!?!)
2. Set up  INBOUND GROUP reply from address is never seen in emails, always system outbound email
3. Email to the sender for creating case 'New Case Auto-Reply Template' is not sent, if sent it is 3 days after for 1% of the case created
4. Emails in list view are not shown, something must be select in search to show
5. On some occasions system won't read from IMAP, no mail at all
6. In Email I have 40 emails, 20 are on one page, but I can not select another page. Also, Order by any column is not working.
7. When I have a case created I (administrator) got an email that case is updated, but nothing is saved in CaseUpdates ?! On some occasions, I would get my email body written in Description and CaseUpdates.
8. When I try to reply from Cases->History email, select another outgoing mail account, but received mail has the system setting FROM ADDRESS???? Also user is ROOT in that mail.
9. I sign in as another user (not admin) and can not see any email, and can not reply to emails in Cases.

#### Expected Behavior
Everythis should work out of the box.

#### Actual Behavior
Nothing works as expected. Also error are not reproducable, bceause when I delet inbound mail account and create new, beahvior is changed and I have different problems.

#### Steps to Reproduce

1.Create 2 inbound mail adresse with apropriate fields populated.
2.Try to import and create Cases
3.Try to view mails and manipulate with responses to sender and answer to CRM
4.

#### Context
Email module with all connected modules and actions needs an overhaul.

#### Your Environment

* SuiteCRM Version used: 7.10.7, 7.10.9, 7.8.22
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox, Chrome
* Environment name and version (e.g. MySQL, PHP 7):7.2
* Operating System and version (e.g Ubuntu 16.04):Ubuntu 16.04

**Comment by labcerouno** [comment] 2018-10-22 14:41
Thank you @fcorluka for your report. In my opinion, your message would be better placed in the forums (https://suitecrm.com/suitecrm/forum). It's great to have contributions, but the goal of GitHub is to serialize each issue for better resolution. 

It works like these: the unique issue is discussed, one or more fixes are proposed, tests are made and labels are placed to identify if the issue is solved or not. According to this information, it is possible to select which issues are solved for the next release. That's the way GitHub works. If we have many issues inside the same post, it is impossible to follow this workflow.

I'm sure the community appreciates very much your contribution, as I do, while we invite you to file each issue in a separated report, so we can solve, place labels and set the corrections for the next versions. I have done the same as you before and now I'm creating separated issues.

Thank you. Best regards

**Comment by fcorluka** [comment] 2018-10-23 09:11
Hi @labcerouno,

I agree with you about organizing this 'text' into issues, but I have so many issues that are closely related, and pardon me, I have been very frustrated with this not working so I just gathered all in one place.

When this is solved I will be glad to close issue, or if someone thinks that is not appropriate, then close it now.

* Just to add something to the list, I have 2 inbound accounts that are INACTIVE, but mails are imported.

**Comment by Dillon-Brown** [comment] 2018-10-25 09:44
Issue 1. and 7. should now be resolved. I'll take a look at the rest and update here with what I can replicate.

**Comment by Mausino** [comment] 2019-09-02 13:04
@fcorluka hi, should you evaluate your ticket and write here which points are still the issues ? It was done many updates with pressure on emails

**Comment by fcorluka** [comment] 2019-09-02 13:29
Hi @Mausino,

thank you for your question. I am right now in the process of upgrading the same CRM system upon which this issue was created and I can tell that in version 7.10.19 all of these items except one are solved.

I have problem with auto-import and auto-create Case (regardless of the fix #6866).

**Comment by Mausino** [comment] 2019-09-02 13:36
@fcorluka i am suggesting you to close the issue and create new one.. which will describing only issue with auto import and will fine if will added to current sprint #7717

**Closed** 2019-09-02 13:41 UTC
Labels: Bug, Emails, Medium Priority
