### ISSUE TITLE
Notifications list (bell) not populating even though popups are working (SuiteCRM 7.9.8)

### ISSUE THREAD

**Issue by Andrew640** [salesagility/SuiteCRM#4832] opened 2018-01-03 13:40 UTC
#### Issue
Cron and pop up notifications are working but haven't been able to get the bell list or number to populate.

#### Expected Behaviour
The list should display notifications and the number over the icon should increase

#### Actual Behavior
A browser pop up appears. Nothing shows on the bell icon / in that list.

#### Steps to Reproduce
1. Installed SuiteCRM 7.9.8 from scratch on MAMP without adjusting any settings / options (everything in default)
2. Enable desktop notifications for administrator user
3. Log a call with a reminder set to demonstrate issue

Thread for this issue: https://suitecrm.com/forum/feedback/8309-suitecrm-notifications-alerts-not-working-on-out-of-the-box-installation#57608

#### Context
Inconvenient but not major issue. Email alerts work and pop-ups work but is useful to see a list of notifications.

#### Your Environment
* SuiteCRM Version used: 7.9.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Tested in Chrome, Safari, Firefox on Mac and Edge on Windows
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6.35, PHP 7.1.8
* Operating System and version (e.g Ubuntu 16.04): Mac OS 10.13.2

**Comment by PedroErnst** [comment] 2018-01-03 16:18
Thanks for raising the issue. I've looked into this and fixed some scenarios in which alerts were not shown.

I'm not yet 100% that this will fix your issue, please let us know if the problem persists.

**Comment by Andrew640** [comment] 2018-01-03 17:21
Problem still there unfortunately. I assume this should populate the alerts table? This doesn't seem to happen at the moment.

Just tried it on the live demo and couldn't seem to get it working there either:
![screen shot 2018-01-03 at 17 19 17](https://user-images.githubusercontent.com/6224792/34531535-8412cc54-f0aa-11e7-9aa1-8af0352f2cf5.png)

**Comment by PedroErnst** [comment] 2018-01-04 09:31
The fix is not yet merged, so you won't see changes unless you applied them directly into your installation.

Same for the live demo.

**Comment by Andrew640** [comment] 2018-01-04 09:33
Sorry, should have said I applied the changes directly. And oh yes, of course.

**Comment by PedroErnst** [comment] 2018-01-04 09:55
Ok in that case this needs some more work.

**Comment by PedroErnst** [comment] 2018-01-04 12:02
I maybe need your help here @Andrew640 

On my system the alerts seem to work fine. 

Maybe it has something to do with our environments being different, or maybe you followed slightly different steps than I did. 

First I logged a phone call, with a reminder, to happen in the next 15 minutes

![screenshot from 2018-01-04 11-21-09](https://user-images.githubusercontent.com/34056696/34561763-778bd324-f143-11e7-89a1-1999951b147a.png)

Then I verified through the JS console that the reminder existed and the countdown was running.

![screenshot from 2018-01-04 11-21-53](https://user-images.githubusercontent.com/34056696/34561837-c56c7120-f143-11e7-8a7e-8ac1220d0640.png)

![screenshot from 2018-01-04 11-38-36](https://user-images.githubusercontent.com/34056696/34561857-d50f22e4-f143-11e7-9a58-0d765ce67d01.png)

Upon reaching the time of the call, the popup displayed, and shortly after the bell icon updated. (But if you close the browser window )

![screenshot from 2018-01-04 11-32-36](https://user-images.githubusercontent.com/34056696/34561893-e9cb55cc-f143-11e7-91a3-ec1a89a222ff.png)

![screenshot from 2018-01-04 11-33-51](https://user-images.githubusercontent.com/34056696/34561897-f07d1b76-f143-11e7-9179-f6c0092226b3.png)

And when checking the DB, the alert was in the table

![screenshot from 2018-01-04 11-34-12](https://user-images.githubusercontent.com/34056696/34561917-fe2888a0-f143-11e7-83ac-e1f490aa4e77.png)

The is a few cases in which no alert will be created, for example if the user closes the browser window the DB entry will never be created. But in your case since you can see the Notification Popup, the alert should be there too.

If you could let me know if your steps are the same, and what your outcome is that would be a great help in determining where the issue is now.

**Comment by Andrew640** [comment] 2018-01-04 16:09
Sorry for delay - lots to do with our implementation atm.

That's the same process I follow.. Also get those same console outputs but no alerts.

Downloaded your fork and set that up from scratch too but still the same outcome.

**Comment by Andrew640** [comment] 2018-01-04 16:16
Ah, but there's nothing in the alerts table.

**Comment by PedroErnst** [comment] 2018-01-04 16:31
The notification has an .onclose event handler attached that should send off the ajax request to create the alert in the database.

This handler could be causing the issue, and I don't think it makes much sense in the first place, so I've removed this now.

**Comment by Andrew640** [comment] 2018-01-04 17:07
Applied the changes but still no alerts in the table.

Could there be anything my side which prevents the Ajax request?

**Comment by PedroErnst** [comment] 2018-01-04 17:13
Did you rebuild the JS files and cleared your browser cache?

![screenshot from 2018-01-04 17-12-03](https://user-images.githubusercontent.com/34056696/34575366-6a9a2cfe-f172-11e7-97d1-4d220dd62971.png)

I don't know, in general I'd say no but it can't hurt to check your JS console and the SuiteCRM error logs just in came.

**Comment by Andrew640** [comment] 2018-01-04 17:21
I hadn't but just tried now and still nothing in the table.

Now secondsSinceLoad always seems to be 0.

Also, no new logs either

**Comment by PedroErnst** [comment] 2018-01-05 08:55
Ok thanks for the feedback. We'll get some more people to test it to see if we can pin down this bug.

It's ok that secondsSinceLoad now always shows 0, I've changed the way the script tracks time, it should be more accurate now.

**Comment by Andrew640** [comment] 2018-01-05 09:27
Not quite sure why this is but when I logged in this morning, there was a notification for the last call I scheduled yesterday! I tested it again and it seems to work now

Alerts are also now in the table.

Thanks so much for your help!

**Comment by PedroErnst** [comment] 2018-01-05 10:45
That's great news!

**Closed** 2018-01-11 22:36 UTC
Labels: Fix Proposed, Medium Priority, Resolved: Next Release, bug
