### ISSUE TITLE
Function getRelatedId cannot return NULL value

### ISSUE THREAD

**Issue by JackBuchanan** [salesagility/SuiteCRM#10107] opened 2023-07-05 13:14 UTC
#### Issue
function getRelatedId in lib/Search/SearchResults.php in unable to return null value due to return types

If function is unable to retrieve related ID then null is returned, but function return type prevent this from happening

#### Expected Behavior
Function should be allowed to return a NULL value

#### Actual Behavior
A 500 error is returned

#### Possible Fix
Allow function to return NULL values

#### Steps to Reproduce

1. See line 223 where $relId is set to NULL
2. See line 208 where the only allowed return type is string

Issue occurs when searching, see error: SuiteCRM\Search\SearchResults::getRelatedId(): Return value must be of type string, null returned

#### Context
Issue occurs when using basic search

#### Your Environment

* SuiteCRM Version used: 7.13.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest 
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.0
* Operating System and version (e.g Ubuntu 16.04): 18.04

**Comment by johnM2401** [comment] 2023-07-07 14:01
Hey!
Thanks for raising this

For reference, looks like this may be a duplicate of: https://github.com/salesagility/SuiteCRM/issues/9516
(please feel free correct me if not)

Thanks again!

**Closed** 2023-08-29 11:09 UTC
Labels: Type:Bug, Status:Fix Proposed, Type:Duplicate, Priority:Important, Area: PHP8
