### ISSUE TITLE
data/Link2.php missing from 7.8.1 upgrade patch

### ISSUE THREAD

**Issue by nelem** [salesagility/SuiteCRM#3077] opened 2017-02-09 18:16 UTC
#### Issue
data/Link2.php missing from distribution

View Summary on the Activities History should summarise the closed calls, emails & tasks but pops up an empty window.

#### Expected Behaviour
View Summary on the Activities History show summarise the closed calls, emails & tasks.

#### Actual Behaviour
Popup window is empty. 

Log says: Fatal error:  Call to undefined method Link2::getRelatedTableName() in /var/www/XXX/modules/Activities/Popup_picker.php on line 119,

#### Possible Fix

Copy Link2.php from ./upload/upgrades/patch/SuiteCRM-Upgrade-7.6.x-to-7.8.1-restore/data/Link2.php

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.8.1 upgraded from 7.6.x
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50.0.1
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by mattlorimer** [comment] 2017-02-09 22:42
duplicate of #3079

**Closed by mattlorimer** 2017-02-09 22:42 UTC
Labels: duplicate
