### ISSUE TITLE
SMTP Error:connect() failed. github.com/PHPMailer/PHPMailer​/wiki/Troubleshooting

### ISSUE THREAD

**Issue by opensourcecrm** [salesagility/SuiteCRM#1788] opened 2016-07-26 15:28 UTC
Hi Everyone,

I observed many posts are created with the same issue (SMTP email outbound configuration issue (Error:SMTP connect() failed. github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) irrespective of the version it was reporting) and there are few suggestions too which we already tried but there is no success with the suggested fixes. In fact there are many people are facing a major hurdle. because every thing was blocked. no one are getting any email notification. if any one can concentrate on this major bug and could try to resolve this issue then it would be very great full 

#### Context
We are not able to configure the outbond email handler it is affecting our day to day activity our users are not getting the required notification from the system which they need to get it. 

And it is very important so we consider this issue as HIGH priority

#### Your Environment

* SuiteCRM Version used: Version 7.6.3 
* Environment name and version (MySQL, PHP 5.5.9):
* Operating System and version (Ubuntu 14.04):

**Comment by willrennie** [comment] 2016-07-28 15:40
Duplicate of #1123

**Closed by willrennie** 2016-07-28 15:40 UTC
