### ISSUE TITLE
Report from multiselect field >>> incomplete results

### ISSUE THREAD

**Issue by jtsoukaris** [salesagility/SuiteCRM#4262] opened 2017-09-15 12:35 UTC
#### Issue

Hello everyone,

The case: Our company offers some training events to our partners. We have a custom multi-select field in Contacts module were we log which training events each partner has attended to.

Now, let's say I want to create a report that retrieves the partners that attended a specific event. Just three fields as columns for the report: First Name, Last Name and Events/ Trainings Attended (that how we call the multi-select field).  One condition only, for the Events/ Trainings Attended field: we want only the partners that attended that event (i.e. only one value is selected from the multi-select field).

If the Contact has attended that event only, the report will include him in the results. But if he has attended that event and any other event (i.e. two or more values from the multi-select field are selected), he isn't included in the results. 

#### Expected Behavior

The Contact should be included in the results because he satisfies the condition regardless if other values are selected for that field in the multi-select field.

#### Actual Behavior

Please see above description. Please also let me know which part of the suitecrm.log file you need me to submit (I apologise in advance, I am not a developer).

#### Possible Fix

I think that you should modify the query that retrieves the results for the report.

#### Steps to Reproduce

1. Create a Report. Select some fields as columns and include a (custom) multi-select field.
2. One condition. Return results for contacts that have a specific value selected from the multi-select field.
3. Have some Contacts that have only that particular value from the multi-select field selected and some other Contacts that have this value select along with one or more other values from the field.
3. Save/ generate the report, check the results.

#### Context

It is important in the sense there should no doubts about the trustworthiness of the reporting. No one is going to trust a system for decision making if he/ she cannot trust the data it is reporting.

#### Your Environment

SuiteCRM 7.9.5 but the issue was present in version 7.9.4
Plesk 12.5
Apache 2.4.6
PHP version 5.6.31
MySQL version 5.5.56

Thank you very much in advance.
John Tsoukaris

**Comment by Dillon-Brown** [comment] 2017-09-15 18:18
Hi @jtsoukaris, I believe this is a duplicate of #4084. The above description appears to be correct, I would expect a report using the "Equal To" operator, along with a multi-select, to only return "Exact" matches. The operator that would fulfil the example above would be "Contains".

**Closed by Dillon-Brown** 2017-09-15 18:18 UTC
Labels: duplicate
