### ISSUE TITLE
Cannot duplicate projects

### ISSUE THREAD

**Issue by blloyd78** [salesagility/SuiteCRM#2222] opened 2016-09-14 11:40 UTC
#### Issue
Trying to duplicate an existing Project using the 'Actions' drop down fails

#### Expected Behavior
Clicking the 'Duplicate' option on a Project should create a new project pre-populated with the details from  the parent record, and offer the opportunity to edit those details before saving to create a new record.

#### Actual Behavior
Nothing happens. The system simply reloads a blank screen. No record is created in the MySQL database either

#### Possible Fix
None

#### Steps to Reproduce

1. Select an existing Project
2. Click the Actions button at the top of the screen and select Duplicate
3.
4.

#### Context
For basic projects, this issue presents few serious problems. For complicated projects with lots of different milestones etc, this could be a serious problem.

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari 10.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by mattlorimer** [comment] 2016-09-14 11:42
duplicate of #2154

**Closed by mattlorimer** 2016-09-14 11:42 UTC
Labels: duplicate
