### ISSUE TITLE
Add Tab on home screen not working with Firefox

### ISSUE THREAD

**Issue by mugge6** [salesagility/SuiteCRM#4272] opened 2017-09-18 11:31 UTC
#### Issue
If I try to a add a new tab on home screen with Firefox everything is wroking. I can add a name and select the number of columns. But as soon as I click on Add , the page will be reloaded and the new tap will be not saved. It's working fine within Chrome and IE,

#### Expected Behavior
After clicking Add the new Tab should be added as a new Tab after reloading the home page.

#### Actual Behavior
Tab will be not added. Debugging shows that the POST request will never fired to the backend before the home page gets reloaded. Thee is no JS error displayed.

#### Possible Fix
On file /themes/SuiteP/include/MySugar/javascript/retrievePage.js (Line 55 and 56):

Instead of 
`$.post($('#addpageform').attr('action'), { dashName: $('#dashName').val(), numColumns: $('[name=numColumns] option:selected').val() } );
location.reload();`

use the following code
`$.post($('#addpageform').attr('action'), { dashName: $('#dashName').val(), numColumns: $('[name=numColumns] option:selected').val() } ).then(function() {
        location.reload();
      });`

#### Steps to Reproduce
* Login to SuiteCRM
* Go to "Actions" -> "Add Tab"
* Add new name and select 1 as number of columns
* Click "Add"
* Page will be reloaded but tab is not added

#### Context
It's important that this function is working as well on Firefox

#### Your Environment
* SuiteCRM Version used: 7.9.5
* Browser name and version Firefox: 55.0.3 (64-Bit)
* Environment name and version: MYSQL, PHP-FPM  7.1.1
* Operating System and version: Ubuntu
* Latest SecuritySuite version is installed

**Comment by Dillon-Brown** [comment] 2017-09-18 13:35
Duplicate of #4157

**Closed by Dillon-Brown** 2017-09-18 13:35 UTC
Labels: duplicate

**Comment by Abuelodelanada** [comment] 2017-11-06 21:12
Hi, 
Please @Dillon-Brown may you verify this PR? It's s very simple fix for an annoying behaviour

**Comment by Dillon-Brown** [comment] 2017-11-07 10:04
Hi @Abuelodelanada thanks for the PR. I'll try and get this looked at today :).
