### ISSUE TITLE
In module builder create new module type label issue

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#4313] opened 2017-09-26 13:43 UTC
#### Issue

When i create module from module builder, names of module types are different than original.
![screenshot_1](https://user-images.githubusercontent.com/22373035/30863398-9efca5a4-a2d9-11e7-91f2-1ae68542fe05.png)

#### Steps to Reproduce

1. Open Admin page
2. Select module builder
3. Create module
4.  Create new module
5. See name of module types.

#### Your Environment

* SuiteCRM Version used: 7.9.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 55.0.2
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Dillon-Brown** [comment] 2017-09-26 13:49
Hi @dursuntosun, this has been fixed by #4255. Closing this as a duplicate of #4291.

**Closed by Dillon-Brown** 2017-09-26 13:49 UTC
Labels: duplicate
