### ISSUE TITLE
email contact search issue

### ISSUE THREAD

**Issue by centoasa** [salesagility/SuiteCRM#4437] opened 2017-10-23 04:19 UTC
Also in 7.9.7
Please follow this thread: https://suitecrm.com/forum/suitecrm-7-0-discussion/16248-email-contact-search-issue
In short words: when I try to send new email, search a contact (or account) by related button, popup appear. If I try to search a contact, just press the search button, other popup show me with "invalid email" the search makes me see the contact sought, but I can not add it.

**Comment by pgorod** [comment] 2017-10-23 09:09
I confirm this bug is happening on 7.9.7.

@centoasa the maintainers of this project really appreciate if people fill out the entire Issue template. I know it's big and boring, but if you need to manage 600 Issues the level of detail really makes a difference...

**Comment by Dillon-Brown** [comment] 2017-10-23 10:37
Looks like this is a duplicate of #3733. There is a fix here: #4098 but it i'll need to go back and add in some changes.

**Closed by Dillon-Brown** 2017-10-23 10:37 UTC
Labels: duplicate

**Comment by pgorod** [comment] 2017-10-23 16:38
I love it when I am involved in troubleshooting and reporting a duplicate of an Issue reported by ME a few months ago... these memory leaks... :-)

**Comment by 9480045403** [comment] 2017-11-16 17:44
Issue is not resolved even in suitecrm 7.9.7
