### ISSUE TITLE
Custom admin user name

### ISSUE THREAD

**Issue by celsocos** [salesagility/SuiteCRM#1185] opened 2016-03-30 23:38 UTC
Installing ans testing SuiteCRM 7.6 Beta 1
Using: PHP 5.6.18; Linux CentOS 7; Apache 2.4.18; Mysql 5.5.48, Browser Chrome; Version 49.0.2623

After installing the SuiteCRM with database admin user, I found the initial login screen. Very nice, I typed Webmaster (and I selected in the install process) and password, no way to login.

I found looking directly in the database the admin user was not changed to Webmaster, and once I typed Admin, login successfull.

I deleted everything and tested with a different admin user name, with the sabe result. Maybe this is not so hard to fix. I believe the custom user name select during istall is not being used. I can also reproduce the problem, so I believe this is not a false alarm.

Thank you all for the good work.

**Comment by vladbar** [comment] 2016-04-25 15:06
Hello celsocos , 
thank you for reporting this bug. I also noticed that there was a problem with initial login about month ago. It appears to be fixed now - I am able to login with my new username.  
This is valid for suitecrm_version.php :
$suitecrm_version      = '7.6rc';
$suitecrm_timestamp    = '2016-04-19 17:00';

**Comment by ijdavie** [comment] 2016-09-19 10:55
This appears to be a duplicate of issue #873, I will close this issue.

**Closed by ijdavie** 2016-09-19 10:55 UTC
Labels: bug, duplicate
