### ISSUE TITLE
Module Project - Advanced Search problem, select not working,components are offset

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#1967] opened 2016-08-17 07:21 UTC
#### Issue
Start Date Select not working, components are offset.

#### Expected Behavior
It should work as End Date select.

#### Actual Behavior
Start Date Select not working, components are offset.

#### Steps to Reproduce
Just click advanced search.

#### Context
high

#### Your Environment

* SuiteCRM Version used: 7.7.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 52.0.2743.116 m, Mozilla
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Win10
![ad_se](https://cloud.githubusercontent.com/assets/21075768/17727801/eabac68c-645b-11e6-837c-8255c8b1686b.jpg)

**Comment by ijdavie** [comment] 2016-08-17 08:29
This appears to be a duplicate of #1940

**Closed by ijdavie** 2016-08-17 08:29 UTC
Labels: bug, duplicate
