### ISSUE TITLE
No outbound accounts shown in "From" dropdown with group inbound email

### ISSUE THREAD

**Issue by Dillon-Brown** [salesagility/SuiteCRM#4111] opened 2017-08-14 10:35 UTC
#### Issue

1. Configure system outbound email account, in my case Gmail. Click the checkbox to `allow users to use this account`.
2. Send test email (works well)
3. Configure a group inbound email account
4. Go to `Emails` module
5. Click `Compose`. Note that there is nothing in the `From` dropdown box.

#### Expected Behavior

"From" field should populate with system outbound email

#### Actual Behavior

Field is empty

#### Context

High priority

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by stancel** [comment] 2017-08-27 16:29
Hi @Dillon-Brown. I have recently setup SuiteCRM 7.9.4 for my company and this bug was frustrating me so I got an understanding of the architecture yesterday and debugged through the issue. I was planning to patch our system and also create a pull request that can be merged back in, but have more of a functional / roadmap question before I do as that will determine what code is put into the patch.

The main question is whether an outbound email account should show in this dropdown list or whether a list of inbound email accounts should show and be used? All of the code around this now currently looks for inbound email accounts. I can somewhat see the logic in showing inbound as maybe the original creators were thinking that whoever you were sending this outbound email to would reply, and that is why the inbound email accounts would be listed there. However, my first thought would be to show the outbound email accounts (since you're actually sending an email out of the system). I have seen some other people comment in related issues and say that they only care about the outbound email accounts (and don't want people to reply to the emails coming from those accounts).

It looks like you are an active contributor here and I am wondering if you could help clarify whether this functionality should actually be listing inbound or outbound email accounts when sending these emails? I would obviously just create a pull request for outbound, but all of the code (numerous methods) are looking for inbound related email accounts. When seeing that I did not know if there was some reason they did that or if that was done intentionally for some longer term vision and functionality?

I am going to fix this either way for my company, but I would like to create something that the community will merge back in for future releases so I need further clarification to be sure. Just listing group inbound email accounts or a system account to get it working should be fairly quick. Refactoring the code to list outbound accounts here is more in depth but certainly doable. Appreciate your help and feedback on which should be the proper way. Thanks.

**Comment by stancel** [comment] 2017-08-28 02:24
I went ahead and submitted a Pull Request here:
https://github.com/salesagility/SuiteCRM/pull/4168

**Comment by labcerouno** [comment] 2017-11-28 17:07
Unfortunately, this solution didn't work for us. Instead, the From field shows the admin account's mail configured in his profile.

**Closed** 2017-12-14 17:24 UTC
Labels: bug, Fix Proposed, High Priority, Resolved: Next Release

**Comment by zer0890** [comment] 2018-03-21 16:39
I tried to use this commit and it still dosnt work

**Comment by labcerouno** [comment] 2018-04-20 19:18
I guess the correct behavior would be populate the From field with all the Outbound Accounts configured in Admin / Email / Outbound Email. And only show the system notifications account if the checkbox "Allow users to use this account for outgoing email" is checked. 

In my tests, the only outbound account is the system notifications account. Any other one will be ignored. This is v 7.10.4.

Do you confirm this behavior?
Thank's!!!

**Comment by stancel** [comment] 2018-04-20 20:09
Hi @labcerouno,

The purpose of the pull request is to populate a dropdown so that users responding to tickets can choose to send from a central email account that is setup to deal with Support Cases (or from their profile outbound account if desired). Generally, you would want to make this actually come from a different account than your marketing emails. This also keeps the people you are supporting from just trying to contact individual people in your organization to ask for help.

We have been using this in a production environment now since I created a pull request and it has worked well for us. Currently we are on 7.10.2 but believe we started this on 7.9.4. The idea of this is to be able to have a support group/team that can choose to send from a central outbound account or from their own outbound accounts. Below is a redacted screenshot of what I see when editing a Case. I happen to be the administrator and do not happen (or want to have) a personal outbound account setup in my profile. We have standard employee users that this works for though, some of which do have outbound accounts setup in their profiles. If they do have an outbound account setup that info will be populated in their dropdown and they can choose which account to have it sent from. The default chosen account though is the group email setup in the AOP (Advanced Open Portal) Settings. 

### Screenshot of Editing a Case
![suitecrm_group_email_for_cases](https://user-images.githubusercontent.com/1058532/39070893-11801392-44b3-11e8-81cd-dffd466fc36e.png)

### AOP Portal Settings (needs matching group email outbound account)
![support_group_email_config](https://user-images.githubusercontent.com/1058532/39070970-4f6262fa-44b3-11e8-8753-33c9d87eb1cf.png)

### Support Outbound Email Setup
![outbound_email_support_group](https://user-images.githubusercontent.com/1058532/39071461-2ac195fe-44b5-11e8-9847-b904e20f58ef.png)


### Support Inbound Email Setup
![inbound_email_group_account](https://user-images.githubusercontent.com/1058532/39071468-300dbf7e-44b5-11e8-9a7a-cfb63170ef40.png)



I'll be happy to you if you provide me with what behavior you are seeing.

@Dillon-Brown - would you please re-open this issue?

**Comment by labcerouno** [comment] 2018-04-21 15:14
Thank you very much, @stancel, for your very complete answer. 

Myself, I was testing only the 5 steps @Dillon-Brown wrote in the first post of this issue. And actually it works as expected. Maybe I'm out of scope here. I wanted to point out that, if you DO NOT check `allow users to use this account`, the From field will be always empty, even though if you added outbound email accounts.

My guess is that the expected behavior should be **always show the outbound accounts in the From field in Compose page of Email module.** And only show the notification account if `allow users...` was checked. I didn't test the Support Case Module you mentioned.

Unfortunately, I can't access my installation until monday. Some part of this issue can be seen on demo.suiteondemand.com . But, as we can't login as Admin in this demo, I cannot show you how outbound and notification accounts are configured. All I can show is the unfamous empty From field.

![suitecrm screenshot](https://user-images.githubusercontent.com/2539666/39085723-4d59644a-455d-11e8-8d11-628ca08affb1.png)

Should I create a new issue?
