### ISSUE TITLE
Info Box on Listview is out off screen

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2305] opened 2016-09-23 13:44 UTC
#### Issue

If is sidebar open, the position of info box bubble is out of screen

![box1](https://cloud.githubusercontent.com/assets/5773777/18787718/4e116e4c-81a4-11e6-9d9e-e3faca4c0998.png)

If is sidebar hidden, the position of info box bubble is over the Detaiview menu

![box2](https://cloud.githubusercontent.com/assets/5773777/18787725/54acfe24-81a4-11e6-8656-ee9271ce3583.png)

#### Steps to Reproduce

1. Any Detaview of module
2. Click on info icon on record row
3. Hide and unhide sidebar

#### Your Environment

* SuiteCRM Version used: 7.7.4 Official DEMO of SuiteCRM
* Browser name and version: Chrome 53.x m 32 bit
* Environment name and version 5.6 MySQL 5.6 PHP
* Operating System and version: Linux (Hosting)

**Comment by shogunpol** [comment] 2016-09-23 14:10
This issue has been tested on recent version SuiteCRM(7.7.4), and it appear.
We label this issue as a bug.
@Mausino , thanks for raise this issue.

**Comment by ijdavie** [comment] 2016-09-23 14:40
@Mausino This is a duplicate of #146

**Closed by ijdavie** 2016-09-23 14:40 UTC
