### ISSUE TITLE
SuiteP css issue - missing space between Close & other buttons

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#2147] opened 2016-09-06 12:20 UTC
#### Issue

SuiteP Theme - here is missing the space ... same issue for calls, meetings, tasks, cases 

Official version of SuiteCRM version 7.7.4

![close](https://cloud.githubusercontent.com/assets/5773777/18273322/f1fa24ec-743c-11e6-9ec0-b1488e35df21.png)

**Comment by shogunpol** [comment] 2016-09-06 12:57
The issue has been tested on recent version of SuiteCRM(7.7.4), and i been unable to replicate it.
Is there any other information you can give to us to replicate the issue?
@Mausino , thanks for raise this issue.

**Comment by Mausino** [comment] 2016-09-06 13:51
@shogunpol  tested in chrome 53.x m (32bit) and edge browser http://screencast.com/t/HzO3djXpFtF

**Comment by shogunpol** [comment] 2016-09-06 14:50
@Mausino , I confirm i been able to replicate issue on chrome, in WindowsOS i think it is strictly related with chrome browser.
I decided to labeled issue as a bug.
Thanks for raise this issue.

**Comment by mattlorimer** [comment] 2016-09-14 21:16
Duplicate of #1942

**Closed by mattlorimer** 2016-09-14 21:16 UTC
Labels: bug, duplicate, Resolved: Next Release
