### ISSUE TITLE
Unable to rename tab-actions dropdown button

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#2089] opened 2016-08-31 09:49 UTC
#### Issue

Unable to rename tab-actions dropdown button, I found bug in your code.
#### Expected Behavior

I should be able to rename it using language file.
#### Actual Behavior

Unable to rename
#### Possible Fix

Go to themes/SuiteP/include/MySugar/tpls/MySugar.tpl
line 106
`<a class="dropdown-toggle" data-toggle="dropdown" href="#">Actions{$APP.LBL_LINK_ACTIONS}</a>`
you need to change to 
`<a class="dropdown-toggle" data-toggle="dropdown" href="#">{$app.LBL_LINK_ACTIONS}</a>`
#### Steps to Reproduce

Just go to Home module, button name "Actions"
#### Context

low
#### Your Environment
- SuiteCRM Version used: 7.7.3
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04): win10

**Comment by ijdavie** [comment] 2016-09-01 13:17
This is a duplicate of. #1915 and there is a pull request for this #1951. As the creator of the previous issue has closed this I will leave this was open.

**Comment by shogunpol** [comment] 2016-11-30 14:42
Pull request related to this issue is merged, so this issue can be closed.

**Closed by shogunpol** 2016-11-30 14:42 UTC
Labels: bug, Fix Proposed, Low Priority
