### ISSUE TITLE
SuiteCRM 7.10.6 - The Description will not save when editing in the Case Edit View.

### ISSUE THREAD

**Issue by wcs2013** [salesagility/SuiteCRM#6081] opened 2018-06-25 13:13 UTC
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by PedroErnst** [comment] 2018-06-25 13:17
Such detailed issue report!

No seriously, is this a joke or did you maybe hit submit by mistake?

At the very very least we need to know your SuiteCRM version. There was a bug like this that got fixed recently.

**Comment by wcs2013** [comment] 2018-06-25 14:00
#### Issue
The updated text in the Description field does not save when editing an existing case in Edit View, 

#### Expected Behavior
Should be able to edit an existing Case in Edit View, edit the Description, press Save or Save and Continue, and the updated Description text is saved and appears in Detailed View.

#### Actual Behavior
When editing a Case in Edit View by going to Actions then Edit, I update the Description text field with whatever changes I want to make, then I press the Save button at the bottom.  When the page goes back to the Details view, the text is not updated in the Description field.  the original text appears.

#### Possible Fix
I've found no fix to this problem.  However, a workaround is to just double-click the Description field while in the Detail view.  Update the text, hit Enter or click on the arrow to the right of the field.  This saves the text.

#### Steps to Reproduce
1. Open an already existing Case.
2. Go to Actions and Edit.
3. Update the text in the Description field.
4. Press Save or Save and Continue.

#### Context
My guys find it annoying, but we are still able to update the text with the in-line edit in the Detail view.
Priority on this medium to low.

#### Your Environment
* SuiteCRM Version used: 7.10.6
* Browser name and version: Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP Version 7.0.30-0ubuntu0.16.04.1
MySQLi Version: mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
MySQLi Host Info: Localhost via UNIX socket
MySQLi Server Info: 5.5.5-10.0.34-MariaDB-0ubuntu0.16.04.1
MySQLi Client Encoding: utf8
MySQL Character Set Settings: character_set_client = utf8, character_set_connection = utf8, character_set_database = utf8, character_set_filesystem = binary, character_set_results = utf8, character_set_server = utf8mb4, character_set_system = utf8


* Operating System and version (e.g Ubuntu 16.04): Linux SuiteCRM 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64

**Comment by wcs2013** [comment] 2018-06-25 14:03
Hey PedroErnst.  This is my first issue submission.  I accidently hit the submit by mistake.  While you were commenting on my lack of description, I was filling out detailed information via the template provided and running my business at the same time.  So, I apologize if I did not get the detailed information to you fast enough.  But thanks for the fast comment!!

**Comment by PedroErnst** [comment] 2018-06-25 14:15
Thanks for the detailed report.

I'm not able to reproduce this, but there was a related bug that got fixed in 7.10.6 precisely. It might have something to do with this.

Is there any related error message in the SuiteCRM logs or the javascript console?

**Comment by wcs2013** [comment] 2018-06-25 18:33
I reproduced this problem twice, once at 2:27pm and 2:29pm.  The two log entries are what I saw at those times.  Attached is the complete SuiteCRM log file.

[suitecrm.log](https://github.com/salesagility/SuiteCRM/files/2134257/suitecrm.log)

Mon Jun 25 14:27:09 2018 [11050][5e4ccfa6-e520-5359-fcd4-5aa91e21ee38][FATAL] log call at: modules/Administration/index.tpl:54 - MY_FRAME is not set
Mon Jun 25 14:29:52 2018 [11108][5e4ccfa6-e520-5359-fcd4-5aa91e21ee38][FATAL] log call at: modules/Administration/index.tpl:54 - MY_FRAME is not set

**Comment by PedroErnst** [comment] 2018-06-29 14:43
I've been able to reproduce this now, it appears to affect only intermittently... tricky.

The error messages in the log seem unrelated to this particular issue, actually I think it's an issue with tinyMCE. I'll keep looking into it.

**Comment by pgorod** [comment] 2018-07-02 11:49
The log entries are solved here: #6097 

But this might not mean much to the actual issue here.

**Comment by PedroErnst** [comment] 2018-07-17 10:33
Thanks for the feedback @wcs2013 @boombata 

I've submitted a PR with a fix #6165

If you get a chance to test it let me know if it works for you.

**Closed** 2018-09-13 14:51 UTC
Labels: Low Priority, Module, Resolved: Next Release, bug
