### ISSUE TITLE
Error with spanish translation

### ISSUE THREAD

**Issue by ErMaqui** [salesagility/SuiteCRM#78] opened 2014-09-26 13:00 UTC
Hi,

I have lot of cases when use the CRM who i see a "undefined" message when i'm using CRM on Spanish. As i can see, the js file with strings lacks some of them (They have one array empty).

Tested on latest version.

**Comment by cmarrero** [comment] 2015-01-20 05:54
Hi,

The "undefined" still appears even if you set to 775 the permision for the cache folder.


![2015-01-20 00-52-15](https://cloud.githubusercontent.com/assets/212819/5812741/dc7304f0-a03e-11e4-92d8-f95065b9ea85.png)
![2015-01-20 00-51-21](https://cloud.githubusercontent.com/assets/212819/5812742/dc75fe3a-a03e-11e4-937d-156ef00b085c.png)
![2015-01-20 00-51-10](https://cloud.githubusercontent.com/assets/212819/5812740/dc6e0432-a03e-11e4-84f3-557452da5c10.png)

**Comment by fgpalacios** [comment] 2015-01-21 17:38
edit the config.php of sugar and replace


'default_permissions' =>
array (
'dir_mode' => 493,
'file_mode' => 420,
'user' => '',
'group' => '',
)

**Comment by cmarrero** [comment] 2015-01-23 14:27
Hi,
I try the solution about permissions, rebuilt the languages in repair and still the same problem
Regards

**Comment by cmarrero** [comment] 2015-02-04 14:27
Hi,

I see this error in the console every time a page is access:

SyntaxError: expected expression, got ')'
SUGAR.language.setLanguage('app_strings', );
es_es.j...zimvnow (línea 1, col 42
Route to file= cache/jsLanguage/es_es.js?v=CbTah9NLNnDAATDzimvnow

Regards

**Comment by cmarrero** [comment] 2015-02-13 19:17
I have found this on the forums 

https://suitecrm.com/forum/bug-tracker/2559-calendar-form-empty-with-no-english-language

"
I've fouun the reaons why of this problem ... but not the solution. The problem (seems) caused by the following statement
SUGAR.language.setLanguage('app_strings', );
which is repeated twice at the beginning of the file..cache\jsLanguage\it_it.js.
I've tried to remove this double statement and everything works fine.
"

In some part SuiteCRM is inserting for no english lenguaje  this  line: SUGAR.language.setLanguage('app_strings', ); 

If you see the file in the cache folder "cache/jsLanguage/es_es.js" has no the label "LBL_LOADING_PAGE" but that is include in the file "include/language/es_es.lang.php"

Regards

**Comment by cfiorillo** [comment] 2015-02-22 22:38
Hi,
I had the same problem with Italian (it_it) language ("undefined" message boxes, etc). 
I verified the problem was not permissions-related (already 755 and config.php OK), but one language file with WRONG ENCODING.

The file

custom/Extension/application/Ext/Language/it_it.SecurityGroups.php 

has encoding "MacOS Roman" (as detected from TextWrangler on Mac) instead of "Unicode UTF-8" (as for other language files), so when a quick repair and rebuild is done, this file is included in the file custom/application/Ext/Language/it_it.lang.ext.php and the Javascript language rebuild fails to generate the 'app_strings' content for the language, hence the incomplete statement SUGAR.language.setLanguage('app_strings', );

As a workaround, I saved the file with the right UTF-8 encoding (and the right "à" letters for Italian language), did a "quick rebuild & repair" followed by a "Javascript language rebuild", and cleared the browser cache.
Now it's working without problems.

You could verify what file causes the issue in Spanish language by renaming all es_es.* files in your custom/Extension/application/Ext/Language/ folder and try "quick repair & rebuild" + "Javascript language rebuild" to verify if the cache/jsLanguage/es_es.js file is built without problems, then try to rename back one file at a time (and rebuild each time) until you found the wrong file that causes the error.

**Comment by cmarrero** [comment] 2015-02-23 03:07
Hi,
I can confirm that the solution proposed by cfiorillo works for the spanish translation.

I change custom/Extension/application/Ext/Language/it_it.SecurityGroups.php with the right UTF-8 encoding, did a "quick rebuild & repair" followed by a "Javascript language rebuild", and cleared the browser cache.

This must solve the problem with the others translations.

Is very important because affect significatively the Maps and Calendar modules.

Regards

**Comment by megaboty** [comment] 2015-04-14 16:14
Hi,

I have the same issue with the 7.2.1 version with spanish translation.

In that version I saw that the file custom/Extension/application/Ext/Language/it_it.SecurityGroups.php has encoding "ANSI" (i saw it in the notepad).

When I change the encoding y do "quick rebuild and repair" the suitecrm crash and I can't access to it again. I need to re-install it.

Please help!

**Comment by JanSiero** [comment] 2015-08-08 14:59
The problem should already have been fixed in the current version of SuiteCRM.

Please see 
https://github.com/salesagility/SuiteCRM/pull/226

To patch older versions, 
 - go here:
https://github.com/JanSiero/SuiteCRM/commit/f6ca385ceb4e25fa9a6e9eeac524b89b921a6a3b
 - Click on "View" for the language you need
 - Right click on "Raw" and save the file
 - Copy it into your SuiteCRM

**Comment by willrennie** [comment] 2015-08-18 10:06
This issue has been resolved in the latest releases.

**Closed by willrennie** 2015-08-18 10:06 UTC
Labels: bug
