### ISSUE TITLE
Remove unused LBL_MODIFIED_USER_NAME_MOD label?

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#1424] opened 2016-05-17 09:01 UTC
The label `LBL_MODIFIED_USER_NAME_MOD` has been generating some talk between translators, everybody wondering what it means.

I searched the code, and if I'm seeing things right, it's not even used anywhere:

https://github.com/salesagility/SuiteCRM/search?utf8=%E2%9C%93&q=LBL_MODIFIED_USER_NAME_MOD

So perhaps it could simply be removed to avoid wasting the translators' time. Thanks.

**Comment by pgorod** [comment] 2016-05-20 12:06
While you're at it, there's a typo in the new Campaigns strings:
LBL_SELECT_EMAIL_TRACKER
"please selected" should be "please select"

I don't think this kind of thing is worth opening multiple issues and multiple PRs...

**Comment by shogunpol** [comment] 2016-12-22 15:28
@pgorod  -  this is a duplicate of issue #2534 . This is issue will be closed, please follow the tagged issue, i know this issue is older one, but just try to keep consistence of issue.

**Closed by shogunpol** 2016-12-22 15:28 UTC
Labels: suggestion
