### ISSUE TITLE
Unable to create a relationship in Module Builder

### ISSUE THREAD

**Issue by nsrosenqvist** [salesagility/SuiteCRM#5014] opened 2018-01-25 05:10 UTC
#### Issue
When I'm trying to create a relationship between two modules an empty error dialog shows up.

![screenshot-2018-1-25 suitecrm 1](https://user-images.githubusercontent.com/1303475/35371778-09c33328-01fb-11e8-8e68-8a256bc2447b.png)

#### Expected Behavior
Relationship should be created.

#### Actual Behavior
It fails to perform the operation and doesn't give an explanation to why.

#### Possible Fix
...

#### Steps to Reproduce
1. Go to Administration > Module Builder
2. Create a new package with two modules
3. Try to create a relationship between the two modules

#### Context
I'm unable to configure the CRM for our organization's use cases.

#### Your Environment
* SuiteCRM Version used: Version 7.9.9 - Sugar Version 6.5.25 (Build 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57.0.4 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 x64

**Comment by Dillon-Brown** [comment] 2018-01-25 10:17
@nsrosenqvist I'm unable to replicate on 7.9.x. Have you checked permissions?

**Comment by nsrosenqvist** [comment] 2018-01-25 10:32
I'm using the default administrator account so I should have full rights. Will check if I can find anything in the server log

**Comment by nsrosenqvist** [comment] 2018-01-25 10:36
Found this in the error log (replaced all occurrences of the domain with [domain]):

```
[Thu Jan 25 23:33:19.033549 2018] [:error] [pid 7273] [client 165.84.59.27:39454] PHP Fatal error:  Uncaught Error: Cannot access private property UndeployedMetaDataImplementation::$_packageName in /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php:432\nStack trace:\n#0 /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/views/UndeployedMetaDataImplementation.php(155): AbstractMetaDataImplementation->getFileName('editview', 'Course_Instance...', 'history')\n#1 /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/views/GridLayoutMetaDataParser.php(136): UndeployedMetaDataImplementation->deploy(Array)\n#2 /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/relationships/UndeployedRelationships.php(373): GridLayoutMetaDataParser->handleSave(false)\n#3 /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/relationships/UndeployedRelationships.php(315): UndeployedRelationships->updateUndeployedLayout(Object(ManyToOneRelationship), true)\n#4 /var/www/crm.ywambethlehem in /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php on line 432, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
```

**Comment by dhayner** [comment] 2018-01-26 02:53
I have a similar issue in Module Builder on 7.9.9
Enter module builder, existing built module.  Change ListView layout.  Click Save.
I get the error screen you show above, and in the logs:
`PHP Fatal error:  Uncaught Error: Cannot access private property UndeployedMetaDataImplementation::$_packageName in [[MyFilePath]]\\www\\suitecrm\\modules\\ModuleBuilder\\parsers\\views\\AbstractMetaDataImplementation.php:432\nStack trace:\n#0 [[MyFilePath]]\\www\\suitecrm\\modules\\ModuleBuilder\\parsers\\views\\UndeployedMetaDataImplementation.php(155): AbstractMetaDataImplementation->getFileName('listview', 'WhsBinDetail', 'history')\n#1 [[MyFilePath]]\\www\\suitecrm\\modules\\ModuleBuilder\\parsers\\views\\ListLayoutMetaDataParser.php(132): UndeployedMetaDataImplementation->deploy(Array)\n#2 [[MyFilePath]]\\www\\suitecrm\\modules\\ModuleBuilder\\controller.php(796): ListLayoutMetaDataParser->handleSave()\n#3 [[MyFilePath]]\\www\\suitecrm\\include\\MVC\\Controller\\SugarController.php(523): ModuleBuilderController->action_listViewSave()\n#4 [[MyFilePath]]\\www\\suitecrm\\include\\MVC\\Controller\\SugarController.php(491): SugarController->do_action()\n#5 [[MyFilePath]]\\www\\suitecrm\\include\\MVC\\Controller\\SugarController.php(465): SugarController->handle_action()\n#6 [[MyFilePath]]\\www\\suitecrm\\modules\\ModuleBuilder\\ in [[MyFilePath]]\\www\\suitecrm\\modules\\ModuleBuilder\\parsers\\views\\AbstractMetaDataImplementation.php on line 432, referer: http://localhost/index.php?module=ModuleBuilder&action=index&type=mb`

Actual file path replaced with [[MyFilePath]].  This was on my local test instance, hence the reference to localhost.  But the same happens in production.

**Comment by nsrosenqvist** [comment] 2018-01-26 03:33
I don't think it would be a permission issue since I set the filesystem permissions by the exact commands instructed in the installation instructions.

**Comment by dhayner** [comment] 2018-01-26 03:36
Go take a look at #4969 - this just solved my issue in test and prod.

**Comment by nsrosenqvist** [comment] 2018-01-26 03:50
That did it. Thanks @dhayner!

**Comment by nsrosenqvist** [comment] 2018-01-26 04:49
Got another error this time. I had to recreate one of the modules that I've created within a custom package due to this [bug](https://github.com/salesagility/SuiteCRM/issues/5031). Now when I tried to recreate that same relationship I got another empty error dialog showing up and this is what I found in the log.

```
[Fri Jan 26 17:42:33.310378 2018] [:error] [pid 18327] [client 165.84.20.248:46314] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:42:33.311896 2018] [:error] [pid 18327] [client 165.84.20.248:46314] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:42:33.312394 2018] [:error] [pid 18327] [client 165.84.20.248:46314] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:42:33.318478 2018] [:error] [pid 18327] [client 165.84.20.248:46314] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:43:46.708688 2018] [:error] [pid 18539] [client 165.84.20.248:46356] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:43:46.710545 2018] [:error] [pid 18539] [client 165.84.20.248:46356] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:43:46.713030 2018] [:error] [pid 18539] [client 165.84.20.248:46356] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:43:46.714150 2018] [:error] [pid 18539] [client 165.84.20.248:46356] PHP Notice:  Undefined index: LBL_SEARCH in /var/www/[domain]/public_html/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:44:17.056094 2018] [:error] [pid 18610] [client 165.84.20.248:46362] PHP Notice:  Undefined index: crss_Courses in /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/relationships/AbstractRelationship.php on line 449, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:44:17.056149 2018] [:error] [pid 18610] [client 165.84.20.248:46362] PHP Notice:  Undefined index:  in /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/relationships/AbstractRelationship.php on line 450, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:44:17.056185 2018] [:error] [pid 18610] [client 165.84.20.248:46362] PHP Warning:  require_once(/var/www/[domain]/public_html): failed to open stream: No such file or directory in /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/relationships/AbstractRelationship.php on line 450, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Jan 26 17:44:17.056200 2018] [:error] [pid 18610] [client 165.84.20.248:46362] PHP Fatal error:  require_once(): Failed opening required '' (include_path='/var/www/[domain]/public_html:/var/www/[domain]/public_html/include/HTMLPurifier/standalone:/var/www/[domain]/public_html/include/..:.:/usr/share/php') in /var/www/[domain]/public_html/modules/ModuleBuilder/parsers/relationships/AbstractRelationship.php on line 450, referer: https://[domain]/index.php?module=ModuleBuilder&action=index&type=mb
```

**Comment by Dillon-Brown** [comment] 2018-01-26 13:27
Closing as a duplicate of #4962. If you encounter further issue please create a new issue. Thanks!

**Closed by Dillon-Brown** 2018-01-26 13:27 UTC
Labels: duplicate
