### ISSUE TITLE
Issue with apostrophes in search

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#99] opened 2014-12-03 16:18 UTC
When filling a search field with single quoted value (O'hara...) it gets escaped after clicking on the next page button or ordering a column.

After the second click, the searching lead to an empty result, because the field has become O\\'hara.

https://suitecrm.com/forum/bug-tracker/2930-search-fields-get-escaped

**Comment by recci** [comment] 2015-01-21 17:25
Cant see the issue in action. Created many contacts with the last name O'hara and searched for them. Changing page seems to work ok as does the column ordering.

**Comment by recci** [comment] 2015-01-22 12:28
This a known sugar bug which is still in Sugar CE. https://web.sugarcrm.com/support/issues/52725

Seems to be caused by include/database/MssqlManager.php line 257 where they call mysqli_real_escape_string on the search query.

**Comment by shogunpol** [comment] 2016-07-28 12:18
The bug doesn't appear to exist any more in recent version of SuiteCRM, it was tested by creating multiple instances contained " ' "(apostrophe/ single quote sign), in first and/or  second name. Testing has been done in basic and advanced search facility.

**Comment by willrennie** [comment] 2016-07-28 15:37
Nope @shogunpol this bug still exists and has not been resolved. The issue lies with the global search.

**Comment by shogunpol** [comment] 2016-08-04 12:46
This bug is fixed, suggest close

**Comment by horus68** [comment] 2016-12-19 18:04
@shogunpol  This should be closed by the merge https://github.com/salesagility/SuiteCRM/pull/1823

**Closed** 2016-12-19 18:38 UTC
Labels: bug, Fix Proposed
