### ISSUE TITLE
Photo field - Remove button doesn't do anything

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#1243] opened 2016-04-15 12:24 UTC
Tested on 7.5.3, but I know this bug has been around for quite some time.

Steps to reproduce:
1. Add photo field to Contact (the SuiteCRM photo field, not the one from a famous add-on).
2. Add that field to the Edit screen layout.
3. Open a contact and add a photo to it by uploading a file. Everything works properly and the photo is displayed.
4. Go into the Editing screen for that contact. A remove button appears, but clicking on it does nothing. 

There is no other way of removing the photo, except going into the database...

[I notice the photos go into a directory called `1711-upload`. It seems (from what I gather on forum posts) that normally this directory is simply called `upload`. I have no idea why my directory has this name. I did not rename it, and it works properly for all other things that use that directory, like upgrades, etc.]

**Comment by mattlorimer** [comment] 2016-04-15 18:48
duplicate of #216

**Closed by mattlorimer** 2016-04-15 18:48 UTC
Labels: duplicate
