### ISSUE TITLE
Projects Templates - Project Tasks are not created

### ISSUE THREAD

**Issue by MTet** [salesagility/SuiteCRM#5991] opened 2018-06-06 09:41 UTC
#### Issue

The error occurs also at the online-demo (firefox+chrome+edge, edge gets a 500 error)

If I add a new project-template with new project-task-template and then create a new project from this template, I only see a white screen and nothing else happens. 
If i reload the page, then a new project will be created...every time I hit reload to get the white screen away.
If I access to the CRM from the start-page and open the new created project, then no project-tasks are created.
#### Expected Behavior

No white page
Project Tasks should be created
#### Actual Behavior

white page
Project Tasks are not created

#### Steps to Reproduce

1. New Project-Template with Project-Task-Templates
2. Create new Project from the Template

#### Context

Using of project-templates is impossible.

#### Your Environment

* SuiteCRM Version used: suitecrm-demo and 7.10.4 local
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): firefox+chrome+edge
* Environment name and version (e.g. MySQL, PHP 7): mySql + PHP7
* Operating System and version (e.g Ubuntu 16.04): Windows Server

**Comment by Mausino** [comment] 2018-06-06 10:42
@MTet  i think that's duplicate of #5804

**Comment by MTet** [comment] 2018-06-06 11:10
@Mausino yes, thats right. I havn´t seen it.

**Comment by Mausino** [comment] 2018-06-06 11:51
@MTet if yes.. please close your issue.. and you can check the other one on which are developers working :)

**Closed** 2018-06-06 11:53 UTC
