### ISSUE TITLE
Inline editing of date fields resets date to current date

### ISSUE THREAD

**Issue by rholighaus** [salesagility/SuiteCRM#1783] opened 2016-07-24 17:41 UTC
#### Issue

When using the inline edit feature for a date field, a date selection box pops up, but doesn't use the date in the date field, but the current date.

#### Expected Behavior

The date selector should be set to the value of the date field.
#### Actual Behavior

The date selector in an inline editing date field always defaults to the current date. When saving, the content of the date field will be overwritten with the current date.
#### Possible Fix

We are using German date format (dd.mm.yyyy) - could this be the reason?
#### Your Environment

* SuiteCRM Version used: 7.6.2 and newer

**Comment by Mausino** [comment] 2016-08-02 14:56
duplicate of issue #1042

**Closed** 2016-08-15 14:42 UTC
Labels: bug, duplicate
