### ISSUE TITLE
aow_workflow_audit is not filled up with historical information

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#2827] opened 2016-12-22 16:38 UTC
the workflow module does not register in "View Change Log"
and we can not add from studio since the whole module is not listed...
the table aow_workflow_audit is empty.

**Comment by ijdavie** [comment] 2016-12-23 13:44
@bmwtourer, This module is not listed in studio by design. the view change log for this module only records the change of the assigned to user. if other fields are to be added to this it should be done via code. 

However function fields are not able to be recorded into the audit tables again unless there is custom work to allow this. (the condition lines and action lines).

**Comment by bmwtourer** [comment] 2017-01-03 16:08
I was expecting this answer for visual studio...

Since the workflow conditions and actions may be changed over time,  I believe we that the change log should be active for this module...  don't you think?

**Comment by shogunpol** [comment] 2017-01-04 09:10
@bmwtourer , thanks for raise this suggestion, i will processing it to future consideration, add this functionality.

**Comment by samus-aran** [comment] 2017-04-01 16:19
I would disagree as that same logic would apply to Quotes and Invoices if were adding line items and groups would also add to the View Change Log which it doesn't.  Actions and Conditions of Workflows are similar in that they are separate modules and therefore you can not view them via the parent module of Workflow's View Change Log.

We at SalesAgility don't see implementing a child View Change Log would be beneficial but you are free to re-open this if you wish the Community to tackle this suggestion.

**Closed by samus-aran** 2017-04-01 16:19 UTC
Labels: suggestion
