### ISSUE TITLE
Cannot edit tasks from Calendar

### ISSUE THREAD

**Issue by SpudR** [salesagility/SuiteCRM#2315] opened 2016-09-26 11:25 UTC
#### Issue
Tasks cannot be edited from the Calendar, meetings are fine

#### Expected Behavior
Clicking on the task brings up the task details to be edited, just like the meetings.

#### Actual Behavior
The task cannot be clicked - it's not a link.

#### Steps to Reproduce
1. Add a task
2. View the Calendar
3. Attempt to edit the task from the Calendar

Confirmed with the demo - same issue exists.

#### Your Environment
PHP 7
SuiteCRM 7.7.4

**Comment by ijdavie** [comment] 2016-09-26 12:01
This is a duplicate of issue #2088

**Closed by ijdavie** 2016-09-26 12:01 UTC
