### ISSUE TITLE
Inbound email username does not support special characters

### ISSUE THREAD

**Issue by soupernashwan** [salesagility/SuiteCRM#7664] opened 2019-07-30 14:17 UTC
#### Issue

On 7.11.6
Linux (Ubuntu 16.04)
PHP 7

I'm trying to configure an inbound email address on SuiteCRM. I want to use a shared mailbox over imap. The username is of the format personal-user-name/alias-of-shared-mbox.

I am getting authentication errors and think it may be that the slash is being stripped out.

**Comment by pgorod** [comment] 2019-07-31 08:05
@soupernashwan that long Issue template we have is there for some reason... so we get all the information we need.

There are several places in SuiteCRM to define "inbound email accounts", if you can provide the "steps to reproduce" it will help us test in the exact same place where you are. Thanks.

Also, if you can please un-comment [this line](https://github.com/salesagility/SuiteCRM/blob/master/include/SugarPHPMailer.php#L457), raise your log level to `DEBUG` and then run the test, you can know for sure if the problem is with the slash being stripped out or not.

**Comment by LeoZandvliet** [comment] 2020-11-19 19:07
I think this is just the same problem to resolve, as #8737

**Comment by pgorod** [comment] 2020-11-20 09:56
@LeoZandvliet thanks, I think you're right. Anyway this issue here is incomplete and quite useless.

@johnM2401 youmight want to close this one. Thanks

**Comment by johnM2401** [comment] 2020-11-20 10:08
@pgorod 
Agreed, been >1 year without an update, and sounds similar to #8737 

@soupernashwan 
If you feel that this is different enough from #8737, please feel free to raise again, filling in the template provided.
Thanks!

**Closed by johnM2401** 2020-11-20 10:08 UTC
Labels: Status:Requires Updates
