### ISSUE TITLE
SuiteCRM Token Expired / Revoked Immediately After creating it

### ISSUE THREAD

**Issue by ananth23087** [salesagility/SuiteCRM#5880] opened 2018-05-15 10:50 UTC
SuiteCRM Token Expired / Revoked Immediately After creating it

#### Issue 
I have installed the SuiteCRM and configured the keys using openssl, then when i try to create any oauth token, its getting created successfully, but its ( oauth token) getting expired and its expiry date-time is 7 hours behind the Date-Created, please check the following screenshot. Please reply as fast as possible.

**Sample data :** 

**Date created :** 2018-05-15 10:20 
**Access token expires :**  2018-05-15 04:20

#### Expected Behavior 
When we create the Oauth token, then it should have expiry date greater then date created. 

#### Actual Behavior 
We created the Oauth token, then token's expiry date  lesser than (6 hours lesser ) Date-Created. i.e. . 

#### Steps to Reproduce 
 Access Oauth token API ( http://127.0.0.1:81/suitecrm/api/oauth/access_token ) 
 
 
 

#### Context 
This is high priority bug, because i'm not able to proceed further to get any modules details through API. because i did fresh installation in 3 different machine and also in a hosting aws instance, we are facing the same issue, Its considered as the big issue. I'm sure none of the new users can able to proceed with this bug. 

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

SuiteCRM Version :  7.10.4
PHP Version : 7
POSTMAN Collection : https://www.getpostman.com/collections/8778451052f49d913a44
Operating System : Windows 10
Browser Name : Chorme

**Comment by afernandez2000** [comment] 2018-05-22 04:59
Im having the same issue with SuiteCRM version 7.10.5, PHP 7

**Comment by ananth23087** [comment] 2018-05-22 06:53
I found the fix for this issue, i have added the answer for this issue in this stackoverflow 

https://stackoverflow.com/questions/50346554/suitecrm-token-expired-revoked-immediately-after-creating-it/50368887#50368887

**Comment by Dillon-Brown** [comment] 2018-06-02 00:53
Duplicate of #5711

**Closed** 2018-06-02 00:53 UTC
Labels: duplicate
