### ISSUE TITLE
Calendar new meeting/call ignores required fields

### ISSUE THREAD

**Issue by staganyi** [salesagility/SuiteCRM#2645] opened 2016-11-15 16:04 UTC
#### Issue
As reported in #2510 (which was closed for some reason), when add/editing a meeting/call from the calendar, you can save without entering any values for the required fields and the form will not prevent it.

#### Expected Behavior
You should get prompted to enter data into the required fields.

#### Actual Behavior
Saves without prompting user.

#### Your Environment
SuiteCRM v7.7.7
Ubuntu 14.04.1
PHP 5.5.9
Apache 2.4.7
Chrome 54 on Windows 10 (same behavior with other browsers)

**Comment by shogunpol** [comment] 2016-11-17 09:06
@staganyi , can you reset layout for mentioned module, when you do this the issue will not appear.

**Comment by staganyi** [comment] 2016-11-17 16:10
I reset the edit & quick create layouts for meetings but it did not fix the issue when add/editing from the calendar. It works perfectly fine when add/editing a meeting outside of the calendar.

**Comment by staganyi** [comment] 2017-01-17 14:26
I noticed in **modules/Calendar/Cal.js**, the save button function **CAL.check_forms** does not include the **check_form('CalendarEditView')** call from previous versions.

**Comment by afrugone** [comment] 2018-01-17 13:54
This problem is still present in version 7.9.9, it will be soved in version 7.10?

**Comment by TB-effective** [comment] 2021-02-11 11:31
This issue is still present, and can be easily reproduced on demo.suiteondemand.com (Version 7.11.18 Sugar Version 6.5.25 (Build 344) at time of writing):

1. Go to calendar
2. Click in calendar to create new meeting
3. Click Save (without filling in required field "Subject")

Expected result: Validation warning for empty mandatory field(s)

Actual result: Meeting is created with no subject.

Let me know if I should open a fourth issue about this (in addition to #4483, #2510, and #2645).

**Comment by TB-effective** [comment] 2021-02-12 16:52
Forgot to mention: This also applies to any custom fields added for meetings via Studio and declared mandatory. These are not validated either when the meeting is created from the calendar view. They are all correctly validated when creating the meeting directly in the meetings module.

I can't say whether this has worked in previous Suite versions, because we have only recently switched from Sugar. (This used to work as expected on the old Sugar install, just for reference.)

**Comment by TB-effective** [comment] 2021-03-26 16:24
Anything?

Is SuiteCRM still being maintained? Not trying to sound entitled, it's an honest question... I know, OS and all, sure, and I understand this ticket was set to prio moderate, but it's from 2016. And the last "Sprint" according to the projects tab was almost a year ago, and is closed even though it shows only 5 done tickets but a backlog of 9, 3 "to do", 4 in progress, and 8 in review. And it looks like there have been no commits at all since October 2020... Then again I see about a million forks – does anyone know if any of these are maybe more active?

**Comment by mattlorimer** [comment] 2021-04-01 16:57
@TB-effective Thanks for championing this issue, this one annoys me also, so hopefully our patch will be in the up and coming maintenance release and we can hopefully close these issues. So otherwise all I can say yes we are still actively maintaining the SuiteCRM project. There a lot of issue, question, pull requests for us to work and it not always possible for us to get to them all in a timely manner, but we are working to improve that. Thanks for your contribution and feedback.

**Comment by TB-effective** [comment] 2021-04-01 17:08
> @TB-effective Thanks for championing this issue, this one annoys me also, so hopefully our patch will be in the up and coming maintenance release and we can hopefully close these issues. 

That sounds great, thanks!

> So otherwise all I can say yes we are still actively maintaining the SuiteCRM project. 

:-) thanks for confirming, and apologies again if I came across feeling entitled.

> There a lot of issue, question, pull requests for us to work and it not always possible for us to get to them all in a timely manner, but we are working to improve that. Thanks for your contribution and feedback.

I completely understand. Thanks and happy Easter!

**Closed** 2021-04-28 22:59 UTC
Labels: Priority:Moderate, Type:Bug
