### ISSUE TITLE
7.8.5 users cannot add email fields to contact reports

### ISSUE THREAD

**Issue by boombata** [salesagility/SuiteCRM#4067] opened 2017-07-28 13:47 UTC
#### Issue

when user is look for email address field to add to a report, he goes to : 
expand "Email address: Email address" , 
select "Email address". 

Now in the field section in the left down side there is no  "Email address" field
if i'm using an admin account the fields are present  but simple users have nothing.

#### Expected Behavior

the screenshot from admin account, email fields are present in the lower left fields section 
![email fields for admin](https://user-images.githubusercontent.com/8605061/28719530-825e854c-73aa-11e7-8723-9f4d41032121.png)
#### Actual Behavior

the screenshot from a user, no field in the lower left field section
![email fields for users](https://user-images.githubusercontent.com/8605061/28719531-8262b612-73aa-11e7-904b-d4a13f8b815f.png)
#### Steps to Reproduce

1.
2.
3.
4.

#### Context

users have to ask admin to add email field to reports.

#### Your Environment

* SuiteCRM Version used: 7.8.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):tested on firefox and safari
* Environment name and version (e.g. MySQL, PHP 7):PHP 7
* Operating System and version (e.g Ubuntu 16.04):Ubuntu 16.04
tested and reproduced on suitecrm online demo

**Comment by dursuntosun** [comment] 2017-08-10 10:53
is it same with #3420

**Comment by Dillon-Brown** [comment] 2017-08-10 11:53
Duplicate of #3420

**Closed by Dillon-Brown** 2017-08-10 11:53 UTC
Labels: duplicate
