### ISSUE TITLE
Direct HTML Editor strips important HTML tags

### ISSUE THREAD

**Issue by bennnjamin** [salesagility/SuiteCRM#4481] opened 2017-11-02 23:19 UTC
#### Issue

When you use the Direct HTML Editor, it does not preserve the HTML exactly. There are some changed tags and id's and classes related to "sugar". When using a Direct HTML Editor it should not modify the HTML at all. If it is going to modify the HTML rename it to "Sugar HTML Editor". A direct HTML Editor should just be a passthrough to the database.

#### Expected Behavior

When you enter HTML into the Direct HTML Editor, it should render properly when sent and it should go into the suitecrm database exactly as entered.

#### Actual Behavior

The HTML entered into the database is stripped of certain important styles and replaced with other "sugar" styles. Furthermore, html tags, head tags are stripped as well.

#### Possible Fix

Just pass through the data entered into the HTML textbox into the database, or at least provide an _option_ to do that so that I do not have to go into the database every time to create templates that render properly.

#### Steps to Reproduce

1. Create a template on mailchimp
2. Export template as HTML
3. Copy HTML and paste into Direct HTML Editor
4. Go to email_templates table in database, look at 'html' column for the template and see that it is not identical to what you pasted in

#### Context

I am trying to use the Campaigns module. The built-in editors are okay, but I prefer to code templates in HTML from scratch or with other editors. Every time I modify a campaign, I have to go into the database, find the template, and paste the correct HTML directly into the database for it to render properly in the recipients' email client.

#### Your Environment

* SuiteCRM Version used: Latest 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome, Mac, Latest
* Environment name and version (e.g. MySQL, PHP 7): 10.0.23-MariaDB, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Debian 8

**Comment by Dillon-Brown** [comment] 2017-11-03 09:51
Duplicate of #3672

**Closed by Dillon-Brown** 2017-11-03 09:51 UTC
Labels: duplicate
