### ISSUE TITLE
Case overview description displays as HTML

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#1763] opened 2016-07-19 06:49 UTC
#### Issue
When viewing the overview of a case or listing the case in case search layout, the description displays with embedded HTML codes making it very difficult to read.

#### Expected Behavior
I would expect that HTML was stripped out and CR/LF inserted for line breaks to make it somewhat readable.

#### Actual Behavior
Raw HTML is displayed.

#### Possible Fix
Remove all HTML and replace < p >/< br >" with CR/LF so that it becomes somewhat readable. Not perfect (tables etc) but better than how it is now.

Alternately, give option for Case description to be in plain text.

#### Steps to Reproduce
Open Cases Module to search for cases.
Ensure you add Description to search listview.
Note descriptions all have HTML.
Drill down to open a case.
Note the description in the Overview section has HTML.
Open an account and go to cases listpanel. Notice that Description has HTML.

#### Context

We are using cases to hold job information synchronised from another system. These cases will never be edited but will be viewed by sales people so that they can see job history for any account (and they do not have access directly to the job system). 
As it currently is, the job details are very difficult to read due to the embedded HTML.

I would say this is a low to medium priority since users can sort of read HTML or can edit the case to see the full HTML but it is annoying.

#### Your Environment

* SuiteCRM Version used: 7.6.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All
* Environment name and version (e.g. MySQL, PHP 7): MYSQL, PHP 5.5 - Not Applicable
* Operating System and version (e.g Ubuntu 16.04): Windows - Not Applicable

**Comment by willrennie** [comment] 2016-07-28 15:43
Duplicate of #975

**Closed by willrennie** 2016-07-28 15:43 UTC
