### ISSUE TITLE
Inbound group email : SCHEDULERS: could not get an IMAP connection resource for ID 

### ISSUE THREAD

**Issue by opensourcecrm** [salesagility/SuiteCRM#1199] opened 2016-04-04 13:34 UTC
Hi @willrennie  @ghermans , @mattlorimer  @JimMackin 

Previously the email to case activity is working fine. and we mark that email as inactive and created a new inbound email handler while setting up the handler is shows the test setting result as completed connection successfully. Ref image1

then we are getting a error log as stated below: Ref iamge2
[FATAL] SCHEDULERS: could not get an IMAP connection resource for ID [ 729affe6-4fd3-fd42-cdfb-57025a612d8e ]. Skipping mailbox [ CRM Renewals Handler ]

then I again check with the inbound handler setting which shows an error Ref image3.

can anyone tell me how to resolve it.
![error1](https://cloud.githubusercontent.com/assets/17160050/14249579/14941bee-fa98-11e5-8fc9-607ae9ca0eec.png)
![error2](https://cloud.githubusercontent.com/assets/17160050/14249580/1496c146-fa98-11e5-818c-4e23bdc98737.png)
![error3](https://cloud.githubusercontent.com/assets/17160050/14249581/1497c6ae-fa98-11e5-97f0-71d96ac79f91.png)

**Comment by ghermans** [comment] 2016-04-04 15:20
@opensourcecrm some questions:

- What is the version that you are using?
- Did you try quick repair in the admin section?
- Do you only have the issue with gmail mailboxes?

**Comment by opensourcecrm** [comment] 2016-04-05 05:10
@ghermans 
1. We are using SuiteCRM 7.4.3 version
2. We have done all the repair and rebuild activity, repairing roles, relationships, inbound emails and Repair and rebuild.  
3. we only tried with our email as well as our regular gmail accounts in both the cases same issue. We were shock because its working fine on 1st of April just after 3 days its not working with the same settings, that is our major concern. 

Note: in fact we are experiencing lot of issues with  email to cases, instantly the inbound emails get marked to achieved folder for some time those email need to create manual cases. and some emails directly comes to an inbox and create the case. even we try to drill-down in the code. but we wont get any ice break with these issues.

**Comment by hturkoz** [comment] 2016-04-05 05:57
Hi,
i dont use gmail but i have same issue in these condition :  

we have a global email like support@.. who is the generic and then this email create a case. 
this email is too configured on all user computer client email. When all user open computer email client, this error occur ! 
when i close some computer email client, the issue is resolve.
I think, this is a restriction of email server who limit concurrent connection.

Regards

**Comment by shogunpol** [comment] 2016-08-23 10:18
@opensourcecrm  , from what you saying it sounds like this is related with the password field, when editing existing group mail account, you have to reentered the password for functionality to work. Am I correct?

**Comment by opensourcecrm** [comment] 2016-08-27 05:15
yes seems the problem with password. when we first time entire the credentials its get connected with the test settings. once we save the record the inbound handle wont work it give you an error message in the log.and skip the mail box.  And i notice one more strange activity when your password is with Alfa Numeric and  Special characters the SuiteCRM wont authenticate the email address. But when we change the password with simple Alfa numeric combination (password123) its get connected. I reported this issue for both inbound handle as well as SMTP handle. Still waiting for fix for both the issues.

**Comment by ijdavie** [comment] 2016-09-26 08:03
There is known issues with the password field, #871, is this what was causing the problem you seen @opensourcecrm ?. if so can we close this issue as it would then be a duplicate of #871

**Comment by opensourcecrm** [comment] 2016-10-07 09:01
There are many issue with Email Either with SMTP or IMAP but we reported
those issues but no solution yet. please before closing make them point to
some open issue which is related to the problem.

**Comment by ijdavie** [comment] 2016-10-11 11:24
I have linked the related issues above, if there are more please added them in. I will close this being a duplicate of the above.

**Closed by ijdavie** 2016-10-11 11:24 UTC
Labels: bug, Pending Input
