### ISSUE TITLE
7.1.0 BETA 3

### ISSUE THREAD

**Issue by gray1st** [salesagility/SuiteCRM#4989] opened 2018-01-19 11:06 UTC
Can't add conditions onto a new workflow

Can't see conditions for an existing workflow

**Comment by PedroErnst** [comment] 2018-01-19 11:34
Hello @gray1st 

Thank you for taking the time to report this issue.

It does not appear to be obvious from your description what the issue is. Please follow the Github template for reporting issues that appears in the text box when you open the issue. It should (at the very least) include:

- A detailed description of the error
- Expected outcome
- Actual outcome
- Precise steps to reproduce the error
- Your environment

If you are not sure if this is an issue with the program or if it might be related to your setup, or if you require any help with using SuiteCRM, I suggest you [check out the forums](https://suitecrm.com/forum/index)

**Comment by gray1st** [comment] 2018-01-19 12:13
When trying to edit an existing Workflow, any conditions that were previously set don't appear within the 'Conditions' part of the screen (They do on the quickview)..  There is the option to Add Condition, but on pressing the button nothing happens (on either an existing workflow, or a new one).

I would expect to see existing conditions in the edit view

I would expect the Add Condition button to do something

I'm using 7.1.0 BETA 3

**Comment by pgorod** [comment] 2018-01-19 12:26
On my Beta3 the Edit view works fine, everything appears there, and I can add conditions and view existing ones.

It's the Detail view that doesn't show conditions, this looks like a bug.

**Comment by PedroErnst** [comment] 2018-01-19 12:28
@gray1st 
It seems to be working for me. We need more details in order to find the cause of this.

Is it a fresh install of beta 3 in an empty directory?
Localhost or web server?
Which module is the workflow related to?
Do you get anything in php SuiteCRM log / php error log / js console?
Which browser do you use?
Screenshots might be helpful too.

**Comment by gray1st** [comment] 2018-01-19 13:28
![ie vs firefox](https://user-images.githubusercontent.com/10898895/35152972-761a21be-fd1c-11e7-9e98-6133fc26b601.png)
Internet Explorer on top / Firefox on the bottom

In IE it isn't showing the Conditions within the view screen, but does in firefox



![ie vs firefox 2](https://user-images.githubusercontent.com/10898895/35152971-7603aff6-fd1c-11e7-91c5-40c4c6122055.png)
Firefox at top / Internet Explorer on the bottom

In IE it does allow you to edit the conditions within the edit screen, but you can't see the conditions in firefox

**Comment by PedroErnst** [comment] 2018-01-19 13:56
The issue with the condition lines not being visible in detailview is fixed now.

As for the IE issue, we will have to get someone with IE to look into it.

**Closed** 2018-01-24 12:30 UTC
Labels: Fix Proposed, Medium Priority, Resolved: Next Release, bug
