### ISSUE TITLE
MySQL error when creating campaign

### ISSUE THREAD

**Issue by roomer-ph** [salesagility/SuiteCRM#3163] opened 2017-02-20 12:17 UTC
tested on versions 7.7.9 and 7.8.1

#### Issue
It's not possible to create a Telesales, but probably any other type of campaign.

#### Expected Behavior
Adding a campaign

#### Actual Behavior
No campaign is created and no warning or error messages are shown.
In the log file there is an entry:
INSERT INTO campaigns (id,name,date_entered,date_modified,modified_user_id,created_by,deleted,assigned_user_id,tracker_count,refer_url,end_date,status,impressions,currency_id,campaign_type,frequency)
					VALUES ('fe0704c0-3755-8534-d9a3-58aad972f3cc','leads 2017','2017-02-20 11:56:48','2017-02-20 11:56:48','1','1',0,'680e356f-3eab-3445-89a2-4cfa5cf6e490',0,'http://','0000-00-00','Planning',0,'-99','Telesales',''): MySQL error 1292: Incorrect date value: '0000-00-00' for column 'end_date' at row 1
There's no field shown to enter the end date when creating the campaign so it should be omitted from the query.

**Comment by horus68** [comment] 2017-02-20 14:09
Take a look into https://github.com/salesagility/SuiteCRM/issues/1719 and https://github.com/salesagility/SuiteCRM/issues/1321

Note: when creating an issue please follow the template for issue creating.
You need to provide all the details on your SuiteCRm instance, like if you are using MySql 5.7 and so on

**Comment by roomer-ph** [comment] 2017-02-21 07:14
It's indeed a duplicate of the mentioned issues.

Currently i'm using version 7.8.1 on a mysql Server version: 5.7.17-0ubuntu0.16.04.1.
The sql_mode is set to ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DI...

**Comment by shogunpol** [comment] 2017-02-21 11:19
@roomer-ph , please provide all details about created campaign, it also did you st up cron and scheduler?

**Comment by pgorod** [comment] 2017-02-21 13:12
This really looks like it could just be closed, the OP already knows what's wrong, and how to fix it...

**Comment by shogunpol** [comment] 2017-02-21 13:14
(tag and Close issue)

Response - Thank you for highlighting this issue, however, this is a duplicate of issue #1719. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2017-02-21 13:14 UTC
