### ISSUE TITLE
Workflow Calculate Field Action Not working under PHP8

### ISSUE THREAD

**Issue by markbond1007** [salesagility/SuiteCRM#10115] opened 2023-07-17 13:49 UTC
#### Issue

When setting up a workflow (I've only tried on brand new Workflows) and selecting a Calculated field, the field options do not appear. Using Chrome Dev tools you can see that the url returns an error 500.

#### Expected Behavior

The editor should show the calculated fields edit panel

#### Actual Behavior

Blank panel, debugging shows an error in the actionComputeField line 453 about Count() requiring a parameter of type Countable, bool given.

Tracking back, in AOW_Workflow/controller.php action_getAction we have this:

`$params = array();
        if (isset($_REQUEST['id'])) {
            require_once('modules/AOW_Actions/AOW_Action.php');
            $aow_action = BeanFactory::newBean('AOW_Actions');
            $aow_action->retrieve($_REQUEST['id']);
            $id = $aow_action->id;
            $params = unserialize(base64_decode($aow_action->parameters));
        }`

the urls all have `...&id=&`

under PHP8 this still classes as set so params will be the result of the last line above.

#### Possible Fix

change the first lines to the below, this will also stop possible issues for other actions and prevent running this code when uneccessary.

`$params = array();
        if (isset($_REQUEST['id']) && strlen(trim($_REQUEST['id'])) > 0 ) {`

#### Steps to Reproduce

1. Create new Workflow
2. Select Module type (any but say Account for testing)
3. Add Action
4. Select Calculate Field

#### Context

high Priority given that PHP8 is a priority.

#### Your Environment

* SuiteCRM Version used: 7.13.3 & 8.3.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome  114.0.5735.198 (Official Build) (x86_64)
* Environment name and version (e.g. MySQL, PHP 7): PHP8.0
* Operating System and version (e.g Ubuntu 16.04): Debian

**Comment by johnM2401** [comment] 2023-07-18 08:13
Hey
Thanks for getting in touch!

For reference sake, this is likely a duplicate of: https://github.com/salesagility/SuiteCRM-Core/issues/93

Thanks!

**Comment by chris001** [comment] 2023-07-19 21:04
@markbond1007 Can you make a PR with your fixed code line?

**Closed** 2023-10-30 10:12 UTC
Labels: Type:Bug, Status:Fix Proposed, Type:Duplicate, Priority:Important, Area: Workflow, Area: PHP8
