### ISSUE TITLE
Salutation variable in campaigns displays item name instead of value 7.10.4 

### ISSUE THREAD

**Issue by viking68** [salesagility/SuiteCRM#5771] opened 2018-04-23 15:37 UTC
After upgrading to 7.10.4 the variable $contact_salutation links to the the internal item name in the dropdown menu, not the actual value (display label). This only happens with campaigns. When using the same template with the internal mail client, $contact_salutation correctly shows the value on the receiver side.

#### Expected Behavior
Campaign receivers should see the value for the variable $contact_salutation (e.g. "Herr").

#### Actual Behavior
Campaign receivers see the item name for the variable $contact_salutation (e.g. "Hr.").

#### Steps to Reproduce
1. In the contact_salutation dropdown menu, there are values not identical to the internal item name (e.g. Item Name = Hr, Display Name = Herr)
2. Create a template with the $contact_salutation variable
3. Use the template within a campaign
4. The receiver will see the Item Name, not the value

#### Your Environment
* SuiteCRM Version used: 7.10.4
* Browser name and version: Safari Version 11.0.2 (13604.4.7.1.3), Chrome Version 66.0.3359.117 (Official Build) (64-Bit)
* Environment name and version: MariaDB, PHP 7.1.16 FastCGI
* Operating System and version: Debian 9.4

**Comment by pgorod** [comment] 2018-04-29 18:27
What kinds of people do you have in the Target List used in the Campaign? Are they Contacts, or another kind (Leads, Targets, Accounts, Users)?

**Comment by viking68** [comment] 2018-04-30 08:33
Contacts

**Comment by pgorod** [comment] 2018-04-30 10:18
Maybe this is a duplicate of #3321

If so, then the scope of this bug is larger (thus deserving the `Medium priority` label that other issue has).

**Comment by mbennoer** [comment] 2018-06-12 13:48
No, this is not a duplicate of #3321. It is not a matter of a variable not being replaced at all, but rather being replaced wrong (internal name instead of display name). Unfortunately I have exactly the same problem as viking68, and this bug makes it impossible to send out campaigns for us.

**Comment by mbennoer** [comment] 2018-06-13 07:58
Good morning @pgorod, thank you for your reply. Indeed, #5964 sounds like the same or at least similar issue. Since I'm new to github, could you tell me how to try the fix? Do I need to exchange the EmailTemplateParser.php in our installation, and where exactly can I find the fixed file?

**Comment by viking68** [comment] 2018-06-13 09:09
The fixed file is at "Files changed". Click on "View". You can copy it and paste/replace it into your installation. You might set write permissions before.

**Comment by viking68** [comment] 2018-06-13 09:31
[#5964](https://github.com/salesagility/SuiteCRM/pull/5964) fix did not solve the problem for me.

**Comment by mbennoer** [comment] 2018-06-14 07:42
@viking68 thank you for testing. Maybe @zoltankocsardi is able to help finding a fix if the bug is related to #5944

**Comment by mbennoer** [comment] 2018-08-27 09:45
Hello everyone, any news on this bug? I couldn't find any corresponding fixes in the 7.10.7 release notes, so does it still persist? Sending out mailings in 7.10.6 is nearly impossible, why is the issue labelled "low priority"?

**Comment by mbennoer** [comment] 2018-09-28 08:45
7.10.9 - Bug persists. Is it just me and @viking68 having these problems? As a workaround we've created normal text field with the complete salutation, but we're still waiting for a proper fix.

**Comment by pgorod** [comment] 2018-09-28 09:38
I heard on the forums that this happens with every dropdown-style field, where the value needs to be translated to a string. If somebody can check this we could at least make this Issue a higher priority.

**Comment by EZS-JD** [comment] 2018-10-14 17:08
I can confirm this happens with every dropdown-style field (as indicated in #6345 

Please give this medium priority at least.

**Comment by micker** [comment] 2018-10-16 15:47
Yes for me same all variables doesnt work un email like quote_name etc

**Comment by micker** [comment] 2018-10-19 08:20
for me its a hight priority lol

**Comment by Dillon-Brown** [comment] 2018-10-19 08:56
Hi @micker, it's being looked at :). You can expect a fix soon.

**Comment by micker** [comment] 2018-10-19 08:58
+10000 thanks

**Comment by micker** [comment] 2018-11-12 11:32
hello thtat solve all variable in email ??

**Closed as completed** 2019-01-14 14:28 UTC
Labels: Type: Bug, Priority:Important, Area: Campaigns
