### ISSUE TITLE
"Group " option not working properly in Suite 7.6.4 ( Reports Module )

### ISSUE THREAD

**Issue by phanik18** [salesagility/SuiteCRM#1553] opened 2016-06-04 05:33 UTC
"Group " option not working in 7.6.4 version .

**Query Trace:** 

SELECT `opportunities`.assigned_user_id AS 'Assigned_to0', COUNT(`opportunities`.id) AS 'ID1' FROM `opportunities`  WHERE opportunities.deleted = 0  GROUP BY `opportunities`.assigned_user_id, `opportunities`.id LIMIT 0,20

SELECT count(*) c FROM (SELECT `opportunities`.assigned_user_id AS 'Assigned_to0', COUNT(`opportunities`.id) AS 'ID1' FROM `opportunities`  WHERE opportunities.deleted = 0  GROUP BY `opportunities`.assigned_user_id, `opportunities`.id) as n

**Report Design**

![image](https://cloud.githubusercontent.com/assets/6194856/15797882/b7a84082-2a43-11e6-8cb3-00d2d3c29f25.png)

**Report Output**

![image](https://cloud.githubusercontent.com/assets/6194856/15797886/db9e2f06-2a43-11e6-9502-9ddb2a1b2989.png)

**Comment by mattlorimer** [comment] 2016-06-04 09:06
duplicate of #1519

**Closed by mattlorimer** 2016-06-04 09:06 UTC
Labels: duplicate

**Comment by phanik18** [comment] 2016-06-04 16:15
Thanks Mattlorimer . it is working fine now after applying the fix .
