### ISSUE TITLE
DateTime calendar popup button & manual edit of data entry doesn't work in 7.9.10

### ISSUE THREAD

**Issue by bunk3m** [salesagility/SuiteCRM#5029] opened 2018-01-26 00:00 UTC
#### Issue
The pop-up calendar button doesn't function.
You are able to manually add the date portion but not the time.
So you can't add any datetime to any task.

This also happens in the create Call screen.

See picture.
<img width="174" alt="screen shot 2018-01-25 at 17 43 45" src="https://user-images.githubusercontent.com/3494567/35418442-3c7e5be4-0200-11e8-9484-56dc45b90dd3.png">

#### Expected Behavior
As in past versions, you should be able to select the date & time in the pop-up calendar or manually add the date & time.

#### Actual Behavior
Can't add the date or time in a task or call

#### Possible Fix
Haven't found any.

#### Steps to Reproduce
1. Create a new Task (Call) from a drop down or edit a task (call).  You will see that there are }} braces above the datetime entry dialog box.  
2. Try to click on the calendar icon
3. Try to add date & time in the dialog box

#### Context
I can't change or add any calls or tasks.  This is a major issue.

#### Your Environment
This happens using Mac versions of Chrome Version 63.0.3239.132 (Official Build) (64-bit); Firefox 58.0 (64-bit)
SuiteCRM 7.9.10
Debian 9; Apache 2.4.25; mysql  Ver 15.1 Distrib 10.1.26-MariaDB; PHP 7.0.27

**Comment by ksmith892** [comment] 2018-01-26 08:52
The problem appears to have been caused by additions to the template code in:

/var/www/suitecrm/suitecrm/include/SugarFields/Fields/Datetimecombo/EditView.tpl

Lines 45 - 51 are new additions in version 7.9.10, and I belive the issue is cause by the template delimiters around line 49-50. I don't know enough Smarty Templating to work out the correct fix for this. But I believe it is being caused by a mismatch between single and double curly brackets on thoxse lines.

**Comment by ksmith892** [comment] 2018-01-26 18:24
This fixes the issue when there is a single DateTimeCombo on the form, however it doesn't fix the issue when there is a second DateTimeCombo box underneath it i.e. on a meeting or task form.

**Comment by pgorod** [comment] 2018-01-26 18:41
I'm getting this same issue on 7.8.11 in the Create Event screen, which also has two dates and is currently unusable.

**Comment by okoester** [comment] 2018-01-27 11:42
Also getting this error in Tasks view when trying to create a task.
Still after applying Dillon Browns fix.

In Firefox developer console I see these errors referencing to a cached javascript...

`error adding script
sugar_grp1.js:453:76
SyntaxError: missing ( before formal parameters
Stack trace:
globalEval/<@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:141
globalEval@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:107
evalScript@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:452:6
callback@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:653:87
handleTransactionResponse@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:4420
handleReadyState/this._poll[c.tId]<@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:3933
sugar_grp1.js:453:111
Array [ "<script type=\"text/javascript\">\nfunction set_{Array.date_start.name_values(form) {\n if(form.{Array.date_start.name_flag.checked)  {\n\tform.{Array.date_start.name_flag.value=1;\n\tform.{Array.date_start.name.value=\"\";\n\tform.{Array.date_start.name.readOnly=true;\n } else  {\n\tform.{Array.date_start.name_flag.value=0;\n\tform.{Array.date_start.name.readOnly=false;\n }\n}\n</script>", " type=\"text/javascript\"", "\nfunction set_{Array.date_start.name_values(form) {\n if(form.{Array.date_start.name_flag.checked)  {\n\tform.{Array.date_start.name_flag.value=1;\n\tform.{Array.date_start.name.value=\"\";\n\tform.{Array.date_start.name.readOnly=true;\n } else  {\n\tform.{Array.date_start.name_flag.value=0;\n\tform.{Array.date_start.name.readOnly=false;\n }\n}\n", "\n" ]
sugar_grp1.js:453:126
error adding script
sugar_grp1.js:453:76
SyntaxError: missing ; before statement
Stack trace:
globalEval/<@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:141
globalEval@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:107
evalScript@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:452:6
callback@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:653:87
handleTransactionResponse@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:4420
handleReadyState/this._poll[c.tId]<@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:3933
sugar_grp1.js:453:111
Array [ "<script type=\"text/javascript\">\nvar combo_{Array.date_start.name = new Datetimecombo(\"\", \"{Array.date_start.name\", \"23:00\", \"0\", '1', false, true);\n//Render the remaining widget fields\ntext = combo_{Array.date_start.name.html('');\ndocument.getElementById('{Array.date_start.name_time_section').innerHTML = text;\n\n//Call eval on the update function to handle updates to calendar picker object\neval(combo_{Array.date_start.name.jsscript(''));\n\naddToValidateBinaryDependency('EditView',\"{Array.date_start.name_hours\", 'alpha', false, \"Fehlendes Pflichtfeld: Stunden\" ,\"{Array.date_start.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_start.name_minutes\", 'alpha', false, \"Fehlendes Pflichtfeld: Minuten\" ,\"{Array.date_start.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_start.name_meridiem\", 'alpha', false, \"Fehlendes Pflichtfeld: Süden\",\"{Array.date_start.name_date\");\n\nYAHOO.util.Event.onDOMReady(function()\n{\n\n\tCalendar.setup ({\n\tonClose : update_{Array.date_start.name,\n\tinputField : \"{Array.date_start.name_date\",\n    form : \"EditView\",\n\tifFormat : \"%d.%m.%Y %H:%M\",\n\tdaFormat : \"%d.%m.%Y %H:%M\",\n\tbutton : \"{Array.date_start.name_trigger\",\n\tsingleClick : true,\n\tstep : 1,\n\tweekNumbers: false,\n        startWeekday: 1,\n\tcomboObject: combo_{Array.date_start.name\n\t});\n\n\t//Call update for first time to round hours and minute values\n\tcombo_{Array.date_start.name.update(false);\n\n}); \n</script>", " type=\"text/javascript\"", "\nvar combo_{Array.date_start.name = new Datetimecombo(\"\", \"{Array.date_start.name\", \"23:00\", \"0\", '1', false, true);\n//Render the remaining widget fields\ntext = combo_{Array.date_start.name.html('');\ndocument.getElementById('{Array.date_start.name_time_section').innerHTML = text;\n\n//Call eval on the update function to handle updates to calendar picker object\neval(combo_{Array.date_start.name.jsscript(''));\n\naddToValidateBinaryDependency('EditView',\"{Array.date_start.name_hours\", 'alpha', false, \"Fehlendes Pflichtfeld: Stunden\" ,\"{Array.date_start.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_start.name_minutes\", 'alpha', false, \"Fehlendes Pflichtfeld: Minuten\" ,\"{Array.date_start.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_start.name_meridiem\", 'alpha', false, \"Fehlendes Pflichtfeld: Süden\",\"{Array.date_start.name_date\");\n\nYAHOO.util.Event.onDOMReady(function()\n{\n\n\tCalendar.setup ({\n\tonClose : update_{Array.date_start.name,\n\tinputField : \"{Array.date_start.name_date\",\n    form : \"EditView\",\n\tifFormat : \"%d.%m.%Y %H:%M\",\n\tdaFormat : \"%d.%m.%Y %H:%M\",\n\tbutton : \"{Array.date_start.name_trigger\",\n\tsingleClick : true,\n\tstep : 1,\n\tweekNumbers: false,\n        startWeekday: 1,\n\tcomboObject: combo_{Array.date_start.name\n\t});\n\n\t//Call update for first time to round hours and minute values\n\tcombo_{Array.date_start.name.update(false);\n\n}); \n", "\n" ]
sugar_grp1.js:453:126
error adding script
sugar_grp1.js:453:76
SyntaxError: missing ( before formal parameters
Stack trace:
globalEval/<@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:141
globalEval@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:107
evalScript@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:452:6
callback@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:653:87
handleTransactionResponse@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:4420
handleReadyState/this._poll[c.tId]<@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:3933
sugar_grp1.js:453:111
Array [ "<script type=\"text/javascript\">\nfunction set_{Array.date_due.name_values(form) {\n if(form.{Array.date_due.name_flag.checked)  {\n\tform.{Array.date_due.name_flag.value=1;\n\tform.{Array.date_due.name.value=\"\";\n\tform.{Array.date_due.name.readOnly=true;\n } else  {\n\tform.{Array.date_due.name_flag.value=0;\n\tform.{Array.date_due.name.readOnly=false;\n }\n}\n</script>", " type=\"text/javascript\"", "\nfunction set_{Array.date_due.name_values(form) {\n if(form.{Array.date_due.name_flag.checked)  {\n\tform.{Array.date_due.name_flag.value=1;\n\tform.{Array.date_due.name.value=\"\";\n\tform.{Array.date_due.name.readOnly=true;\n } else  {\n\tform.{Array.date_due.name_flag.value=0;\n\tform.{Array.date_due.name.readOnly=false;\n }\n}\n", "\n" ]
sugar_grp1.js:453:126
error adding script
sugar_grp1.js:453:76
SyntaxError: missing ; before statement
Stack trace:
globalEval/<@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:141
globalEval@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:445:107
evalScript@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:452:6
callback@http://crm.kits.loc/cache/include/javascript/sugar_grp1.js?v=fPRnLbveJ3Q0eGIZalB4ig:653:87
handleTransactionResponse@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:4420
handleReadyState/this._poll[c.tId]<@http://crm.kits.loc/cache/include/javascript/sugar_grp1_yui.js?v=fPRnLbveJ3Q0eGIZalB4ig:55:3933
sugar_grp1.js:453:111
Array [ "<script type=\"text/javascript\">\nvar combo_{Array.date_due.name = new Datetimecombo(\"\", \"{Array.date_due.name\", \"23:00\", \"0\", '1', false, true);\n//Render the remaining widget fields\ntext = combo_{Array.date_due.name.html('');\ndocument.getElementById('{Array.date_due.name_time_section').innerHTML = text;\n\n//Call eval on the update function to handle updates to calendar picker object\neval(combo_{Array.date_due.name.jsscript(''));\n\naddToValidateBinaryDependency('EditView',\"{Array.date_due.name_hours\", 'alpha', false, \"Fehlendes Pflichtfeld: Stunden\" ,\"{Array.date_due.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_due.name_minutes\", 'alpha', false, \"Fehlendes Pflichtfeld: Minuten\" ,\"{Array.date_due.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_due.name_meridiem\", 'alpha', false, \"Fehlendes Pflichtfeld: Süden\",\"{Array.date_due.name_date\");\n\nYAHOO.util.Event.onDOMReady(function()\n{\n\n\tCalendar.setup ({\n\tonClose : update_{Array.date_due.name,\n\tinputField : \"{Array.date_due.name_date\",\n    form : \"EditView\",\n\tifFormat : \"%d.%m.%Y %H:%M\",\n\tdaFormat : \"%d.%m.%Y %H:%M\",\n\tbutton : \"{Array.date_due.name_trigger\",\n\tsingleClick : true,\n\tstep : 1,\n\tweekNumbers: false,\n        startWeekday: 1,\n\tcomboObject: combo_{Array.date_due.name\n\t});\n\n\t//Call update for first time to round hours and minute values\n\tcombo_{Array.date_due.name.update(false);\n\n}); \n</script>", " type=\"text/javascript\"", "\nvar combo_{Array.date_due.name = new Datetimecombo(\"\", \"{Array.date_due.name\", \"23:00\", \"0\", '1', false, true);\n//Render the remaining widget fields\ntext = combo_{Array.date_due.name.html('');\ndocument.getElementById('{Array.date_due.name_time_section').innerHTML = text;\n\n//Call eval on the update function to handle updates to calendar picker object\neval(combo_{Array.date_due.name.jsscript(''));\n\naddToValidateBinaryDependency('EditView',\"{Array.date_due.name_hours\", 'alpha', false, \"Fehlendes Pflichtfeld: Stunden\" ,\"{Array.date_due.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_due.name_minutes\", 'alpha', false, \"Fehlendes Pflichtfeld: Minuten\" ,\"{Array.date_due.name_date\");\naddToValidateBinaryDependency('EditView', \"{Array.date_due.name_meridiem\", 'alpha', false, \"Fehlendes Pflichtfeld: Süden\",\"{Array.date_due.name_date\");\n\nYAHOO.util.Event.onDOMReady(function()\n{\n\n\tCalendar.setup ({\n\tonClose : update_{Array.date_due.name,\n\tinputField : \"{Array.date_due.name_date\",\n    form : \"EditView\",\n\tifFormat : \"%d.%m.%Y %H:%M\",\n\tdaFormat : \"%d.%m.%Y %H:%M\",\n\tbutton : \"{Array.date_due.name_trigger\",\n\tsingleClick : true,\n\tstep : 1,\n\tweekNumbers: false,\n        startWeekday: 1,\n\tcomboObject: combo_{Array.date_due.name\n\t});\n\n\t//Call update for first time to round hours and minute values\n\tcombo_{Array.date_due.name.update(false);\n\n}); \n", "\n" ]
sugar_grp1.js:453:126
`
(Please dont mind german translations. I've checked also in en_US locale. Same error)

**Closed** 2018-01-27 16:22 UTC
Labels: Fix Proposed, High Priority, Resolved: Next Release, bug
