### ISSUE TITLE
Email Variable Merge Not Working for Some Variables

### ISSUE THREAD

**Issue by bennnjamin** [salesagility/SuiteCRM#2292] opened 2016-09-22 18:18 UTC
It seems that some variables when inserted into an email template do not actually populate when the email is sent and is related to a relevant record.

#### Issue

I'm not sure if this is a bug or not since I can't find any other reports on it. For what it's worth, merging some variables in email has never worked 100% for me in the year or so I've been using SuiteCRM.

This appears to not work for every single variable I've tried so either it is a very serious bug or my installation is seriously corrupted.

#### Expected Behavior

The email should be received the the variables replaced by the record's corresponding fields.

#### Actual Behavior

The variables are sent in plaintext instead. 

#### Steps to Reproduce

1.  Create an email template like this

![template](https://cloud.githubusercontent.com/assets/10929253/18760260/2df2239e-80b5-11e6-898e-54e6191cecd0.png)

2. Send an email from an Opportunity
3. Observe in your inbox it looks like this
![email](https://cloud.githubusercontent.com/assets/10929253/18760304/50853d6a-80b5-11e6-9f21-3297c51f4e25.png)

#### Context

High priority - email templates that relate to records are unusable. Email templates can be only be used if they do not embed any information about the record directly in the email.

#### Your Environment

* SuiteCRM Version used: 7.7.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 53.0.2785.116 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.6.20, mysql  Ver 15.1
* Operating System and version (e.g Ubuntu 16.04): Debian GNU/Linux 8

**Comment by ijdavie** [comment] 2016-09-23 14:55
This is a duplicate of #1366

**Closed by ijdavie** 2016-09-23 14:55 UTC
Labels: bug, High Priority

**Comment by crmwa-marjhun** [comment] 2017-03-31 01:07
Hi Guys,

Any updates regarding the issue for field mappings?

Regards!

**Comment by chris001** [comment] 2017-03-31 01:26
@crmwa-marjhun  Check #2562 #2659 #3306 for fixes to test.

**Comment by crmwa-marjhun** [comment] 2017-03-31 01:35
Thank you @chris001,  will try that.

Regards!

**Comment by crmwa-marjhun** [comment] 2017-03-31 02:36
Hi @chris001,

I tried the fixes but it didn't fix my issue while sending email in Opportunity module using a template with variables defined on it. The variable are not parsed and sent only in plain text.
Any other thoughts for this?

Thanks!

**Comment by chris001** [comment] 2017-03-31 08:31
@crmwa-marjhun If you're able to edit your php file, you could try manually applying #2562.
@daniel-samson  Your PR #2562 should fix this bug #2292 right?
@samus-aran  Any idea why merge #2562 hasn't happened yet?
