### ISSUE TITLE
dashlet navigation broken 7.7.4

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#2263] opened 2016-09-20 14:13 UTC
I just upgraded from 7.6.5 to 7.7.4
Now using _any_ theme EXCEPT Suite P the navigation no longer works.
BUT using Suite P it works...  Most users won't use Suite P because of the distance between controls, many are still using classic theme!
tried with Chrome, I.E, 11... on 2 systems, dev and production instances, even tried with fresh test instance, not an upgrade.....
I tried repair all possible choices from admin menu
even tried from iphone so not related to c

as first reported on forum
https://suitecrm.com/forum/suitecrm-7-0-discussion/11234-dashlet-navigation-broken#38331
John confirmed that this is a bug

it is the reason of having dashlet, to quickly navigate trought module list

now, clicking on next prev icon does ot do anything

we are running 7.7.4, on win 2008 IIs server with Mssql 2012
also tried on dev machine similar but win 10 
this is not related to browser, tried ie and chrome

thank you

**Comment by shogunpol** [comment] 2016-09-21 07:45
I tested the issue on recent version of SuiteCRM(7.7.4), and it not appear.
@bmwtourer , can you give me more details, to help us to replicate the issue. For example:
which particular dashlet, 
step by step how to reproduce the bug, 
environment: PHP version and anything what can help
Thanks for raise this issue.

**Comment by bmwtourer** [comment] 2016-09-21 13:00
thank you for looking at this really disturbing issue for the users.
it does not seem to be related to a module, I would be surprised if it is related to my environment because if I go to the demo page, I am experiencing the very same issue.
[http://demo.suiteondemand.com/index.php?module=Home&action=index](url)

As you can see, the focus is on the button if I click nothing happens
![image](https://cloud.githubusercontent.com/assets/9001018/18711464/15de64c6-7fd8-11e6-99a1-820c216c796d.png)

*** but you need to go back to Suite R theme, actually anything but Suite P,  
My personal dev environment is in Canadian French so was the first user that reported it.
BUT this morning Michelle from our UK office just complained about it... she is using standard windows installation from our UK office, nothing related to French which she does not speak...

but just in case :
Chrome Version 53.0.2785.116 m (64-bit)
![image](https://cloud.githubusercontent.com/assets/9001018/18711338/7b53d210-7fd7-11e6-8d7c-912a602d9104.png)
the server is Win2008 (english) IIs PHP 5.6 Mssql

I also tried from an english windows 7 pro english installation
and in a terminal server session win2012 R2 english with Chome up to date browser

**Comment by terrymatzff** [comment] 2016-09-21 14:27
We are also experiencing the same issue since upgrading to 7.7.4. We are running SuiteCRM 7.7.4 and using the SuiteR theme. The pagination navigation doesn't work on any dashlets we have tried - My Activity Stream, My Open Tasks, etc. I have also experienced a similar problem in the SuiteP theme with Report dashlets, though the My Activity Stream pagination seems to work. 
The browsers we have checked are  Google Chrome Version 53.0.2785.116 m and Firefox 48.0.2
Our server is running on Ubuntu 14.04 LTS

**Comment by staganyi** [comment] 2016-09-21 15:42
I can also confirm the pagination on dashlets does not work with Suite7 theme. It does work with SuiteP. Using an upgraded v7.7.4 instance.

**Comment by dursuntosun** [comment] 2016-09-22 14:51
I can also confirm the pagination on dashlets does not work with Suite7 theme. My version is v7.7.4

**Comment by brunohass** [comment] 2016-09-23 20:45
+1

Version 7.7.4

Running some tests I've found that the possible cause for this was introduced in c92b41ce85a730b0e3a5194e0900d04902de4b47 ([here](https://github.com/salesagility/SuiteCRM/commit/c92b41ce85a730b0e3a5194e0900d04902de4b47#diff-1db7be61d235a0978a606461ed22ab0fR54) and [here](https://github.com/salesagility/SuiteCRM/commit/c92b41ce85a730b0e3a5194e0900d04902de4b47#diff-d9bd8825485bb9e909b957835a0ef5ecR246)).

So, you have something like this:

`$('#' + SUGAR.mySugar.currentDashlet.id).closest('.tab-pane').html(data.responseText);`

The problem is with `.closest('.tab-pane')`.

If you change to this: 

`$('#' + SUGAR.mySugar.currentDashlet.id).html(data.responseText);`

Suite 7 and Suite R start working :-)

**Comment by bmwtourer** [comment] 2016-09-26 13:35
@brunohass : Thank you!

I found the problematic line 246 in jssource/src_files/include/MySugar/javascript/MySugar.js
and added a remark to it ("//")
I then copied below your proposition and Bingo it was working.

I do not know why in my dev environment (where I use IE as client) , it appeared that the modification was not recognised automatically I tried to "Repair JS Files Repair JS Files = Compresses Existing JS files - includes any changes made, but does not overwrite original JS Source files  " from Admin menu and then the fix was working. I was logged in before the modification so may be the file was in my IE cache.
*** Although on my production instance after coping the file from my dev and login in (using Chrome this time) the fix seemed to be applied automatically...

The dashlet navigation works fine now in dev and prod...

Thank you again Bruno

**Comment by bmwtourer** [comment] 2016-10-24 15:07
This problem appears to be solved but with a different wrong behavior 
as reported in #2479

**Comment by sieberta** [comment] 2016-10-28 11:52
@bmwtourer, I think this has been closed prematurely.

After my upgrade from 7.7.4 to 7.7.6, this issue still exists with the original behavior, not the new behavior indicated in #2479.

sieberta

**Comment by bmwtourer** [comment] 2016-10-28 15:06
For me it is cleared,
but sieberta indicates he still have the problem and refrened it to #2304

**Comment by staganyi** [comment] 2016-11-08 17:49
This appears to be fixed in 7.7.7

**Comment by samus-aran** [comment] 2016-11-14 22:22
This should be resolved in the 7.7.7 release as completed by this PR
https://github.com/salesagility/SuiteCRM/issues/2548

Feel free to re-open the issue if this has not been resolved.

**Closed by samus-aran** 2016-11-14 22:22 UTC
Labels: bug, Fix Proposed, Medium Priority
