### ISSUE TITLE
SuiteCRM Report Date Parameter

### ISSUE THREAD

**Issue by HMahboob** [salesagility/SuiteCRM#3389] opened 2017-04-12 11:09 UTC
#### Issue

I have created a report that takes the date as parameter from the user and runs the report for that date. The problem is that after selecting the required date (field shows as dd/mm/yyyy) and clicking update, the system takes the date as mm/dd/yyyy and process as such. And everytime I click on Update button, it switches the date format.

For example, I select 1st April, field shows 04/01/2017.
When I click update, the field now displayed 01/04/2017.
Clicking the update button again, field displays 04/01/2017.

Kindly help.

#### Your Environment

* SuiteCRM Version used: Version 7.5.5 (Sugar Version 6.5.23)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Operating System and version (e.g Ubuntu 16.04): Windows 10

**Comment by Dillon-Brown** [comment] 2017-04-18 15:59
@HMahboob This looks like a duplicate of #1624. It seems that the date parameter only accepts format 2017-04-18 and if the user has a different date format the report wont work with the new parameters.

**Closed** 2017-04-18 16:01 UTC
Labels: duplicate
