### ISSUE TITLE
Checkbox not parsing in SuiteCRM 7..4.3 reports

### ISSUE THREAD

**Issue by CRMConsultant** [salesagility/SuiteCRM#945] opened 2016-02-11 04:39 UTC
Hi 

We are generating a report in suitecrm. everything is working fine but its not parsing the checkbox value in both export and download pdf action.

**Comment by samus-aran** [comment] 2016-02-15 11:17
This could be related - #592

**Comment by recci** [comment] 2016-06-10 13:56
These were two separate issues. I fixed both. One is #517.

**Comment by ijdavie** [comment] 2016-09-23 14:54
This is a duplicate of #517 and #592.

**Closed by ijdavie** 2016-09-23 14:54 UTC
Labels: bug
