### ISSUE TITLE
Problem with HTML e-mails for Cases - Showing HTML codes instead of rendering it

### ISSUE THREAD

**Issue by Arkys9009** [salesagility/SuiteCRM#1643] opened 2016-06-23 19:51 UTC
Hello,

We have a problem with our SuiteCRM Version 7.5.3 - Sugar Version 6.5.23 (Build 1061).

When a Cases is assigned to a user, the e-mail received is in HTML code instead of showing the HTML rendering of the e-mail.

We've searched in the forums and the problem was present in version 7.1 and 7.3. I've tried the fixes suggested on these forums, but they won't work with version 7.5.3.

Is there a fix for this?

Thank you.

**Patrick Lagrange
ITC Coordinator
Arkys Web Software Inc.**

**Comment by Mausino** [comment] 2016-06-23 20:21
maybe duplicate of #398

**Closed** 2016-06-23 20:28 UTC
Labels: duplicate

**Comment by Arkys9009** [comment] 2016-06-27 18:24
Did the quick repair and rebuild after the modifications... Tried it and it still doesn't work...

This is what we get as a response e-mail when a case is assigned to someone : 

John Smith has assigned a Case to Non-Assigné.

Subject: Test de courriel #3
Priority: High
Status: New
Description: 
<div class="WordSection1">
<p class="MsoNormal">Test #3… Tonnerre de Brest!!!</p><p></p> <p class="MsoNormal"></p><p> </p> <p class="MsoNormal"><span lang="en-us" style="color:#000055;">Cordialement,</span></p><p></p>
<p class="MsoNormal"><span style="font-size:8pt;font-family:Arial, sans-serif;"></span></p><p> </p> <table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tbody><tr style="height:110.4pt;"><td width="224" valign="top" style="width:168.3pt;padding:0cm 5.4pt 0cm 5.4pt;height:110.4pt;"> <p class="MsoNormal"><a href="http://www.arkys.com/"><span style="text-decoration:none;"><img border="0" width="210" height="139" style="width:2.1875in;height:1.4479in;" id="sugar_text_Image_x0020_3" class="image" src="http://suitecrm.arkys.com/index.php?entryPoint=download&id=90405984-2d9e-b451-00cf-57716d2d561f&type=Notes&.jpeg" alt="cid:image008.jpg@01D172FB.347F97F0" /></span></a><span></span></p><p></p>
</td>
<td width="333" valign="top" style="width:249.9pt;padding:0cm 5.4pt 0cm 5.4pt;height:110.4pt;"> <p class="MsoNormal"><b><span lang="en-us" style="font-family:Arial, sans-serif;color:#000055;">Patrick Lagrange</span></b></p><p><b></b></p><b></b>
<p class="MsoNormal"><span lang="en-us" style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;">Coordonnateur TIC / ICT Coordinator</span></p><p></p> <p class="MsoNormal"><span lang="en-us" style="font-size:8pt;font-family:Arial, sans-serif;color:#000055;"></span></p><p> </p> <p class="MsoNormal"><span lang="en-us" style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;">1-877-874-9009 # 2013</span></p><p></p> <p class="MsoNormal"><span lang="en-us" style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;">plagrange@arkys.com</span></p><p></p>
<p class="MsoNormal"><span lang="en-ca" style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;"><a href="http://www.arkys.com/"><span style="color:#0563C1;">www.arkys.com</span></a></span><span lang="en-ca" style="font-size:10pt;font-family:Arial, sans-serif;color:#000080;"></span></p><p></p>
<p class="MsoNormal"><span lang="en-ca" style="font-size:8pt;font-family:Arial, sans-serif;color:#000080;"></span></p><p> </p> <p class="MsoNormal"><span lang="en-us" style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;">SUPPORT TI / IT SUPPORT :
</span><span style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;"><a href="mailto:support@arkys.com"><span lang="en-us" style="color:#000055;">support@arkys.com</span></a></span><span lang="en-ca" style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;"></span></p><p></p>
<p class="MsoNormal"><b><span style="font-size:10pt;font-family:Arial, sans-serif;color:#FF0000;">URGENCES / EMERGENCIES :</span></b><span style="font-size:10pt;font-family:Arial, sans-serif;color:#FF0000;"> </span><b><span style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;">1-877-874-9009</span></b><span style="font-size:10pt;font-family:Arial, sans-serif;color:#000055;"> </span><b><span style="font-size:10pt;font-family:Arial, sans-serif;color:#C00000;">#500</span></b></p><p><b></b></p><b></b>
<p class="MsoNormal"><span></span></p><p> </p> </td> </tr></tbody></table><p class="MsoNormal"><span style="font-size:8pt;font-family:Arial, sans-serif;"></span></p><p> </p> <p class="MsoNormal"></p><p> </p> </div>


You may review this Case at:
<http://suitecrm.arkys.com/index.php?module=Cases&action=DetailView&record=5cc3c710-000a-2566-531d-57716d3f16d1>

**Comment by Arkys9009** [comment] 2016-06-27 18:29
Hi,

Did the modifications in the threads, did Quick Repair and Rebuilt and still doesn’t work.

See attached image file of an examble of the email we receive when a Case is assigned to someone.

Please come back to me on this.

Thank you.

Cordialement,

[cid:image008.jpg@01D172FB.347F97F0]<http://www.arkys.com/>

Patrick Lagrange
Coordonnateur TIC / ICT Coordinator

1-877-874-9009 # 2013
plagrange@arkys.com
www.arkys.com<http://www.arkys.com/>

SUPPORT TI / IT SUPPORT : support@arkys.com<mailto:support@arkys.com>
URGENCES / EMERGENCIES : 1-877-874-9009 #500




De : Miky Mikolaj [mailto:notifications@github.com]
Envoyé : 23 juin 2016 16:21
À : salesagility/SuiteCRM <SuiteCRM@noreply.github.com>
Cc : Support-CRM <Support-CRM@arkys.com>; Author <author@noreply.github.com>
Objet : Re: [salesagility/SuiteCRM] Problem with HTML e-mails for Cases - Showing HTML codes instead of rendering it (#1643)


maybe duplicate of #398<https://github.com/salesagility/SuiteCRM/issues/398>
