### ISSUE TITLE
The new record can't take any data from choosed WorkFlow Module

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1990] opened 2016-08-19 13:51 UTC
#### Issue

I want create some check calls for the own reservation module in case if the Reservation will end, and i need to check if everything in accommodation was ok.  The problem is, that i can't define (set up) by normal way without hardcoding the situation, how can the new created module take same DATE, in my case the END day in (from) Reservation module, that call can be schnedulled on time & date when my Reservation record finished.
#### Expected Behavior

I will have some possiblity to take (choose) the data like time, date or others from Workflow module
#### Actual Behavior

:D without hardcode no possible
#### Your Environment

- SuiteCRM Version used:
- Browser name and version: Chrome Version dev-53.0.2704.63 (64-bit)):
- Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.6
- Operating System and version (e.g Ubuntu 16.04): Linux on hosting

Here is image which i sent to my developer. It is ilustrating the problem with End Day

![end_day](https://cloud.githubusercontent.com/assets/5773777/17811728/56d60966-6624-11e6-86f3-cd9020c4a492.png)

**Comment by shogunpol** [comment] 2016-08-19 14:45
@Mausino , just a few questions about your issue:
Is this what you looking for is a try do some customisation for a reservation control?
Im not sure what mean: "my Reservation record finished" or " Reservation will end",
so if i can ask about more details, it may be helpful to solve your issue.

**Comment by Mausino** [comment] 2016-08-22 07:28
Hi, 

Now we have reservation module. And it has START and END day.  And we want create by workflow process, that if we create the reservation record, in same time creates by the workflow the call (or task) with START date (or duo date) in same date as has the reservation END DAY record (i want call to my client on end day of reservation for feedback). And now is inpossible without adding the custom code into workflow.

I will explain it by ohther way :) In SuiteCRM we have by default module Opportunities and there you have the CLOSE day... it can be in future like 2 month.  Can you set up by workflow that the workflow process create call or task which is starting on this close day ? no, it is not possilbe. it is possilbe only create the start day of task or calll ( or other action) only in day when was workflow executed (when was the primary module = "workflow module" modified or created) but it is no possible to take the CLOSE DAY  data from Opportunity module and uses it as data input for start day of new task or call created by workflow.

@shogunpol or @ijdavie if you have some questions, it will my pleasure to answer you :)

**Comment by shogunpol** [comment] 2016-08-22 10:33
I replicated this issue, it will be assigned as a bug, and we will work on solve problem.
Thanks for raise this issue.

**Comment by Jason-Dang** [comment] 2018-01-15 14:47
This issue appears to be a duplicate of Issue #533 https://github.com/salesagility/SuiteCRM/issues/533. I believe the issue is that when the workflow is run, the date/datetime field to be used is being ignored and the current date/datetime value of today/now is being used instead. 

This is because the record being created that triggers the workflow has not yet been saved in the database and so fetched_row returns false so the date value is blank and thus automatically set to today/now which is what is set on the date/datetime field of the record being created by workflow.

**Closed** 2018-01-15 14:51 UTC
Labels: Low Priority, bug, duplicate
