### ISSUE TITLE
include/ListView/ListView.php does not allow custom widgets

### ISSUE THREAD

**Issue by HVStechnik** [salesagility/SuiteCRM#2516] opened 2016-10-30 19:30 UTC
#### Issue

Custom field widgets placed in custom/include/generic/SugarWidgets are not working for e.g. subpanels. The ListView.php file in include/ListView/ListView.php directs different widgets to different files, but the last elseif statement in line 481 does not allow custom widgets.
#### Expected Behavior

Widgets placed in custom/include/generic/SugarWidgets should be usable via including the widget name in the viewdefs file (e.g. 'widget_class' => 'SubPanelCustomWidget',).
#### Actual Behavior

The widget is not working, cause the custom widget file in  custom/include/generic/SugarWidgets  is not called.
#### Possible Fix

Change include/ListView/ListView.php line 481 to allow all widgets: 

```
} else if(isset($list_field['widget_class'])) { // && $list_field['widget_class'] == 'SubPanelEmailLink' ) {    
   $widget_contents = $layout_manager->widgetDisplay($list_field);
}
```
#### Your Environment

SuiteCRM 7.6.4

**Comment by shogunpol** [comment] 2016-10-31 15:54
This issue has been tested in the most recent version of SuiteCRM(7.7.6), and can not be replicated, can you confirm this is still an issue and supply a step by step list to replicate this, If this is no longer an issue could you close this.

**Comment by HVStechnik** [comment] 2016-11-02 10:21
Hi shogunpol, sorry for spamming the issue log with this. I was able to solve my problem via a custom SugarField. I wasn't aware that SugarFields are going to replace the SugarWidgets for fields in future and that hence custom SugarWidgets for fields aren't working any more. 
For simple modifications of a field based on the subpaneldefs/viewdefs, I think SugarWidgets still are a great and much easier way than creating an entire new SugarField with e.g. just an slightly changed ListView.tpl. Especially, because a SugarWidget was working for multiple variable types (enum, varchar, etc.), while I will have to create multiple custom SugarFields to manipulate variables of different types.

Just in case, you're thinking of enabling custom Sugar Widgets, please find attached the steps to reproduce: I took a new install of the most recent version of SuiteCRM (7.7.6) and were able to replicate the issue by the following steps:

Ambition: Add a custom ForAccounts.php subpaneldef to the Cases module, including a custom widget to wrap the status field with a css class depending on the selected status.

Step 1: Copy /modules/Cases/metadata/subpanels/ForAccounts.php to /custom/modules/Cases/metadata/subpanels/ForAccounts.php

Step 2: Create a custom widget in /custom/include/generic/SugarWidgets/. I called my widget file SugarWidgetSubPanelWrapSpanWithContent.php with the following content:

```
<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

class SugarWidgetSubPanelWrapSpanWithContent extends SugarWidgetField
{
	function displayList($layout_def){

		if(isset($layout_def['varname']))	{
			$key = strtoupper($layout_def['varname']);
		}
		else 	{
			$key = $this->_get_column_alias($layout_def);
			$key = strtoupper($key);
		}

		$value = $layout_def['fields'][$key];
		
		return '<span class="_' . str_replace(str_split(' .~!@$%^&*()+=,./;:?><[]\{}|`#'),'',htmlentities($value)) . '">' . $value . '</span>';
	}
}
?>
```

Step 3: In order to apply the widget in the subpanel I added the widget_class to the custom subpaneldef created in step 1 (line 66 in the ForAccounts.php file):

```
		...
		'status'=>array(
	 		'vname' => 'LBL_LIST_STATUS',
			'widget_class' => 'SubPanelWrapSpanWithContent', //newly added
			'width' => '10%',
		),
		...
```

Step 4: I would now expect the widget to become active and wrap the output of the status field with an additional <span class="_xxx"></span> tag. 

However, the custom widget file in /custom/include/generic/SugarWidgets/ is not executed, because custom field widgets aren't called in include/ListView/ListView.php (around line 460-485) any more. Instead the code looks for custom SugarFields only. A possible fix is stated in my original post.

**Comment by shogunpol** [comment] 2016-11-02 13:40
@HVStechnik , just to clarify my thoughts, do you talk about subpanelView or listView?

**Comment by HVStechnik** [comment] 2016-11-02 13:48
@shogunpol, I'm talking about subpanelView.

**Comment by shogunpol** [comment] 2016-11-02 14:24
@HVStechnik ,I tried on account module, and i inserted the custom widget, and work as expected.
Thank you for you question. However, We use github primarily for reporting of Core SuiteCRM Issues and we feel your question would be more suited to our [Community Forum](https://suitecrm.com/forum/index). We will be able to help you with your issue there.

**Closed by shogunpol** 2016-11-02 14:24 UTC
Labels: question

**Comment by HVStechnik** [comment] 2016-11-02 15:58
@shogunpol, thanks. Just to clarify, were you able to insert a custom widget in the subpanel header (e.g. additional action button, which is working on my side, too) or in the body as a modification of a field in the table (e.g. wrap a integer number with a custom link, which is still not working for me)?

**Comment by owl-mark** [comment] 2021-05-05 02:59
I use SuiteCRM v7.11.19.

### Issue
   I have the same problem. My scenario is I find out sub panel data will be different when generated by ajax or backend side. If you use ajax to show the data, you will find out data is render by custom field. The different results is caused by it used static variable to store the data.

I believe the @HVStechnik talking about this file include/ListView/ListViewSubPanel.php at lines from 454 to 475.
```
// include/ListView/ListViewSubPanel.php
                                ...
                                } else {
                                    if (isset($list_field['widget_class']) && $list_field['widget_class'] == 'SubPanelEmailLink') {
                                        if (isset($list_field['fields']['EMAIL1_LINK'])) {
                                            $widget_contents[$aVal][$field_name] = $list_field['fields']['EMAIL1_LINK'];
                                        } else {
                                            $widget_contents[$aVal][$field_name] = $layout_manager->widgetDisplay($list_field);
                                        }
                                    }
                                  ...
```

But I guess the problem is happened at the line ListViewSubPanel.php at line 439 
```
// include/ListView/ListViewSubPanel.php
                               ...
                                if (isset($vardef['type'])) {
                                    $fieldType = isset($vardef['custom_type']) ? $vardef['custom_type'] : $vardef['type'];
                                    $tmpField = SugarFieldHandler::getSugarField($fieldType, true);
                                } else {
                                    $tmpField = null;
                                }
                               ...
```
which uses the function from the file include/SugarFields/SugarFieldHandler.php at line 102.

```
// include/SugarFields/SugarFieldHandler.php
    /**
     * return the singleton of the SugarField
     * @param $field
     * @param bool $returnNullIfBase
     * @return mixed
     */
    public static function getSugarField($field, $returnNullIfBase=false)
    {
        static $sugarFieldObjects = array(); // <-- this line while keep the first type of the sugarfield

        $field = self::fixupFieldType($field);
        $field = ucfirst($field);

```

We can see it used static variable. Static variable will keep the value when it first time to be call. But this method should be check each sugar field is exist or not. Because when it render the page in backend, it will first get the value when generate the main panel but missed to re get the value when generate the sub panel.

### Possible Fix

```
// include/SugarFields/SugarFieldHandler.php
    /**
     * return the singleton of the SugarField
     * @param $field
     * @param bool $returnNullIfBase
     * @return mixed
     */
    public static function getSugarField($field, $returnNullIfBase=false)
    {
        $sugarFieldObjects = array(); // <-- take off static

        $field = self::fixupFieldType($field);
        $field = ucfirst($field);
```

What I fix now is take off the static from the variable, but it will cause problem that it need to get the files many times.
