### ISSUE TITLE
Check box field do not Export value in module Reports

### ISSUE THREAD

**Issue by cvasselai** [salesagility/SuiteCRM#517] opened 2015-09-30 19:40 UTC
When I create a report for example Leads, and I list the field "do not call" the value is displayed on the screen correctly, but when I export to csv or Download PDF the value of this field is not shown.

![lead_report_problem_check_box](https://cloud.githubusercontent.com/assets/14912777/10204324/7c4932a0-6791-11e5-9141-749c1b8014a8.PNG)

and in csv file

![lead_report_problem_check_box_csv](https://cloud.githubusercontent.com/assets/14912777/10204411/e6837b4e-6791-11e5-97c3-7e80597ec82a.PNG)

**Comment by darthtang** [comment] 2015-10-28 13:34
https://github.com/salesagility/SuiteCRM/issues/123

**Comment by cvasselai** [comment] 2015-10-29 19:19
Thanks Darthtang.

For download PDF is OK, but to CSV not yet!

*Clovis Murilo Vasselai*
*+55 (47)3036-7776 | (47)9176-1185*
clovis@teclogica.com.br
*www.teclogica.com.br <http://www.teclogica.com.br/>
 ------------------------------*
*TECLÓGICA SERVIÇOS EM INFORMÁTICA LTDA.*
Rua XV de novembro, 759 | 12º andar - Ed. Hering | CEP 89010-902 | Centro |
Blumenau | SC | Fone: +55 47 3036.7700
------------------------------
Esta mensagem foi enviada pela Teclógica, para uso exclusivo do
destinatário, podendo conter informações confidenciais. Se for recebida por
terceiro que não o destinatário, deve ser apagada imediatamente do seu
computador e a Teclógica notificada (contato@teclogica.com.br). As
informações aqui prestadas não podem ser distribuídas ou reproduzidas sem a
expressa autorização da Teclógica. Apesar do conteúdo deste e-mail ser
baseado em informações cuidadosamente selecionadas ou disponibilizadas pelo
Cliente, a Teclógica não se responsabiliza pelo uso indevido e/ou decisões
tomadas com base em informações contidas neste documento.


2015-10-28 11:35 GMT-02:00 darthtang <notifications@github.com>:

**Comment by recci** [comment] 2016-02-26 13:53
The problem is caused by line 842 in modules/AOR_Reports/AOR_Report.php

$csv .= $this->encloseForCSV(trim(strip_tags(getModuleField($att['module'], $att['field'], $att['field'], 'DetailView',$row[$name]))));

More specifically when getModuleField returns the field in most cases it returns a value like "<span> value </span>" so when strip_tags is run it strips off the span tags and leaves the value but in the case of a check box field getModuleField  just returns the <input> tag with its value checked so therefore strip_tags removes everything leaving it blank. 

There doesn’t seem to be an easy way to fix this without altering aow_utils.php since AOR_Fields doesn’t store the field type.

**Comment by shogunpol** [comment] 2016-11-29 11:08
@cvasselai , the issue has been tested in recent version of SuiteCRM(7.7.8), and not appear, can you confirm is not an issue any more, and if yes can you close this issue?
Thanks for your contribution.

**Comment by shogunpol** [comment] 2016-12-13 09:29
Thank you for raising this issue however due to no activity in the last 14 days this issue will be closed, If this issue still exists and information can be given to allow us to proceed with this it can be reopened.

**Comment by graphix** [comment] 2017-01-25 22:06
@shogunpol I did tests for the Version 7.7.9 with checkboxes in the CSV export but it doesnot working. OK in PDF export, but not in CSV. Still empty values and should be reopened.

**Comment by cvasselai** [comment] 2017-01-25 22:23
Yes, still empty values and should be reopened.

**Comment by gody01** [comment] 2017-05-12 10:23
Issue still exist in:

Version 7.8.3
Sugar Version 6.5.24 (Build 509)

**Comment by ChangezKhan** [comment] 2017-05-12 20:31
I have used some part of @recci's solution, `9b39345` and able to solve the issue. But I don't know, whether I can create a PR for that, as I am unable to understand why that solution was not merged and also originally, that solution was not mine. I think @recci should do that, if everything is OK.

**Comment by ChangezKhan** [comment] 2017-05-18 10:58
@shogunpol @samus-aran, any update here?

**Comment by crespo5** [comment] 2018-05-15 08:27
I have the same issue in SuiteCRM 7.10.3 and in Clean Version of SuiteCRM 7.10.4. Please fix it because there are a lot of solutions.
The solution of @recci works well for me but the other solutions have php notices and warnings.

**Comment by Mausino** [comment] 2018-05-15 10:02
@cvasselai @crespo5 i reported simmilary issue #5706 where the checkboxes are missing in exported pdf
This issue is very old.. september 2015  

@PedroErnst should we merge the fixes ??? there are more as year here and wont merged yet :(

**Comment by crespo5** [comment] 2018-05-15 11:00
Yes @Mausino ... this issue is very old, please link the fix (the first fix of this issue works well) to your issue.

**Comment by pstevens71** [comment] 2018-07-21 15:42
Hey This is still an issue in 7.8.18 LTS.  However the fix proposed is old and the code is substantially different.  Any chance anyone could update the fix?

**Comment by pstevens71** [comment] 2018-07-21 15:53
Found this and it works...
[https://github.com/salesagility/SuiteCRM/issues/2531](url)

**Comment by ChangezKhan** [comment] 2018-07-21 16:34
@pstevens71 above link is not working.

**Comment by cameronblaikie** [comment] 2019-02-04 11:44
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.

**Comment by cameronblaikie** [comment] 2019-02-04 11:48
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue. There is still the issue of the CSV export but this has been raised separately - #2531

**Closed by cameronblaikie** 2019-02-04 11:48 UTC
Labels: Fix Proposed, Low Priority, bug

**Comment by gavinjackson** [comment] 2019-02-10 06:51
Hi, I'm experiencing this problem in Suitecrm version 7.11.1

Trying to export a report with checkbox (boolean) fields - not appearing in resulting csv file.

**Comment by pgorod** [comment] 2019-02-10 16:57
@gavinjackson I think the idea of closing this was that, for the exports, the fix proposed in #2531 seems to work, so that issue is enough.

But since that fix hasn't been merged in to the product yet, it makes sense that you are still experiencing the bug. You might want to try and apply that fix manually.

**Comment by gavinjackson** [comment] 2019-02-11 04:36
Thanks @pgorod the proposed patch doesn't seem compatible with the version that I'm running - 7.11.1 (I went it to the source code but the line numbers don't line up, I'll have another crack at it tonight!
