### ISSUE TITLE
Campaigns: Test-Emails sent out twice

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#6420] opened 2018-10-14 16:53 UTC
#### Issue

When I send a campaign mail as test I get dual entries for every single address in the testlist.

#### Steps to Reproduce

1. create newsletter campaign (with marketing email)
2. add one or more targets to targetlist of type test.
3. send test email
4. check campaign status (and or database table campaign_log with activity_type "targeted"): notice double entries per target id
5. check inbox of recipient email address: notice double emails received.

#### Your Environment

* SuiteCRM Version used: 7.10.9 (via upgrade)

**Comment by dursuntosun** [comment] 2018-10-14 17:45
Yes, i have this issue. But not all time.

**Comment by MrSykes** [comment] 2019-01-03 03:41
Until it's properly corrected you can prevent this by manually running the following query on the "prospect_list_campaigns" table before you send the campaign messages:

DELETE FROM `prospect_list_campaigns` WHERE `deleted` = 1 

I'm using the 7.8.24 LTS version and noticed that any targets that get added to a campaign and are later removed and added again will get sent as many times as they were added and removed. It appears that the campaign mailer routine does not ignore the matching deleted records when it finds a matching record that is not deleted. Since nothing is really ever deleted from the db (just gets marked as deleted),  these deleted records are included if the same record is added again. 

For example:  I added a test target to a test campaign and removed it, then added it again and removed it and finally added it again. This sends the email to the test target 3 times.  Here's what the db table "prospect_list_campaigns" looks like for the test campaign:

![image](https://user-images.githubusercontent.com/4641084/50622924-0f60aa80-0edf-11e9-948d-0645b01cbbb2.png)

Hope that helps.

**Comment by lazka** [comment] 2019-05-20 13:11
I can reproduce this with 7.10.16

**Closed** 2019-06-03 16:05 UTC
Labels: Campaigns, Low Priority, Resolved: Next Release, bug
