### ISSUE TITLE
SuiteR Responsive Theme, edit Calendar action

### ISSUE THREAD

**Issue by Eve-APG** [salesagility/SuiteCRM#570] opened 2015-10-15 13:16 UTC
In the mobile menu, clicking on "+" for calendar view leads to the following error message:

    Error: File [modules/Calendar/metadata/editviewdefs.php] is missing. 
    Unable to create because no corresponding HTML file was found.

![suite_calendar_bug](https://cloud.githubusercontent.com/assets/15142161/10514676/7792ba8c-734f-11e5-9c12-9150815151c9.png)

(It apparently tries to execute the "module=Calendar&action=EditView" action but there is no such action for Calendar. It should probably trigger "module=Meetings&action=EditView").

**Comment by mattlorimer** [comment] 2015-10-19 12:42
duplicate of #430

**Closed by mattlorimer** 2015-10-19 12:42 UTC
Labels: bug, duplicate
