### ISSUE TITLE
7.9.1 Email: Lead "Insert Variable" does not insert selected data when sending 

### ISSUE THREAD

**Issue by someguynamedphil** [salesagility/SuiteCRM#3731] opened 2017-06-16 13:52 UTC
Create an email template, 
insert variable "Account/Lead/Lead First name"
"$lead_first_name" appears in preview boxes
Select "Send Text Only" check box

When sending, the receivers email only displays "$lead_first_name"

#### Expected Behavior
Variable data should be inserted in email before sending

**Comment by Dillon-Brown** [comment] 2017-06-16 15:33
@someguynamedphil This is an older bug and technically a duplicate of some other issues #3321 #3410 #3110. However we'll keep this one open and raise it as a high priority for 7.9.1.

**Comment by someguynamedphil** [comment] 2017-06-16 15:41
Thanks - this worked perfectly in 7.8.4 (Was a cornerstone of our workflow)

**Comment by stenfalp** [comment] 2017-06-16 15:43
Tried with $account_name and it doesn't work eihter.

**Closed** 2017-07-17 16:33 UTC
Labels: bug, Fix Proposed, High Priority, Resolved: Next Release
