### ISSUE TITLE
cannot use popup windows 7.8.3.

### ISSUE THREAD

**Issue by edilex** [salesagility/SuiteCRM#3520] opened 2017-05-08 14:44 UTC
#### Issue

Since update 7.8.3, the popup windows for email "related to" or dashlet mods do not take into account the top menu bar so it is not usable.

#### Expected Behavior

To take into account top bar

#### Actual Behavior

Does not take into account top bar

#### Possible Fix

To take into account top bar

#### Steps to Reproduce

1. Go to dashboard
2. Click on little pen to modify dashlet info
3.
4.

#### Context

Cannot use  the popup (medium priority)

#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 54.0
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): Centos7

**Comment by Dillon-Brown** [comment] 2017-05-08 15:41
@edilex Do you think you could clarify further or provice screenshots? I cant seem to replicate this issue. When I click on the pen icon to modify a dashlet the popup appears to display correctly:

![issue-3520](https://cloud.githubusercontent.com/assets/26431166/25811891/8c37a608-340c-11e7-87a7-9f43f75a28ba.png)

**Comment by edilex** [comment] 2017-05-08 15:42
Oooppps forgot printscreen my bad. And it is with Suite R. 
![capture d ecran 2017-05-08 a 10 30 55](https://cloud.githubusercontent.com/assets/23078474/25812155/65d7113e-33e3-11e7-8c14-daea2db94536.png)

**Comment by pgorod** [comment] 2017-05-09 11:13
Duplicate of #2792.

I would love to see that merged. Another person came up in the forums today with this same problem.

**Closed** 2017-05-09 11:53 UTC
Labels: duplicate

**Comment by edilex** [comment] 2017-05-09 15:33
This fixed everything except for dashlet edit. Please reopen.

**Comment by Dillon-Brown** [comment] 2017-05-09 15:45
@edilex This issue is a duplicate of #2762 which addresses the pop up window appearing under the header when editing a dashlet. If you have more information feel free to add it there. Thanks.
