### ISSUE TITLE
Dropdown box does not show selected option in Version 7.7.4

### ISSUE THREAD

**Issue by liveincan** [salesagility/SuiteCRM#2270] opened 2016-09-21 06:15 UTC
Dropdown box does not show selected option in Version 7.7.4. All you see is a number of dots which turned out to be the very top of the caracters that should be visible.
#### Expected Behavior

Selected option should be clearly visable.
#### Actual Behavior

All you see is a number of dots which turned out to be the very top of the caracters that should be visible.
#### Possible Fix

Removing line-height: 40px; in the following css solves the problem.

select, select:focus, select::selection, .saved_search_select {
    line-height: 40px;
}
#### Steps to Reproduce

This problem is visible in all drop-down boxes across entire application.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):
Windows 10 Professional
Google Chrome Version 53.0.2785.116 m
SuiteCRM Version 7.7.4

**Comment by Mausino** [comment] 2016-09-21 06:18
I think, that is duplicate of #1930

**Comment by ijdavie** [comment] 2016-09-21 07:17
@liveincan, This does seem to be a duplicate of #1930, I will close this as a duplicate. 

@Mausino Thanks for the link to the duplicate :+1:

**Closed by ijdavie** 2016-09-21 07:17 UTC
