### ISSUE TITLE
7.9.4 PDF Templates Not Working

### ISSUE THREAD

**Issue by mruch2** [salesagility/SuiteCRM#3934] opened 2017-07-21 04:03 UTC
All PDF templates are the same in the editor and when using them to send emails.

#### Issue
When sending emails with the "Email Quotation" and the "Email Invoice" it only uses the invoice template though I am selecting quote template for quotes and invoice template for invoices.

#### Expected Behavior
I need to send separate documents for each item when send quotations and invoices.

#### Actual Behavior
All emails that I start have the same template being used even if I select a different one.

#### Steps to Reproduce
Editing a PDF Template.
Sending a quotation
Sending an invoice

#### Context
This bug has made it impossible to use SuiteCRM.

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version Chrome latest version 64bit
* Environment name and version MySQL, PHP 7
* Operating System and version: Windows 10 Pro

**Comment by mruch2** [comment] 2017-07-22 15:02
Any feedback on this issue? This is a real struggle for me.

**Comment by Dillon-Brown** [comment] 2017-07-25 15:24
@mruch2 I'm unable to replicate this on 7.9.4. After clicking on "Email Invoice" or "Email Quotation" and selecting a template, I am correctly receiving that template in my email.

Is there any more information you can provide that may help with replication? I would also check permissions / repair + rebuild.

**Comment by mruch2** [comment] 2017-07-25 17:31
In order to get the email to load with the current quote I have been repairing and rebuilding after each quote so I can send the next one. What permissions should I be looking at?




Outlook For Android







On Tue, Jul 25, 2017 at 8:27 AM -0700, "Dillon-Brown" <notifications@github.com> wrote:












@mruch2 I'm unable to replicate this on 7.9.4. After clicking on "Email Invoice" or "Email Quotation" and selecting a template, I am correctly receiving that template in my email.


Is there any more information you can provide that may help with replication? I would also check permissions / repair + rebuild.

**Comment by mruch2** [comment] 2017-07-25 17:32
I should also add that if I don't repair and rebuild each time  the next quote I do will load the exact quote I had previously worked on in the template and does not pull the information from the current quote I am working on. 




Outlook For Android







From: Mike Ruch


Sent: Tuesday, July 25, 10:31 AM


Subject: Re: [salesagility/SuiteCRM] 7.9.4 PDF Templates Not Working (#3934)


To: salesagility/SuiteCRM, salesagility/SuiteCRM


Cc: Mention






In order to get the email to load with the current quote I have been repairing and rebuilding after each quote so I can send the next one. What permissions should I be looking at?




Outlook For Android










On Tue, Jul 25, 2017 at 8:27 AM -0700, "Dillon-Brown" <notifications@github.com> wrote:




@mruch2 I'm unable to replicate this on 7.9.4. After clicking on "Email Invoice" or "Email Quotation" and selecting a template, I am correctly receiving that template in my email.


Is there any more information you can provide that may help with replication? I would also check permissions / repair + rebuild.

**Comment by pgorod** [comment] 2017-07-25 19:21
(@mruch2 please remove the extra text from your replies, something about your email client isn't helping)

How about this version of the problem, isn't it simpler?

1. Go into PDF Templates
2. Click `Create` 
3. Give it a name, make it based on Quotes module, load from sample "Quote group sample"
4. Save it
5. Now edit it, content is empty

This doesn't have to be with "Load sample". If you simply add content manually, it's gone when you edit it.

This is probably a more basic problem, it simply doesn't save correctly. 

Reproduced on the live demo.

**Comment by mruch2** [comment] 2017-07-25 20:00
This is not my issue. May be another one but I have not run into it yet. 




Create a quote


Hit email quotation (I only have 1 template so it picks quote email teamplate)


Send email


Create another quote


Hit email quotation (use the same template as the first quote)


Notice the template that loaded has the previous quote info in it




Outlook For Android







On Tue, Jul 25, 2017 at 12:21 PM -0700, "pgorod" <notifications@github.com> wrote:












(@mruch2 please remove the extra text from your replies, something about your email client isn't helping)


How about this version of the problem, isn't it simpler?

Go into PDF Templates
Click Create
Give it a name, make it based on Quotes module, load from sample "Quote group sample"
Save it
Now edit it, content is empty



This doesn't have to be with "Load sample". If you simply add content manually, it's gone when you edit it.


This is probably a more basic problem, it simply doesn't save correctly.


Reproduced on the live demo.

**Comment by pgorod** [comment] 2017-07-25 20:54
@mruch2 I know your issue is generated with different steps, but can you please try my steps in your system? It would be important to know if that is working for you. The two things seem very close and are probably related. If they are not, I will be happy to open a new Issue, no problem.

(and have you tried visiting this issue in the Github website to see what your "Outlook for Android" client is doing with your answers?)

Thanks!

**Comment by mruch2** [comment] 2017-07-26 01:04
I have been able to reproduce this issue by following your steps. What do I do next to resolve the issue?

**Comment by pgorod** [comment] 2017-07-26 16:30
I did some more testing, while looking at the database, and the Template editor is not even loading the `Body` field correctly. So simply going into the Edit view of a template displays the bug. If there is `Body` content in the database, it won't show in the Edit view, the editor will be blank.

**Comment by mruch2** [comment] 2017-07-26 17:06
Ok so what do I need to do to fix it? Is there anything else I need to test?

**Comment by pgorod** [comment] 2017-07-26 17:14
@mruch2 nobody knows how to fix this yet. I've investigated a bit today, nothing conclusive, I expect some people from SalesAgility will investigate, since it got a `High Priority` label... but unless you are a developer (or have one in your company), all you can do now is track the evolution of this Issue and wait...

**Comment by Dillon-Brown** [comment] 2017-07-27 10:01
@pgorod Body being wiped out when editing a quote is fixed in this PR: #4009 which related to all html fields in the crm.

**Comment by pgorod** [comment] 2017-07-27 10:04
@mruch2 can you please apply [this change](https://github.com/salesagility/SuiteCRM/pull/4009/files) and confirm if it solves your original issue? Thanks!

**Comment by mruch2** [comment] 2017-07-27 15:21
Dillon this has resolved my issue. I approved the change on the pull request. Thanks for the help.

**Comment by qroft** [comment] 2017-08-18 13:32
@mruch2 I applied the line to my code but for me the body stays blank when i reopen it. Is there any other file that needs to be changed to make it work?

**Comment by Dillon-Brown** [comment] 2017-08-18 13:34
@qroft Did you make sure to do a repair + rebuild after applying the change?

**Comment by qroft** [comment] 2017-08-18 13:46
I just changed the line as mentioned in the above fix.
A new problem appears.

1. Create a new PDF template.
2. Insert inside the body a simple "Hello"
3. Save the Template
4. Re-open the template
5. The body now shows "<p>Hello</p>"

**Comment by Dillon-Brown** [comment] 2017-09-07 23:08
Hi @qroft, I've confirmed this issue and others related to HTML fields. I've raised this as a high priority here: #4223 if you want to follow this. Thanks.

**Closed by Dillon-Brown** 2017-09-07 23:08 UTC
Labels: bug, Fix Proposed, High Priority, Resolved: Next Release
