### ISSUE TITLE
Checkbox on Delegates subpanel doesn't work

### ISSUE THREAD

**Issue by pribeiro42** [salesagility/SuiteCRM#7239] opened 2019-04-30 11:47 UTC
After creating an event, and associating some delegates, the checkbox on the subpanel header doesn't select the delegates.

#### Issue

The Delegates subpanel on the Events module has a checkbox, to the left of the "Name" column, that supposedly should select the delegates, including options similar to the same button on list views (Select All, Select this page, Deselect All). This button doesn't do anything, and doesn't show the drop-down menu.

#### Expected Behavior

On clicking the caret, the drop-down menu should appear and the checkbox should select all the delegates:

![Delegates_1](https://user-images.githubusercontent.com/5657365/56959392-2d64b180-6b45-11e9-94fa-1b1211315429.png)

![Delegates_2](https://user-images.githubusercontent.com/5657365/56959401-30f83880-6b45-11e9-98b3-52b34bcdb9cd.png)

#### Actual Behavior

Nothing. The checkbox reacts but no action... 

No errors shown on suitecrm.log, php_error.log, etc...

#### Steps to Reproduce

1. Create an event
2. Associate some delegates (can be Contacts, Leads, etc..)
3. Try to check all the delegates with the header checkbox.

#### Your Environment

* SuiteCRM Version used: 7.11.3 and also the Suiteondemand version.
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 60.6.1esr (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1.37 / PHP 7.3.4 (and other versions)
* Operating System and version (e.g Ubuntu 16.04): Debian stable (9.8) and testing

**Comment by Dillon-Brown** [comment] 2019-05-01 09:00
Duplicate of #4560

**Closed by Dillon-Brown** 2019-05-01 09:00 UTC
