### ISSUE TITLE
Campaign target lists lost by Wizard (not Gandalf)...

### ISSUE THREAD

**Issue by virtualme123** [salesagility/SuiteCRM#2388] opened 2016-10-06 12:53 UTC
#### Issue

When I have added a target list, then go back through the campaign wizard the target list disappears and the target lists go back to the default (Subscription List, Unsubscription List). Having multiple target lists per campaign is quite important to me so hope it is just a bug... My other concern is that the campaign wizard doesn't seem to allow for multiple target lists?

#### Expected Behavior

If I add target lists to a campaign I expect them to stay there.

#### Actual Behavior

I add a target list, go through the campaign wizard which will revert back to the default 3 lists.

#### Possible Fix

Allow for more than 3 target lists, at the moment I try to avoid going through the Wizard and saving it at the target list stage - although I am not the only person doing campaigns and it can happen by accident.

#### Context

Accidently saving through the campaign wizard means all assigned target lists can get removed in an instant, only way to revert is to have a list saved and re-add them manually.

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 53.0.2785.116 m (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 5.9
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 14.04

**Comment by shogunpol** [comment] 2016-10-11 11:06
The issue has been tested on recent version of SuiteCRM(7.7.5), and it not appear
So if you can give me some more additional details how to replicate the bug it will be great, screenshots, step-by-steps basically everything what may help me replicate the issue.
@virtualme123  ,thanks for raise this issue

**Comment by virtualme123** [comment] 2016-10-11 12:42
Ok so I think I see the issue, I have a campaign type set as type 'Email' and using the Wizard got to the target list area which is completely different to what I have seen before. So it seems that with type 'Newsletter' I have the restriction of 'Subscription List', 'Unsubscription List' and 'Test list', and if I follow the Wizard through to the end but instead of clicking send campaign I 'View Details' it looses any other target lists I have.

Not sure why having a type of 'Newsletter' wouldn't come with the same detail as type 'Email'?

**Comment by shogunpol** [comment] 2016-10-12 08:13
@virtualme123 , i did attempt to testing issue, just question to make clear. 
Do you mean the issue is when you in:
1. Create newsletter campaign
2. Open wizzard
3. Type name and details in Campaign Header section
4. Click Next - entered to Subscription section
5. In this moment if i good understand you expect to have possibility choose more than one target list, in all 3 section of select facility?

Just confirm this is an issue you described.

**Comment by virtualme123** [comment] 2016-10-12 10:37
That is correct, however the same should happen if I edit an existing campaign as well - it will give me option to add more target lists. Thanks

**Comment by shogunpol** [comment] 2016-10-12 12:10
@virtualme123 , to use the newsletter type of campaign, you use 3 types of list: if you read carefully the information about lists, you will see why you do not have possibility, for example to use 2 different target lists of excluded people, or test receivers (usually internal people from your company). To send emails in more than one target list you have dedicated type of Campaign, which is email campaign.
As an addition the way how campaign are created in logic are not changed since version 7.1 of SuiteCRM.
If you thing this is solve your issue, can you close this issue? 
If not we can label this issue as a suggestion.
Thanks for your contribution.

**Comment by virtualme123** [comment] 2016-10-12 12:46
Ok I understand, in the past I have not used the Wizard so probably didn't notice the 'Newsletter' restrictions. I will now use instead the type 'Email'.

For reference we are sending 'Newsletters' on a monthly basis but our target lists are from various sources or groups, so when the campaign results come in we can split the report based on related target list.

**Comment by shogunpol** [comment] 2016-10-13 07:11
@virtualme123, If you thing this is solve your issue, can you close this issue?

**Closed** 2016-10-17 06:59 UTC
Labels: Pending Input
