### ISSUE TITLE
Issue with inbound email

### ISSUE THREAD

**Issue by sameekshaagrawal** [salesagility/SuiteCRM#5813] opened 2018-05-02 08:53 UTC
#### Issue
Want to create leads when new mail occurs in crm so for that i wrote a logic hook after_save but its not working when new mail occurs but its working fine when i check it manually 

Error : 
Unable to find relationship emails_email_templates

#### Expected Behavior
Option should work as in previous versions.

#### Your Environment
SuiteCRM Version used: 7.9.12
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari v10
Environment name and version (e.g. MySQL, PHP 7): mySQL php 7.0.8
Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by PedroErnst** [comment] 2018-05-03 09:51
Thank you for reporting this @sameekshaagrawal 

Please make sure you fill out the issue report template and provide adequate details, like precise steps to reproduce the issue.

I'd suggest that maybe it would be more helpful for you to take this to the [forums](https://suitecrm.com/suitecrm/forum/index) until you are 100% sure that this is a bug.

**Comment by sameekshaagrawal** [comment] 2018-05-04 06:59
Please Help

**Comment by pgorod** [comment] 2018-05-04 10:34
@sameekshaagrawal this is definitely something you should be asking in the Forums, not here. It's probably an issue with your code, not a bug in SuiteCRM. 

https://suitecrm.com/suitecrm/forum

Please close this Issue here, and open a thread in the forums, I will try to help you out there. Make sure you include details about your logic_hook, including code. Thanks

**Comment by sameekshaagrawal** [comment] 2018-05-04 11:04
No issue in code because that is working fine in 7.8.0 but not working in
7.9.12

**Comment by sameekshaagrawal** [comment] 2018-05-04 11:09
Previously in 7.8.0 when new mail comes to CRM then new entry is inserted
in email table but in 7.9.12 its not like it so please help me

**Comment by pgorod** [comment] 2018-05-04 11:13
The fact that it worked in one version, and not in the next, still does not show it's a bug in SuiteCRM. Something could be less than perfect in your code, something might have been broken in your upgrade. 

Anyway, there's no way of "helping you" without knowing what it is, without seeing your code.

**Comment by sameekshaagrawal** [comment] 2018-05-04 11:30
i am using this code on after save of email

SyntaxEditor Code Snippet

class AnswerUpdatesClass
{

	
	public function AnswerUpdatesFun($bean, $event, $args)
	{
		
			
			$date=gmdate("Y-m-d H:i:s");
			$EmailBean = BeanFactory::newBean('Leads');   //Create
bean			$EmailBean->first_name = 'test_ssameeksa';
			$EmailBean->save();   //Save			
		//	die;					
		

        }
   }

**Comment by PedroErnst** [comment] 2018-05-04 11:37
Please make a post in the forums.

**Closed** 2018-05-04 14:12 UTC
