### ISSUE TITLE
Accounts Module - Copy Button Disappears When Address Added

### ISSUE THREAD

**Issue by briansalesagility** [salesagility/SuiteCRM#1544] opened 2016-06-02 10:40 UTC
Copy button disappears when adding an address to an Account record in Detail View. Button only reappears on page refresh.

![accounts copy address bug](https://cloud.githubusercontent.com/assets/17987506/15742395/8310b14e-28b6-11e6-9ed4-90e1493ea372.png)

The issue is where the address is being edited, when the tick is clicked to confirm the edit only the address line shows and there is no copy button"

**Comment by recci** [comment] 2016-06-10 15:39
There is more to this issue than just the copy button disappearing. There are actually 5 fields being displayed in the Billing and shipping address fields. 

billing_address_street
billing_address_city
billing_address_postalcode
billing_address_country

But inline editing only takes billing_address_street and allows you to edit that then only returns that one field. inline editing has not been designed to handle address fields as these are not standard.

Not sure if inline editing should be allowed on address fields.

**Comment by ijdavie** [comment] 2016-09-19 11:26
This appears to be a duplicate of #450,

**Closed by ijdavie** 2016-09-19 11:26 UTC
Labels: bug, duplicate
