### ISSUE TITLE
sugar_grp_overlib.js  is not generated but required by InboundEmail/EditView.html 

### ISSUE THREAD

**Issue by mrbarletta** [salesagility/SuiteCRM#2496] opened 2016-10-27 02:09 UTC
#### Issue

 modules/InboundEmail/EditView.html requires the file sugar_grp_overlib.js which is no longer created not even after a repair and rebuild / js rebuild / etc.
#### Expected Behavior

No 404 on the InboundEmail/EditView.html  page .
#### Actual Behavior

404 when editing InboundEmail 
#### Possible Fix

Either create the file or remove the dependency.
#### Steps to Reproduce

1. Admin -> Inbound Email
2. Open Browser console  (Ctrl Shift I on chrome )
3. Create a New Bounce Handling Account/New Group Account
4. Watch the console with 404
#### Context

Creating the inbound email for a email marketing campaign
                        #### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version: Chrome Version 52.0.2743.116 (64-bit)
- Environment name and version:
  - mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper
  - PHP Version 5.6.25-2+deb.sury.org~xenial+1
  - Apache/2.4.18 (Ubuntu)
- Operating System and version: 
  - Distributor ID: neon
  - Description:    KDE neon User Edition 5.7
  - Release:        16.04
  - Codename:       xenial

**Comment by shogunpol** [comment] 2016-11-01 09:20
This issue has been tested in the most recent version of SuiteCRM(7.7.6), and can not be replicated, can you confirm this is still an issue and supply a step by step list to replicate this, If this is no longer an issue could you close this.

**Comment by mrbarletta** [comment] 2016-11-02 21:28
Just tested the latest version and the issue is still there.

My steps where, git clone the repo and then go through the default installer with demo data.

the file `sugar_grp_overlib.js ` is not generated but still required here `module=InboundEmail&action=EditView&mailbox_type=bounce`

**Comment by shogunpol** [comment] 2016-11-03 08:43
@mrbarletta , can you tell me what Repo you clone? even better paste link for it, 
thanks.

**Comment by mrbarletta** [comment] 2016-11-03 14:26
@shogunpol  thanks for your prompt answer

HEre -> https://github.com/salesagility/SuiteCRM

this is my git/config so I don't forget a thing
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = https://github.com/salesagility/SuiteCRM.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```

**Comment by sk1p** [comment] 2016-12-20 13:23
I'm having the same problem, maybe because I didn't initially have the right file permissions on install (?). I tried the repair commands to no avail. As I understand, js groupings need to be defined in https://github.com/salesagility/SuiteCRM/blob/master/jssource/JSGroupings.php but I don't see  sugar_grp_overlib.js anywhere in that file (nor was it ever there according to the git history...?). Am I missing something?

Using SuiteCRM Version 7.7.8

Btw: I think the 404 causes unusable dialogs when editing the email settings, for example, when you click "test settings" a dialog pops up that is not confirmable/closable without fiddling with devtools or something like that...

**Comment by Mac-Rae** [comment] 2019-08-02 14:46
Confirmed in latest 7.10.x

**Comment by Kevconry** [comment] 2023-02-06 11:29
Can't replicate in 7.13.1, please re-raise or get in touch if you are still having this issue

**Closed** 2023-02-06 14:59 UTC
Labels: Type:Bug, Priority:Moderate
