### ISSUE TITLE
7.10.12 Auto Import of Emails not working

### ISSUE THREAD

**Issue by afnieves** [salesagility/SuiteCRM#6866] opened 2019-01-31 01:41 UTC
Fresh install of 7.10.12 Auto Import of group mail account no longer working.
#### Issue

Upgraded from 7.10.7 where this was working fine.  

#### Expected Behavior
<img width="358" alt="screenshot 2019-01-30 18 26 47" src="https://user-images.githubusercontent.com/18472889/52024065-a3ad3580-24bc-11e9-9093-606e6bbab4e8.png">

#### Actual Behavior
<img width="574" alt="screenshot 2019-01-30 18 43 59" src="https://user-images.githubusercontent.com/18472889/52024727-10c1ca80-24bf-11e9-854f-5be183134226.png">
I can manually import but auto import stoped working.   I also applied the SuiteCRM-hotfix-7.10.x which corrected the listview no records problem. But not the auto import.
No errors in logs related to this issue.

#### Steps to Reproduce
1. Install 7.10.12
2. Create group inbound email account and checked 
<img width="256" alt="screenshot 2019-01-30 18 36 10" src="https://user-images.githubusercontent.com/18472889/52024388-f0454080-24bd-11e9-8421-52c024214b30.png">

3.Review the Emails module listview

#### Context

Auto import of emails creates records in the system to be processed without this all automation is not working. 

#### Your Environment

* SuiteCRM Version used: 7.10.12
* Browser name and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Environment name and version MySQL , PHP 7): PHP 7.0.32, MYSQL 5.7.25
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.1

**Comment by Dillon-Brown** [comment] 2019-02-04 13:49
Hi @afnieves, have you tried a repair and rebuild? (Make sure to scroll to the bottom and hit "execute") there was a change in 7.10.12 to the email table that might be causing this.

If you are still able to replicate this after a repair+rebuild then let me know and I can re-open this issue and investigate further. Thanks!

**Comment by afnieves** [comment] 2019-02-05 04:14
Hi @Dillon-Brown 

I did a repair and fix the table it still does not auto import.  I found these two bugs so far. 

include/Imap/ImapHandler.php
line 456
 
-  $ret = imap_append($this->getStream());
+ $ret = imap_expunge($this->getStream()); /* E2E FIX */

modules/InboundEmail/AOPInboundEmail.php
line 59

- public function handleCreateCase(Email $email, $userId)
+ public function handleCreateCase($email, $userId) /* E2E Fix */

By applying the above changes stoped these error messages

Warning [2]: Declaration of AOPInboundEmail::handleCreateCase(Email $email, $userId) should be compatible with InboundEmail::handleCreateCase($email, $userId) in /var/www/suitecrm-esg/modules/InboundEmail/AOPInboundEmail.php on line 27

Warning [2]: imap_append() expects at least 3 parameters, 1 given in /var/www/suitecrm-esg/include/Imap/ImapHandler.php on line 456

**Comment by afnieves** [comment] 2019-02-05 18:51
Hi @GFanta,

They just prevent the errors I was getting.  The auto import is still not working.  We are using IMAP with RACKSPACE hosted exchange.  I also tried it with GMAIL and no luck.

**Comment by Dillon-Brown** [comment] 2019-02-06 12:40
@afnieves I think i've finally been able to replicate this. Try adding ```$sugar_config['imap_test'] = false;``` to your config_override and then re-creating the email account.

It looks like this value was missed in 7.10.12 but fixed in the 7.10.13 upgrade packs.

**Comment by afnieves** [comment] 2019-02-06 18:20
@Dillon-Brown I added `$sugar_config['imap_test'] = false;` to your config_override and then re-creating the email account.  Same issue the mail is left unread in the mailbox

<img width="772" alt="screenshot 2019-02-06 11 14 16" src="https://user-images.githubusercontent.com/18472889/52363909-1c524b80-2a01-11e9-9208-3574ac271aaa.png">

**Comment by afnieves** [comment] 2019-02-07 17:10
@Dillon-Brown ,

On the new version 7.10.13 the server is saying BADCHARSET.

![screenshot 2019-02-07 10 08 00](https://user-images.githubusercontent.com/18472889/52429045-8d0c6d00-2ac0-11e9-9514-68109740d3fc.png)

**Comment by afnieves** [comment] 2019-02-07 19:35
@Dillon-Brown 
These are the changes I had to make in order to get emails being auto imported.

include/Imap/ImapHandler.php
line 456

* $ret = imap_append($this->getStream());

* $ret = imap_expunge($this->getStream()); /* E2E FIX */

line 724

- $ret = imap_search($this->getStream(), $criteria, $options, $emailCharset);

+  $ret = imap_search($this->getStream(), $criteria, $options); /*  E2E FIX */

modules/InboundEmail/AOPInboundEmail.php
line 59

* public function handleCreateCase(Email $email, $userId)

* public function handleCreateCase($email, $userId) /* E2E Fix */

This is communicating with MS Echange 2016 IMAP backend

**Comment by afnieves** [comment] 2019-02-07 19:43
@GFanta

This is the fix I had to implement.

**Comment by g-fantini** [comment] 2019-02-08 10:21
> @GFanta
> 
> This is the fix I had to implement.

Thank you so much @afnieves I'm testing your solution right now.

**Comment by Dillon-Brown** [comment] 2019-02-08 16:13
Hmm, so it seems like Exchange servers don't like UTF-8 at all. Have you tried changing ```default_email_charset``` in the config?

**Comment by afnieves** [comment] 2019-02-08 19:16
I set it to NULL and I still got BADCHARSET errors.

**Comment by afnieves** [comment] 2019-02-10 18:20
@GFanta,

Did it work for you?

**Comment by afnieves** [comment] 2019-02-27 18:00
@Dillon-Brown 

I also found this about the UTF-8 problem

https://github.com/barbushin/php-imap/issues/128

**Comment by cekowu** [comment] 2019-06-11 07:20
now ，What's the status about the issue ?

**Comment by wolfkiss0110** [comment] 2019-06-20 09:46
include/imap/ImapHandler.php line 717
original:
public function search($criteria, $options = SE_FREE, $charset = null)
change:
public function search($criteria, $options = SE_FREE, $charset = "US-ASCII")

I am not sure is it totally fix it. But, I can auto create case and import also.

**Comment by samus-aran** [comment] 2019-06-20 13:04
Thanks for your input @wolfkiss0110 !
@Dillon-Brown

**Comment by Dillon-Brown** [comment] 2019-06-24 11:33
I've put up a potential fix for this #7459. Let me know if you run into any issues.

**Closed** 2019-07-01 12:51 UTC
Labels: Emails, Fix Proposed, Medium Priority, Resolved: Next Release, bug

**Comment by fcorluka** [comment] 2019-09-02 14:06
Hi all, 

just to let you know that i had upgrade from 7.8.27. to 7.10.19. and now auto import and auto case creation is not working.
Inside my upgrade is code from #7459 but no help. I have tried with @afnieves fix, nothing.

I have a custom code inside modules/InboundEmail/AOPInboundEmail.php in function _handleCreateCase_ but now it seems that this code is never called.

We are comunicating with Microsoft O365.

**Comment by fcorluka** [comment] 2019-09-03 12:59
Today I have tested it with Gmail and it worked, so there must be something related to Microsoft.
Has anyone successfully connected and got auto-import-create from Microsoft Office 365?

**Comment by fcorluka** [comment] 2019-10-04 07:12
Just to tell you that this is still not working on my side.
I have a 7.10.19 version (upgraded from 7.8.27.), and connection with GMAIL is working fine, but with Office365 not.

I have managed to pinpoint line of code where the problem is:
_modules/Schedulers/_AddJobsHere.php_
code:
function: _**pollMonitoredInboxesAOP**_
`$GLOBALS['log']->debug('Trying to connect to mailserver for [ ' . $inboundEmailRow['name'] . ' ]');
            if ($connectToMailServer) {
                $GLOBALS['log']->debug('Connected to mailserver');

                if (!$aopInboundEmailX->isPop3Protocol()) {
                    **$newMsgs = $aopInboundEmailX->getNewMessageIds();**
                }

                **if (is_array($newMsgs))** {
                    $current = 1;`

Here is the funniest and from the developer side most horrible part of code.
This  " _**if (is_array($newMsgs))**_" in my case is FALSE, and there is NONE check for that. So the process simply stops at that part and nothing happens, no error, no info.
Real stopper is in the line up : " _**$newMsgs = $aopInboundEmailX->getNewMessageIds();**_", where the return value is somehow unclear, beacuse of the problem with Office365.
This function is in the file: _**modules/InboundEmail/InboundEmail.php**_, function: _**getNewMessageIds**_ .
For me this line returns nothing: _**$ret = $this->getImap()->search('UNDELETED UNSEEN');**_, or to be correct returns false. This false passes to a count function in logging and it says that there is "1 new Messages", returns that in "pollMonitoredInboxesAOP", checks if the value is array (FALSE != array), and code does no more ?!?!

Maybe I am totally wrong and have some major issues on my side, but the same code works with GMAIL but simply won't work with Office365 and code gives me no meaningful error.

**Comment by babington-andy** [comment] 2019-12-05 17:43
This still appears to be an issue on Office 365, the change [#7459](https://github.com/salesagility/SuiteCRM/pull/7459/files/2ebe3538ab61a4bc2e20a5b3e28694b52b2336d8) does not fix this unfortunately, I believe it's because Office 365 is not returning an exception when calling imap_search() (so it isn't caught by the try/catch), it's simply returning false (or a falsy value).

Hardcoding the charset as 'US-ASCII' does fix the problem, but obviosuly that's not a goof idea.

**Comment by QuocurIQ** [comment] 2021-04-27 19:07
Hello. 
For me it's working on 7.11.3 and not working on 7.11.18. IMAP on self managed server with dovecot/postfix. The emails are in the Activity table, but they don't get the imported checkmark ad on the other instance with 10.11.3.
