### ISSUE TITLE
SuiteP Themes bugs

### ISSUE THREAD

**Issue by edwardleehl7097** [salesagility/SuiteCRM#2939] opened 2017-01-18 07:08 UTC
billing address field showing outside of textbox in account module

**Comment by shogunpol** [comment] 2017-01-18 09:20
@edwardleehl7097  - Thank you for highlighting this issue, however, this is a duplicate of issue #2403. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2017-01-18 09:20 UTC
