### ISSUE TITLE
Reply-to address not saved in Profile > Email Settings

### ISSUE THREAD

**Issue by Monsonder** [salesagility/SuiteCRM#3202] opened 2017-02-28 15:35 UTC
#### Issue
When you go to Profile > Email Settings, there is a *Reply-to* checkbox after each email address. However, if you check the checkbox and press *Save*, the changes are not saved.

#### Expected Behavior
When you tick the checkbox and press *Save*, the checked checkboxes should remain checked. 

#### Actual Behavior
After saving, the Reply-to checkboxes are empty again. 

#### Steps to Reproduce
1. Go to Profile
2. Scroll down to Email Settings
3. Tick one or more Reply-to checkboxes
4. Press Save

#### Context
We want our employees to be able to choose from a set of Reply-to email addresses when sending emails to clients. Right now, you can only use your primary email address to send email (your other email addresses are not shown in the from dropdown in the compose email screen). 

#### Your Environment
* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 55.0.2883.87 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): Ubuntu 14.04, PHP 5.5.9, MySQL 5.5.54
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by kdjmonaghan** [comment] 2017-03-10 16:41
Hi, 

If this is still being an annoying issue you're trying to make some use of, I have a fix in the following PR: #3260 

This when reviewed and approved, will be merged into SuiteCRM eventually, but if you need it urgently, you can modify (or download) the file in the PR and append it to your SuiteCRM installation.

Thanks for reporting your issue! :)

**Comment by Monsonder** [comment] 2017-03-13 08:45
I tried the fix, but it still doesn't seem to be working. 

I think the problem is that the information is not correctly saved to the database. The `reply_to_address` of the corresponding email address in table `email_addr_bean_rel` still has a value of `0` after pressing the Save button. When you manually set the value to `1` and refresh the Edit Profile page, the checkbox is properly checked. But when you press Save on the Edit Profile page, `reply_to_address` goes back to `0` again.

**Comment by kdjmonaghan** [comment] 2017-03-13 10:02
@Monsonder I'll look into that - thanks - the data samples I was using appeared to store the record, but it might be a caching thing. I'll check the entry in the database against the records and see what the problem is with saving to that record if there's no changes.

Thanks for trying the fix - it's good to have the person who opened the issue's data sample tested also.

**Comment by kdjmonaghan** [comment] 2017-03-13 10:43
@Monsonder strange - I just checked my instance, the column is being upgraded correctly with my sample data. Version I'm using is 7.8.2, using the admin account. Have you tried to delete your cache? The problem before is that it was being cached inside of a SMARTY template when it shouldn't have been. :)

**Comment by Monsonder** [comment] 2017-03-13 14:48
I am also on 7.8.2 using an admin account. I deleted the cache directory, but it didn't have any effect. 

Initially we thought we needed the reply-to boxes in order for our users to be able to send email from our main email account, but we've already found another way to let them do this. 

I'm not sure about the intended functionality either, but I'll gladly try some more fixes and find out :-)

**Comment by kdjmonaghan** [comment] 2017-03-13 16:56
Hi,

I've been looking into this, this afternoon using 7.8.2 with demo data upon install. I modified a few files to match what the input fields should have been...

Previously they were checkboxes when they should have been radio buttons based on what Sugar 5 was showing these as. I don't think this will be the source of your problem, but it was different to how the functionality was supposed to be as checkboxes normally entails a multiple choice scenario where radio is singular choice.

Regardless, the radios have been changed in the latest commit to that PR, which you can find here should you wish to try the changes to see if it makes any difference: #3260 

Using the following files, please do the following from your admin account:

* From the user dropdown once logged in, click "Admin"
* Under "System" click "Repair"
* Click "Repair JS Files"
* Wait a few minutes
* Try the email reply-to options again, selecting a different (or new if one has not been yet set) option.
* Save it and then go back to the editing page and see if it went to the one you expect.

**NOTE: for some reason, the order restructures, so please take note of the e-mail address you select to reply-to before you submit the changes and compare against only that e-mail. This is another issue I'll be looking into at some point to do with this as it's confusing from a user experience point of view. :)** 

Hopefully we can find out what's wrong with this functionality between us. :)

**Comment by Monsonder** [comment] 2017-03-15 09:31
It works! 

The different order of the email addresses after changing the reply-to address may indeed be a bit confusing, but not too big of an issue for me because the radio buttons are working properly now. 

Thanks for all your help @kdjmonaghan

**Comment by kdjmonaghan** [comment] 2017-03-15 10:02
Good to hear it works. Thanks for testing the solutions. :)

**Comment by jack7anderson7** [comment] 2019-02-04 14:02
We have found that this is no longer an issue in our latest 7.8 version and advise upgrading to that if you still find this an issue.

**Closed by jack7anderson7** 2019-02-04 14:02 UTC
Labels: Fix Proposed, Low Priority, bug
