### ISSUE TITLE
Reports generates incorrect sql when field equals value and value is blank

### ISSUE THREAD

**Issue by mikesolo** [salesagility/SuiteCRM#2091] opened 2016-08-31 13:36 UTC
#### Issue
When adding a condition of field equals value and the value is blank the sql generated is incorrect

#### Expected Behavior
what should happens is that the sql should read
AND ( field = '' OR field IS NULL)
what gets generated is AND  field = '' OR field IS NULL 

when you have multiple conditions you get too many records returned 

#### Possible Fix
edit modules/AOR_Reports/AOR_Report.php

on line 1484 replace
if($condition->value_type == 'Value' && !$condition->value && $condition->operator == 'Equal_To') {
                        $value = "{$value} OR {$field} IS NULL";
                    }

with 

if($condition->value_type == 'Value' && !$condition->value && $condition->operator == 'Equal_To') {
                        $value = "{$value} OR {$field} IS NULL)";
                        $condition->logic_op = 'AND(';
                        
                    }

**Comment by ijdavie** [comment] 2016-09-01 13:12
this appears to be a duplicate of issue #1812

**Closed by ijdavie** 2016-09-01 13:12 UTC
