### ISSUE TITLE
Reference to /custom/themes/  in jjwg_Maps

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#1207] opened 2016-04-06 09:43 UTC
Highlighted in this forum post: 
https://suitecrm.com/forum/suite-themes/8803-i-can-t-to-see-image-markers-in-maps

When investigating:
In the file: _/modules/jjwg_Maps/views/view.map_markers.php,_
I found a few references to _/custom/themes/_ locations where there are no longer any folders/files.

Some examples:
Line 126 contains:   **$icons_dir_base = 'custom/themes/default/images/jjwg_Maps/';**

Line 153 contains:   **var icons_dir = <?php echo (!empty($icons_dir)) ? json_encode($icons_dir) : "'custom/themes/default/images/jjwg_Maps/0-10/'"; ?>;**

**Comment by JimMackin** [comment] 2016-04-06 15:24
Duplicate of #1186

**Closed by JimMackin** 2016-04-06 15:24 UTC
Labels: duplicate
