### ISSUE TITLE
Autoloading Classes in SuiteCRM - nice to have

### ISSUE THREAD

**Issue by opravil-jan** [salesagility/SuiteCRM#3593] opened 2017-05-25 10:00 UTC
I think SuiteCRM should have autoloading classes mechanism implemented so it can get rid of include and require in code. Something similar to this https://doc.nette.org/en/2.4/auto-loading. Keep recommendation http://www.php-fig.org/psr/psr-4/ and https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md in mind.

**Comment by pgorod** [comment] 2017-05-25 11:25
You are right, of course, but I think this can be considered a duplicate of #3237 which takes some excellent steps in that direction, although it's not the complete thing yet.

**Comment by chris001** [comment] 2017-05-25 18:49
From the Sugar 7.9 release notes:
An improvement to Sugar's Autoloader, the majority of core Sugar PHP classes are now autoloadable, even many of those that are not PSR{0,4} compliant. This means that boilerplate code like require_once 'include/api/SugarApi.php' is no longer needed. Most of the unnecessary require_once calls have been removed from the Sugar codebase. When adding new non-PSR4-compliant classes (e.g. custom/clients/base/api/SomeNewApi.php) then you may need to delete cache/class_map.php and cache/file_map.php or run a Quick Repair and Rebuild. This will clean the autoloader cache so that your new class is indexed and autoloaded by Sugar at runtime.

How to use it from a blog post :
If you want to use namespaces following the PSR-0 standard for your custom code, it is now possible with the SugarAutoLoader in sugar7. Now you don’t have to insert require statements all over the place.

```
require_once('include/utils/autoloader.php');   // SugarAutoLoader

SugarAutoLoader::addNamespace('ThirdPartyLibrary\\', 'custom/include/ThirdPartyLibrary');
```
Sugar’s autoloader will now map requests for the class `ThirdPartyLibrary\Example\Test` to the file `custom/include/ThirdPartyLibrary/Example/Test.php`.

Sugar 6.5 includes `SugarAutoLoader`, yet it's missing the function `addNamespace`.  This function should be added.

**Comment by opravil-jan** [comment] 2017-05-27 12:09
I think it is not only about implementing function addNamespace. SuiteCRM should reimplemented autoloader.php as is describe here https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md. Not just add one function.

**Comment by chris001** [comment] 2017-05-27 16:33
Both would be great to add.  The PSR-4 autoloading, and the compatibility with Sugar 7.9 by adding `SugarAutoLoad::addNamespace()`.

**Comment by Dillon-Brown** [comment] 2017-06-01 15:45
![](https://github.trello.services/images/mini-trello-icon.png) [Autoloading Classes in SuiteCRM - nice to have](https://trello.com/c/wCTOi3xp/185-autoloading-classes-in-suitecrm---nice-to-have)

**Comment by Dillon-Brown** [comment] 2017-06-01 15:46
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Closed by Dillon-Brown** 2017-06-01 15:46 UTC
Labels: suggestion
