### ISSUE TITLE
Repair and Rebuild 

### ISSUE THREAD

**Issue by ijdavie** [salesagility/SuiteCRM#991] opened 2016-02-23 08:57 UTC
If you change the vardef type of a field from decimal to varchar. 

the repair and rebuild process does not appear to pick up the change, resulting in the database being out of sync with the system.

**Comment by paulgodley** [comment] 2016-03-09 15:02
I have found the cause of this.  In DBManager->repairTableParas, the foreach for the column checks only runs for those items with a source of 'db'.  This means that custom_fields are skipped.  I have added in a fix for this, but this also means changes to the MySQLManager, and therefore the other Managers as well.  This would introduce a potential brittle area to the created SQL (as the current managers are not intended to be used in this way), so after speaking to @JimMackin, this issue is parked until a further discussion can be had around it.

**Comment by vjaro** [comment] 2016-03-10 03:17
+1

**Comment by cameronblaikie** [comment] 2019-06-14 09:36
Closed due to inactivity, if you feel this should be reopened then do so and we will review your issue again.

**Closed by cameronblaikie** 2019-06-14 09:36 UTC
Labels: Low Priority, Requires Review, bug
