### ISSUE TITLE
WYSIWYG field does not render html in PDF Templates

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#4436] opened 2017-10-22 08:24 UTC
#### Issue
HTML not interpreted in PDF tempaltes
#### Expected Behavior
Having an exported PDF with interpreted HTML
#### Actual Behavior
You get the RAW  HTML code displayed in the PDF file.
#### Steps to Reproduce
1)install the WYSIWYG module on suitecrm 7.8.8 ( upgrade from fresh install of 7.8.7)
https://suitecrm.com/index.php?option=com_mtree&task=viewlink&link_id=53&Itemid=1225
2) created a field WYSIWYG in my quote. 
3)Then edit  WYSIWYG field within my quote
4)Finally  "print PDF"
5) get the RAW html in the PDF
![bug-wysiwyg-7 8 8](https://user-images.githubusercontent.com/26340942/31859929-21a976e2-b713-11e7-81d5-178bdc91837a.png)

#### Your Environment
Ubuntu 16.04
apache 2.4
firefox and chrome
suitecrm 7.8.8

**Comment by hubyhuby** [comment] 2017-10-22 08:56
Oops, please close this bug if you think it is a dublicate...
I saw the bug here but as it is closed and fixed.... and not aclually fixed in the latest release I am running 7.8.8 I thought it needed to be reopened...https://github.com/salesagility/SuiteCRM/issues/241

I tried to replace the templateParser.php with the fixed one on 7.8.8 but had no luck it then show BLANK text in place of the HTML before : https://github.com/salesagility/SuiteCRM/commit/5533dcb7a6260ff71c646ed760da4f6a020e1581

**Comment by Dillon-Brown** [comment] 2017-10-25 11:21
Closing as a duplicate of #241. The original issue was closed after being moved over to Trello and not because the fix was merged or confirmed to be working. It looks like we still need a proper fix for this issue.

**Closed by Dillon-Brown** 2017-10-25 11:21 UTC
Labels: duplicate

**Comment by hubyhuby** [comment] 2019-08-12 15:00
Dear @Dillon-Brown ,
Yes I applied again manually the fix provided here from the PR ; and it works like a charm.
https://github.com/ApatheticCosmos/SuiteCRM/blob/aac97a311ddb4e8fcb24d693c5ee26be1ec079b8/modules/AOS_PDF_Templates/templateParser.php

Please merge this PR, as I doubt it is solved in 7.10 + branch
I don t have access to Trello .... I believe it is "a bit" confusing to have the bug #241 closed ....and not have the fix merged ... I guess I ll open a "New new new " bug in one year when I switch to 7.10 ;)
