### ISSUE TITLE
Web to lead multiselect fields not working

### ISSUE THREAD

**Issue by osypets** [salesagility/SuiteCRM#3598] opened 2017-05-26 10:03 UTC
Hello! 

Its seems problem with multiselect fields in forms they are not adding in Lead when submitting form. 

#### Issue

Create custom multiselect filed in Studio for Leads module after that create new web to lead form which includes that filed and after publish it somewhere. After open that form fill all fields and submit form, data from mutiselect fields isn't adding to the database.

#### Expected Behavior

Multiselect fileds must be added to system DB like other form data types (input, select, etc).

#### Actual Behavior

Data from mutiselect fields isn't adding to the database.

#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version: Safari 10.1.1
* Environment name and version: Apache + MySQL5.7.18 + PHP7.0.15
* Operating System and version: Ubuntu 16.04

**Comment by osypets** [comment] 2017-05-31 03:53
There are also errors in Apache error log file when submitting form:

`[Wed May 31 03:38:54.552654 2017] [fcgid:warn] [pid 9420] [client ] mod_fcgid: stderr: PHP Warning:  mysqli_real_escape_string() expects parameter 2 to be string, array given in /home/drm/public_html/include/database/MysqliManager.php on line 260, referer: https://forms.mysite.net/`

`[Wed May 31 03:38:54.552656 2017] [fcgid:warn] [pid 9420] [client ] mod_fcgid: stderr: PHP Warning:  urlencode() expects parameter 1 to be string, array given in /home/drm/public_html/modules/Campaigns/WebToPersonCapture.php on line 208, referer: https://forms.mysite.net/`

**Comment by bakay78** [comment] 2018-03-28 19:37
Hey !

I have the same problem, did you find any solution for this issue?

Thanks

**Comment by lazka** [comment] 2019-01-07 15:42
Likely fixed by #6732

**Comment by Mausino** [comment] 2019-01-07 19:55
@Dillon-Brown @lazka thanks, i can confirm, that it solved my issue with multiselect fields.

**Comment by lazka** [comment] 2019-01-08 07:58
> @Dillon-Brown @lazka thanks, i can confirm, that it solved my issue with multiselect fields.

Thanks for testing it!

**Comment by Mausino** [comment] 2019-01-08 10:50
@Dillon-Brown @samus-aran shoud it be in newiest upcoming relase and marking with milestone label 7.10.12 ???

I asking only because I know that in this milestone we have almost 50 issues, but if issues is reported and fixed and tested, will great if will go (after your check of quality of code) to next upcoming relase that everybody will see if create good patch for issue... will this moved to next relase. This will have great value for people which worked on isssue, patch and tests.

**Comment by Dillon-Brown** [comment] 2019-01-08 13:13
@Mausino We were usually adding the milestone labels after the PR had actually been merged unless it was pre-planned to get fixed. Atm with 138 "Fix Proposed" I don't think it would be very useful for tracking to add them all to the milestone as the ones that didn't make it into the release would all need continuously moved to the next milestone.

**Comment by Mausino** [comment] 2019-01-08 13:33
@Dillon-Brown thank you for your answer 👍 Last question: Is any key by which should be the issue label by milestone ? I am asking only that i don't want spam you by this type of requests.

**Comment by Dillon-Brown** [comment] 2019-01-08 16:20
@Mausino Essentially any issue that has "Resolved: Next release" should have a milestone applied. Although if you do see an issue that you think needs to go into the next release even if it doesn't have a fix already, don't hesitate to mention it. Though it won't always be possible for us to get to it in time.

**Comment by Mausino** [comment] 2019-01-08 16:43
@Dillon-Brown do you think thats will good idea another milestone like 7.10.13 ??? because in 7.10.12 is too much issues which need to process by @salesagility  and i think there is no capacity to add next issues to 7.10.12.

I think will great if users will see that their issues which are solved + tested by community should be in plan to next relases and 7.10.13 will great place where we can handle issues with solutions till time when relase 7.10.12  will done.

**Closed** 2019-04-30 16:46 UTC
Labels: Fix Proposed, Medium Priority, Resolved: Next Release, bug
