### ISSUE TITLE
7.11.3 version, inbound email don't show attachment

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7181] opened 2019-04-11 08:41 UTC
#### Steps to Reproduce

1. config inbound email account
2. send email to the account with attachment
3. view the email detail
4. don't show attachments

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mausino** [comment] 2019-04-11 11:24
@cekowu is your ticket the duplicate of this #5190 ???

**Comment by cameronblaikie** [comment] 2019-04-11 13:07
Closing this issue as its a duplicate from - https://github.com/salesagility/SuiteCRM/issues/5190

**Closed by cameronblaikie** 2019-04-11 13:07 UTC
