### ISSUE TITLE
[language] Unused language strings in ver. 7.10.8

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#6314] opened 2018-09-17 07:43 UTC
['LBL_LOGIN_AS']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/include/language/en_us.lang.php#L3481

['LBL_LOGOUT_AS']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/include/language/en_us.lang.php#L3482

--------------------------------------------------------------------------------

['LBL_FTS_SETTINGS']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L250

['LBL_FTS_SETTINGS_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L251

['LBL_GLOBAL_TEAM_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L252

['LBL_GLOBAL_TEAM_SELECT']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L253

['LBL_GLOBAL_TEAM']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L254

['LBL_UPDATE_CHECK_AUTO']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L536

['LBL_UPDATE_CHECK_MANUAL']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L537

['LBL_JJWG_MAPS_ADMIN_DONATE_TITLE']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L796

['LBL_JJWG_MAPS_ADMIN_DONATE_DESC']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L797

['LBL_AOP_OPENING_DAYS']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L854

['LBL_AOP_OPENING_HOURS']

https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L855

['LBL_AOP_CLOSING_HOURS']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Administration/language/en_us.lang.php#L856

--------------------------------------------------------------------------------

['LBL_SEND_BUTTON_KEY']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Meetings/language/en_us.lang.php#L103

--------------------------------------------------------------------------------

['LBL_TRIMSUGARFEEDS']
https://github.com/salesagility/SuiteCRM/tree/v7.10.8/modules/Schedulers/language/en_us.lang.php#L149

**Comment by ChangezKhan** [comment] 2018-10-11 18:36
@Dillon-Brown What should we do this here? Delete all these language strings?

**Comment by Dillon-Brown** [comment] 2018-10-12 07:46
@ChangezKhan If they are truly unused then yes, a simple search won't always work as some strings are built dynamically.

**Comment by ChangezKhan** [comment] 2018-10-12 07:52
@Dillon-Brown if some language strings are built dynamically, then how can we check whether the string is unused or not? Is there any way to do that?

**Comment by likhobory** [comment] 2018-10-12 08:40
Small addition:  these labels have been removed earlier, in versions 7.9.x,
but again appeared in version 7.10.8
Was it done on purpose or by mistake?

**Comment by Dillon-Brown** [comment] 2018-10-12 09:14
@ChangezKhan There's no easy way to check but you can play around with grep and do some manual testing to confirm, see #4291 for an example.

**Comment by Dillon-Brown** [comment] 2018-10-12 09:19
@likhobory Looks like a mistake, they were removed in the hotfix branch but then re-added in when hotfix-7.8.x was merged back into hotfix.

**Comment by pgorod** [comment] 2019-04-25 16:07
@likhobory sorry, this is off-topic here, but can you reproduce the bug described in this thread? 
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/24411-the-problem-is-sending-a-new-letter-if-the-username-is-in-cyrillic

**Comment by likhobory** [comment] 2019-04-26 16:33
Confirmed.

![изображение](https://user-images.githubusercontent.com/5983672/56822501-ed0de680-6859-11e9-9149-bbe1aa5a5281.png)

**Closed** 2019-11-04 14:25 UTC
Labels: Fix Proposed, Good First Issue, HacktoberFest, Language, Resolved: Next Release
