### ISSUE TITLE
Pop up window under the header when edit dashlet 

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#2762] opened 2016-12-06 09:00 UTC
#### Issue

When i edit my dashlet widget with edit button, the pop up stay under the header and i could not close it.

![issue](https://cloud.githubusercontent.com/assets/22373035/20919145/6136e52e-bbab-11e6-9b09-aaf33ad226f8.png)

#### Steps to Reproduce

1. Edit dashlet
2. Look at the pop up and try to close it

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL 10.0.27
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Linux 16.04
* Theme : Suite 7

**Comment by pgorod** [comment] 2016-12-06 13:20
I've seen this happen in other situations with similar pop-ups (some error messages, for example).

I know how to get around this, but it is annoying for some less technical users because they will actually get stuck and call for support on a situation like this - they don't know where to click (on the error messages you need to click the X on the top-right corner), can't think about refreshing the page, etc.

I get this with SuiteR theme, btw.

**Comment by Dillon-Brown** [comment] 2019-08-05 13:16
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Closed by Dillon-Brown** 2019-08-05 13:16 UTC
Labels: Fix Proposed, Low Priority, bug
