### ISSUE TITLE
Target list export, export of contacts

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#858] opened 2016-01-21 06:47 UTC
export of target list funktion only exports contacts if they have an assignment to an account.
when they don't have an assignment they are ignored in the export query.

**Comment by EZS-JD** [comment] 2016-02-03 13:51
I'm getting database failure when exporting the "members" of the target lists, but no log entry.
Don't know if this is a problem particular to our installation though.

**Comment by CaptainChainsaw** [comment] 2016-02-03 15:40
@Lehnerr I've tested this using Version 7.5 of SuiteCRM and its working for me.  I was able to create a new target with only, first name, last name and email address and no other values.  I tried exporting the record and it was exported as expected.  I understand that this has already been fixed.

@EZS-JD are you receiving any error message at all?  What version of SuiteCRM are you using?  How many records are you trying to export?  It would be worth checking the apache error log too.  Any further information on this would be great.

**Comment by adriangibanelbtactic** [comment] 2016-02-05 21:09
I'm not sure about @Lehnerr  description but what @EZS-JD and @CaptainChainsaw are reporting I'm pretty sure it's fixed by my pull request: https://github.com/salesagility/SuiteCRM/pull/923 . Feedback by using the pull request is welcomed.

**Comment by Lehnerr** [comment] 2016-02-08 10:32
Hi.
I've tested now with 7.5.1.
I've created some contacts without an relationship to an account. And one conatct with relationship to an account.
Then I create a target list and put in all created contacts.
When I start export of the target list, only the one account with the relationship to the account is exported. All others are missing in the csv file.
think it is a bug.
regards

**Comment by CaptainChainsaw** [comment] 2016-02-09 11:35
@Lehnerr I've reproduced this.  I have a target list containing two contacts, one with an associated account and one without.  Only one record is exported.  Looks like a bug to me, I'm looking into it.

**Closed** 2016-03-07 17:27 UTC
Labels: bug, fix proposed

**Comment by chris001** [comment] 2016-03-16 00:50
@johnwbyrd will be happy!
https://github.com/sugarcrm/sugarcrm_dev/pull/202

**Comment by johnwbyrd** [comment] 2016-03-16 05:29
Yes, I am quite happy.  Please continue to eat SugarCRM's lunch as much as you possibly can.
