### ISSUE TITLE
Remove a custom module and add again dont manage acl_actions correctly

### ISSUE THREAD

**Issue by dflois** [salesagility/SuiteCRM#4477] opened 2017-11-02 13:13 UTC
#### Issue
When you create a custom module from modulebuilder and you do the deployment, the crm populate the table acl_actions with the appropiate data. If you remove your customization from Moduleloader, the crm marks as deleted your data in the table acl_actions. However, if you do a new deployment of your module, in this case the crm doesnt add new rows for your custom modules; when that happens you can't see your modules as regular user, etc...

#### Expected Behavior
A new redeploy must add his acls to acl_actions.

#### Actual Behavior
When you redeploy a deleted package the crm doesnt populate the acl_actions table.

#### Possible Fix
A fix for the users is update the table acl_actions to deleted=0 for all the modules of your packages

#### Steps to Reproduce

1. Create a new package on modulebuilder and deploy it
2. Uninstall and delete the package from moduleloader
3. Deploy de package from modulebuilder

#### Your Environment
PHP 7.1.9
SuiteCRM 7.9.7
CentOS 7

**Comment by PedroErnst** [comment] 2018-02-08 14:46
Thanks for reporting this @dflois 

I haven't been able to reproduce this issue on the current LTS 7.8 version or any of the newer ones.

**Comment by Mausino** [comment] 2019-07-26 19:58
@Dillon-Brown i thing this is outdated issue, because version 7.8 is EOL and without any respond from @dflois more as one year.

**Comment by Dillon-Brown** [comment] 2019-08-02 15:30
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Closed by Dillon-Brown** 2019-08-02 15:30 UTC
Labels: Medium Priority, bug
