### ISSUE TITLE
Fields with link aren't working (cann't load related record) if you edited by inline edit other link record

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#3148] opened 2017-02-17 16:11 UTC
#### Issue

Hi, it is hard to describe, but i did the videoscreen: https://www.screencast.com/t/LaYhXPmvD

This issue persist in listview and in detailview. Problem is if you edit the linked record and after the other linked field isn't react on click. they do nothing. It is working only if you refresh the page. 

This issue flustrating us, because if we edit some linked field or assign something to record, you must first refresh the page and after all the linked fields are working correctly.

#### Expected Behavior

If i edit link field, the other link fields stay clickable.

#### Steps to Reproduce

1. Any listview (or detailview)
2. Edit link field 
3. Try to click ohter link field and open in same window a record

#### Your Environment

* SuiteCRM Version used: Official SuiteCRM Demo 7.8.1
* Browser name and version: Chorme 54.x
* Operating System and version: Win 10 Home

**Comment by kdjmonaghan** [comment] 2017-02-17 17:05
Hi,

Thanks for your video - helped replicating the issue quicker.

The problem is when you close the relate field via either saving or just closing, the clicks counter thinks it's at 2 when you click on the URL and not 1 (as it should be, but isn't, for whatever reason) until you go into another inline edit field.

When you change the check where the link is followed if the clicks is set to 1 to also checking for 2, the url is followed as expected. Problem with this is that the clicks are just incorrectly counted to 2 for some reason (the increment happens twice, for some reason)

I've taken note of this and looking into fixing it.

Thanks for flagging the issue.

**Comment by kdjmonaghan** [comment] 2017-02-20 11:04
@Mausino Applied a fix in the pull request above. As it'll need to be merged back in to master and released in a later version of SuiteCRM, you can modify your local version with the changes listed within the PR if you feel comfortable doing so to resolve the frustrating issue for now. :+1:

**Comment by Mausino** [comment] 2017-02-20 11:38
@kdjmonaghan  thank you so much :) we changed our local version, because solutions for many issues aren't still merged yes (some pull request have almost 2 years) but i understand that SuiteCRM team has many challenges ahead them and i hold all which are contributing on this great project my finges 🥇

**Closed** 2017-02-27 17:02 UTC
Labels: bug, Fix Proposed, Low Priority, Resolved: Next Release
