### ISSUE TITLE
Bad data passed in; When duplicate campaign

### ISSUE THREAD

**Issue by danicv94** [salesagility/SuiteCRM#2557] opened 2016-11-03 11:20 UTC
Hey,

When I'm in the module campaigns, and I try to duplicate, this error appear:
Bad data passed in; Return to Home
I tested it on other suiteCRM's, from version 7.6.5 to 7.7.6 it's not working, but I tried the same thing in other suiteCRM with version 7.1.7 and it works perfect, so I think it is a version problem.

Thanks!

**Comment by garrettw** [comment] 2016-11-08 16:36
I just installed SuiteCRM yesterday and I get this error when I try to create a new user from the admin account. Sure would be helpful to know exactly what data is bad.

**Comment by shogunpol** [comment] 2017-02-02 14:33
@danicv94 , an issue has been tested in recent version SuiteCRM(7.8), and seems to not appear, can you confirm it?

**Comment by shogunpol** [comment] 2017-02-21 13:15
Thank you for raising this issue however due to no activity in the last 14 days this issue will be closed, If this issue still exists and information can be given to allow us to proceed with this it can be reopened.

**Comment by khalidk7** [comment] 2017-03-04 21:05
This issue still persists.
I just installed a new SuiteCRM build instance.  Here are the specs:
-Suite Version 7.8.1
-CentOS 7
-PHP 7

When I click on a campaign and then under Actions go to "Duplicate", I get the following error:

Bad data passed in; Return to Home

I have my System Log Level set to "Debug" and there's no logging activity in the log after executing the above steps.

Any advice would be appreciated.

Thank you,

**Comment by pgorod** [comment] 2017-03-23 20:07
Can anybody with this problem please test if [this fix](https://github.com/imtg-suitecrm/SuiteCRM/commit/162236fcb53465d85100eee35d8683170aee790e) (for a similar error) solves your problem too?

**Comment by khalidk7** [comment] 2017-03-26 19:46
@pgorod I replaced my version of /include/SubPanel/SubPanelTiles.js with your [version](https://github.com/imtg-suitecrm/SuiteCRM/commit/162236fcb53465d85100eee35d8683170aee790e) 

I then went to Admin and did "Quick Repair and Rebuild" and "Rebuild Relationships"

Then I retried the above steps in my initial post and I still get the same error.  So this does not appear to fix the issue.

**Comment by pstevens71** [comment] 2017-10-22 16:30
I can confirm this is still an issue in 7.9.7
When you duplicate a "newsletter" type campaign you immediately get "bad data passed" in your browser.  There is no other information and there are no errors in php log or suite crm log.

**Comment by pstevens71** [comment] 2019-06-25 14:16
In case anyone is still following this is still an issue in 7.11.4.  You don't get the "bad data" warning but when you duplicate a campaign it just refreshes the browser and directs you to the final screen of the campaign wizard with no duplicate created.

**Comment by Mac-Rae** [comment] 2019-08-02 15:18
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)

**Closed by Mac-Rae** 2019-08-02 15:18 UTC
Labels: Low Priority, bug
