### ISSUE TITLE
Run Email Reminder Notifications

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#8277] opened 2019-11-19 15:28 UTC
I have noticed that my installation does not send out email reminder notifications for meetings, tasks or calls. These are the scheduler settings:

![image](https://user-images.githubusercontent.com/34719141/69160260-f6121e00-0af1-11ea-9600-a736427cab15.png)

Currently on SuiteCRM version 7.11.8

**Comment by Mac-Rae** [comment] 2019-11-20 10:49
Hi @MyBlissIT,

Can you confirm if other Schedulers are running correctly?

**Comment by MyBlissIT** [comment] 2019-11-20 15:46
> Hi @MyBlissIT,
> 
> Can you confirm if other Schedulers are running correctly?

The only scheduler running is system reminders

**Comment by Mac-Rae** [comment] 2019-11-20 16:55
Thanks @MyBlissIT,

I'm assuming you mean that all schedulers are disabled other than Email Reminder Notifications? If this is the case and you verify that cron is running correctly?

**Comment by MyBlissIT** [comment] 2019-11-21 01:49
> Thanks @MyBlissIT,
> 
> I'm assuming you mean that all schedulers are disabled other than Email Reminder Notifications? If this is the case and you verify that cron is running correctly?

All schedulers are abled or active:

![image](https://user-images.githubusercontent.com/34719141/69293535-d3772680-0c11-11ea-8b16-889fbd97af02.png)

**Comment by pgorod** [comment] 2019-11-21 11:09
You need to go into each one and check the "last ran successfully" field.

**Comment by Dillon-Brown** [comment] 2019-11-21 11:13
I can take a quick look at this, looks like a duplicate of #6990

**Comment by Dillon-Brown** [comment] 2019-11-21 11:17
Put up a quick fix here: #8285, let me know if you encounter any further issues and we can re-open. Will close this as a duplicate for now.

**Closed by Dillon-Brown** 2019-11-21 11:17 UTC
Labels: Question
