### ISSUE TITLE
blank list view after doing a basic search 

### ISSUE THREAD

**Issue by dursuntosun** [salesagility/SuiteCRM#2771] opened 2016-12-07 07:17 UTC
#### Issue

I am using the accounts module as an example but also happens for other modules.
If I go to Accounts it gives me a list view of all my accounts.
If I type a search term in the search box and hit search, the search comes back blank.
If I then click 'clear' and press search I get nothing returned.
I can now NOT get the list view of accounts back, it always returns blank.

However if I go to 'advanced search' and click search without selecting any criteria it returns the full list of accounts.
Every time I now go to Accounts it defaults to advanced search!
If I go back to basic search it still returns a blank page.

This occur after changing  multi-select field to drop down field in basic search form. All dropdown fields are rendered as multi select fields at SearchForm. In order to render it as a regular enum fields i should need to add the following attribute at the field defs inside searchdefs.php

'displayParams' => array(

  'size' => 1,

),

After doing this, some dropdown list selection does not have result.

![issue1](https://cloud.githubusercontent.com/assets/22373035/20958342/38aa55d0-bc66-11e6-9976-4a1f24192e86.png)

![issue2](https://cloud.githubusercontent.com/assets/22373035/20958341/38aa259c-bc66-11e6-8811-0eca162a2cb4.png)

![issue3](https://cloud.githubusercontent.com/assets/22373035/20958344/38ab00fc-bc66-11e6-94d6-83fce78eb358.png)

![issue4](https://cloud.githubusercontent.com/assets/22373035/20958345/38ab2f1e-bc66-11e6-9bdd-63ef9d8ae8ef.png)

![issue5](https://cloud.githubusercontent.com/assets/22373035/20958343/38aa612e-bc66-11e6-95ac-77af5d09e8a0.png)

![issue6](https://cloud.githubusercontent.com/assets/22373035/20958340/38a80906-bc66-11e6-98f1-109d5862d0a8.png)

![issue7](https://cloud.githubusercontent.com/assets/22373035/20958346/38c232fe-bc66-11e6-8411-e41aca7ff07f.png)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL 10.0.27
* Operating System and version (e.g Ubuntu 16.04): Ubuntu Linux 16.04
* Theme : Suite 7

**Comment by shogunpol** [comment] 2016-12-12 14:24
(tag and Close issue)

@dursuntosun  - Thank you for highlighting this issue, however, this is a duplicate of issue #2581. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2016-12-12 14:24 UTC

**Comment by dursuntosun** [comment] 2016-12-13 06:36
When i try to fix issue according to  #2581, it does not solve my problem. My problem is continue and not same as this issue.
