### ISSUE TITLE
Calendar Display Issue on Dashboard

### ISSUE THREAD

**Issue by murdal** [salesagility/SuiteCRM#550] opened 2015-10-09 12:56 UTC
Displaying the side-bar on the dashboard is causing the Calendar to scramble, hiding the side-bar fixes the issue.

![calendardashlet](https://cloud.githubusercontent.com/assets/7024475/10394205/72eebbdc-6e8d-11e5-9cf5-9ae5379546bf.png)

**Comment by mattlorimer** [comment] 2016-03-07 08:52
duplicate of #160

**Closed by mattlorimer** 2016-03-07 08:52 UTC
Labels: duplicate
