### ISSUE TITLE
HTML tags visible in notification email Subject

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#1472] opened 2016-05-23 15:03 UTC
From what I gather, every single notification email for **every SuiteCRM installation that is using a Crowdin translation** is currently being sent with this sort of subject line (as viewed by end-users):

Record assignment:
`<p>Contacto CRM - Francisco Silva</p>`

Call Reminder:
`<p>Chamada de CRM - Perguntar ao cliente</p>`

Despite not being a critical bug, it _is_ quite visible and doesn't make SuiteCRM look good.

Those HTML tags are a consequence of the way the Crowdin translation platform handles the template file `include/en_us.notify_template.html` which is not a real HTML file, though it pretends to be one. I've checked with @horus68 and there is no easy fix for this from the Crowdin side of things.

So I will propose a PR here to fix this, by stripping HTML from all email notification's Subject lines. I argue that this makes sense anyway because we are using bits of HTML from a template file, but subject lines should never include HTML tags, according to the official specs.

This is my first PR, let me know if I'm doing something wrong...

**Comment by pgorod** [comment] 2016-05-23 15:08
If this PR gets merged, then (_and only then_) it would be a good idea to move this one forward also:
https://github.com/salesagility/SuiteCRM/pull/867
so that this tricky file stops giving headaches to dozens of translators out there.

It's important that Crowdin can see each string as a separate string, that's why this is needed. Otherwise manual processes have to be used, it's (a lot) more work for horus68 and it also causes some translators to not understand how to translate, and just give up on translating those files.

Every hour of work spent merging horus68 pending PR's will translate (pun intended) to dozens of hours of work for the SuiteCRM cause as a whole, because there are _many_ people working on the translations...

**Comment by pgorod** [comment] 2016-05-23 18:13
PR is #1473

**Comment by samus-aran** [comment] 2016-06-24 08:47
@pgorod - Why would we need to wait for the PR #1473 to be merged before merging horus68's PR #867? :)

**Comment by pgorod** [comment] 2016-06-24 09:04
@samus-aran because in his commit he adds a bunch of `<p>` and `</p>` to the English version of the file. You would basically extend the bug, currently only visible in the translated versions, to the English version as well. It only makes sense once the code to strip the HTML codes is in.

Of course, you can merge this one first and the other only later, as long as you make sure they get released simultaneously...

I'm not familiar really with Github, and I'm working only from the web interface (no git), but I'll try re-doing my PR this morning following your instructions.

**Comment by horus68** [comment] 2016-07-04 14:54
If this is not possible to merge on issues using Github and conflict on merging, Salesagility should be able to do that by hand.
Else this is not merged at all!

**Comment by samus-aran** [comment] 2016-07-04 15:39
@horus68 We understand not all users have the technical know how to resolve github issues easily - and we do certainly try to help where we can (if we can since more recently its been a clahub issue).  We are at the moment have limited time ourselves when it comes to github issues (we categorise, test issues, then review PRs, and test them aswell) and we are working through what we can.  If you can see recently we have placed a few PRs into the Backlog category with the aim to get through these as physical merges (as you state we need to do) so we are aware that things need to be mopped up.  We assure you we are mowing through this bugs/PRs as quickly as we can but please raise an issue as a high priority and we'll review it (either as an issue or PR).

@pgorod Have you been able to re commit via git and not via the webface?  If not, then let me know and I'll high priority that backlog issue :+1:

**Comment by pgorod** [comment] 2016-07-04 15:53
@samus-aran I don't think we non-admins have the option of creating an issue as high-priority. And we also can't add labels.

I didn't try to commit via git. I don't have an appropriate development setup to do that easily yet. I hope to set things up better when I have a chance. But not this week - I have a tough deadline to meet on another project by Friday and I really can't get involved in anything else. Sorry about that.
 
My suggestion to you in the PR (#1473) was for you to please do it yourself, if you don't mind - my fix is just a one-line change. And I believe horus68 was suggesting the same for his PR. Do you think that could be a viable option to get things "unstuck"?

**Comment by samus-aran** [comment] 2016-07-04 16:04
I've updated my comment in regards to how non-admin users set an issue/pr to a different label - just to simply ask. :+1: 

Regards to these two PRs I'll have a look at them as soon as I can.

**Closed by samus-aran** 2016-07-04 16:04 UTC
Labels: Fix Proposed

**Comment by horus68** [comment] 2016-07-05 08:18
@samus-aran don't take it personally our ramblings. We know there PR and issues take time to solve. But there is a need to streamline the process on an open source project or people simple  solve their problems and do not upload here their solutions.
Things that can be done to please code contributes: 
- Any PR needs to be tagged in a week (people need to know that someone has seen it). 
- The more complex ones needs to be assigned to be tested and merged
- Some should be considered "release stoppers" (no new release until they get merged... as they solve a "functionality not working")
- You can't have PR without reply more then 2 weeks, or else it will get code conflicts when merging 

Note: I know not all code contribution will be accepted by main devs of any app but devs need to reply and say "no thanks, that's not the direction we want to go". 

**Solving issues** is more difficult as some are not confirmed in different environments or require more infos. But there should be a procedure involving their acknowledge and solving. 

- Users should be able to see what is going on from your side (x number by week done, "what are the issues we are going to solve next", "issues under working this week").
- You should also have a way for other users say "I have this problem too" and when more then X users have the same problem it will be tagged as "release stoppers". People will focus on solving this ones first.

_As I read all PR and most of the issues (and I have other projects where I'm involved) I don't see this impossible to do by a small team of professionals)_

**Comment by samus-aran** [comment] 2016-07-05 08:34
@horus68 I completely agree we need a more outward facing process that contributors can see and your suggestions we will definitely look to see if they are achievable (whether now or in the future).  As we all know that putting in processes do have teething problems and don't happen overnight but I hope you (and all the contributors) can see we are introducing new things to help with the project's maintenance (new issue/PR templates) and _slowly_ working through the oldest PRs.  :star:
