### ISSUE TITLE
PDF font too small when report contains many columns 

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM#1692] opened 2016-07-04 13:02 UTC
When the report contains many columns the font size is not readable/usable.

Possible solution could be to add print to Landscape format option.

**Comment by samus-aran** [comment] 2017-04-01 15:17
This is a duplicate of https://github.com/salesagility/SuiteCRM/issues/628 so closing this.

**Closed by samus-aran** 2017-04-01 15:17 UTC
Labels: suggestion
