### ISSUE TITLE
Inline editing of address buggy

### ISSUE THREAD

**Issue by vic-t** [salesagility/SuiteCRM#450] opened 2015-09-07 15:15 UTC
Inline editing of the address only works for the actual "address" field. It is not possible to edit the city, post code, or country this way. 

Furthermore, when inline editing the "address" field, the other fields related to the address dissapear until the page is refreshed.  

SuiteCRM 7.3.1. Tried on Chrome and Firefox on Windows.

**Comment by darthtang** [comment] 2015-09-25 10:51
the problem is that when the double click is made. the billing address street is only called from the bean.
if you wanted to get all of the fields for the address and display it in the inlineEdit you can. However, once you have made your changes and save. the whole string will be saved back into the "billing_address_street" of the bean.

So just need to figure out to display the values separately and make sure the system knows the differences of fields when it saves the changes.

**Comment by darthtang** [comment] 2015-09-25 11:13
http://jsbin.com/otedi5/156/edit?html,js,output

something like this might help

**Comment by darthtang** [comment] 2015-09-25 13:04
#366

**Comment by jobvector** [comment] 2016-02-22 15:23
Tested with a clean 7.5.1 install: 
Exactly the same problem.

**Comment by Mausino** [comment] 2017-11-21 17:04
@samus-aran @Dillon-Brown i saw that issue was merged, but i tested it in SuiteCRM 7.10 beta for account module and if i'm inline editing the address the issue is still persisting 

![2017-11-21_1803](https://user-images.githubusercontent.com/5773777/33085881-5353ae66-cee6-11e7-8c8b-d6acd7647c70.png)

**Comment by Dillon-Brown** [comment] 2017-11-22 09:32
@Mausino The PR for #2203 fixes a different issue than the one you're experiencing. I think the proper fix is #3106 but we'll need to investigate if it's still an appropriate fix before we can merge.

**Comment by cameronblaikie** [comment] 2019-06-13 09:39
Closed due to inactivity, if you feel this should be reopened then do so and we will review your issue again.

**Closed by cameronblaikie** 2019-06-13 09:39 UTC
Labels: Fix Proposed, Medium Priority, bug
