### ISSUE TITLE
From Email Field Is Not Populated

### ISSUE THREAD

**Issue by ankitjha** [salesagility/SuiteCRM#3835] opened 2017-07-05 13:02 UTC
#### Steps to Reproduce

1. Log in as an admin/user
2. Click on Emails
3. Compose Email

#### Context
 Trying to send emails to clients from the CRM
 high

#### Your Environment

* SuiteCRM Version used: 7.9.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome (64-bit) 
* Environment name and version (e.g. MySQL, PHP 7): MYSQL 5.7, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by Dillon-Brown** [comment] 2017-07-05 13:09
Duplicate of #3741

**Closed** 2017-07-05 13:09 UTC
Labels: duplicate
