### ISSUE TITLE
Double Attachment in Email

### ISSUE THREAD

**Issue by uvainternational** [salesagility/SuiteCRM#4156] opened 2017-08-24 13:56 UTC
#### Issue

When attach an attachment in an email, the recipient will receive 2 similar attachments.
#### Expected Behavior

Just attach an attachment, when receive it will be 2 similar attachments.
#### Steps to Reproduce

1. Compose an email
2. Attach attachment
3. When receive, you will see double number of attachments received
4.

#### Your Environment

* SuiteCRM Version used: 7.9.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 60.0.3112.101 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7)
* Operating System and version (e.g Ubuntu 16.04): Linux

**Comment by Dillon-Brown** [comment] 2017-08-24 14:21
@uvainternational Duplicate of #3818

**Closed** 2017-08-24 14:22 UTC
Labels: duplicate
