### ISSUE TITLE
Next button broken on Accounts page after using Column Chooser

### ISSUE THREAD

**Issue by GanimanSwift** [salesagility/SuiteCRM#6621] opened 2018-12-14 17:35 UTC
#### Issue
When limiting the columns viewed on the Accounts page in Column Chooser, clicking the "Next" arrow does not load the next 20 accounts. 

#### Expected Behavior
I should see accounts 21-40.

#### Actual Behavior
The page reloads, but shows the same 1-20 accounts and not 21-40.

#### Steps to Reproduce

1. Go to the accounts page
2. Click the "Column Chooser"
3. Limit the columns to show only 6 columns
4. Save Changes
5. Click the "Next" arrow
6. Notice you are still viewing accounts 1-20 and not 21-40

#### Context

This hurts our billing process and makes it difficult for our accounts receivable people to find overdue customers.

#### Your Environment

* SuiteCRM Version used: 7.10.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All browsers are affected
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by pgorod** [comment] 2018-12-17 10:23
I believe this is a duplicate of #6298

**Closed** 2018-12-18 08:30 UTC
Labels: High Priority, bug, duplicate
