### ISSUE TITLE
Opt-In "ticks" for email addresses not showing on list or detail view

### ISSUE THREAD

**Issue by gremlinuk** [salesagility/SuiteCRM#5859] opened 2018-05-11 11:16 UTC
#### Issue
The documentation at https://docs.suitecrm.com/user/modules/confirmed-opt-in-settings/ shows the "opt-in" status of an email address show be indicated by a single or double tick.  The ticks don't appear so there is no easy way to check if a contact has been confirmed opted in..

#### Expected Behavior
When a contact has opted in a single or double tick should show alongside their email address as shown here https://docs.suitecrm.com/user/modules/confirmed-opt-in-settings/

#### Actual Behavior
No ticks are displayed. Just the email address.

#### Steps to Reproduce
Click on contacts list or contact detail. 

#### Context
We need to know the status of a contact for GDPR purposes. The only way we can check currently is by creating a saved filter to list those confirmed opted in.

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version: Chrome Version 67.0.3396.40 (Official Build) beta (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.0.28
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.1

**Comment by pgorod** [comment] 2018-05-12 14:08
Did you turn on Opt-in in your settings?

> To configure your Opt In settings, open the Admin panel and select Email Settings. Opt In settings can be found on the Email Options panel.

**Comment by gremlinuk** [comment] 2018-05-12 17:31
Yes. The setting is on and the feature works including the consent emails going out (and the database table gets updated correctly). It's just the status indicator doesn't appear when looking at contacts either as a list or in detail.  

The documentation states this should be indicated by a single or double tick next to the email address. This is absent.

**Comment by poynter2** [comment] 2018-05-15 09:43
Seems that regular users on our system can see the ticks, but I'm an admin and cant...

**Comment by pgorod** [comment] 2018-05-18 18:34
@actXc this is not common, no. But I guess we need to wait for the fix to be done in order to understand if the problem can have more manifestations in other areas of the app.

**Comment by poynter2** [comment] 2018-05-22 13:39
Also tried to run a report after confirmed opt in emails were sent, all users just see lots of grey lines with only one or two "date sent" fields populated.

**Comment by gremlinuk** [comment] 2018-05-24 10:17
This issue still happens in 7.10.5 - any chance of a fix soon? GDPR goes live tomorrow and it's vital we know who is and isn't opted in with accuracy.

**Comment by gremlinuk** [comment] 2018-06-13 11:31
Thanks @mbennoer - just tried this and can confirm it works.

**Comment by lazka** [comment] 2018-11-12 13:21
This might be the same as #6485 for which I've opened a PR #6486

**Comment by Mausino** [comment] 2019-01-04 13:59
@gremlinuk @poynter2 @mbennoer @actXc as @lazka wrote in ticket.. he found that his issue is related to type of email client which is using SuiteCRM

Did you set up external email account in your user settings or internal suitecrm ?

![2019-01-04_1456](https://user-images.githubusercontent.com/5773777/50691505-38915000-1031-11e9-8e3c-790d12f5a963.png)

**Comment by Dillon-Brown** [comment] 2019-01-04 16:00
This should be a duplicate of #6485 which is now marked as resolved next release.

**Closed by Dillon-Brown** 2019-01-04 16:00 UTC
Labels: Emails
