### ISSUE TITLE
MyActivityStream - Edit Button Shows Error

### ISSUE THREAD

**Issue by mikebeck** [salesagility/SuiteCRM#1760] opened 2016-07-18 14:59 UTC
#### Issue

Fresh install of SuiteCRM (tested with 7.5.4 / 7.6.5 / 7.7beta2) when clicking on the pencil (edit) on MyActivityStream the popup window shows nothing and php throws this error

> [Mon Jul 18 10:42:03.260335 2016] [:error] [pid 3854] [client 192.168.120.109:54760]
> PHP Warning:  Smarty error: unable to read resource: &quot;odules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl&quot;
> in /var/www/html/include/Smarty/Smarty.class.php on line 1094, referer: http://192.168.180.215/index.php?module=Home&action=index

#### Expected Behavior

the windows should let you edit some field of that activity stream

#### Actual Behavior

shows nothing

#### Possible Fix

I'll post a pull request

#### Steps to Reproduce

1.Fresh install
2.Click on edit button in MyActivtySteam
3.Window appears but shows nothing

#### Your Environment

* SuiteCRM Version used: 7.5.4/7.6.5/7.7beta2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 51.0.2704.103 m (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5.49, PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): 14.04

**Comment by samus-aran** [comment] 2016-07-18 15:10
Hey @mikebeck We are currently developing on the develop branch for the suitep theme ( which I suspect is what the issue is as we are now making the templates specific to the theme selected).  We haven't reached as far as the homepage and dashlets so I would suggest holding on on making the PR (unless our RC doesn't resolve it).

As we are working on the development branch the usual PR will not be to hotfix but rather you should branch off from the develop branch :)

See our How to Contribution guide on the Wiki for how to aid the beta/release candidate branches. https://github.com/salesagility/SuiteCRM/wiki

**Comment by mikebeck** [comment] 2016-07-19 19:45
I don't understand what you mean about PR? help me you make this fix merge to SuiteCRM

**Comment by ijdavie** [comment] 2016-09-20 07:16
This appears to be #2225 & #2230, which has been merged in. I will close this case now.

**Closed by ijdavie** 2016-09-20 07:16 UTC
Labels: bug
