### ISSUE TITLE
Export report to CSV dont export Total

### ISSUE THREAD

**Issue by holdusback** [salesagility/SuiteCRM#6821] opened 2019-01-24 08:52 UTC
Im trying to customise the report to make a Grand Total at the end of the report.

While trying to do this I've encounters a "bug" :
If you make a Total of a field, it will not be exported in the CSV.

(https://image.noelshack.com/fichiers/2019/04/3/1548235062-exportsuitepb.png)

The total fields circled in green are not exported to CSV.

#### Issue
Total not exported in the CSV.

#### Expected Behavior
A Total fields in the CSV.

#### Actual Behavior
The Total fields is displayed when I export a PDF file, but not in the CSV.

#### Possible Fix
A fix in the AOR_Report.php, Im actually trying to override it in /SuiteCRM/custom/modules/AOR_Reports/AOR_Report.php but its not working.

#### Steps to Reproduce
1. Make a report
2. Add fields
3. Make a Total of a fields (Total in the dropdown)
4. Export to CSV.

#### Context
Im trying to customise the report to make a Grand Total at the end of the report.

#### Your Environment
* SuiteCRM Version used: Version 7.11.0 Sugar Version 6.5.25 (version de construction 344)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Last Chrome Version
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.2 
* Operating System and version (e.g Ubuntu 16.04): Hosted by 1&1, I think its a Linux server.

**Comment by cameronblaikie** [comment] 2019-01-24 11:54
Duplicate of #441

**Closed by cameronblaikie** 2019-01-24 11:54 UTC
