### ISSUE TITLE
SQL errors with sql_mode=STRICT_TRANS_TABLES

### ISSUE THREAD

**Issue by lazka** [salesagility/SuiteCRM#7107] opened 2019-03-26 14:05 UTC
#### Issue

The test suite fails with the default mysql modes which includes STRICT_TRANS_TABLES.
I don't know what this would affect in the real app.

#### Expected Behavior

Things work with the the default DB config.

#### Actual Behavior

The InbountEmailTests fail with

```
Tue Mar 26 13:50:59 2019 [10049][-none-][FATAL] Mysqli_query failed.
Tue Mar 26 13:50:59 2019 [10049][-none-][FATAL] INSERT INTO email_cache (ie_id,mbox,subject,fromaddr,toaddr,senddate,message_id,mailsize,imap_uid,msgno,recent,flagged,answered,deleted,seen,draft) VALUES ('1', 'INBOX', 'subject', 'from', 'to', '2019-03-26 13:50:59', '1', 0, '', '', '', '', '', '', '', '') Query Failed: INSERT INTO email_cache (ie_id,mbox,subject,fromaddr,toaddr,senddate,message_id,mailsize,imap_uid,msgno,recent,flagged,answered,deleted,seen,draft) VALUES ('1', 'INBOX', 'subject', 'from', 'to', '2019-03-26 13:50:59', '1', 0, '', '', '', '', '', '', '', ''): MySQL error 1366: Incorrect integer value: '' for column `automated_tests`.`email_cache`.`imap_uid` at row 1
```

#### Possible Fix

Maybe SuiteCRM should call `SET sql_mode=(SELECT REPLACE(@@sql_mode, 'STRICT_TRANS_TABLES', ''));` in connect() if that's not supported ?

SutieCRM could try testing with a newer mysql using the travis-ci xenial image instead of the trusty one.

#### Your Environment
* SuiteCRM Version used: php 7.2 and php 7.3
* Environment name and version (e.g. MySQL, PHP 7): mariadb 5.5 and mariadb 10.3

**Comment by lazka** [comment] 2019-03-27 14:14
I've worked it arround using this for now:

```patch
diff --git a/include/database/MysqliManager.php b/include/database/MysqliManager.php
index 14b6d7296..a75a09775 100755
--- a/include/database/MysqliManager.php
+++ b/include/database/MysqliManager.php
@@ -356,6 +356,9 @@ class MysqliManager extends MysqlManager
         }
         mysqli_set_charset($this->database, "utf8");
 
+        // https://github.com/salesagility/SuiteCRM/issues/7107
+        mysqli_query($this->database, "SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode, 'STRICT_TRANS_TABLES', ''))");
+
         if ($this->checkError('Could Not Connect', $dieOnError)) {
             $GLOBALS['log']->info("connected to db");
         }
```

**Comment by lazka** [comment] 2019-03-28 09:35
I've created #7124 which should make it easier to test any fix for this and to prevent similar issues in the future.

**Comment by lazka** [comment] 2019-05-25 10:13
I think the "Resolved: Next Release" label should be removed, because there exists no fix as far as I'm aware.

**Comment by Dillon-Brown** [comment] 2019-05-29 14:42
@lazka Done, thanks!.

**Comment by mphilipps** [comment] 2019-06-05 11:40
hi,
I just came here from the 7.10.17 release page, according to that page this is fixed. 
However here the issue is still open and the last commit includes 'It shouldn't be merged'.

On the topic of this issue, I hope you will fix the query. Implicitly converting '' to 0 feels like an ugly hack and mysql should be ashamed for supporting it in the first place.

**Comment by Dillon-Brown** [comment] 2019-06-05 11:48
@mphilipps It probably got linked into the release notes due to having a related merged PR. I'll highlight this to be removed from the release page. Thanks!

**Closed** 2019-07-01 12:51 UTC
Labels: Databases, Medium Priority, Resolved: Next Release, bug
