### ISSUE TITLE
Logo not uploading 

### ISSUE THREAD

**Issue by MyBlissIT** [salesagility/SuiteCRM#7424] opened 2019-06-19 07:19 UTC
Hi, I am interested in using SuiteCRM from YetiForce.

I am, however, not able to upload my company logo. I keep getting an error message that i must change picture format to PNG or JPEG.

My company logo is in both these formats, I even recreated the logo but I still get the same error message. Please assist.

**Comment by Mac-Rae** [comment] 2019-06-19 10:29
Hi MyBlissIT,

Could you please confirm what version of SuiteCRM you are running,
along with what PHP version and web stack you are using (I.e Apache, Nginx, etc, etc)

Thanks,
Mac

**Comment by pgorod** [comment] 2019-06-19 11:15
It's probably a permissions or file format issue, but if it's not, then it's a duplicate of #2464

**Comment by MyBlissIT** [comment] 2019-06-20 11:31
> Hi MyBlissIT,
> 
> Could you please confirm what version of SuiteCRM you are running,
> along with what PHP version and web stack you are using (I.e Apache, Nginx, etc, etc)
> 
> Thanks,
> Mac

Hi, I am running SuiteCRM Version 7.10.17 - PHP 7.3 - Web Stack = Apache

**Comment by Dillon-Brown** [comment] 2019-07-18 15:56
Closing this as a duplicate of #2464. Let me know if you still run into this issue when uploading an image without any spaces in the filename and I can re-open.

**Closed by Dillon-Brown** 2019-07-18 15:56 UTC
Labels: Duplicate
