### ISSUE TITLE
My Calendar dashlet on home page missing left/right scroll buttons

### ISSUE THREAD

**Issue by jzuberek** [salesagility/SuiteCRM#4175] opened 2017-08-29 08:10 UTC
#### Issue

After upgrading to SuiteCRM 7.9.4 calendar dashlet stopped displaying the '<' '>' buttons to scroll view one week forward/backward. It's the same on demo version (demo.suiteondemand.com) 
#### Expected Behavior

When I place a calendar dashlet on home page tabs therethere should be left/right scroll buttons. They are present and working fine when we open calendar as a separate page.
#### Actual Behavior

Calendar does not have '<' '>' buttons

#### Your Environment

* SuiteCRM Version used: 7.9.4 
* Firefox 55.0.3. 32-bit  or Chrome 60.0.3112.113  (64-bit)
* MariaDB 10.2.6. , PHP 7.1.8
* CentOS Linux release 7.3.1611 (Core)

**Comment by Dillon-Brown** [comment] 2017-08-29 10:35
@jzuberek Duplicate of #2783

**Closed by Dillon-Brown** 2017-08-29 10:35 UTC
Labels: duplicate
