### ISSUE TITLE
Issue Suite P Invoices Screen

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2433] opened 2016-10-17 21:06 UTC
Hi, when you goes to create any document (quote, invoice), details sections not works fine.

i've added screencapture.

![captura](https://cloud.githubusercontent.com/assets/20840700/19455653/24d6402a-94be-11e6-9711-00fb7eb39ba5.PNG)
#### Your Environment

- SuiteCRM Version used: 7.7.5
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Any
- Environment name and version (e.g. MySQL, PHP 7): MSSQL , PHP7
- Operating System and version (e.g Ubuntu 16.04): WINDOWS SERVER IIS

**Comment by shogunpol** [comment] 2016-10-18 10:52
@GrupImatica , im not able to replicate the bug because simple i do not know what an issue is, can you write what an issue is, and step to reproduce. If you did any customisation of module can you write what exactly changes you did?
Thanks for your contribution.

**Comment by GrupImatica** [comment] 2016-10-24 16:23
Hi, problem is resolution, please make more small you screen or your windows, and see that the fields are not displayed properly.

**Comment by Mac-Rae** [comment] 2019-08-02 14:04
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. We have also been unable to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x however if you are able, please leave a comment explaining how and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Closed by Mac-Rae** 2019-08-02 14:04 UTC
Labels: Medium Priority, bug
