### ISSUE TITLE
report assigned to user 

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#1247] opened 2016-04-19 10:52 UTC
To Clarify,

The 'assigned to' field in the picture below comes from Leads. This report will produce a report Per user, (As the main group). For each user, the report will show the number of leads at different status.

![image](https://cloud.githubusercontent.com/assets/6104874/14669468/eadb6140-06e0-11e6-80b3-ed0d047a3b60.png)

![image](https://cloud.githubusercontent.com/assets/6104874/14669494/06d27050-06e1-11e6-90e2-cb3381fd84f5.png).

![image](https://cloud.githubusercontent.com/assets/6104874/14669551/57272a46-06e1-11e6-8c4a-5c1235ac71b9.png) -- using the "assigned to" field from the Leads. 

-----------------------------

This issue occurs if instead of using the "Assigned To" field from the Lead, you use the "assigned to" user field from the 'Users: Assigned To User' section from the module tree and select 'User' from the module tree and then select "User Name" from the 'Fields (Users)'

![image](https://cloud.githubusercontent.com/assets/6104874/14669641/9e8ca0fa-06e1-11e6-8499-b8a8a3a3ea3c.png)

![image](https://cloud.githubusercontent.com/assets/6104874/14669652/aa889562-06e1-11e6-94a0-a9fa08769fcb.png)

Using this alternative field will cause SuiteCRM to blank screen. Then if you try to revisit the report, it will display error.

**Comment by samus-aran** [comment] 2016-05-04 10:38
I would of though that it would be Leads > User > Assigned To.... So that would create a query to list the Assigned User of a User whom is related to the Lead?

Agreed it shouldn't should a blank screen.  What error does it display?

**Comment by willrennie** [comment] 2016-07-06 21:37
@darthtang please can you provide the information @samus-aran has requested?

**Comment by shogunpol** [comment] 2016-09-16 14:51
The issue has been tested on the recent version of SuiteCRM(7.7.4), and it not appear,
@darthtang  , can you confirm the issue is not exist any more? 
If yes can you close an issue?

**Comment by ijdavie** [comment] 2016-09-21 07:35
Due to no activity to this issue, we will close this if more information is given and the issue still exists this can be reopened to be resolved. 
Thanks

**Closed by ijdavie** 2016-09-21 07:35 UTC
Labels: bug, Pending Input
