### ISSUE TITLE
WorkFlow detail view does not display value field from condition.

### ISSUE THREAD

**Issue by shogunpol** [salesagility/SuiteCRM#2585] opened 2016-11-08 12:18 UTC
WorkFlow detail view does not display value field from condition.

#### Issue

When i create WorkFlow for opportunities, and set up conditions, the value field doesnt display anything.
#### Expected Behavior

When i save condition with "value" field, i will be able see it in Detail View.
#### Actual Behavior

When i save condition with "value" field, the set number in "value" field doesnt appear.
#### Steps to Reproduce

1. Create WorkFlow for opportunities
2. Set condition for:
module: opportunities
Field: ammount
Operator: Greater or equal to
Type: value
Value: 10000
3. Hit Save button
4. In edit view number: 10000 for "value" field not appear.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):Version 53.0.2785.143 Built on Ubuntu 
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):Ubuntu 14.04 (64-bit)

**Comment by salesagility-davidthomson** [comment] 2018-05-18 08:47
This seems to be specifically a currency issue. When you create the condition and choose a currency field type there is no way to choose the currency symbol. On Detail view when value is loaded the application looks for the currency type before it displays then fails as no currency type is saved with the value.

**Comment by Mac-Rae** [comment] 2019-08-02 15:22
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. 
This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. 
If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.
For more information about 7.8.x end of life please visit our [blog post ](https://suitecrm.com/7-8-x-end-of-life/)

**Closed by Mac-Rae** 2019-08-02 15:22 UTC
Labels: Low Priority, bug
