### ISSUE TITLE
"My Calendar" dashlet is not displaying any activities in Suite7.

### ISSUE THREAD

**Issue by tjaafar** [salesagility/SuiteCRM#2621] opened 2016-11-12 11:23 UTC
#### Issue
On default tab in dashboard, I added a "My Calendar" dashlet.
The calendar view and events/activites appeared well in SuiteP theme (which is great),
But in Suite7 all the dashlet title appear, no calendar view at all, and of course nothing appears in dashlet (this is the error).
I believe this error was happening even since v7.7.6 (I'm not sure if earlier).

See screenshot here:
![ss-01](https://cloud.githubusercontent.com/assets/7531735/20237439/eeffbb1a-a8eb-11e6-8f39-3eebb4380e4f.png)

#### Expected Behavior
The "My Calendar" dashlet should appear a proper calendar view in Suite7.

#### Actual Behavior
The "My Calendar" dashlet didn't appear in "My Calendar" dashlet at all in Suite7.

#### Possible Fix
Don't know

#### Steps to Reproduce
1. Set your theme to "Suite7"
2. On Home, in the default "SuiteCRM Dashboard" tab, add a "My Calendar" dashlet.  The calendar view doesn't appear in dashlet.
3. Change your theme to "SuiteP"
4. Refresh your Home page.  The calendar view appears.

#### Context
Viewing my calendar in my dashboard
medium

#### Your Environment
* SuiteCRM Version used: 7.7.7 (upgraded from 7.7.6)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Version 54.0.2840.71 m
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.19, MySQL  5.0.11
* Operating System and version (e.g Ubuntu 16.04): Windows 8.1 (64-bit)

**Comment by tjaafar** [comment] 2016-11-12 11:25
This is appears in the console log:

Cal.js:153:   Uncaught ReferenceError: calendar_items is not defined(…)
lang-all.js:1   Uncaught TypeError: a.fullCalendar.datepickerLang is not a function(…)

**Comment by tjaafar** [comment] 2016-11-12 12:16
This seems to be related somehow to issue #2466 and #2688... However, in my case it is happening only for "My Calendar" dashlet.  The module is displaying calendar correctly.

**Comment by shogunpol** [comment] 2016-11-15 10:57
(tag and Close issue)

Response - Thank you for highlighting this issue, however, this is a duplicate of issue #2466. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2016-11-15 10:57 UTC
