### ISSUE TITLE
Links in report not working

### ISSUE THREAD

**Issue by HeiHyd** [salesagility/SuiteCRM#1575] opened 2016-06-08 16:01 UTC
![bildschirmfoto 2016-06-08 um 17 59 57](https://cloud.githubusercontent.com/assets/5616374/15901263/da591fc2-2da2-11e6-8c88-1af94f4603bb.png)

missing ID in Detail Link:
![bildschirmfoto 2016-06-08 um 18 01 04](https://cloud.githubusercontent.com/assets/5616374/15901293/0423cf14-2da3-11e6-89e5-62a5365d86ca.png)

**Comment by mattlorimer** [comment] 2016-06-08 16:04
duplicate of #1558

**Closed by mattlorimer** 2016-06-08 16:04 UTC
Labels: duplicate
