### ISSUE TITLE
Reminders for meetings and calls (pop up and e-mail) are sent at the wrong time

### ISSUE THREAD

**Issue by lakomaa** [salesagility/SuiteCRM#822] opened 2015-12-29 12:18 UTC
Probably there is a problem with the timezone, e.g. timezone: Europe/Warsaw (GMT+1), meeting is planned for 10:00, e-mail reminder is set 15 min before meeting (9:45) but it came at 10:45 which is an hour too late.

**Comment by KhyberPass** [comment] 2016-02-15 06:03
This is a duplicate of #766. Reminders only work correctly when the users time zone is UTC.

**Closed** 2016-03-16 12:39 UTC
Labels: Resolved: Next Release
