### ISSUE TITLE
Embedded images in email templates are sent as attachments

### ISSUE THREAD

**Issue by mrndig** [salesagility/SuiteCRM#1521] opened 2016-05-31 14:34 UTC
Hi all. I'm running SuiteCRM 7.6.4. When you try to send an email from a saved email template and it includes an image, this image is not sent inline but as an attachment. These are the steps to reproduce:
## 1) Create an email template:

![suitecrm1](https://cloud.githubusercontent.com/assets/19667899/15676956/8ec9c256-2748-11e6-92f1-3230a3b6f26b.jpg)
## 2) Upload an image:

![suitecrm2](https://cloud.githubusercontent.com/assets/19667899/15676598/23eac774-2747-11e6-82d2-39efe7919168.jpg)

The image's URL is: index.php?entryPoint=download&type=Notes&id=1440fcd2-d94b-0e07-1b33-574d8f6a6536&filename=Koala.jpg
## 3) Now compose a new email, using this template, and send it:

![suitecrm3](https://cloud.githubusercontent.com/assets/19667899/15676704/a52d9938-2747-11e6-85a0-260fd4f6a99c.jpg)
## 4) The image is sent as an attachment, but not inline

![suitecrm4](https://cloud.githubusercontent.com/assets/19667899/15676766/d927dd66-2747-11e6-8245-134b12944e9f.jpg)

The image is sent as an attachment, but not inline. Where the image should be, you can see the alt text (sample.jpg by default).

This is the HTML version of the email:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">=0A<html>=0A<head>=0A</head>=
=0A<body>=0A<div class=3D"mozaik-inner" style=3D"font-family: Arial, Helvet=
ica, sans-serif; font-size: 14px; line-height: 22.4px; color: #444444; padd=
ing: 0px 30px; margin: 0px;">=0A<p style=3D"font-family: Arial, Helvetica, =
sans-serif; font-size: 14px; line-height: 22.4px; color: #444444; padding: =
0px; margin: 0px;">&nbsp;</p>=0A<h1 style=3D"font-family: Arial, Helvetica,=
 sans-serif; font-size: 24px; line-height: 38.4px; color: #444444; padding:=
 0px; margin: 0px;">Add your headline here..</h1>=0A<div class=3D"mozaik-cl=
ear" style=3D"font-family: Arial, Helvetica, sans-serif; font-size: 14px; l=
ine-height: 22.4px; color: #444444; padding: 0px; margin: 0px; height: 0px;=
">&nbsp;</div>=0A</div>=0A<div class=3D"mozaik-inner" style=3D"font-family:=
 Arial, Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; color:=
 #444444; padding: 0px 30px; margin: 0px;">=0A<table class=3D"mce-item-tabl=
e" style=3D"width: 100%; font-family: Arial, Helvetica, sans-serif; font-si=
ze: 14px; line-height: 22.4px; color: #444444; padding: 0px; margin: 0px;">=
=0A<tbody style=3D"font-family: Arial, Helvetica, sans-serif; font-size: 14=
px; line-height: 22.4px; color: #444444; padding: 0px; margin: 0px;">=0A<tr=
 style=3D"font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-=
height: 22.4px; color: #444444; padding: 0px; margin: 0px;">=0A<td style=3D=
"font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 2=
2.4px; color: #444444; padding: 3px 3px 3px 0px; margin: 0px;"><img style=
=3D"font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height=
: 22.4px; color: #444444; padding: 0px; margin: 0px;" src=3D"cid:1440fcd2-d=
94b-0e07-1b33-574d8f6a6536&filename=3DKoala.jpg" alt=3D"sample.jpg" width=
=3D"130" /></td>=0A<td style=3D"font-family: Arial, Helvetica, sans-serif; =
font-size: 14px; line-height: 22.4px; color: #444444; padding: 3px 3px 3px =
0px; margin: 0px;">=0A<h2 style=3D"font-family: Arial, Helvetica, sans-seri=
f; font-size: 18px; line-height: 28.8px; color: #444444; padding: 0px; marg=
in: 0px;">Title</h2>=0ALorem ipsum dolor sit amet, consectetur adipiscing e=
lit. Etiam tempus odio ante, in feugiat ex pretium eu. In pharetra tincidun=
t urna et malesuada. Etiam aliquet auctor justo eu placerat. In nec sollici=
tudin enim. Nulla facilisi. In viverra velit turpis, et lobortis nunc eleif=
end id. Curabitur semper tincidunt vulputate. Nullam fermentum pellentesque=
 ullamcorper.</td>=0A</tr>=0A</tbody>=0A</table>=0A<p style=3D"font-family:=
 Arial, Helvetica, sans-serif; font-size: 14px; line-height: 22.4px; color:=
 #444444; padding: 0px; margin: 0px;">&nbsp;</p>=0A<div class=3D"mozaik-cle=
ar" style=3D"font-family: Arial, Helvetica, sans-serif; font-size: 14px; li=
ne-height: 22.4px; color: #444444; padding: 0px; margin: 0px; height: 0px;"=
>&nbsp;</div>=0A</div>=0A</body>=0A</html>
```

Any help with this issue is appreciated. Thank you.

**Comment by samus-aran** [comment] 2016-06-01 09:50
@mrndig Is this via the standard Create Email Template and not via the Campaign Wizard?

**Comment by samus-aran** [comment] 2016-06-02 10:11
@mrndig Are you coping and pasting the URL into the uploading section of the Image properties?

![23eac774 2747 11e6 82d2 39efe7919168](https://cloud.githubusercontent.com/assets/4041275/15741668/9b6a56c2-28b2-11e6-8192-fe6c9dcff1d1.png)

If you reupload the image (from your machine directly) it should alter the URL and give you something like below:

http://domain.com/public/id.jpg (bchb-cbhcdbjhd-bcbdjh-.jpg).

The old entrypoints for images have now been removed due to mail clients using caching to deliver images so they need direct access to the files.

**Comment by mrndig** [comment] 2016-06-02 15:57
@samus-aran No, I don't copy/paste anything. This URL is automatically populated when I upload the image using the uploader in that "Insert/edit image" window.

![1](https://cloud.githubusercontent.com/assets/19667899/15750774/ff424094-28e7-11e6-8221-4a779ca5b7bf.jpg)

When the image is uploaded, the path to the image is populated like this: **cache/images/Koala.jpg**. Then click Ok and save the email template. After saving the template, the image's path changes into: **index.php?entryPoint=download&type=Notes&id=9383f8ee-2e54-3b89-d972-57500f1876cf&filename=Koala.jpg** as shown here:

![2](https://cloud.githubusercontent.com/assets/19667899/15750708/c2668400-28e7-11e6-946a-24d476bdba1f.jpg)

The image is correctly uploaded to folder /upload, but without extension.

![3](https://cloud.githubusercontent.com/assets/19667899/15751518/b0b36b58-28ea-11e6-9c90-21f77cd3983c.jpg)

**Comment by gymad** [comment] 2016-06-09 15:10
@mrndig I found similar issue in SuiteCRM 7.6.3 if I follow your instructions but I can't recreate it in 7.6.4 so please clear your browser cache make sure file system having appropriate write access and make a Quick Repair and Rebuild  and check again. -- did you upgrade SuiteCRM to version 7.6.4 or installed this version directly?

**Comment by mrndig** [comment] 2016-06-14 08:47
@gymad I installed version 7.6.3 and then upgraded to 7.6.4. I will check with a brand new 7.6.4 installation.

**Comment by mrndig** [comment] 2016-06-14 10:13
@gymad I just made a new installation with version 7.6.4 -no upgrade- and the issue is still there. Tested in two different computers with different OS and different email addresses to no avail.

**Comment by gymad** [comment] 2016-06-21 10:29
This issue seems to related to change for issue #1551 (PR was #1579) at commit a7b8dd0.
@mrndig Can you please check your sent email's images url from 7.6.4 in the email source? The entryPoint images remove from the SuiteCRM because the remotely email clients doesn't show any images without real image url for security reason so we use a /public folder for email images. you should see an url in your sent email source like this: http://domain.com/public/12345678-1234-1234-1234-123456789012.jpg

**Comment by adminibt** [comment] 2016-09-20 12:04
@ijdavie Is there any chance that this will be reolved soon? This stops us moving forward to 7.7.4 because we heavily use the email campaigns.

**Comment by pgorod** [comment] 2016-10-11 10:23
I don't know if this helps, but the PHP Mailer class we use has a method called `msgHTML` that handles similar issues (works with images to get them into the email in the correct manner). I believe (not 100% sure, though) that we don't even need to set up a public directory to send inline images, MIME email already has a way to do that, just put them as attachments and reference them in the correct way, and email clients will just show them inline without the user seeing any attachment.

However, we use the simpler, more direct, `body_html` method to load the html. 

I recently solved mailing problems in our notification emails (a different area of the code, a different way of templating) and one of the things I changed was precisely dropping `body_html` in favour of `msgHTML`, with resulting benefits in terms of how much HTML variety we can put into the emails (this is as yet unexplored, but could be improved in the future).

I'm not sure of the full consequences of switching to`msgHTML` here, but they might be worth exploring.

**Comment by pgorod** [comment] 2016-10-11 10:41
Just to confirm what I said above, here is the source of a simple email with an inline image (made with Thunderbird, simply pasting a gif into the email):

```
Return-Path: <obfuscated@gmail.com>
Received: from [10.0.0.128] (bl9-48-16.dsl.telepac.pt. [85.242.48.16])
        by smtp.googlemail.com with ESMTPSA id 198sm704413ljf.17.2016.10.11.03.30.09
        for <obfuscated@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 11 Oct 2016 03:30:10 -0700 (PDT)
To: "obfuscated" <obfuscated@gmail.com>
From: "obfuscated" <obfuscated@gmail.com>
Subject: Inline image
Message-ID: <b90dba17-bd2a-ac1f-5cea-9c56bec2dbdd@gmail.com>
Date: Tue, 11 Oct 2016 11:30:05 +0100
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101
 Thunderbird/45.3.0
MIME-Version: 1.0
Content-Type: multipart/related;
 boundary="------------C2C0F8F54B76D88C0157DC83"

This is a multi-part message in MIME format.
--------------C2C0F8F54B76D88C0157DC83
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    <p>Here it goes:</p>
    <p><img src="cid:part1.63CB202A.836025ED@gmail.com" alt=""></p>
    <p>Bye</p>
    <p>P.<br>
    </p>
  </body>
</html>

--------------C2C0F8F54B76D88C0157DC83
Content-Type: image/gif;
 name="mblcnjlenlnmibnp.gif"
Content-Transfer-Encoding: base64
Content-ID: <part1.63CB202A.836025ED@gmail.com>
Content-Disposition: inline;
 filename="mblcnjlenlnmibnp.gif"

R0lGODlhNgA2AOMAAMDAwAAAAJSUlM3Nzf7+/mNjY+fn5wAA/q2trVqMjIzN1nt7e0Jja0pK
SgAAAAAAACH5BAEAAAAALAAAAAA2ADYAAAT+EMhJq7046827/2AojlZgngGpTqcwEDCRruL5
xrhMf0Fx57nZbhMwGIBI3QplKhmTSSHPZjQMBE1J8QhFSom9X86KBQQGx8OhC/xWTgU2jNwz
rtk+nJtSFHeNV1tqBHdyMHtaT4SFQEdWCD52jEh5ehhbMGuTYwNXaIoEBXGGiAZFmWqbMYBY
nzCjSZUxe6ZPqjgDPgOQn6KGQRcDmDmisKsEu52gvr9ugcvGuLq8T8y/Sny1jsbWq1ZnaLDd
bF9nwzHj3p6uodeHFS5YTwbpY9+90c1v2r+OucrXZGHTIgxNjFR/dhWogtDdwDPyuGj6c89O
JjxipJgQpijVrTn+/xgSQqdPS5EzXEZ+JAAIpYFBofIhEVDG5DOJH0MWNPiK5BgBBVoIYJHg
JCgc6apQoyfuZw+aUIdqUWCO3SuZuVp+4mKMnokCC1x0GjtBAQOIw6zJBBTpiDVTosRuNZIF
QAIFRfkhRWJloUKrcMOOnYeCAl6qptjV4wSuSo8Cch3XrXC3aKdzV5NYCfmN5mADC04kyMDg
bgAX5xazVKoLslwEJhYwmF2aAYbSiF1CyRX0awFepxF0gh2AtvHSoy+ULhKxUa6nUOOeFiCc
+PHryJWDw8RFmAkEShEgoNljgSjY2LEHSG6BgQBtR7Bw781kgX3zxdPTPhGatAH5X6WwlN91
PYiHHnb0BXBffxmsA4oJ+p2FgnqxLWgfIhK4AMhzECZQm4cgRsifhQtiSAEDCqRYWXEhtvjh
chWSeN9vtnWAYmV4sfhiiyPKaN9v4oVw42GmuVhUjD6aFyQJs+FYJIwBGCilhUAiMARuOJ4g
5ZbiCaCklUNMgOVhDXBpoJcLGRFmeziWySWaVaxJ2l0KuHmmeWrKuQFubsKZp54coLiAeHEC
CgID98Vm6KIgRAAAIf4VTmljb2xhcy5QaW9jaEBlbnN0LmZyADs=
--------------C2C0F8F54B76D88C0157DC83--
```

Notice that `img src="cid:part1.63CB202A.836025ED@gmail.com"` that references the `Content-ID` in the following MIME-part. That's what PHP Mailer takes care of in the method `msgHTML`.

There are a few things to ponder if we switch to this:

1. Emails become heavier, the images are included
2. Emails are probably better to read when reopened on a mobile device while offline, because the email client doesn't have to fetch the image, it came with the email
3. There is the advantage of not having to worry about broken links when somebody opens the email after our local files have been deleted

Maybe we should provide both options, and users could choose which is more adequate (probably depending on how many KB worth of images they are sending). But if I had to choose only one, I would choose inline images, not links to a public directory.

**Comment by dursuntosun** [comment] 2016-10-27 14:18
Is there any solution for this? Difficult to send email😂

**Comment by chris001** [comment] 2016-10-27 17:29
@pgorod @gymad 
There is issue to be aware of when considering switching between `body_html` and `msgHTML` methods of adding image to email messages with `phpmailer`.   When you embed images in an email, so that the entire email message is self contained and doesn't need to go out to the network to retrieve images, then SuiteCRM server can lose the ability to track/detect when each user opens and reads the email.  Detecting how many people opened an email is required for sales and marketing campaign reports/statistics and for many other things such as being sure that an email campaign was not widely delivered to recipients spam boxes, which is obvious when a message remains 99% unopened after some time.
Anyway, the solution is to link or embed all images, except one special image. For that image, to use a virtual image URL, which is really aliased to a PHP file.  This PHP file, when requested, uses the request unique ID to lookup which user is requesting the image.  It inserts into the database the fact that the user has opened the email, then it returns to the user's browser the mime type of an image, plus the actual image data.
This is how mailchimp and other email campaign applications accurately measure the overall success rate of how many targets/leads/contacts are opening your email campaign messages in their inboxes.

**Comment by samus-aran** [comment] 2017-01-17 16:39
@mrndig @adminibt Is this still an issue for you guys?  I've tested it on 7.7.9 (hotfix branch) and following these steps:
1. Create an Email Template  via Email Module
2. Click on an area on the Body of the template to bring up the HTML Editor
3. Upload an image
4. Save
5. Send Email
6. See Email shows inline images

![emailtemplate1](https://cloud.githubusercontent.com/assets/4041275/22029763/6e31f41e-dcd3-11e6-96d6-6d2c9440ec66.png)
![emailtemplate4](https://cloud.githubusercontent.com/assets/4041275/22029759/6e21d96c-dcd3-11e6-9be5-a3b526053bb6.png)
![emailtemplate3](https://cloud.githubusercontent.com/assets/4041275/22029760/6e26dbce-dcd3-11e6-918f-d20955bc9e32.png)
![emailtemplate2](https://cloud.githubusercontent.com/assets/4041275/22029762/6e2aaf88-dcd3-11e6-96dc-8f932e9a7c6f.png)

**Comment by chris001** [comment] 2017-01-18 01:35
Embedding all images would surely kill the feature of the email marketing campaign reports, which depends on the small hidden tracker image, which tracks the when a target/contact has "opened the email". How the "email opened tracker" works is by remote image loading to a php script hosted on the crm server.  If all of the important image content is embedded in the email, except for the remote image "email opened tracker", the the target/contact usually will ignore the warning in their email app which says "Click here to see the remote images in this email" because every image is already embedded so they'll think, "why bother clicking one or two more clicks  to allow loading remote images on this email, since I can see every image I want to see already in this email (because they're embedded so no remote loading needed)."

> Taking a look at the 6.5.x Documentation for Campaign Responses ( http://support.sugarcrm.com/02_Documentation/01_Sugar_Editions/04_Sugar_Professional/Sugar_Professio... ) I found the following info:
>
>    Viewed Message : The list of targets who viewed the emails that were delivered. Sugar includes a very small, invisible image in each email. Each time the recipient downloads this image, Sugar records that they viewed the email.
>
>I tested real quick against a local 6.5.16 instance on a Linux VM (my Mac doesn't have the IMAP c-client libraries compiled for PHP), so I could only test against a Gmail account.  When I opened the email in Gmail, the subpanel didn't update.
>
>However, I have Thunderbird Mail hooked up to the same Gmail Account.  When I opened the message there, there was a warning to download remote content (the image mentioned above).  Until I clicked that button, the 'Viewed Message' subpanel remained blank.

**Comment by adminibt** [comment] 2017-01-18 12:43
@samus-aran Yes, this is still relevant for me. We use the Campaigns very heavily and we have customers who have email access but no internet access. In this case they will not see the images and the email looks very "ugly".

One fix was posted (https://github.com/gymad/SuiteCRM/commit/a16471d88a1eb1f2cd02ef20a2bf537f2cb2fb7e). This worked for me. Maybe you could introduce a configuration in "Admin/Campaign Email Settings" where you enable/disable image embedding. If it is enabled run the code from the fix.

Mentioning Campaigns: This is currently very buggy:
- After choosing a Campaign it is not possible to duplicate it. Still editing the original.
- How do I modify the start and end date? To my knowledge this is not possible.
- If I add another field via studio how do I modify this one? I can only use the "Wizard" which is not aware of the new field. Seems to me that the "Wizard" breaks some general behavior.

@chris001 The tracker image will not be replaced in case of a replacement. So this should not be a problem.

**Comment by chris001** [comment] 2017-01-18 17:41
> @chris001 The tracker image will not be replaced in case of a replacement. So this should not be a problem.
Look at it from the point of view of human behavior.  If the customer receives all content images embedded in the marketing campaign email message, then what is their incentive to click one or two additional times to allow loading the remote tracker image, a tiny single pixel  image which has no visual impact on the content of the message?  Answer, maybe the customer will try loading the remote tracker image one time, soon learn that there is no interesting image that gets loaded, and from that moment on, for all future emails from your company, 99.999% of the time, the customer won't bother wasting their time to click and allow remote loading of the tracker image.  So, the "email has been opened" tracker feature would be dead.

**Comment by pgorod** [comment] 2017-01-19 09:31
I think Chris is right, although what he says doesn't necessarily contradict other opinions stated here. Basically, for something so relevant, so impacting, so outward-facing as Campaigns, we need to have full control, we need to be able to tweak the details.

For some, tracking opened emails will be essential; for others, making sure images show up-front, without the need to click "show images", will be preferable.

**Comment by chris001** [comment] 2017-01-19 23:32
Marketing campaign email is a very touchy controversial topic since it's the legitimate one, closely related to its crooked cousin unsolicited commercial email spam/junk mail.  Look at google gmail handles campaign emails.  They load email images, css, and javascripts through a malware-scanning proxy, rewrite them and serve them up to the user's browser from googleusercontent.com , in effect this practice shields the user's IP address and therefore, location privacy, from the mail sender's servers.  For your customers on gmail, the first user to open the campaign email will probably trigger the "opened the email" remote loading image counter, but the rest of the gmail customers will load the images from google's cache and never hit your crm server.  Someone should test this to verify.
More details from other users who have experienced the same:
http://stackoverflow.com/questions/20903967/gmails-new-image-caching-is-breaking-image-links-in-newsletter

So @pgorod  and @adminibt make a reasonable suggestion, it'd be best to offer the option in the campaign wizard, to send campaign images embedded (larger emails yet images load correctly for customers without client internet access) or linked (better telemetry for customers with client internet access).  The global default could start as "linked" which is the original sugar behavior.

This feature - the remote image load as telemetry to count "this user has opened the email" - needs to be re-implemented to work in today's more security minded email environment.  There's a way to do it which will work.

**Comment by daniel-samson** [comment] 2017-03-06 17:13
Tested SuiteCRM 7.8.2 on Ubuntu 14.04 / PHP 5.6 / MySQL.  I can confirm that Image appears inline. However it still shows up as an attachment.

I have tested:
* Email Templates
* Emails
* Campaigns (Emails)

Also #3111 seems fix  the tiny mce issue / attachment issue.

**Comment by dspaan** [comment] 2017-03-13 23:00
> One fix was posted (gymad@a16471d). This worked for me. Maybe you could introduce a configuration in "Admin/Campaign Email Settings" where you enable/disable image embedding. If it is enabled run the code from the fix.

This did the trick for me too. If there is an insert image option in SuiteCRM it should simply work like this or otherwise it should be removed or you should not be allowed to upload your own image?

**Comment by pgorod** [comment] 2017-04-04 09:29
Just to ask for some clarification: does the Fix proposed allow choice of attaching/embedding for the user?

Because that was the gist of the long discussion up there: this needs to be an option because there are serious reasons on both sides...

**Comment by Dillon-Brown** [comment] 2018-01-05 10:46
Issue appears to be resolved in 7.8.x. However in 7.9.x and 7.10 I seem to be receiving none of the images that were included in my email template either as an attachment or embedded.

**Comment by actXc** [comment] 2018-02-04 18:11
my experiance with pictures in emails: 
it works for the first use and test - and when a mail in suiteCRM is copied, or resend, the img url is wrong and I have not enough experience to understand what is wrong. 
But pictures are rare in the emails I sent. Its seems to work by chance and not very often.

**Comment by e-reeley** [comment] 2018-02-05 14:52
Hi,

I have just tried to recreate this issue and it seems to work with no problems.

version: 7.9.11
Php: 7.1

When i create a template and use this template in an email, send it with an image embedded in the email.
Receive the email as expected, forward the email on.
Again receive the email as expected.

Hope this helps.

Thanks.

**Comment by pgorod** [comment] 2018-02-05 15:01
Even if the bug seems fixed, I just ask that this is not closed without looking at the discussion above: we should really provide both options (embed/don't embed images) because there is no one-size-fits-all and it's a delicate issue.

For some people, sending their images inline would kill their campaigns; for others, _not_ sending them inline will be seen as a terrible option because of the need to click "show images". Depends on your targets, on your message, on ISP's, we should leave that complex decision to our users.

**Comment by PedroErnst** [comment] 2018-02-05 16:29
On 7.8.11

The result for me was that the email was sent as an <img> tag linking to the image in the /public folder of the SuiteCRM server.

**Comment by Dillon-Brown** [comment] 2018-02-12 13:10
![](https://github.trello.services/images/mini-trello-icon.png) [Embedded images in email templates](https://trello.com/c/BnW777br/246-embedded-images-in-email-templates)

**Comment by Dillon-Brown** [comment] 2018-02-12 13:12
Unable to replicate original issue. I agree we shouldn't just close this without further considering inline/not inline images. I've raised this as a suggestion on trello if you want to discuss further. Thanks.

**Closed by Dillon-Brown** 2018-02-12 13:12 UTC
Labels: High Priority, bug

**Comment by DeFB** [comment] 2018-05-22 23:52
This issue is really a headache for me. I have to change include/SugarPHPMailer.php each time I upgrade SuiteCRM, but after the last upgrade to 7.10.4 the stop stoped to work and now, I don't know why, the alteration from /public path to the ID embeded image stop working. Someone else have this issue with the patch provided? Could the a mail server change affect somehow?

Would the devel team some plan to solve this -I consider- problem?

**Comment by pgorod** [comment] 2018-05-23 08:31
I confirm that recently more people have been showing up in the Forums with issues related to image links in emails. So I guess we are being hit by some regression.

**Comment by pgorod** [comment] 2019-04-30 09:28
@lazka you might want to read through this Issue, if you're working with Email images. Despite being closed, this is really still to be implemented, and would be a great addition to SuiteCRM IMHO - the ability to choose between inline or linked images in Campaigns.
