### ISSUE TITLE
Non-Latin Characters don't allow search.

### ISSUE THREAD

**Issue by GeorgeWL** [salesagility/SuiteCRM#796] opened 2015-12-17 15:59 UTC
https://suitecrm.com/forum/suitecrm-7-0-discussion/6353-aod-advanced-open-discovery-and-non-latin-characters-with-russian-language#26652

My Data consists of English and Russian companies and names. Russian are most written in Cyrillic. Using AOD to find a Cyrillic name I need to search for transliterated name, i.e. Andrey instead of 'Андрей'. And 'Andrey' searches results for both 'Andrey' and 'Андрей'.

Search for 'Андрей' outputs an empty result.

Which seems not logical

**Comment by celsocos** [comment] 2016-03-30 23:52
In portuguese, we have a similar situation. In Portuguese, we have accents in many strings, and this is causing problems too. Issues with characters like "ã" or  "ç" or "ñ". Maybe in portuguese a simple way to solve this is remap accent to regular characters in the search, because it is not so different from English. The search wil not be "really" perfect, but it is far better than output an empty result.

For Cyrillic this is more complex, of course, but maybe a solution is to replace in the search to improve result with some languages (spanish, french, etc):

André => Andre
órfão => orfao

**Comment by GeorgeWL** [comment] 2016-12-21 12:28
Any progress on this? still an issue in latest.

**Comment by pgorod** [comment] 2016-12-21 15:44
This seems almost a duplicate of #1133.

However, this part
> Search for 'Андрей' outputs an empty result

seems different. It's when I search _without_ accents that I get an empty result. Searching _with_ accents returns results (but it's more cumbersome).

Maybe accented characters get a different treatment from foreign, non-accented characters. Or maybe the libraries cover some of the european cases better than the asian ones.

**Comment by vladbar** [comment] 2017-01-18 15:35
Could not replicate this issue on SuiteCRM 7.7.9 . 

1. Created a new Account and named it "Андрей". 
2. Created a new Account and named it "My new account". 
3. Tried to search for "Андрей" or "My new account" without any success.
4. Enabled crontab.
5. Changed "Perform Lucene Index" and "Optimise AOD Index" schedulers to run every minute.
6. Checked the Job Log to make sure that both of these schedulers have run.
7. Changed "Perform Lucene Index" and "Optimise AOD Index" schedulers to their initial values.
8. Successfully searched for "Андрей" or "My new account".

**Comment by shogunpol** [comment] 2017-02-08 14:30
@GeorgeWL , an issue has been tested on recent version of SuiteCRM(.7.8.1), and not appear, can you confirm and close the issue?

**Comment by GeorgeWL** [comment] 2017-02-08 15:12
I think that it's fixed now,  but not sure which version did that.

**Closed** 2017-02-08 15:13 UTC
Labels: bug, Medium Priority, Pending Input
