### ISSUE TITLE
Dropdown list does not display correctly after upgrading Chrome

### ISSUE THREAD

**Issue by tomi798** [salesagility/SuiteCRM#2116] opened 2016-09-02 08:38 UTC
#### Issue
Dropdown list does not display correctly after upgrading Chrome, tested on two devices.
![dropdownlist](https://cloud.githubusercontent.com/assets/21075768/18197785/58d1fe7a-70f9-11e6-8c89-27719110f877.jpg)

#### Actual Behavior
Dropdown list does not display correctly

#### Steps to Reproduce

1.Upgrade your chrome to newest version
2. Go to login panel or somwhere where you have dropdown list

#### Context
medium/high

#### Your Environment

* SuiteCRM Version used: 7.4.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): chrome 53.0.2785.89 m
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04): win10

**Comment by Mausino** [comment] 2016-09-02 08:52
Similary to #2113 #1969 +this appearance is related to #1940

**Comment by Mausino** [comment] 2016-09-02 09:15
+ i have same problem as you (on chrome 32 bit version is working fine) 

As i suggested before, the dropdowns for 64 bit versions are working in Layout Options part of SuiteCRM but in Basic or Advance search (or editview) aren't ... look on picture from official demo version 7.7.4 and my version of Chrome was 53.0.2785.80 beta-m (64-bit) 

![oppor](https://cloud.githubusercontent.com/assets/5773777/18198906/533d47c6-70fe-11e6-84d2-2dc9a24f7264.png)

**Comment by ijdavie** [comment] 2016-09-02 12:54
This appears to be a duplicate of #1930, I will close this and investigation can be done in that issue. 
Thanks.

**Closed by ijdavie** 2016-09-02 12:54 UTC
