### ISSUE TITLE
Cannot email Quote/Invoice PDFs

### ISSUE THREAD

**Issue by blloyd78** [salesagility/SuiteCRM#3724] opened 2017-06-15 21:02 UTC
#### Issue

When attempting to email a PDF copy of an invoice or quote, nothing happens. The PDF is not created, and the email screen does not load.

#### Expected Behavior

A PDF of the quote/invoice should be created and automatically attached to an email ready to be sent.

#### Actual Behavior

Nothing happens. The central panel of the screen fails to load.

<img width="984" alt="screen shot 2017-06-15 at 21 55 36" src="https://user-images.githubusercontent.com/17355746/27201390-7297b0ea-5215-11e7-84f7-79ad08ea8702.png">

A check of the sugarcrm.log file shows no errors or problems.

#### Possible Fix

None. 

As a workaround you can "print" the PDF and manually attach to an email (3rd party or SuiteCRM client), but that is unsatisfactory in the medium to long term.

#### Steps to Reproduce

1. Select an Invoice or Quote
2. Click Actions -> Email PDF
3. Select an Invoice/Quote template (if prompted)
4. The screen reloads blank (see screenshot above)

#### Context

Medium severity bug

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Safari v10
* Environment name and version (e.g. MySQL, PHP 7): mySQL php 7.0.8
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by samus-aran** [comment] 2017-06-16 07:37
HI @blloyd78 This is a duplicate of this issue here - https://github.com/salesagility/SuiteCRM/issues/3654

**Closed by samus-aran** 2017-06-16 07:37 UTC

**Comment by blloyd78** [comment] 2017-06-16 08:23
Many apologies @samus-aran - I didn't find the other report when I searched.
