### ISSUE TITLE
Radio button validation not showing error message

### ISSUE THREAD

**Issue by satheeshsagadevan** [salesagility/SuiteCRM#1280] opened 2016-04-25 07:14 UTC
Hi All,

Custom field Radio button validation not showing validation error message.

We are using Suite version 7.5.1

Thanks,
Satheesh.

**Comment by samus-aran** [comment] 2016-05-04 10:25
Does this resolve it?

https://github.com/salesagility/SuiteCRM/pull/750

**Comment by Dillon-Brown** [comment] 2017-09-18 05:55
Duplicate of #715

**Closed by Dillon-Brown** 2017-09-18 05:55 UTC
Labels: duplicate
