### ISSUE TITLE
Translation problem in Calendar (incompatibility fullcalendar with Cal.js)

### ISSUE THREAD

**Issue by plessmann** [salesagility/SuiteCRM#4222] opened 2017-09-07 22:38 UTC
#### Issue
Weekdays in Calendar are not translated properly (e.g. german). These are shown in English. It seems the the fullcalendar lib has been updated but it is not properly initialized (changes in the new version).

#### Expected Behavior
The specified user language should be used to display the weekdays and other literals.

#### Actual Behavior
Some literals are not translated from english to another language (e.g. German).

#### Possible Fix
See the corresponding pull request of me. I fixed it myself.

#### Steps to Reproduce
1. Open Calendar in a language different from the default language english
2. See the weekdays are not translated properly.

#### Context
It happens always.
I fixed the bug myself. See pull request.

#### Your Environment
* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 60.0.3112.113
* Environment name and version (e.g. MySQL, PHP 7): LAMP Stack based on PHP 7.1.1
* Operating System and version (e.g Ubuntu 16.04): debian 8.7

**Comment by Dillon-Brown** [comment] 2017-09-08 04:30
@plessmann Duplicate of #2498 and fixed here: #2983

**Closed by Dillon-Brown** 2017-09-08 04:30 UTC
Labels: duplicate
