### ISSUE TITLE
suitecrm 7.10.7: Cannot read property 'value'

### ISSUE THREAD

**Issue by doug3132** [salesagility/SuiteCRM#6428] opened 2018-10-17 12:32 UTC
Uncaught TypeError: Cannot read property 'value' of undefined
    at Function.SugarWidgetScheduler.update_time (jsclass_scheduler.js:82)
    at Cal.js?v=hxzkn2l-GejcfR21aQF4vA:107

jsclass_scheduler.js:82 Uncaught TypeError: Cannot read property 'value' of undefined
    at Function.SugarWidgetScheduler.update_time (jsclass_scheduler.js:82)
    at Object.CAL.GR_update_focus (Cal.js?v=hxzkn2l-GejcfR21aQF4vA:71)
    at Object.CAL.reset_edit_dialog (Cal.js?v=hxzkn2l-GejcfR21aQF4vA:54)
    at Object.CAL.load_create_form (Cal.js?v=hxzkn2l-GejcfR21aQF4vA:103)
    at callback (Cal.js?v=hxzkn2l-GejcfR21aQF4vA:115)
    at Object.CAL.dialog_create (Cal.js?v=hxzkn2l-GejcfR21aQF4vA:113)
    at Et.function.e.constructor.select (Cal.js?v=hxzkn2l-GejcfR21aQF4vA:157)
    at Ot.W [as trigger] (fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:6)
    at Et.function.e.constructor.trigger (fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:8)
    at Et.function.e.constructor.triggerSelect (fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:9)
SugarWidgetScheduler.update_time @ jsclass_scheduler.js:82
CAL.GR_update_focus @ Cal.js?v=hxzkn2l-GejcfR21aQF4vA:71
CAL.reset_edit_dialog @ Cal.js?v=hxzkn2l-GejcfR21aQF4vA:54
CAL.load_create_form @ Cal.js?v=hxzkn2l-GejcfR21aQF4vA:103
callback @ Cal.js?v=hxzkn2l-GejcfR21aQF4vA:115
CAL.dialog_create @ Cal.js?v=hxzkn2l-GejcfR21aQF4vA:113
select @ Cal.js?v=hxzkn2l-GejcfR21aQF4vA:157
W @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:6
trigger @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:8
triggerSelect @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:9
reportSelection @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:9
interactionEnd @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:7
trigger @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:7
handleInteractionEnd @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:7
handleInteractionEnd @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:7
endInteraction @ fullcalendar.min.js?v=hxzkn2l-GejcfR21aQF4vA:7
f @ sugar_grp1_jquery.js?v=hxzkn2l-GejcfR21aQF4vA:2
dispatch @ sugar_grp1_jquery.js?v=hxzkn2l-GejcfR21aQF4vA:3
r.handle @ sugar_grp1_jquery.js?v=hxzkn2l-GejcfR21aQF4vA:3
********************************************************************************************
**when i click on the cel of calendar, in first time the quickcreate load normally the form, 
but the next quickcreate stay a loop loading!! i need help because idk how to fix this.**

**Comment by pgorod** [comment] 2018-10-17 15:49
On my 7.10.9 this seems to work fine. 

But maybe you can explain better where you click the second time? On top of the Calendar entry you created before, or on a blank space?

Please try this on the demo to see if the problem is only in your system:
https://demo.suitecrm.com

If it doesn't happen in the demo, then please close this issue here, and open a thread on the forums, I will help you out there. Thanks.

**Closed** 2018-10-17 16:15 UTC
