### ISSUE TITLE
Dropdowns on chrome do not display its contents when browsing - suiteP

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#2290] opened 2016-09-22 17:22 UTC
#### Issue

Dropdowns on chrome do not display its contents when browsing

#### Expected Behavior

Values should be visible!

#### Actual Behavior

Dropdowns on chrome do not display its contents when browsing:
![chrome_dropdown](https://cloud.githubusercontent.com/assets/3055443/18758646/cb4f2818-80f0-11e6-98d5-a219aaea0cf1.png)

#### Possible Fix

Solution posted by forum user @araneus: 
https://suitecrm.com/forum/suite-themes/11176-suitep-theme-incompatible-with-ie#38492

changing line 5453 of style.css from
`line-height: 40px;`
to
`line-height: 20px;`

#### Your Environment

* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome

**Comment by ijdavie** [comment] 2016-09-22 20:27
This is a duplicate of issue #1930, which has been resolved in the next release.

**Closed by ijdavie** 2016-09-22 20:27 UTC

**Comment by horus68** [comment] 2016-09-23 22:00
confirmed as solved in the hotfix
