### ISSUE TITLE
Finsales - Definition and use

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1018] opened 2016-02-26 17:20 UTC
What is Finsales and in what context is this used?
`'LBL_FINSALES' => 'Finsales',`

It should have a description field too. 

Language file with the term:
https://github.com/salesagility/SuiteCRM/blob/master/modules/Connectors/language/en_us.lang.php

**Comment by mattlorimer** [comment] 2016-03-01 18:49
its not used, probably should be removed

**Comment by shogunpol** [comment] 2016-11-25 10:28
@horus68 , this label is not used and will be removed.

**Comment by shogunpol** [comment] 2016-11-25 12:36
(tag and Close issue)

@horus68  - Thank you for highlighting this issue, however, this is a duplicate of issue #2552. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2016-11-25 12:36 UTC
Labels: suggestion

**Comment by horus68** [comment] 2016-11-25 22:07
No problem, this is an old one (nine months!)
