### ISSUE TITLE
AOW wont trigger on audited fields

### ISSUE THREAD

**Issue by mikebeck** [salesagility/SuiteCRM#1647] opened 2016-06-24 13:18 UTC
SuiteCRM 7.6.4
Ubuntu 14.04.4 LTS (GNU/Linux 3.19.0-59-generic x86_64)
PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)
Apache/2.4.7 (Ubuntu)

All correct permissions and ownership, when you create a workflow to trigger on any field that has the Audit option activated, it wont work.

How to reproduce:
1- Create a custom field in Accounts module, dropdown type and select an existing dorpdown list, in my example I selected the call_status_dom
2- Make it Audit
<img width="179" alt="audited" src="https://cloud.githubusercontent.com/assets/545556/16338626/f086f0c6-39eb-11e6-9b4f-9d2c9035f6e9.png">
3- Create a workflow only on save, on Account module, repeated runs, with condition on any change and when the field status is changed to Planned
<img width="818" alt="log" src="https://cloud.githubusercontent.com/assets/545556/16338655/10c8c0a8-39ec-11e6-8a7d-74819aa3baca.png">
4- Go to the account module, edit any account and modify the field status to planned, save it, an email should be sent to you, but doesn't happen. The change log shows that I changed the audited field status to matching the criteria on my workflow
<img width="382" alt="changelog" src="https://cloud.githubusercontent.com/assets/545556/16338729/84ada04c-39ec-11e6-9896-b5df663d8fa9.png">
5- Go again to studio, remove the Audit option in the status_c field
6- Test again the workflow and now works

best regards

**Comment by willrennie** [comment] 2016-06-24 15:18
Duplicate of #195, fixed in PR #1648

**Comment by mikebeck** [comment] 2016-06-24 17:39
thank you will, I forgot to search in Pull request

best regards

**Closed** 2016-06-30 11:55 UTC
