### ISSUE TITLE
Jotpad Dashlet

### ISSUE THREAD

**Issue by daniel-samson** [salesagility/SuiteCRM#786] opened 2015-12-16 10:48 UTC
The Jotpad Dashlet doesn't save text in SuiteCRM 7.4.3.

**Comment by FrenchySuiteCRM** [comment] 2015-12-31 07:18
{*

/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/




*}


{literal}<script>
if(typeof JotPad == 'undefined') { // since the dashlet can be included multiple times a page, don't redefine these functions
	JotPad = function() {
	    return {
	    	/**
	    	 * Called when the textarea is blurred
	    	 */
	        blur: function(ta, id) {
	        	ajaxStatus.showStatus('{/literal}{$saving}{literal}'); // show that AJAX call is happening
	        	// what data to post to the dashlet	
				ta.value=ta.value.replace(/&/gi, "%26");				
    	    	var va=YAHOO.lang.JSON.stringify(ta.value);				
    	    	postData = 'to_pdf=1&module=Home&action=CallMethodDashlet&method=saveText&id=' + id + '&savedText=' + va;
				var cObj = YAHOO.util.Connect.asyncRequest('POST','index.php', 
								  {success: JotPad.saved, failure: JotPad.saved}, postData);
	        },
		    /**
	    	 * Called when the textarea is double clicked on
	    	 */
			edit: function(divObj, id) {
				ta = document.getElementById('jotpad_textarea_' + id);
				if(SUGAR.isIE) ta.value = divObj.innerHTML.replace(/<br>/gi, "\n");
				else ta.value = divObj.innerHTML.replace(/<br>/gi, '');
				ta.value = ta.value.replace(/&amp;/gi, "&");
				divObj.style.display = 'none';
				ta.style.display = '';
				ta.focus();
			},
		    /**
	    	 * handle the response of the saveText method
	    	 */
	        saved: function(data) {
	        	eval(data.responseText);
	           	ajaxStatus.showStatus('{/literal}{$saved}{literal}');
	           	if(typeof result != 'undefined') {
					ta = document.getElementById('jotpad_textarea_' + result['id']);
					theDiv = document.getElementById('jotpad_' + result['id']);
					theDiv.innerHTML = result['savedText'];
				}
				ta.style.display = 'none';
				theDiv.style.display = '';
	           	window.setTimeout('ajaxStatus.hideStatus()', 2000);
	        }
	    };
	}();
}
</script>{/literal}

**Comment by Mausino** [comment] 2016-01-04 12:41
:+1:

**Comment by willrennie** [comment] 2016-01-27 10:54
Resolved in 7.5.x

**Closed by willrennie** 2016-01-27 10:54 UTC
Labels: bug, High Priority

**Comment by pgorod** [comment] 2016-04-21 15:50
I'm not sure if it's the same bug, since this was marked as solved, but my Jotpad in 7.5.2 isn't saving anything either.

It always shows $defaultText (literally like that, visible to the end user) when the page loads.

**Comment by pgorod** [comment] 2016-04-23 10:39
I noticed it works well when I log in using English language, but breaks when I login using another language (portuguese). 

The english file has this (modules/Home/Dashlets/JotPadDashlet/JotPadDashlet.en_us.lang.php
):
```
$defaultText = "";
$dashletStrings['JotPadDashlet'] = array('LBL_TITLE'            => 'JotPad',
                                         'LBL_DESCRIPTION'      => 'A dashlet to keep your notes',
                                         'LBL_SAVING'           => 'Saving JotPad ...',
                                         'LBL_SAVED'            => 'Saved',
                                         'LBL_CONFIGURE_TITLE'  => 'Title',
                                         'LBL_CONFIGURE_HEIGHT' => 'Height (1 - 300)',
                                         'LBL_DBLCLICK_HELP'    => 'Double click below to Edit.',
                                         'LBL_DEFAULT_TEXT'     => $defaultText,
);
?>
```

While the translated file (/modules/Home/Dashlets/JotPadDashlet/JotPadDashlet.pt_PT.lang.php) adds apostrophes...
```
$defaultText = "";
$dashletStrings['JotPadDashlet'] = array('LBL_TITLE'            => 'JotPad',
                                         'LBL_DESCRIPTION'      => 'Uma aplicação de painel onde pode tomar notas',
                                         'LBL_SAVING'           => 'A guardar JotPad...',
                                         'LBL_SAVED'            => 'Guardado',
                                         'LBL_CONFIGURE_TITLE'  => 'Título',
                                         'LBL_CONFIGURE_HEIGHT' => 'Altura (1-300)',
                                         'LBL_DBLCLICK_HELP'    => 'Duplo clique para editar.',
                                         'LBL_DEFAULT_TEXT'     => '$defaultText',
);
?>
```
No wonder there is a problem. The translations included by default don't seem to have this problem (Spanish, Russian), but this one (generated in Crowdin) seems to be treating this as a special case, I can't find this string there. I guess it doesn't handle assigning variables to labels. It would be nice if somebody could check a different language from Crowdin just to see if it's working.

I will be contacting user horus68 who runs the Crowdin platform to work with him on a solution. 

I don't know if this issue should be reopened, or a new one made. But even if the solution lies outside the scope of this repository, it might be nice to be able to document it and track it here.

**Comment by pgorod** [comment] 2016-04-25 10:53
The issue with the apostrophes is now fixed in the translations. Thanks, horus68.

However, there is still a bug, and** it's showing in the original English version** too.

Basically, if you insert text without a carriage return, the JotPad dashlet saves the text. But as soon as the first return is there, the text doesn't get saved. I'm on 7.5.3.

@daniel-samson can you reproduce? Do you think this is the same issue you were seeing when you opened the original issue? Do you want to reopen, or should I open a new issue myself? 

Thanks.
