### ISSUE TITLE
Inbound email body contains utf8 hex code instead of real char (e.g. à = =C3=A0; è = =C3=A8)

### ISSUE THREAD

**Issue by Sasamous** [salesagility/SuiteCRM#7880] opened 2019-09-18 11:12 UTC
#### Issue

When I receive mails with special character like (à, è, ì, ò, ù,) or just characters like "=", special chars are translated in hex code instead of normal text.
Cases created with mails get wrong text in DB too, Cases created with Joomla AOP are stored correctly.
![Wrong char screen](https://user-images.githubusercontent.com/40520020/65143605-af327a00-da15-11e9-88f1-72a345ff5df8.PNG)

#### Steps to Reproduce

1. Clean install or SuiteCRM 7.11.8
2. Setup of mail and "Create case from mail"

3. Get mails

#### Your Environment

* SuiteCRM Version used: 7.11.8
* Browser name and version: anyone
* Environment name and version: MariaDB, PHP 7.2
* Operating System and version: Ubuntu 18.04

**Comment by Mac-Rae** [comment] 2019-09-20 14:19
I think it is a known issue across the CRM, Might be related to https://github.com/salesagility/SuiteCRM/issues/3192

@Dillon-Brown What's your opinion on this one?

**Comment by Sasamous** [comment] 2019-09-20 15:12
@Mac-Rae The strange is the problem appears only in email body, if I send and email with special chars in subject, it is correct, everywhere in SuiteCRM special chars are accepted, the problem is only in emails body

**Comment by Dillon-Brown** [comment] 2019-09-23 07:42
@Mac-Rae This definitely shouldn't be a known issue anymore, I had created a new field type "EmailBody" to handle this. I'll take a look at this when I get a chance, thanks.

**Comment by Dillon-Brown** [comment] 2019-09-23 11:17
Confirmed, this will be fixed for the next release. Thanks for the report!

**Closed** 2019-11-04 14:25 UTC
Labels: Bug, Emails, Fix Proposed, High Priority, Resolved: Next Release

**Comment by Laszlo-Gaessler** [comment] 2019-11-05 11:03
We updated our CRM to version 7.11.9 and newly imported emails are displayed in the correct way again.
Old emails, that have been imported to the database before the update, however, are still being displayed in the “unreadable” way. Is there an option to fix the display of these old emails as well? If so, how?

**Comment by Dillon-Brown** [comment] 2019-11-05 17:06
> Old emails, that have been imported to the database before the update, however, are still being displayed in the “unreadable” way. Is there an option to fix the display of these old emails as well? If so, how?

Hi @Laszlo-Gaessler, unfortunately if you've already imported the email there's no way to fix the display since it will already be physically in the database.
