### ISSUE TITLE
Adcanced search with dropdowns broken in 7.7.7

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#2607] opened 2016-11-10 18:48 UTC
Dropdowns in advanced search produces query errors.

#### Issue

I have created this field:
![777-1](https://cloud.githubusercontent.com/assets/19223035/20189410/597feb1a-a77d-11e6-9b73-15b1d71c7e9a.png)

The field can be searched in the advanced search:
![777-2](https://cloud.githubusercontent.com/assets/19223035/20189460/8cb075f4-a77d-11e6-9281-a131b68ad68f.png)

No records will show. In the log file I can find this:

Thu Nov 10 19:34:48 2016 [20881][1][FATAL]  Query Failed: SELECT  leads.id ,leads_cstm.gm_genug_c,leads_cstm.gm_gesperrt_c, leads.assigned_user_id , LTRIM(RTRIM(CONCAT(IFNULL(leads.first_name,''),' ',IFNULL(leads.last_name,'')))) as name, leads.first_name , leads.last_name , leads.salutation , leads.status , leads.account_name , leads.account_id , leads.phone_work  , jt0.user_name assigned_user_name , jt0.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod, leads.date_entered , leads.date_modified , leads.created_by  FROM leads  LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c   LEFT JOIN  users jt0 ON leads.assigned_user_id=jt0.id AND jt0.deleted=0

 AND jt0.deleted=0 where ((leads_cstm.gm_genug_c in (b))) AND leads.deleted=0 ORDER BY name ASC LIMIT 0,21::: MySQL error 1054: Unknown column 'b' in 'where clause'

Shouldn't it be ...((leads_cstm.gm_genug_c in ("b"))... ? Quotes missing?

"Search Email Templates" is another expample. Choose i.e. "Tpye Email" and then search. At least the Event Invite Template should show up.

#### Expected Behavior

Result should show related records.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 49
* Environment name and version (e.g. MySQL, PHP 7): PHP 56
* Operating System and version (e.g Ubuntu 16.04): FreeBSD 10.2

**Comment by mattlorimer** [comment] 2016-11-10 19:35
Duplicate of #2581

**Closed by mattlorimer** 2016-11-10 19:35 UTC

**Comment by adminibt** [comment] 2016-11-10 20:51
@mattlorimer Works now. Thanks.
