### ISSUE TITLE
Body tag seems to be duplicated in new email

### ISSUE THREAD

**Issue by PhillyD1973** [salesagility/SuiteCRM#3780] opened 2017-06-23 23:47 UTC
Upgraded from 7.8.4 directly to 7.9.1

Issues sending email when composing from scratch.

#### Issue
There seems to be two body tags.  One with a field, one without.

#### Expected Behavior
When opening the form there should be body with an input field.

#### Actual Behavior
When opening the form.  There is two body tags.  One with and one without an input field.  Additionally, the input field that is there appears to be misformatted (running off the edge of the screen).

![image](https://user-images.githubusercontent.com/29067877/27503679-79d6406e-584c-11e7-8b95-0b992e890eea.png)
 

#### Steps to Reproduce

1. Go to email module
2. Compose a new email

#### Your Environment

*SuiteCRM Version used: 7.9.1
*Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome (MAC) Version 58.0.3029.110 (64-bit)
*Environment name and version (e.g. MySQL, PHP 7): MySQL PHP 5.4
*Operating System and version (e.g Ubuntu 16.04): Unknown (hostgator)

**Comment by PhillyD1973** [comment] 2017-06-24 00:06
Addition to this.  
When opening an inbound email.  The same issue exists and the senders email seems to be split between the two.

![image](https://user-images.githubusercontent.com/29067877/27503905-78c91568-584f-11e7-84cf-d6deb0471e88.png)

**Comment by Dillon-Brown** [comment] 2017-06-26 09:38
@PhillyD1973 I'm able to replicate this, #3781 and #3780 on the activities subpanel by creating a group inbound and personal outbound account. This is then fixed by creating a personal inbound. I seem unable to replicate any of those issues on the email module however. Is there any info you can give that might help in replication?

**Comment by Dillon-Brown** [comment] 2017-06-27 08:50
@PhillyD1973 Able to replicate the second issue but not the first. The first I can only seem to replicate in the activities subpanel.

**Comment by PedroErnst** [comment] 2018-04-06 15:15
Can't reproduce this in the current version 7.10.3

**Closed** 2018-04-06 15:26 UTC
Labels: Medium Priority, bug
