### ISSUE TITLE
[PHP7] Too many warnings like: Declaration ... should be compatible with ...

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#2697] opened 2016-11-23 12:48 UTC
#### Issue
In apache error.log there are many log entries like:

PHP Warning:  Declaration of MyOpportunitiesDashlet::process($lvsPar
ams = Array) should be compatible with DashletGeneric::process($lvsParams = Array, $id = NULL) in /var/www/sugar/modules/Opportunities/Dashlets/MyOppo
rtunitiesDashlet/MyOpportunitiesDashlet.php on line 0, referer: ...

They are all over the code and thus making it impossible to debug with the apache error log.
Disabling ~STRICT in php.ini is not enough.

#### Expected Behavior
Theses warnings should not be there if programming is correct.

#### Actual Behavior
Too much Warnings in the error log, to debug "real" errors.

#### Possible Fix
Functions from derived classes should be compatible with parent class.
(Most are easy fixes with adding optional parameters and not using this parameter, or changing pass by ref to pass by value. Email->save(...) seems a bit more complicate to fix. )

#### Steps to Reproduce

1. Use Sugar
2. Look into apache error.log

#### Context
As it does not affect function directly, does not need to be high prio.

#### Your Environment

* SuiteCRM Version used: 7.7.8
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 50
* Environment name and version (e.g. MySQL, PHP 7): PHP7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by gunnicom** [comment] 2016-11-23 13:00
Patterns i found so far:
Function saveOptions needs type hint "array":
> Declaration of SugarFeedDashlet::saveOptions($req) should be compatible with DashletGeneric::saveOptions(array $req) in /var/www/sugar/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php


Function displayInput should have parameter passed by value:
> Declaration of SugarWidgetFielduser_name::displayInput(&$layout_def) should be compatible with SugarWidgetFieldVarchar::displayInput($layout_def) in /var/www/sugar/include/generic/SugarWidgets/SugarWidgetFielduser_name.php


Function process should have the optional parameter "$id=null" added:
> Declaration of MyCallsDashlet::process($lvsParams = Array) should be compatible with DashletGeneric::process($lvsParams = Array, $id = NULL) in /var/www/sugar/modules/Calls/Dashlets/MyCallsDashlet/MyCallsDashlet.php

These should be the low hanging fruits. Functions like Email->save(...) need some more look to find a solution.

**Comment by shogunpol** [comment] 2016-11-24 08:32
(tag and Close issue)

@gunnicom  - Thank you for highlighting this issue, however, this is a duplicate of issue ##942. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2016-11-24 08:32 UTC
