### ISSUE TITLE
$site_config_url does not correctly interpret variables in relevant template

### ISSUE THREAD

**Issue by alexcicche78** [salesagility/SuiteCRM#8321] opened 2019-11-27 13:57 UTC
Hi,
I've recently installed SuiteCRM 7.10.22 LTS on a LAMP environment
Linux 18.10 Kernel 4.15.0.70
Apache 2.4.29-1 Ubuntu 4.11
MySQL 5.7.25
PhP 7.2
and I have an issue sending email with variables in template, not correctly interpreted

#### Issue
I've tryed to use several predefined templates but all the mail has the varibles not interpreted and therefore displayed in plain text as $variable, even if the 
Send in Plain Text check box is not thicked
I've also tried to create a new template, using some other variable relevant to the employee I'm using, but with the same results
For the System-generated password email template i got the mail in plain text 
Here is your account username and temporary password:

Username : $contact_user_user_name

Password : $contact_user_user_hash

$config_site_url

#### Expected Behavior
Variables should be converted accondingly

#### Actual Behavior
Variables are expressed in plain text as $variable

#### Possible Fix
No idea...

#### Steps to Reproduce
1. Compose an email
2. Select one of the predefined template ( for example "System-generated password email")
3. select a user email
4.Leave "Send in Plain Text:" unchecked

#### Context
High Priority

#### Your Environment
SuiteCRM 7.10.22 LTS on a LAMP environment
Linux 18.10 Kernel 4.15.0.70
Apache 2.4.29-1 Ubuntu 4.11
MySQL 5.7.25
PhP 7.

**Comment by Mausino** [comment] 2019-11-27 14:17
@alexcicche78 did you use the select button relate to in compose of email to right user? or did you ony put user email to from field and sytem cant catch to which record is the email related if relate to field was empty

**Comment by alexcicche78** [comment] 2019-11-27 15:56
I've selected the outbound email for the from dropdown list and I've selected the user clicking on the double man icon, retriving the data from existing users.
![email](https://user-images.githubusercontent.com/11873500/69738563-9f7e9280-1136-11ea-8a24-f895a09b06d9.png)
As you can see both the from and the to are related to the same email box, but this should be not an issue

**Comment by Mac-Rae** [comment] 2019-11-27 16:00
@alexcicche78 As @Mausino said it appears you must relate the field using the related to selection on the right. However, I do believe this is a bug, I would assume that ether method should relate the recipient correctly. I'll do some further testing to ensure this doesn't affect campaigns.

**Comment by Mac-Rae** [comment] 2019-11-27 16:01
As a workaround, for now, please relate the contact via the related to select field (This will also pull in the email address)

**Comment by alexcicche78** [comment] 2019-11-27 16:20
None of the method works, you a can either select the "to" field inserting the "emai addressl" or selecting it from either the "users" or the "contacts".
I've also tried to fist select the "to" and then select the template or the reverse way and none of them works. This is definetly an issue unless you give me the correct sequence that currently works on your system

**Comment by Mac-Rae** [comment] 2019-11-27 16:50
@alexcicche78 I've just tested with the Related To field and it appears to work fine. Just to confirm - Starting on the Compose page, Select an Email Template, then change the Related to option to Contacts, press the select arrow and chose a contact. See that an email is added to the "To" field and press send. The received emails will have the correct variables.

Let me know further steps to replicate if this is unsuccessful

**Comment by alexcicche78** [comment] 2019-11-27 17:30
Now I've understood what are you referring to "related to"
I've followed your step but there are also ate least two issues
I've created a contact

Here is your account username and temporary password:
Username : admin
Password : $2y$10$ZRTc4/zsD9VTyANueZ1frebZcs78AJRQpzZgTiPVJOX/QRIIEYY/O

$config_site_url

After you log in using the above password, you may be required to reset the password to one of your own choice.
--

As you can see the username is not the contact username that I've selected but is the user I've used to send the mail, and the config_site_url is not correctly interpreted.

In my opinion contacts should receive this king of email, only users should and  config_site_url should be the same used to log into the suiteCRM application.

Let me know....

**Comment by Mac-Rae** [comment] 2019-11-28 10:29
Hi @alexcicche78,

What's the intended purpose of this email template?

As an example, if I was providing a Contact with a username and password for a Joomla portal I could use the following template;

```
Hi $contact_name,

An account has been created for you at $portal_address.
You may login using this email address and the password $joomla_pass
```

Could you confirm the variable you are using are produced via the Insert Variable menu on the Email Templates page as this should ensure validity?
![Screenshot from 2019-11-28 10-28-17](https://user-images.githubusercontent.com/45397629/69798755-cdf97d80-11c9-11ea-9046-e0c4201601b0.png)

**Comment by alexcicche78** [comment] 2019-11-28 13:43
Hi @Mac-Rae , the intent of the template is to allow the CRMsuite users (tipically internal workers) to reset their password, but as you can see the variables are not filled correctly.
Instead of the user ($contact_user_user_name) the current CRMsuite user has been used (admin)
More over the $config_site_url is not used.
This is a standard template,predefined in CRMsuite and I think is useful for internal management and should not be used for contact that has no user name

**Comment by Mac-Rae** [comment] 2019-11-28 16:26
I agree, I don't understand why that would have contact on the front :laughing: @Dillon-Brown Any thoughts? 

Think this is brought up in #8315

**Comment by alexcicche78** [comment] 2019-11-28 16:59
I definetly think that also "Related To:" need to have user as field, for the purpose of the template and all related communications between CRMsuite users.
I'm brand new to this environment, do you know who will be in charge for this bug and feature resolution? and how will I be notified, when resolved?
Thanks

**Comment by Dillon-Brown** [comment] 2019-11-28 17:17
@alexcicche78 I agree that it would make sense to have the "Related To:" dropdown contain users, otherwise this default template doesn't make much sense. I would suggest perhaps raising this as a separate issue so that it can be tracked as a suggestion.

For the second part of your issue, the ```$config_site_url``` not being correctly replaced, I would consider this a bug. You can follow along with the progress here on GitHub and will receive email notifications by subscribing to the issue which will then get closed and included in the release notes once completed.

**Comment by samus-aran** [comment] 2021-09-15 11:27
Suspect this is a duplicate of a general wider issue with template variables...

**Comment by samus-aran** [comment] 2021-09-15 11:31
Setting this as a "duplicate" of https://github.com/salesagility/SuiteCRM/issues/8877 and that a new issue will be created with a suggestion of adding Users to the Relate To.

Generally the variables for emails need to be thoroughly tested when fix is proposed including this scenario.

**Closed by samus-aran** 2021-09-15 11:31 UTC
Labels: Type:Bug, Priority:Important, Area: Emails:Templates
