### ISSUE TITLE
Missing AND for condition with multiple value

### ISSUE THREAD

**Issue by wolfsolver** [salesagility/SuiteCRM#996] opened 2016-02-23 21:57 UTC
In 7.5.1 if a condition have field with multiple value, where clausule missing AND
<img width="675" alt="cattura" src="https://cloud.githubusercontent.com/assets/3205448/13268024/749cdf86-da80-11e5-98a7-4a93513cb4f0.PNG">

the where generated is:
WHERE ( `opportunities`.sales_stage = 'Closed Won' AND `opportunities`.assigned_user_id = 'ad73228a-b69d-2b85-2c50-555cdee21196' (`opportunities`.opportunity_type = 'Service' OR `opportunities`.opportunity_type = 'Contract') ) AND  opportunities.deleted = 0  

MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(`opportunities`.opportunity_type = 'Service' OR `opportunities`.opportunity_typ' at line 7

Can be fixed with the following code (see line ISSUE FIX and below:

>           case 'Multi':
>                             $sep = ' AND ';
>                             if ($condition->operator == 'Equal_To') $sep = ' OR ';
>                             $multi_values = unencodeMultienum($condition->value);
>                             if (!empty($multi_values)) {
>                                 $value = '(';
>                                 foreach ($multi_values as $multi_value) {
>                                     if ($value != '(') $value .= $sep;
>                                     $value .= $field . ' ' . $app_list_strings['aor_sql_operator_list'][$condition->operator] . " '" . $multi_value . "'";
>                                 }
>                                 $value .= ')';
>                             }
>                             //  ISSUE: Fix per multi and missing AND: 
>                             // $query['where'][] = $value;
>                             $query['where'][] = ($tiltLogicOp ? '' : ($condition->logic_op ? $condition->logic_op . ' ': 'AND ')) . $value;
>                             $tiltLogicOp = false;
>                             $where_set = true;
>                             break;

**Comment by paulgodley** [comment] 2016-03-02 15:11
Hi @wolfsolver, thank you for this submission.  I will look at getting this fix in place as soon as possible.

**Comment by paulgodley** [comment] 2016-03-03 08:08
This is a duplicate of bug #924 and this fix has been implemented.  Thank you again for your fix.  @JimMackin can you please mark this issue as closed?

**Closed** 2016-03-03 16:17 UTC
Labels: bug, duplicate
