### ISSUE TITLE
Typo in include/SugarObjects/templates/basic/Dashlets/Dashlet/m-n-Dashlet.php

### ISSUE THREAD

**Issue by jannepesonen** [salesagility/SuiteCRM#3870] opened 2017-07-10 23:41 UTC
#### Issue

Typo in line 48:
now it is "<module_name > Dashlet"
shoud it be? "<module_name>Dashlet"

#### Expected Behavior

Make custom module in module builder, add module dashlet in dashboard.

#### Actual Behavior

Can not add custom module dashlet (made by module builder) in dashboard.

#### Possible Fix

Fix typo before deploy module.
If already deployed, find and remove 2 files <module_name>Dashlet.php
inside custom/modulebuilder... packages/... (1 file) and builds/... (1 file),
fix typo and redeploy.

#### Steps to Reproduce

1. Make No 1 custom module in module builder
2. Deploy modules
3. Try to add No 1 custom module dashlet in home dashboard
4. fix typo
5. Make No 2 custom module in module builder
6. Deploy modules
7. Add No 2 custom module dashlet in home dashboard

#### Your Environment

* SuiteCRM Version used: 7.9.2

**Comment by Dillon-Brown** [comment] 2017-07-11 08:12
Duplicate of #3831

**Closed by Dillon-Brown** 2017-07-11 08:12 UTC
Labels: duplicate
