### ISSUE TITLE
Calendar display problems in 7.7.1

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1939] opened 2016-08-12 16:59 UTC
After upgrading from 7.4.3 via 7.6.6 to 7.7.1 the calendar displays nearly nothing

#### Issue

This worked in 7.4.3 and 7.6.6.

#### Expected Behavior

Calendar should display entries. Tried this with a fresh installation and had no problems.
Under 7.6.6 the calendar was OK.

#### Actual Behavior

Calendar display nearly nothing. Settings button does not work. Shared button produces a fatal error:

[Fri Aug 12 18:43:41.117301 2016] [:error] [pid 68794] [client 192.168.1.30:44620] PHP Catchable fatal error:  Argument 1 passed to TimeDate::tzGMT() must be an instance of DateTime, null given, called in /usr/local/www/apache24/data/modules/Calendar/CalendarActivity.php on line 97 and defined in /usr/local/www/apache24/data/include/TimeDate.php on line 870, referer: http://192.168.1.101/index.php?module=Calendar&action=index&view=agendaDay&year=2016&month=8&day=12&hour=0

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.7.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 48, IE 11
* Environment name and version (e.g. MySQL, PHP 7): MYSQL 5.6.24, PHP 5.6
* Operating System and version (e.g Ubuntu 16.04): FreeBSD 10.2

![cal](https://cloud.githubusercontent.com/assets/19223035/17630137/410fd550-60be-11e6-89bf-db01a5df394b.jpg)

**Comment by mattlorimer** [comment] 2016-08-12 18:51
this may be a duplicate of issue #1938 please see my comments in there

**Comment by adminibt** [comment] 2016-08-12 19:14
@mattlorimer  I have also seen those things (esp. the stuff in the logs). I have not mentioned them because the issue had already been posted. With a clean 7.7.1 installation I get similar results.

Please have look my screenshot. I don't even see the table (no grid lines) with the week days and the time. So, I think this is a different problem. Keep in mind that I upgraded from 7.4.3 to 7.6.6 (calendar was fine) and then to 7.7.1 where the issue occurs.

**Closed** 2016-08-23 17:05 UTC
Labels: bug, Resolved: Next Release

**Comment by gpant** [comment] 2016-09-21 11:50
Hace exact same issue on 7.7.4, complete new install. I checked all themes and they have the same issue. There are no tasks without due dates, the issue appears in a brand new installation.

Am I correct to assume that in 7.7.4 this issue should be fixed?
