### ISSUE TITLE
Unable to add own local images to PDF templates

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#1804] opened 2016-07-28 09:08 UTC
As a User I am unable to add an image from my local machine into a PDF template. This is missing functionality i assume from the implemented tinyMCE
#### Issue

As a User I am unable to add an image from my local machine into a PDF template. This is missing functionality i assume from the implemented tinyMCE
#### Expected Behavior

As a User i should be able to click on a button which points to my local directory so that I can select an image from a from local file directory and use an image for the PDF template
#### Actual Behavior

---
#### Possible Fix

If you running into this problem, you can dump the image you want to use in the 'themes/default/images'...then point to it. 
#### Your Environment

- SuiteCRM 7.6.5
- Chrome 52.0.2743.82 (64-bit)

**Comment by shogunpol** [comment] 2016-12-28 10:18
@darthtang  - Thank you for highlighting this issue, however, this is a duplicate of issue #2153. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2016-12-28 10:18 UTC
Labels: suggestion
