### ISSUE TITLE
v7.8.6 LTS - User Management dropdown menu edit button doesn't work

### ISSUE THREAD

**Issue by JBrace1990** [salesagility/SuiteCRM#4276] opened 2017-09-18 13:21 UTC
#### Issue

When in the user management screen (http://atlas.c-4analytics.com/index.php?module=Users&action=index) and viewing a user (http://atlas.c-4analytics.com/index.php?module=Users&offset=1&stamp=1505740554063185800&return_module=Users&action=DetailView&record=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx), the Actions -> Edit button throws a JS error.

~~As a note, this potentially also affects the quick edit for users, which is not working as intended. This could be duplicated in #4270, but I'm unsure as to whether this is one root issue or 2.~~ (Edit: Fix has nothing to do with this)

#### Expected Behavior

The edit button should take you to the edit screen

#### Actual Behavior

Throws a JS error

#### Possible Fix

The ID of the record is not quoted, so JS throws a "Uncaught SyntaxError: Invalid or unexpected token" error

#### Steps to Reproduce

1. Go to the User Management screen under Admin
2. View a users Record
3. Click "Actions"
4. Click "Edit"

#### Context

Makes it impossible for normal users without JS knowledge to edit a user account. 

#### Your Environment

* SuiteCRM Version used: 7.8.6 (Latest LTS)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): N/a
* Environment name and version (e.g. MySQL, PHP 7): N/a
* Operating System and version (e.g Ubuntu 16.04): N/a

**Comment by Dillon-Brown** [comment] 2017-09-18 14:17
Looks like this is also present in 7.9.5

**Comment by JBrace1990** [comment] 2017-09-18 14:49
The possibility is there, since they contain a lot of the same edits. 

I found the commit that this happened in: https://github.com/salesagility/SuiteCRM/commit/831b56fa70b677060d280ebcaa56dd2f31498cda line 117. The single quotes are just on the wrong side.

This looks like it's been fixed in Master now, since I just went to edit it on a branch and it's fine.

**Comment by JBrace1990** [comment] 2017-09-18 17:33
Create a PR for this that fixes the issue #4277

**Comment by Dillon-Brown** [comment] 2017-09-22 10:46
Duplicate of #4232

**Closed by Dillon-Brown** 2017-09-22 10:46 UTC
Labels: bug, Fix Proposed, High Priority
