### ISSUE TITLE
SugarEmailAddress->addAddress does not set other addresses to non-primary if $primary parameter is true

### ISSUE THREAD

**Issue by RejakuP2N** [salesagility/SuiteCRM#3295] opened 2017-03-20 11:16 UTC
#### Issue
The existing code iterates over $this->addresses and sets primary_address to 0 for all existing addresses, if a new primary address should be added.
It does so though in local scope within the loop, as such it is effectively dead code, as it does not effect anything outside the loop. If you rely on the functionality, you could therefor end up with multiple addresses that are set as primary_address 1.

#### Expected Behavior
The code should be doing what it's set out to do, namely ensuring that after the call, only the new primary address is set as such.

#### Actual Behavior
When calling addAddress to add a primary address, you could end up with several primary addresses.

#### Possible Fix
$address['primary_address'] = '0';
should be changed to
$this->addresses[$k]['primary_address'] = '0';

#### Steps to Reproduce
1. Retrieve a record that has a primary email address
2. Call $bean->emailAddress->addAddress("someone@somewhere.com", true) // isPrimary true
3. Inspect $bean->emailAddress->addresses and notice now 2 addresses with is_primary 1 existing
4. Call $bean->save and notice now 2 records with primary_address=1 existing in email_addr_bean_rel

#### Context
* Usage scenario: Parsing and storing records via protobuf exchange, in a custom scheduler task.
* Priority: low, as it is a bug that has existed since at least SugarCRM 4.5, but is trivial to fix.

#### Your Environment
* SuiteCRM Version used: 7.8.2

**Comment by chris001** [comment] 2017-03-20 17:50
@RejakuP2N Great find!  I'm sure there is many more of these subtle bugs in the code.  These tools should be used to locate them:
https://github.com/exakat/php-static-analysis-tools
Which tool did you use to help you find this bug?

**Comment by RejakuP2N** [comment] 2017-03-21 09:39
None, I stumbled upon it while implementing a new feature, and noticed that the function didn't result in the expected behaviour.

**Comment by chris001** [comment] 2017-03-21 10:46
Have you ever written a phpunit test, or wanted to give it a go, this is a perfect opportunity to write a few lines to make a test case, add an address with `SugarEmailAddress->addAddress` and check if there is only one primary address, and if not, you fail the test and github stops the code from being merged.  When this code gets new features at some point, the changes will get in only if the phpunit tests pass.

**Comment by opensourcecrm** [comment] 2017-03-24 03:54
Hi Even I am facing an issue.

When I am trying to create leads from a Json file with Leads object. its creating the record, creating email addresses in the database with primany email.

there are few leads which have no primany email address information, while updating the emails with below code
                  if($i==0)
		{
		$sea = new SugarEmailAddress;
		$sea->addAddress($email[$i],true);
		$sea->save($lead_id, "Leads");	
		}
		else
		{
		$sea = new SugarEmailAddress;
		$sea->addAddress($email[$i],false,false,false,false,null);
		$sea->save($lead_id, "Leads");
		}
Its creating all the records in the system with primany emails in no primary email case its creaing the email record in the db but marking the primany email address relationship as deleted=1;

can anyone please suggest soem fix to this issue.

**Comment by RejakuP2N** [comment] 2017-03-24 10:14
I'm sorry @opensourcecrm, but this has nothing to do with the issue. Your code is just wrong.
What you'd want to do is something more like (not exact, just out of memory):
$lead = new Lead();
$lead->retrieve($leadId);
foreach ($emails as $idx => $email) {
  // This will set the first email address to primary
  $lead->emailAddress->addAddress($email, ($idx == 0 ? true : false));
}
$lead->save();

**Comment by chris001** [comment] 2017-03-24 13:20
@opensourcecrm 
What @RejakuP2N said is accurate.
Also, you're calling the wrong method, `save()` is the old one.  You have to change it to use the new `saveEmail()`.
Read the code to find out more:
https://github.com/salesagility/SuiteCRM/blob/master/include/SugarEmailAddress/SugarEmailAddress.php

**Comment by Dillon-Brown** [comment] 2017-04-06 14:46
@RejakuP2N can you submit a PR to the hotfix branch for this issue? the referenced PR is for your own fork. Thanks.

**Comment by chris001** [comment] 2017-04-06 21:00
@RejakuP2N You only need to edit your PR to reference the PR against `salesagility/suitecrm:hotfix`. No need for a new PR.

**Comment by RejakuP2N** [comment] 2017-04-07 08:09
I'm confused, I already had created a pull request against the hotfix branch:
"RejakuP2N  wants to merge 1 commit into hotfix from RejakuP2N-patch-1"

**Comment by chris001** [comment] 2017-04-07 08:20
It can be confusing.  The PR you made is Requesting to Pull your changes into your own fork.
When you edit your PR and set the branch right, it'll say:
`RejakuP2N wants to merge 1 commit into salesagility:hotfix from RejakuP2N-patch-1`.

**Comment by RejakuP2N** [comment] 2017-04-07 08:42
I haven't found an option to switch the fork in the existing pull request, so I did end up creating a new one after all.

**Comment by chris001** [comment] 2017-04-07 08:46
It's not easy to find the option to switch the fork.

**Comment by RejakuP2N** [comment] 2017-04-07 08:47
Should be all set now though.

**Comment by opensourcecrm** [comment] 2017-04-26 15:08
by adding this to the lead object its not adding the email address. $lead->emailAddress->addAddress($email, ($idx == 0 ? true : false));

I tried both the option which you nd cris has suggested. still the issue is same. when we add more secondary email address it will delete the primany email address relation in the database table.

**Comment by chris001** [comment] 2017-04-26 17:41
@opensourcecrm Have a look at the code for `SugarEmailAddres::addAddress()`, `Lead::save()` and `Person::save()`.
* https://github.com/salesagility/SuiteCRM/blob/master/include/SugarEmailAddress/SugarEmailAddress.php#L573
* https://github.com/salesagility/SuiteCRM/blob/master/modules/Leads/Lead.php#L557
* https://github.com/salesagility/SuiteCRM/blob/master/include/SugarObjects/templates/person/Person.php#L177

**Closed** 2017-05-29 15:33 UTC
Labels: bug, Fix Proposed, Low Priority, Resolved: Next Release
