### ISSUE TITLE
Cannot duplicate role - buttons cannot be seen/clicked

### ISSUE THREAD

**Issue by willrennie** [salesagility/SuiteCRM#75] opened 2014-09-25 11:50 UTC
https://suitecrm.com/index.php?option=com_kunena&view=topic&catid=10&id=1685&Itemid=1136

**Comment by recci** [comment] 2015-01-22 10:01
This looks like a feature that has been pulled across from SugarCE not a bug.

**Comment by willrennie** [comment] 2015-01-22 10:07
It's a bug. The action menu is not displaying correctly. It will display correctly if you click 'Edit' and then 'Cancel'. This is a bug inherited from SugarCRM CE.

**Comment by danieljsamson** [comment] 2015-07-10 12:22
It's caused by the ajax ui. If you add '1' => 'ACLRoles' to the 'addAjaxBannedModules' array, it seems to fix the problem.

**Comment by willrennie** [comment] 2016-07-28 11:15
Closing as non-issue as this does not occur in the theme for 7.7 and the older themes will be deprecated going forward.

**Comment by ijdavie** [comment] 2018-01-17 10:43
This issue appears to have been fixed in one of the latest releases. 

Due to this I will close this issue.

**Closed by ijdavie** 2018-01-17 10:43 UTC
Labels: Fix Proposed, Low Priority, bug
