### ISSUE TITLE
Non-numeric values encountered in ListViewSubPanel.php

### ISSUE THREAD

**Issue by hinnerkweiler** [salesagility/SuiteCRM#4185] opened 2017-08-30 13:06 UTC
#### Issue

Categories in Detail views show many PHP Warnings:
**Warning: A non-numeric value encountered in [htdocsroot]/include/ListView/ListViewSubPanel.php on line 548**
Before each Category after the Category Name in Detail views for almost all Data (Accounts, Documents,...) at least one Error comes up, sometimes two or three. All refer to Line 548 if more than one come up the warning repeats for each row with refernce to line 323. 

I wasn't sure about a configuration issue at first but since this was reported also to the Forum (https://suitecrm.com/forum/feedback/15648-php-errors-more) I assume I am not alone.

#### Expected Behavior
No Warnings

#### Actual Behavior
annoying Warnings clutter the screen
 
#### Possible Fix
With reference to https://github.com/salesagility/SuiteCRM/issues/3576
I added
`if( !isset($current_offset) || empty($current_offset) )
          $current_offset=0;`

above Line 548 and 

`$offset = empty($this->getOffset($html_varName)) ? 0:$this->getOffset($html_varName);'`
above line 323.

resulting in no more Warnings

 
#### Steps to Reproduce
1. Log on
2. open e.g. a Contact
3. scroll past contact Details to linked data

#### Context
Trief quick Repair/Rebuild but no change

#### Your Environment

* SuiteCRM Version used: Happened after update to 7.9.4 
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): irrelevant (tried Chrome, Safari, Firefox)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP7 (Tried also PHP5.6)
* Shared Host

**Comment by Dillon-Brown** [comment] 2017-09-06 07:33
Duplicate of #3576 and fixed in #3581

**Closed by Dillon-Brown** 2017-09-06 07:33 UTC

**Comment by hinnerkweiler** [comment] 2017-09-12 06:14
I just updated to 7.9.5 and the warnings come up again. probably because my manual chances were overwritten.
@Dillon-Brown : This is the same technical bug referenced in #3581 but happens on different line numbers
