### ISSUE TITLE
Emails - Can't change Email page on SuiteR theme

### ISSUE THREAD

**Issue by johnM2401** [salesagility/SuiteCRM#608] opened 2015-10-30 16:10 UTC
Cannot view E-mails past the 1st page's worth. 
Seems to be an issue on SuiteR theme.

Suite7 theme also has this issue, but you can slightly see the Page Change buttons by shortening the size of the Bottom Section of the E-mails. You can do this using the draggable part.

**Comment by ijdavie** [comment] 2016-09-13 13:46
This appears to be a duplicate of #2068 - Closing this as #2068 has more information around the issue

**Closed by ijdavie** 2016-09-13 13:46 UTC
Labels: bug
