### ISSUE TITLE
Selecting Monitored folders popup appears half off screen 

### ISSUE THREAD

**Issue by darthtang** [salesagility/SuiteCRM#327] opened 2015-07-30 10:47 UTC
If you go to

set inbound emails->file in the fields for mail account information->then click on the monitored,trash,sent folders....the pop up will appear off screen

**Comment by darthtang** [comment] 2015-10-19 11:29
This could have something to do with the scroll bar at the bottom of the page in suite7 theme. 

This scroll bar is not in the sugar theme in email and thus avoiding the bug

**Comment by ijdavie** [comment] 2016-09-21 10:43
This is a duplicate of #286 I will close this issue.

**Closed** 2017-02-01 10:57 UTC
Labels: bug, Fix Proposed, Low Priority
