### ISSUE TITLE
Button go to end in subpanels doesn't do anything

### ISSUE THREAD

**Issue by t-sgi** [salesagility/SuiteCRM#8911] opened 2020-10-28 11:04 UTC
The button wich you go to the end of the list in subpanels in an account doesn't do anything.
![GoTo-End](https://user-images.githubusercontent.com/57987761/97428079-c67cb000-1915-11eb-8e9d-f711f05a2e49.jpg)

#### Steps to Reproduce

1. Open an account
2. scroll down to for example projects subpanel
3. click on the button "end"
4. nothing happens

#### Your Environment

* 7.10.27
* Chrome 
* MySQL, PHP 7.2
* Ubuntu 18.04

**Comment by johnM2401** [comment] 2020-10-28 13:26
Hey,

There has been a fix proposed: #8677 
Can you let us know if this resolves your issue?

<br>
Duplicate of: #8859 / #7608

**Comment by t-sgi** [comment] 2020-10-28 13:37
Yes, that resolve my issue.
Thank's a lot.

**Comment by johnM2401** [comment] 2020-10-28 14:07
Great,
Thanks for letting us know!

**Closed by johnM2401** 2020-10-28 14:07 UTC
Labels: Area: Module, Priority:Important, Type:Bug, Type:Duplicate
