### ISSUE TITLE
PHP parse error "modules/AOW_Actions/actions/templateParser.php"

### ISSUE THREAD

**Issue by FR-JS** [salesagility/SuiteCRM#6849] opened 2019-01-28 12:39 UTC
#### Issue
The file "modules/AOW_Actions/actions/templateParser.php" is incomplete and PHP throws a parse error.

#### Expected Behavior
The file should be parsed correctly.

#### Actual Behavior
The file cannot be parsed.

#### Possible Fix
Append right curly bracket to the end of the file.

#### Context
This prevents workflows we have in place from being actioned after Leads have been created through the API.
Should be a high priority since beans are created before the script is loaded and an error is thrown.
The file is currently incomplete in the source and the latest releases.

#### Your Environment
* SuiteCRM Version used: SuiteCRM 7.11

**Comment by pgorod** [comment] 2019-02-01 13:59
I think this is a duplicate of #6796 

and the fix proposed there (#6876) is the correct one. 

The fix by @pribeiro42 #6857 solves the parse error but doens't reconstitute the broken code to how it was before it got messed up. #6857 should be closed without merging, if I'm not mistaken.

**Closed** 2019-02-01 14:14 UTC
Labels: duplicate
