### ISSUE TITLE
Isn't possible to  add signature of compose email if you using group outbound email account

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#5851] opened 2018-05-09 13:01 UTC
#### Issue

If you using system or outbound email account you are not able to see your signature if you setted up in your email user settings (default signature), also same issue if you want reply or forward to email.

Also missing possibility in revamped emails in compose email to add or choose signature as in old email system #4818

If you are using template, can't add signature #4075

Other outbound email accounts don't show in compose email window #5774

#### Expected Behavior

Will available to get default user signature if compose email

#### Actual Behavior

The email signature which is the most important things in communication with client isn't working properly. Employees can't use the power of SuiteCRM but using saved signature texts in text file which is open on dashboard of windons and copy&paste signature to SuiteCRM because signatures are not usable in latest version of SuiteCRM... 

#### Steps to Reproduce

1. Use outbound email accounts
2. Compose email

#### Your Environment

* SuiteCRM Version used: 7.10.4
* Browser name and version : Chrome 65.x
* Environment name and version: MySQL 5.6 PHP 7.2

**Comment by PedroErnst** [comment] 2018-05-09 13:52
Hi @Mausino 

I'm using system outgoing email account

![image](https://user-images.githubusercontent.com/34056696/39818235-569b19a6-5398-11e8-9e6f-477c617e0fff.png)

With a custom signature

![image](https://user-images.githubusercontent.com/34056696/39818267-6741bae4-5398-11e8-8f64-e036ace4ff04.png)

Seems to work ok?

![image](https://user-images.githubusercontent.com/34056696/39818337-8d263c26-5398-11e8-816d-39171e4e4301.png)

**Comment by Mausino** [comment] 2018-05-09 14:06
@PedroErnst  hi, thank you that you tested it.

Yes, for personal inbound is working as you tested.. but please create group (not bouced) of inboud email account as we did in screen. Is it working for you now ???

![2018-05-09_1333](https://user-images.githubusercontent.com/5773777/39819002-93ef3fe4-53a2-11e8-9f7b-fad008b031ab.png)

**Comment by PedroErnst** [comment] 2018-05-09 14:08
Says outbound in the title and original issue description... maybe you meant inbound?

**Comment by labcerouno** [comment] 2018-05-09 14:14
I had to create 2 accounts, one personal and the other group account which indeed points to the same address/usr/server. This was the only workaround to make disappear the "data error" message in the Mail Accounts list. Also, signature now is working.

**Comment by PedroErnst** [comment] 2018-05-09 14:16
Ok, so I've created an Inbound Group Account,

![image](https://user-images.githubusercontent.com/34056696/39819640-db79d344-539b-11e8-82fd-7f4c6d1fcc24.png)

And the signature still shows up, as before.

**Comment by Mausino** [comment] 2018-05-09 14:31
@PedroErnst yes... i will honest.. in this case i thinked on inboud group email account.. changed now in name of ticket...  if i have group inboud emails i also getting this issue

@labcerouno i think, he is talking about this issue, if create inbound group accounts.. for admin are visible but for user not .... 

admin
![2018-05-09_1333](https://user-images.githubusercontent.com/5773777/39820471-2d7bc1ca-53a6-11e8-8569-4cd0db29cebd.png)

users
![2018-05-09_1309](https://user-images.githubusercontent.com/5773777/39820489-3476b336-53a6-11e8-9ba9-0485198a41b5.png)

on email listview
![2018-05-09_1423](https://user-images.githubusercontent.com/5773777/39820066-37b97962-53a5-11e8-9499-00c71a1fb288.png)

i will again ask my developer about this issue with signature and let you know soon an update... for this what wrote @labcerouno if you want, i can create separate ticket

**Comment by labcerouno** [comment] 2018-05-09 15:12
That would be great, @Mausino

**Comment by pgorod** [comment] 2018-05-09 15:38
I have seen the `data error` issue more times than I can count in the past few months. Do we have a detailed "steps to reproduce" for that one? I guess it's probably just a symptom of larger problems, but we could start by understanding why that shows on the screen, and fixing it.

**Comment by PedroErnst** [comment] 2018-05-09 15:54
The data error is fairly easy to reproduce, create a group inbound account as admin and make it available to other users. then login as a regular user and open email settings... you should get it right there.

It originates in include/SugarFolders/SugarFolders.php L 595 because of the Exception thrown there when there are no subscribed folders found.

I've been looking into this but the way the old and new email systems collide in certain things like the folders make the debugging very difficult.

**Comment by code-ph0y** [comment] 2019-01-25 15:03
Hi @labcerouno, @pgorod, @PedroErnst, 

I have tried to replicate the issue you have detailed, but I was unsuccessful. Can someone confirm that this issue can now be closed?

Thanks.

**Comment by code-ph0y** [comment] 2019-01-28 16:15
Hi @Mausino,

Following my comment, I have now had another colleague (@jack7anderson7) successful test the issue as being resolved.

I will now close this issue, if you're still having issues, please reopen this and we will look into it further.

**Closed by code-ph0y** 2019-01-28 16:15 UTC
Labels: Emails

**Comment by Mausino** [comment] 2019-01-28 16:55
@code-ph0y I can confirm that i didn't have this problem in 7.11 relase

I suggest, that is maybe time to look on other user UX issue #4818 which will great for us, if you can create more signatures, will also great to use them :)
