### ISSUE TITLE
Sanitization on PDF templates doesn't allow nested quotes

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#4476] opened 2017-11-02 12:21 UTC
#### Issue

If a background image is used like so:
`<div style="height:100%;width:100%;background:url('http://my-url.com') no-repeat right bottom;"> </div>`
it is "sanitized" to 
`<div style="height:100%;width:100%;background:url("http://my-url.com") no-repeat right bottom;"> </div>`
which will not work.

#### Expected Behavior

Leave my quotes be or don't sanitize my input.

#### Actual Behavior

Sanitization breaks layout
#### Steps to Reproduce

1. Put above mentioned line in template
2. Save
3. Reopen

#### Context

Breaks my layout

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 56
* Environment name and version (e.g. MySQL, PHP 7): MSSQL PHP 7
* Operating System and version (e.g Ubuntu 16.04): Microsoft Server 2012R2

**Comment by ChangezKhan** [comment] 2018-01-29 17:03
Sorry, I couldn't reproduce the error on SuiteCRM 7.8.10.

**Comment by Dillon-Brown** [comment] 2018-01-29 17:06
This should be fixed with the html cleaner changes made in 7.8.8 onwards. Please reopen if this is still an issue you can replicate.

**Closed by Dillon-Brown** 2018-01-29 17:06 UTC
Labels: Medium Priority, bug
