### ISSUE TITLE
Theme P: everything is too large

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM#2298] opened 2016-09-23 09:37 UTC
#### Issue

Viewing Theme P on a normal or large screen, everything in the main area (detailview/editview, subpanels, search filter...) of Theme P is too large. fonts, paddings, spaces.
The top and left bars are ok imho. As well as listings (list view results).

It's more difficult imho to find my way around when it's all so big...

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used: 7.7.4 (Theme P)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ijdavie** [comment] 2016-09-23 09:54
This is a duplicate of issue #2288

**Closed by ijdavie** 2016-09-23 09:54 UTC
