### ISSUE TITLE
Emails->'Bulk Action' button no longer works.

### ISSUE THREAD

**Issue by evgu** [salesagility/SuiteCRM#7585] opened 2019-07-17 14:32 UTC
After 7.10.18 upgrade, 'Bulk Action' button stopped working when few emails are selected. When all emails are selected button is enabled.  

<img width="616" alt="Screenshot 2019-07-17 at 14 34 10" src="https://user-images.githubusercontent.com/18371928/61384196-09914c00-a8a8-11e9-80b1-58f0ccc99fb8.png">

#### Expected Behavior
When 1 or several emails are selected in the email list view, bulk action button is enabled. 

#### Steps to Reproduce
1. go to inbox. 
2. checkbox on email 
3. try to use bulk upload button - shows disabled. 

#### Context
Users need to go in each email individually to upload it causing extra workload. 

#### Your Environment
* SuiteCRM  7.10.18
* Browser name and version: Chrome 12.1 and Edge 
* Environment name and version MySQL 5.6.44  PHP 7.2.19
* Operating System and version CentOS 7.6

**Comment by Dillon-Brown** [comment] 2019-07-17 15:02
Duplicate of #7298

**Closed by Dillon-Brown** 2019-07-17 15:02 UTC

**Comment by pgorod** [comment] 2019-07-17 16:01
@evgu thanks for reporting anyway! Make sure you check out the solution provided at the other issue #7298
