### ISSUE TITLE
Tasks Related To in 7.10 no longer working

### ISSUE THREAD

**Issue by davidyounger** [salesagility/SuiteCRM#5330] opened 2018-02-26 06:55 UTC
#### Issue
Tasks list view - Related To column no longer showing the account names (does on a few records but not any others)

#### Expected Behavior
Related to should display accoutn name of all tasks linked to an account

#### Actual Behavior
A few random tasks show the related to info but 95%+ are blank.
I clicked on the task to confirm there is in fact an account there.

#### Steps to Reproduce
1.  Upgraded from 7.9x to 7.10
2. Tasks list - Related to not showing properly
3. Repaired
4.  Reset columns to default
5. Removed Related to column and put it back

#### Context
My sales manager is not happy

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

![image](https://user-images.githubusercontent.com/11151401/36656831-26aeaecc-1b1e-11e8-89b5-90024e10c3de.png)

**Comment by samus-aran** [comment] 2018-02-26 09:37
Hi @davidyounger.
I haven't been able to reproduce this. Do newly created tasks have this issue or are the problem records older ones?
Is there any additional relationships in this module to accounts? It would be great to see a screenshot of one of the problem records (list view then detail view).

**Comment by davidyounger** [comment] 2018-02-26 21:18
OK it gets interesting.
The issue is definitely in the list view.

Image 1 shows test 3 with related link. Notice that test2 does not show a link.
![image](https://user-images.githubusercontent.com/11151401/36695768-5b16bdf8-1b96-11e8-9b3f-07516cf7287b.png)

Image 2 after adding test 4.
Notice Test 2 now has a link and test 3 does not.
![image](https://user-images.githubusercontent.com/11151401/36695850-9368809c-1b96-11e8-939a-74dcbf017104.png)


Image 3 after deleting test 4
Notice Test3 has a link again but test2 does not.

![image](https://user-images.githubusercontent.com/11151401/36695896-b15d8e9e-1b96-11e8-82da-be780959ef5b.png)

Hope this helps.
David

**Comment by samus-aran** [comment] 2018-02-27 09:24
That is strange.... :thinking:

**Comment by davidyounger** [comment] 2018-02-28 05:37
Sure is, anything I can try from here?
Cheers
David Younger
Founder
[https://docs.google.com/uc?export=download&id=0BxFGhxL-9ealTWxwT2Z2R3BHaEk&revid=0BxFGhxL-9ealQVY0RzR2VnF6T0tZdDJpUlRYZTNGSTN0SEdRPQ]

| t. +61 2 9690 3888
| e. david@<mailto:david@>theservicemanager.com<http://theservicemanager.com/>
| w. www.<http://www.ramprfid.com/>theservicemanager.com<http://theservicemanager.com/>
| a. Suite 2a, 199 Regent St, Redfern, NSW 2016




This e-mail message and any attachments contain information that is confidential and may be subject to legal privilege. If you are not the intended recipient, you must not peruse, use, pass on or copy this message or any attachments. If you have received this e-mail in error, please notify us by return e-mail and erase all copies of this message including any attachments. Thank you.

**Comment by davidyounger** [comment] 2018-03-01 22:07
Tried updating another copy of our CRM on another server to 7.10.
Got exactly the same result.
Need some resolution to this as my sales people are revolting (lol).
Cheers
David

**Comment by bwlinux** [comment] 2018-03-12 02:52
Since ME TOO never helps anyone I thought I'd try to at least find something else to contribute.  The same bug is affecting the "My Open Task" dashlet, except that it only shows the Releated To for the FIRST record for each set of 10. Hopefully that helps more than a "Me Too".

![capture](https://user-images.githubusercontent.com/3944481/37263440-34387548-2576-11e8-9688-65f827b5e884.PNG)

CentOS 7
Apache 2.3.6-67
php 7.1.14 from IUS repo
MariaDB 10.1.31-1

--
Brian

**Comment by Admoneo** [comment] 2018-03-15 00:31
I f we inline edit, it works, the related account sticks there.
Hope it helps ...

**Comment by davidyounger** [comment] 2018-03-15 01:36
I tried inline editing and re-selected the account but immediately on save, the account did not show up in the list. Viewing the task, it had blanked out the account details which I had to reenter in the detail edit screen.

**Comment by Admoneo** [comment] 2018-03-28 23:45
Davidyounger,
I am on SuiteCRM 7.10.2 and maybe this will help you.
If you inline_edit "Relate To" in listview, the information will be recorded and displayed in listview.
If you inline edit the task "Relate To" in detailview the information is lost or not displayed.
Also found that it seems to affect regular users only.
I spent a few hours playing with our tasks and workflows and didn't notice anything until I switched from admin user to a regular user.

**Comment by davidyounger** [comment] 2018-03-29 03:42
I am an admin user and I cant edit in list view.
Hopefully they can find and fix the bug.
Cheers
David Younger
Founder
[https://docs.google.com/uc?export=download&id=0BxFGhxL-9ealTWxwT2Z2R3BHaEk&revid=0BxFGhxL-9ealQVY0RzR2VnF6T0tZdDJpUlRYZTNGSTN0SEdRPQ]

| t. +61 2 9690 3888
| e. david@<mailto:david@>theservicemanager.com<http://theservicemanager.com/>
| w. www.<http://www.ramprfid.com/>theservicemanager.com<http://theservicemanager.com/>
| a. Suite 2a, 199 Regent St, Redfern, NSW 2016




This e-mail message and any attachments contain information that is confidential and may be subject to legal privilege. If you are not the intended recipient, you must not peruse, use, pass on or copy this message or any attachments. If you have received this e-mail in error, please notify us by return e-mail and erase all copies of this message including any attachments. Thank you.

**Comment by jbrveen** [comment] 2018-04-03 08:45
I have the same issue. I can edit inline in the list view, but than it's not saved. When I save it in the record, its saved but not showing in the list view.

**Comment by torodev1** [comment] 2018-04-03 09:43
Hello,

Same problem here. Updated from 7.9.7 to 10.0.2.

"Related To" names are only displayed in the first row on every page. Inspecting the element I can see the href link value but the name is empty.


![crm_tasks_bug](https://user-images.githubusercontent.com/38035168/38241813-7a7bd986-3733-11e8-9ec4-e4c46388097a.png)

**Comment by mcarquejo** [comment] 2019-05-12 20:06
Hi there,
Does anyone "workarounded" this? Or does a update of version solves this Issue?

Thanks

**Comment by Mac-Rae** [comment] 2021-12-08 14:52
Can confirm this issue appears to be resolved by upgrading to the latest version.

**Closed by Mac-Rae** 2021-12-08 14:52 UTC
Labels: Type:Bug, Priority:Important
