### ISSUE TITLE
Issue With LEADs // Opportunity (critical) in 7.7.7

### ISSUE THREAD

**Issue by GrupImatica** [salesagility/SuiteCRM#2612] opened 2016-11-11 10:04 UTC
Hi, after upgrade of SUITECRm to latest version 7.7.7 we have a BUG in list of leads.

Not shows any lead. (with advanced search opened)

Some information:

When i go to opportunities, we can search for a name of opportunity and work fine. If i use advanced search, and filter for any field, return 0 results.

This issue is after install upgrade of 7.7.7, is very important for us to know how can i resolve this issue, it's affecting all of our users.

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): All Browser
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP7
* Operating System and version (e.g Ubuntu 16.04): MS 2012 R2

**Comment by pedroresende** [comment] 2016-11-14 11:38
Apparently all the advanced search is broken

**Comment by mattlorimer** [comment] 2016-11-14 12:14
This fix is a duplicate of #2581

**Closed by mattlorimer** 2016-11-14 12:14 UTC
Labels: duplicate
