### ISSUE TITLE
Workflow Module - Modified Record action not working Properly

### ISSUE THREAD

**Issue by pavithra-selvam** [salesagility/SuiteCRM#7123] opened 2019-03-28 05:35 UTC
Workflow Module - Modified Record action not working Properly
For example,
Create workflow for account module and add the condition for account and contact module.
Please set the action is modified record in contact module.
Here i have attached  image for references.
![workflowcon-act](https://user-images.githubusercontent.com/36614745/55132548-d421f080-5148-11e9-9b01-cd2a2ac605fb.png)
![contacts](https://user-images.githubusercontent.com/36614745/55132550-d5531d80-5148-11e9-900f-d003b834b2f2.png)

1) In my image this 3 contacts related(https://user-images.githubusercontent.com/36614745/55132550-d5531d80-5148-11e9-900f-d003b834b2f2.png) to test account record only.
2)But in my worklow added one condition for contact and accounts while i'm editing accounts its will affect for all contacts not only my condition matched contacts
#### Expected Behavior
if I edit any account record as per my condition is updated only on my condition records only need to update.

#### Actual Behavior
if i edit any account record as per my conditions is updated all related contacts records.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment
suiteCRM: 7.11.2
PHP: 7
MySQL: 5.7.25

**Comment by PedroErnst** [comment] 2019-03-28 09:49
Hi @pavithra-selvam 

From my understanding this is just how it works. 

You have to see the workflow conditions and actions as two completely separate mechanics, like individual steps if you like.

In the **condition step**, it is decided whether the flow will run on each individual record. So it goes through accounts, and picks any of the accounts which matches all conditions. The condition with the contacts is evaluated here, but the contacts that match are not saved for the action step. It just says: yes, one of the contacts' last name is test2, run the action _on this Account record_.

In the **action step**, it runs the selected actions on all related Contacts. No filtering here, no remembering which Contacts matched in the Condition step.

It sounds to me like what you really want to be doing in your case is running the workflow on the Contacts module instead.
Filter by Contact->Account->Industry like you did above, then filter by Contact->Last Name.
This will then select the Contacts you want and run the actions _on those Contacts_ individually.

Give it a try!

**Comment by pavithra-selvam** [comment] 2019-03-28 10:05
Hi @PedroErnst ,
Thanks for your reply, my point is one-to-many relationship is not working in workflow.
for example account is related to many of contacts so i want to edit account only. If i edit particular account and only update to particular contacts only. but workflow is not update properly,

**Comment by willrennie** [comment] 2019-04-04 15:02
@pavithra-selvam I have tested the workflow with the Conditions and Actions as you have described them and provided in the screen shot. The workflow triggers only on the record with the exact conditions, it does not trigger on all of the Contacts related to the parent Account as you have described. I am marking this as a non-issue for now. If you can provide further information and screen shots of creation dates of the workflow, the Account, the Contact record and also the workflow process audit data to show exactly what is happening we can investigate further.

**Closed by willrennie** 2019-04-04 15:02 UTC

**Comment by pavithra-selvam** [comment] 2019-04-05 04:04
@willrennie , which version you are using?

**Comment by pavithra-selvam** [comment] 2019-04-05 09:49
@willrennie 
Forexample accounts and contacts having one to many relationship.
In account module created one field like status values are (active,Inactive).
In contact module field is also status values are (new,partially paid,fully paid,received).
My condition is while changing account status field value is equal to "Inactive" also condition in contact  module like status is equal to (fullly paid and received) field only update.
Now one accounts has related to many contacts and the status value should be any one like new/partially paid/fully paid/received.

If you create the workflow module = account and added above condtions. Actions is modified the contact module custom field enable payment is equal to no.

but if i trigger the workflow its will affect the all related contacts. the problems is happed by 7.11.3.

This is my problem.

**Comment by PedroErnst** [comment] 2019-04-05 10:20
Not a bug.

**Comment by pavithra-selvam** [comment] 2019-04-05 10:26
@PedroErnst  so SuiteCRM workflow does not support this condition am i correct?

**Comment by PedroErnst** [comment] 2019-04-05 10:29
@pavithra-selvam 

Please see my first post. It was pretty detailed.

If I understand correctly, to achieve your aims you should base you WF on the Contacts module, not the Accounts module.

I'm pretty sure SuiteCRM can do what you want. But there isn't a bug that needs to be solved.

Have a look at the forums for non-code related issues: https://suitecrm.com/suitecrm/forum/index
