### ISSUE TITLE
AOR_Reports Date issues

### ISSUE THREAD

**Issue by lucas7793** [salesagility/SuiteCRM#5663] opened 2018-04-05 13:59 UTC
#### Issue
There are still some serious issues with the date in the AOR_Reports module.
Using two dates in Conditions does break the whole function. The second date will not have any hour and minutes fields, and the fields of the first date will be reseted. The datepicker of the second condition additionaly does not work. When deleting the second date field, its not possible to save because of the error message 'Missing required field: Hours'. When only one date is used and it is set as a parameter, the date will be set to a wrong value if date format d.m.Y is used.
Picking date 01.04.2018 and after clicking "update" the date will be 04.01.2018.
Using the date format Y-m-d the does not resolve the issue, but opens another one. The date will be deleted when clicking update on the DetailView of the Reports module.

#### Expected Behavior
Using dates should work in the Reports module.

#### Actual Behavior
When using dates everythings seems to be messed up. 

#### Steps to Reproduce

1. Go to report module
2. Create condition
3. Add a date field and choose a date
4. Add another date field
5. After that, saving is not possible (If only one date field is used it can be saved)
Also, setting one date to parameters does work, but changing the date in DetailView does not take the right date.

#### Context

Unable to use date fields in the Report module as parameters. Unable to use more than one date as conditions.

#### Your Environment

SuiteCRM Version used: 7.10.3 (demo)
Browser name and version: Chrome 65.0.3325.181
Environment: demo.suiteondemand.com

**Comment by AdminPL** [comment] 2018-04-06 07:44
Confirmed.

**Comment by HrEL81** [comment] 2018-04-06 08:10
+1

**Comment by pgorod** [comment] 2018-04-06 19:26
Probably the same as [this issue in the forums](https://suitecrm.com/suitecrm/forum/developer-help/18516-suitecrm-v7-10-3-module-aor-reports-input-calendar-not-working-and-undefined-labels). It contains some extra information (browser console errors).

**Comment by david-pili** [comment] 2018-04-10 22:49
To make this extra maddening as soon as you put a debugger on the getDisplayForField function in aor_util.php it starts to work correctly, both fields show up like you'd expect and you can get a report out of it.

**Comment by david-pili** [comment] 2018-04-18 19:29
I'm currently working backward through release versions to see when this bug was introduced. I'll keep you posted on what I find and if I find a workaround.

**Comment by david-pili** [comment] 2018-04-18 22:03
Found the culprit
https://github.com/salesagility/SuiteCRM/commit/9dfbb7b12156c0ebe1c74e17f991dc29a2cc2bb5

Reverting this commit fixes the problem. I'm still trying to work out why it's broken. In the mean time changing the type from value to field or any other option then back to value gets you a functional date time picker and lets you run your report.

**Comment by gunnicom** [comment] 2018-04-19 07:34
@david-pili thank you for that. 
It fixes the problem in the EditView, but not for parameters in DetailView or Dashlets.

**Comment by david-pili** [comment] 2018-04-19 16:31
Reverting the commit or the workaround I gave? 

Detail view and dashlets of reports?

**Comment by gunnicom** [comment] 2018-04-19 20:04
> Detail view and dashlets of reports?
@david-pili Yes. When you use conditions as parameter.

**Comment by pgorod** [comment] 2018-04-25 14:30
This is also broken in Workflows, you can't add conditions with two dates.

**Comment by david-pili** [comment] 2018-04-25 17:17
Can we get this marked as a high priority bug, it sounds like it broke a number of things.

**Closed** 2018-05-21 14:02 UTC
Labels: Fix Proposed, High Priority, bug, category:reports

**Comment by gunnicom** [comment] 2018-05-22 09:22
Bug is still there for dashlets after update to 7.8.19 :(

**Comment by david-pili** [comment] 2018-05-23 22:55
@Dillon-Brown  on LTS 7.8.19 This seems to be worse than before, Now its hit or miss on either field working if I have multiple date-time fields on a report
