### ISSUE TITLE
Studio: New Drop Down List Issue

### ISSUE THREAD

**Issue by murdal** [salesagility/SuiteCRM#416] opened 2015-08-28 11:04 UTC
When adding a new drop down list from the add field option there is no prompt when you click the save button. If you click save twice user is prompted with a new message 'This operation is completed successfully'  and all your field definitions are cleared.

**Comment by willrennie** [comment] 2015-08-28 11:05
Linked to/duplicate of issue #370

**Comment by drosenfeldpositive** [comment] 2015-09-07 17:08
In my case, it's enough to click 'Save' just once. After that, I get the "loading" popup, and then "'This operation is completed successfully".
But that's not all. When creating a text field, after clicking 'Save', I get those messages, but I am redirected again to the screen of creation of a field (instead of the field's list).
And when entering to create a dropdown field, clicking on 'Add dropdown list', and clicking 'Save' I get all those messages again, and I am redirected to the creation screen too, but all my field data was cleared.

**Closed** 2015-10-22 19:52 UTC
Labels: bug, High Priority
