### ISSUE TITLE
AOW uses operators from language file

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#2744] opened 2016-12-01 10:15 UTC
#### Issue
AOW uses operators from language files. So translated operators lead to AOW not working.

#### Expected Behavior
AOW should work, no matter how faulty a translation is.

#### Actual Behavior
AOW does not work if operators are translated.

#### Possible Fix
Change AOW to not use $app_list_strings['aow_date_operator'] like in modules/AOW_Workflow/AOW_WorkFlow.php as example line 372.

#### Steps to Reproduce

1. Install other language where aow_date_operator is translated instead of left like in english
2. Use the Operator in Workflow
3. Workflow does not work

#### Context
Its like the bug for AOR, but for AOW: https://github.com/salesagility/SuiteCRM/issues/1662 AND as i already mentioned in this https://github.com/salesagility/SuiteCRM/issues/1451 but seems noone really read this.

#### Your Environment
Does not matter.

**Comment by shogunpol** [comment] 2016-12-01 11:26
@gunnicom  - Thank you for highlighting this issue, however, this is a duplicate of issue #1662. This is issue will be closed, please follow the original issue.

**Comment by gunnicom** [comment] 2016-12-02 09:51
@shogunpol : #1662 is closed. No one will look at that closed issue. And thats the reason i opened a new one.

**Comment by samus-aran** [comment] 2017-04-01 22:26
![](https://github.trello.services/images/mini-trello-icon.png) [AOW uses operators from language file](https://trello.com/c/0or27DHn/49-aow-uses-operators-from-language-file)

**Comment by horus68** [comment] 2017-04-01 22:29
@samus-aran this is an old and major bug and should be tagged as high (it breaks reports)

**Comment by samus-aran** [comment] 2017-04-01 22:31
@horus68 You are too quick fo rme there.  I removed the trello mention as I agree this is a bug, but it is a duplicate of this https://github.com/salesagility/SuiteCRM/issues/2457 with a PR provided https://github.com/salesagility/SuiteCRM/pull/2458

**Closed by samus-aran** 2017-04-01 22:31 UTC
Labels: suggestion
