### ISSUE TITLE
Add Dashlet doesn't work on Suite v7.8, 7.10

### ISSUE THREAD

**Issue by rebbieboi** [salesagility/SuiteCRM#5529] opened 2018-03-19 13:25 UTC
#### Issue
Add dashlet is not working. It's not added to the dashboard.
I've been trying to add console.logs on MySugar.js but it doesn't get triggered as well.

I placed the console.logs just after the addDashlet functions.

#### Expected Behavior
Dashlet should be displayed on the dashboard.

#### Actual Behavior
Dashlets are not added to the dashboard. No errors in logs as well.

#### Steps to Reproduce
1. Add dashlet any dashlets

#### Your Environment

* SuiteCRM Version used: v7.4.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 64.0.3282.186 (Official Build) (64-bit)
PHP 5.4.45-0+deb7u8 (cli) (built: Mar 27 2017 22:43:09)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by AdminPL** [comment] 2018-03-20 07:59
Same problem on 7.10.2 problem showed up on (7.9.14- 7.10 upgrade ) no sign in suitelogs or in browser

**Comment by likhobory** [comment] 2018-03-20 18:37
Confirmed. Can't add dashlet or page on 7.10.2.

**Comment by rebbieboi** [comment] 2018-03-21 12:11
How did you turn on error trace?

**Comment by AdminPL** [comment] 2018-03-21 12:13
In system settings there's "Display stack trace of errors:: in advanced options

**Comment by sanchezfauste** [comment] 2018-03-22 12:36
Same issue on 7.8.17 LTS.
```log
[Thu Mar 22 13:33:20.140037 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP Notice:  Undefined index: server_unique_key in include/MySugar/retrieve_dash_page.php on line 300, referer: index.php?module=Home&action=index
[Thu Mar 22 13:33:20.140082 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP Stack trace:, referer: index.php?module=Home&action=index
[Thu Mar 22 13:33:20.140088 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP   1. {main}() index.php:0, referer: index.php?module=Home&action=index
[Thu Mar 22 13:33:20.140093 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP   2. SugarApplication->execute() index.php:52, referer: index.php?module=Home&action=index
[Thu Mar 22 13:33:20.140112 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP   3. SugarController->execute() include/MVC/SugarApplication.php:105, referer: index.php?module=Home&action=index
[Thu Mar 22 13:33:20.140118 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP   4. SugarController->process() include/MVC/Controller/SugarController.php:315, referer: index.php?module=Home&action=index
[Thu Mar 22 13:33:20.140123 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP   5. SugarController->handleEntryPoint() include/MVC/Controller/SugarController.php:402, referer: index.php?module=Home&action=index
[Thu Mar 22 13:33:20.140128 2018] [fcgid:warn] [pid 7198] [client 127.0.0.1:40808] mod_fcgid: stderr: PHP   6. require_once() include/MVC/Controller/SugarController.php:872, referer: index.php?module=Home&action=index
```

**Comment by AdminPL** [comment] 2018-04-06 12:50
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php on line 342 [2018-04-06 12:50:30] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php[L:342](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/modules/Home/index.php[L:236](SugarFeedDashlet:process)
/var/www/crm.fortecait.pl/modules/Home/views/view.list.php[L:52](:include)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:207](HomeViewList:display)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)
Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php on line 488 [2018-04-06 12:50:30] display_stack_trace caller, file: /var/www/crm.fortecait.pl/include/utils.php line#: 3533
/var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php[L:488](:StackTraceErrorHandler)
/var/www/crm.fortecait.pl/modules/Home/index.php[L:238](SugarFeedDashlet:display)
/var/www/crm.fortecait.pl/modules/Home/views/view.list.php[L:52](:include)
/var/www/crm.fortecait.pl/include/MVC/View/SugarView.php[L:207](HomeViewList:display)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:432](SugarView:process)
/var/www/crm.fortecait.pl/include/MVC/Controller/SugarController.php[L:375](SugarController:processView)
/var/www/crm.fortecait.pl/include/MVC/SugarApplication.php[L:109](SugarController:execute)
/var/www/crm.fortecait.pl/index.php[L:52](SugarApplication:execute)

**Comment by Chrobak77** [comment] 2018-09-10 01:04
Hello,
any news on this?

**Comment by pgorod** [comment] 2018-09-10 09:37
I cna't reproduce this on 7.10.7, it works fine for me...

**Comment by AdminPL** [comment] 2018-09-10 09:42
I did manage to repair this by changing date set to MM.DD.YYYY instaed DD.MM.YYYY in admin account and change apache related stuff to 777 instead recomended but wasn't focused on repairing this particular problem so i can't say which one of helpded.

**Comment by Chrobak77** [comment] 2018-09-10 16:59
Id like to provide some kind of logs or trace. However php error log is empty as well as suitecrm.log.
I cant click the New Dashlet container, even receive 200 response...inside the response is all the necessary data but dashlet is not added to the panel in the end.

**Comment by pgorod** [comment] 2018-09-10 18:02
@Chrobak77 do you have any errors in your browser's Developer console?

**Comment by Chrobak77** [comment] 2018-09-11 18:56
> @Chrobak77 do you have any errors in your browser's Developer console?

Hi!
I have only this warning:

```
XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ sugar_grp1_jquery.js:4:14158
unreachable code after return statement[Learn More] RGraph.common.effects.js:188:8 
```

**Comment by wanesmith** [comment] 2018-09-26 03:40
I removed all the old dashlets and then it started working

**Comment by pgorod** [comment] 2018-11-20 13:05
This specific error

`Unknown Error (8192): Function create_function() is deprecated occurred in /var/www/crm.fortecait.pl/modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php on line 342` is probably on PHP 7.2, am I right?

Is everyone else in this thread that still has this bug also running PHP 7.2?

**Comment by samus-aran** [comment] 2018-11-30 15:02
Hey @pgorod That PHP 72 should be resolved as create_function has been updated in that particular file 2adcce19ea484fd39893d00f403f9fa7c6b8d15c - . The only occurrence I can now find on the latest is in third party libraries.
I'm closing this issue now unless people are still having issues with this on PHP72 as a couple of people stated dashlets have now started working for them (probably since 7.10.5+)

**Closed by samus-aran** 2018-11-30 15:02 UTC
Labels: Medium Priority, bug
