### ISSUE TITLE
7.9.2: Email Template Merge Not replacing variable token with field values

### ISSUE THREAD

**Issue by someguynamedphil** [salesagility/SuiteCRM#3829] opened 2017-07-04 18:25 UTC
After creating an email template, select "Insert Variable: Lead>First Name>".  "$lead_first_name" is displayed in field as expected.

Click on "insert", variable is inserted at insertion point.

Click on Save

Sending from the Sales>Leads>LeadPersonsRecord > tasks > Compose email, select template created above. All template content populates as it should, but receiver only sees "$lead_first_name" not the first name from the record in the email. Sending plain text or not has no effect.

#### Expected Behavior
Variable should be replaced by field value from record

#### Actual Behavior
It don't

#### Possible Fix
Hit it with a stick.

Weep

become a farmer

#### Your Environment

* SuiteCRM Version used: 7.9.2
* Browser name and version: Chrome & FIrefox
* Environment name and version (e.g. MySQL, PHP 7.0): PHP 7.0 MySQL 5.1.73
* Operating System and version (e.g Ubuntu 16.04): CENTOS 6.9 x86_64 kvm

**Comment by Dillon-Brown** [comment] 2017-07-05 13:03
Duplicate of #3731

**Closed** 2017-07-05 13:03 UTC
Labels: duplicate

**Comment by someguynamedphil** [comment] 2017-07-05 16:57
HI - where is this issue duplicated?

**Comment by Dillon-Brown** [comment] 2017-07-06 08:12
@someguynamedphil This is a duplicate of issue #3731 and a few others that I have linked in that issue. I'ts currently being treated as a high priority and a fix has been provided here: #3838

**Comment by someguynamedphil** [comment] 2017-07-06 09:42
Thanks

I’ve found the fix and installed the hot fix - it works!

Thanks!

phil

- - - - - - - - - - -
Phil Emery, creative director
  
phil@focusedcreative.com  
(416) 534-4273

Focused Creative
Big Idea Marketing & Strategic Graphic Design

https://focusedcreative.com
LinkedIn: https:/focusedcreative.com/linkedin/
================================================
