### ISSUE TITLE
use correct login image on install.php 

### ISSUE THREAD

**Issue by mcarpenterjr** [salesagility/SuiteCRM#7547] opened 2019-07-10 18:02 UTC
Install.php references the image sugrcrm_login.png which does not exist. The correct image should be suitecrm_login.php.

This was fixed in #249 but seems to have regressed.

**Comment by cameronblaikie** [comment] 2019-07-11 14:01
Closing as this is a duplicate of this issue ()

**Comment by mcarpenterjr** [comment] 2019-07-13 13:44
Someone should take a look at this, at some point, and decide if this should also be refactored to include just one suite logo or two.

**Closed** 2019-07-31 16:49 UTC
Labels: Fix Proposed, Low Priority, Resolved: Next Release, bug
