### ISSUE TITLE
Cannot select and add existing contacts to an opportunity - SuiteCRM 7.10.30

### ISSUE THREAD

**Issue by TheSmallFry** [salesagility/SuiteCRM#9162] opened 2021-06-02 10:57 UTC
#### Issue
When adding existing contacts to an opportunity using select the system does not allow the selection to be added to the opportunity.

#### Expected Behavior
Normally when you select an existing contact to add to an opportunity the system allows this.

#### Actual Behavior
The selection of an existing contact to add to an opportunity does not work.

#### Possible Fix
Unknown

#### Steps to Reproduce
1. Open Opportunity
2. Go to contact tab and select contact
3. Select contact
4. Choose contacts to add - cannot get it to add

#### Context
Trying to add existing contacts to opportunity. Seems also to be issue adding opportunity to contacts.

#### Your Environment

* SuiteCRM Version used: 7.10.30 (was working on 7.10.27
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 90.0.4430.212
* Environment name and version (e.g. MySQL, PHP 7): 
* Operating System and version (e.g Ubuntu 16.04):

**Comment by gody01** [comment] 2021-06-02 11:23
Can confirm on 7.11.19 (working on 7.11.18).

It seems, that all popup select are broken, if search is performed (You can select first displayed contacts...).

Steps to reporduce:
* Select (pop up windows opens) either subpanel or in Meetigns related object
* Perform search on Last name for excample
* Click on result returns error in JS console:

Uncaught SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data
    send_back http://scrm.tem.si/include/javascript/popup_helper.js?v=EnIzqDxP4bnjVwgTG1Bcog:43
    onclick http://scrm.tem.si/index.php:1

**Comment by gody01** [comment] 2021-06-08 07:19
Seems to be duplicate of: #9106

**Comment by johnM2401** [comment] 2021-06-08 08:47
Hey @TheSmallFry 

I've given this a try in the most recent versions.
(Both 7.11.20 and 7.10.31)
And I'm not able to replicate

Would you be able to try this again in these versions, and let us know if you're still able to replicate?

Thanks!

**Comment by gody01** [comment] 2021-06-08 09:10
It seems to work on: 
7.11.20

**Comment by Mac-Rae** [comment] 2021-11-30 14:13
Closed as it appears to no longer be an issue

**Closed by Mac-Rae** 2021-11-30 14:13 UTC
Labels: Type:Bug, Status:Requires Updates, Area: Module
