### ISSUE TITLE
AOR Report- Date parameter doesn't work with any value of type 'Period'

### ISSUE THREAD

**Issue by ChangezKhan** [salesagility/SuiteCRM#3592] opened 2017-05-25 08:54 UTC
#### Issue

AOR Report- Date parameter doesn't work with any value of type 'Period'

#### Expected Behavior

Reports with a date parameter should display results 

#### Actual Behavior

Report returns empty and getting fatal errors in log 

    05/25/17 14:11:20 [2516][1][FATAL]  Query Failed:SELECT count(*) c FROM (
    SELECT [leads].do_not_call AS N'Do_Not_Call0', 
    [leads].first_name AS N'First_Name1', [leads].last_name AS N'Last_Name2', 
    [leads].id AS N'leads_id' 
    FROM [leads]  WHERE ([leads].date_entered BETWEEN "2017-05-24 00:00:00" AND "2017-05-25 14:11:20") 
    AND  leads.deleted = 0 ) as n::: 
    [Microsoft][SQL Server Native Client 10.0][SQL Server]Invalid column name '2017-05-24 00:00:00'.
    [Microsoft][SQL Server Native Client 10.0][SQL Server]Invalid column name '2017-05-25 14:11:20'.
    
    05/25/17 14:11:20 [2516][1][FATAL]   Query Failed:DECLARE @topCount INT SET @topCount = 20 
    SELECT TOP (@topCount)  [leads].do_not_call AS N'Do_Not_Call0', 
    [leads].first_name AS N'First_Name1', 
    [leads].last_name AS N'Last_Name2', [leads].id AS N'leads_id' FROM [leads]  
    WHERE (  [leads].date_entered BETWEEN "2017-05-24 00:00:00" AND "2017-05-25 14:11:20" ) 
    AND  leads.deleted = 0 ::: 
    [Microsoft][SQL Server Native Client 10.0][SQL Server]Invalid column name '2017-05-24 00:00:00'.
    [Microsoft][SQL Server Native Client 10.0][SQL Server]Invalid column name '2017-05-25 14:11:20'.

#### Possible Fix

Replace `"` (double quotes) with `'` (single quotes)

#### Steps to Reproduce

1. Create a report with a date parameter condition
2. Select `Period` as type and choose any value
3. Empty report is returned

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): NA
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.3, MSSQL Server 2008
* Operating System and version (e.g Ubuntu 16.04): Windows 7

**Comment by Mausino** [comment] 2019-03-18 11:01
@Dillon-Brown this is big issue.. because if paralyses all report on period base. :( and solution we have here more as 3 month. It should be in next milestone 7.11.3 👍

**Comment by willrennie** [comment] 2019-03-19 10:38
Confirmed as working in MSSQL. Which this seems to be specific to. There is still an issue with 'Yesterday' returning records when it should not but there is an issue and fix for this already. @Dillon-Brown  would be good if you can link this for reference.

**Closed** 2019-03-28 16:52 UTC
Labels: Medium Priority, Resolved: Next Release, bug
