### ISSUE TITLE
Spots Graphics on Home Dashboard Problem - RC 2

### ISSUE THREAD

**Issue by gokhanerdogdu** [salesagility/SuiteCRM#1809] opened 2016-07-28 13:03 UTC
#### Issue
In RC 2, I created a simple chart for opportunity. I would like to show this chart on homepage. I added Spots and selected the chart I created, it was added, but the layout is not correct.

#### Expected Behavior
The spots layout should fit to the layout, but not fitting.

#### Environment

SuiteCRM Version used: RC 2
Browser name and version (Chrome Version 52.0.2743.82 (64-bit)):
Environment name and version (
![2016-07-28 15_47_38-spots](https://cloud.githubusercontent.com/assets/20369981/17213364/c84564a6-54dc-11e6-8f29-e5770cb838f6.png)
MySQL, PHP 5.6):

**Comment by shogunpol** [comment] 2016-09-21 08:19
I tested the issue on recent version of SuiteCRM(7.7.4), and it not appear.
@gokhanerdogdu  , can you confirm the issue is not appear in recent version of SuiteCRM, and if yes can you close an issue?
Thanks for contribution.

**Comment by gokhanerdogdu** [comment] 2016-09-22 08:59
Now, there is different problem. Below is the screenshot.
![2016-09-22 11_56_31-homepage-spots](https://cloud.githubusercontent.com/assets/20369981/18742282/ff9b5e50-80bb-11e6-8a30-179e8370a021.png)

**Comment by ijdavie** [comment] 2016-09-22 09:48
I will close this as this relates to issue #2278. it appears that this issue has been fixed which has created a new one.

**Closed by ijdavie** 2016-09-22 09:48 UTC
Labels: bug, Pending Input
