### ISSUE TITLE
Editing via Dashlets - Wird behaviour of CANCEL function

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#893] opened 2016-01-28 14:58 UTC
If are you editing the some record via dashlets, please look you on this:

If you edit the record and you push SAVE button, it takes you back on Dashlets dashboard.
But if you use the CANCEL button, it takes you to Listview of Module which you edited.

Why it can't  take you back to Dashlets dashboard ? as it is now for SAVE function.

**Comment by Mausino** [comment] 2016-03-03 09:23
duplicated of my older issue #698

**Comment by paulgodley** [comment] 2016-03-03 09:40
Hi @JimMackin can you please close bug #698 as this is a duplicate of this bug.  @Mausino, thank you for pointing this out!

**Closed** 2016-03-07 19:39 UTC
Labels: bug, fix proposed
