### ISSUE TITLE
Getting error on visiting notification after creating call/meeting

### ISSUE THREAD

**Issue by jameswill** [salesagility/SuiteCRM#5741] opened 2018-04-18 07:30 UTC
HI,

I have fresh Installed Suite CRM 7.10.4 on my Linux server with PHP 5.5.37 and MySQL 5.5. I am getting error "Call to a member function get_summary_text() on a non-object => /{Path to Suitecrm}/include/MVC/View/SugarView.php [line] => 1615"[/b] on visiting notification after creating any call or meeting.

**Steps to reproduce:**
1. Login to admin panel and create Call/meeting and set pop up for notification.
2. when pop up appears click on "Cancel", it will generate notification icon on"1"
3. click on notification icon to visit already created call/meeting

**Also, this is happening only when I logged in as a admin user and not any other user.**

Can Anyone help me out with this? Is this a bug or am I missing something ?

**Comment by PedroErnst** [comment] 2018-04-18 08:49
@jameswill 

Thanks for reporting this.

It seems your PHP version is not compatible with SuiteCRM 7.10.x, it should be PHP >= 5.5.9 as per [the compatibility matrix](https://docs.suitecrm.com/admin/compatibility-matrix/)

Not saying this is the cause of the issue, there might still be a bug, but if you have the possibility to upgrade your [PHP version](http://php.net/supported-versions.php) and see if the behavior persists that would be helpful.

**Comment by jameswill** [comment] 2018-04-18 10:51
Minimum Requirement is 5.5.9 and my PHP version was 5.5.37 which is greater than 5.5.9

However I have also tested on PHP version 5.6.30 and getting same issue.

**Comment by PedroErnst** [comment] 2018-04-18 11:01
@jameswill 

Yes my bad, got the versions mixed up!

**Comment by PedroErnst** [comment] 2018-05-08 14:03
Hi again @jameswill , had the time to look into this. This particular issue is already fixed in #5563, which is merged into the 7.8.x hotfix branch and will be merged up into 7.10.x for the next maintenance patch.

**Comment by jameswill** [comment] 2018-05-10 11:32
Hi,

Is there any ETA for next maintenance release in 7.10.x ?

**Comment by Dillon-Brown** [comment] 2018-06-02 00:43
Resolved in v7.10.5

**Closed by Dillon-Brown** 2018-06-02 00:43 UTC
Labels: Resolved: Next Release, bug, category:module
