### ISSUE TITLE
Action 'Email PDF' does not work (7.9.1)

### ISSUE THREAD

**Issue by likhobory** [salesagility/SuiteCRM#3739] opened 2017-06-17 16:56 UTC
Issue
Subj.

Steps to Reproduce

1.Create some PDF template for invoice or quote
2.Go to invoices  / quotes and select action "Email PDF"

    SuiteCRM Version used: 7.9.1 (or 7.9.0 from demo)
    Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 54 / Edge
    Environment name and version (e.g. MySQL, PHP 7): PHP 5.5
    Operating System and version (e.g Ubuntu 16.04): Win10

**Comment by ChangezKhan** [comment] 2017-06-17 20:25
Kindly use the template and explain issue very clearly. If possible, with screenshots.

**Comment by likhobory** [comment] 2017-06-18 07:26
1/ Open PDF templates module and create one for quote for example.
2/ Open quotes module, open  some quote  and select action "Email PDF" in Detail view.

In SuiteCRM 7.8 you will see the same picture (works with any theme):

![default](https://user-images.githubusercontent.com/5983672/27258905-3dfb8c8e-540f-11e7-8e2e-2da2b5a0099b.png)

In SuiteCRM 7.9.0/7.9.1 you will see the same result:

![default](https://user-images.githubusercontent.com/5983672/27258933-462e90f8-5410-11e7-93ee-78df069934f6.png)

**Comment by meierwitt** [comment] 2017-06-18 17:35
Exactly the same here, worked with 7.8.x, stoped working with 7.9.0 and 7.9.1.

SuiteCRM Version used: 7.9.0 and 7.9.1
Browser name and version Chromium Version 58.0.3029.110 Built on Ubuntu , running on LinuxMint 18 (64-bit) and firefox 54.0 (64 bit) on Linux
Environment name and version Linux 64 bit, Apache 2.0, PHP 7.0.18, MySQL 5.0.12
Operating System and version Linux Mint (Client) Ubuntu 16.04 (Server)

**Comment by Dillon-Brown** [comment] 2017-06-19 09:29
Duplicate of #3654. This has been raised as a high priority.

**Closed by Dillon-Brown** 2017-06-19 09:29 UTC
Labels: duplicate
