### ISSUE TITLE
Products save without required fields

### ISSUE THREAD

**Issue by duncanf95** [salesagility/SuiteCRM#8660] opened 2020-04-13 15:10 UTC
#### Issue
products save without required fields

#### Expected Behavior
Without the required fields filled the product should not save

#### Actual Behavior
the product saves

#### Possible Fix
on line 74 of EditViewHeader.tpl the line ```form_id="$form_id"``` was removed from the save button, I don't know if this was to fix another issue elsewhere but adding it makes the validation work again.

#### Steps to Reproduce
Go to create new product
don't fill in any info
hit save
product saves

#### Your Environment

* SuiteCRM Version used: 7.10.25
* Browser name and version (e.g. Chrome Version 64 bit):
* Environment name and versionMySQL, PHP 7.2:
* Operating System and version Ubuntu 18.04:

**Comment by mattlorimer** [comment] 2020-04-13 15:32
this looks like a duplicate of #8489

**Closed** 2020-04-20 10:55 UTC
Labels: Type:Duplicate
