### ISSUE TITLE
Reports - Custom Modules and Custom Fields and Order

### ISSUE THREAD

**Issue by sieberta** [salesagility/SuiteCRM#2229] opened 2016-09-14 19:46 UTC
#### Issue
Report query fails when it is a custom module as the base module, related to a non-custom module custom field, if not in the right order.

I have a custom module called milestones, and it has a relationship to projects.  The report works fine, until a custom field within projects is added to the field list.  Even then, it works fine as long as the custom field is the last field in the list of fields.  If it is moved up, the query is built "wrong" and no results are provided.

I have no idea if it matters that this is a custom module, but it very clearly does matter that it is calling on a custom field within the projects module.

> Wed Sep 14 14:38:19 2016 [2393][1][FATAL]  Query Failed: SELECT `mlstn_milestones:mlstn_milestones_project_cstm`.aa_file_c AS 'AA_File0', `mlstn_milestones`.mlstn_date AS 'Date1', `mlstn_milestones`.account_id_c AS 'Other_Party2', `mlstn_milestones`.carrier AS 'Carrier3', `mlstn_milestones`.name AS 'Milestone4', `mlstn_milestones`.activity AS 'Activity5', `mlstn_milestones:mlstn_milestones_project`.name AS 'Project6', `mlstn_milestones:mlstn_milestones_project`.assigned_user_id AS 'Project_Manager7', `mlstn_milestones`.created_by AS 'Completed_By8', `mlstn_milestones`.result AS 'Result9', `mlstn_milestones_cstm`.action_required_c AS 'Action_Required10', `mlstn_milestones`.id AS mlstn_milestones_id FROM `mlstn_milestones` LEFT JOIN mlstn_milestones_project_c `mlstn_milestones|mlstn_milestones:mlstn_milestones_project` ON `mlstn_milestones`.id=`mlstn_milestones|mlstn_milestones:mlstn_milestones_project`.mlstn_milestones_projectmlstn_milestones_idb AND `mlstn_milestones|mlstn_milestones:mlstn_milestones_project`.deleted=0
> 
> LEFT JOIN project `mlstn_milestones:mlstn_milestones_project` ON `mlstn_milestones:mlstn_milestones_project`.id=`mlstn_milestones|mlstn_milestones:mlstn_milestones_project`.mlstn_milestones_projectproject_ida AND `mlstn_milestones:mlstn_milestones_project`.deleted=0
> LEFT JOIN `mlstn_milestones_project_cstm` `mlstn_milestones:mlstn_milestones_project_cstm` ON `mlstn_milestones:mlstn_milestones_project`.id = `mlstn_milestones:mlstn_milestones_project_cstm`.id_c LEFT JOIN `mlstn_milestones_cstm` `mlstn_milestones_cstm` ON `mlstn_milestones`.id = `mlstn_milestones_cstm`.id_c  WHERE ( (  `mlstn_milestones`.mlstn_date BETWEEN "2016-09-05 00:00:00" AND "2016-09-12 00:00:00" AND (`mlstn_milestones`.activity = 'Record_Drawings' OR `mlstn_milestones`.activity = 'Transmittal_In' OR `mlstn_milestones`.activity = 'Transmittal_Out') ) OR `mlstn_milestones_cstm`.action_required_c = '1' ) AND  mlstn_milestones.deleted = 0  ORDER BY `mlstn_milestones`.mlstn_date DESC LIMIT 0,20: MySQL error 1146: Table 'aeng_production.mlstn_milestones_project_cstm' doesn't exist
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.
> Wed Sep 14 14:38:21 2016 [2413][1][ERROR] SugarBean.load_relationships, Null relationship name passed.

#### Expected Behavior
Report query would be successful regardless of the order of the fields.

#### Actual Behavior
Report query fails

#### Context
This is annoying, but a relatively minor bug in my oppinion since we can put the custom field at the end of the list.

#### Your Environment
* SuiteCRM Version used: 7.7.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): CentOS

**Comment by gunnicom** [comment] 2016-09-15 08:00
Maybe related or duplicate of: https://github.com/salesagility/SuiteCRM/issues/1635

**Comment by ijdavie** [comment] 2016-09-15 10:36
@gunnicom This does look like the same issue. 
@sieberta, I will mark this as a duplicate

**Closed by ijdavie** 2016-09-15 10:36 UTC

**Comment by sieberta** [comment] 2016-09-15 10:49
I agree, same issue.  I moved my custom field no longer to the end of the list, but also not before any non-custom fields and no errors.  The custom module portion, I believe, is irrelevant.  That said, in my experience it seems to only be an issue if the custom field is from a related module, not from the report module.

Thanks!
sieberta
