### ISSUE TITLE
Escaped quotes in translated strings breaks JavaScript scripts in SuiteCRM 7.9.5

### ISSUE THREAD

**Issue by Sami-Radi** [salesagility/SuiteCRM#4261] opened 2017-09-15 09:39 UTC
#### Issue
Using French SuiteCRM translation, i found out that SuiteCRM JavaScript scripts do not work because of the escaped quotes in the translation files which are unescaped when put into the scripts.

#### Expected Behavior
It should work with the current translation files. Here's the answer from the translation team on crowdin (to whom i sumbitted a solution replacing all the escaped quotes with typographic - ASCII - apostrophe):

> Hi, escaped symbols need to work even if present on translation. The solution should not be editing the translation but fixing the code to accept them as on any other software. Please create an issue for this on https://github.com/salesagility/SuiteCRM

#### Actual Behavior
Multiple scripts broken.

#### Possible Fix
Replace escaped quotes with typographic - ASCII - apostrophe in the backend logic code when reading the translation arrays.

#### Steps to Reproduce
Installing the french translation, opening the console, monkey clicking on the UI => shows red...

#### Context
Normal daily use.

#### Your Environment
* SuiteCRM Version used: 7.9.5
* Browser name and version : Chrome (current), Firefox (current)
* Environment name and version : MySQL 5.5, Apache 2.5, PHP 5.6
* Operating System and version : Ubuntu 14.0.4

**Comment by pgorod** [comment] 2017-09-15 10:27
I believe this is a duplicate of #4211. That issue has the advantage of providing a specific place to fix.

@Sami-Radi if you can please check that one, and see if you can provide additional info. You say "Multiple scripts broken", but that way we don't really know where to look. If you can specify any other broken script, that would be better.

Maybe add that information to #4211 and close this one?

**Comment by Dillon-Brown** [comment] 2017-09-15 11:58
Also a duplicate of #3056.

**Closed by Dillon-Brown** 2017-09-15 11:58 UTC
Labels: duplicate
