### ISSUE TITLE
Missing add product menu while using PL language - 7.10.1

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#5424] opened 2018-03-07 11:22 UTC
#### Issue
While using PL language i cannot see product menu, but if i change language to eng while login menu is right on place.

PL
![image](https://user-images.githubusercontent.com/30261902/37089795-19f0024a-2202-11e8-8454-edd5cfe9b4bb.png)

ENG
![image](https://user-images.githubusercontent.com/30261902/37089826-3641d310-2202-11e8-8195-7562205ecdc6.png)

#### Your Environment
SuiteCRM Version used: 7.10.1
Browser name and version (e.g. Chrome 64.0.3282.186
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version CentOS

**Comment by ErMaqui** [comment] 2018-03-07 16:24
This error appears on workflow and report module on ES lang.

**Comment by pgorod** [comment] 2018-03-07 19:17
I believe the code that changes this is in [this commit](https://github.com/salesagility/SuiteCRM/commit/44e063ae4fff366629148b790daa014118a00701#diff-f536a67e3b418efc1796ff40f84a9176), search for `data-action-name`

The way the label is used is different.

The problem seems to be for any language pack, any module.

**Comment by topesantos** [comment] 2018-03-08 10:33
I have the same problem with all my custom modules. I use pt_PT lang.

**Comment by horus68** [comment] 2018-03-08 16:55
This is a confirmed bug for all languages. Forum users from different languages share the same problem but not all have problems in the same modules!
See forum: https://suitecrm.com/suitecrm/forum/languages/18130-v7-10-1-context-menu-does-not-appear-for-non-english-languages

For me some modules are working (PHP 7.0.11) after a:
- Rebuild / Rebuild Minified JS Files
- Rebuild / Quick Repair and Rebuild

**Working:**
Accounts, Contacts, Opportunities, Leads, Documents, Calendar, Email, Quotes, Spots
See contacts module for pt_PT language:
![menu_contacts_ok](https://user-images.githubusercontent.com/3055443/37164130-67af69fe-22f1-11e8-9274-8a249f6b9939.png)


**Not working:**
Cases, Bugs, Projects, Calls, Invoices, Contracts, Meetings, Tasks, Prospects, Events, Notes
See notes module for pt_PT language:
![menu_notes_ko](https://user-images.githubusercontent.com/3055443/37164168-7923b7bc-22f1-11e8-8b19-912b11063a5b.png)

**Comment by SNDK77** [comment] 2018-03-08 18:29
Same here, working in spanish.
Some modules works, another not.
Anoying and disturbing bug for workers.

**Comment by manuagui** [comment] 2018-03-08 19:40
Same issue with 7.8.16 working in Spanish.

**Comment by horus68** [comment] 2018-03-09 11:45
I see now this is being looked by @Dillon-Brown.
This should be considered a major issue to require all @salesagility staff to be involved some hours at same time in order to find a quick solution and to release a new version for 7.10 and 7.8 (didn't test 7.9).

I'm also requesting for those more active non-english users to get their hands on this today. I'm not a coder but already sent an email to SA to help testing any solution they can provide. 
So please can you all get a look today @pgorod @pribeiro42 @likhobory @urdhvatech @bmwtourer @SoapJson @Mausino @ghermans @Abuelodelanada @gunnicom @a277913835 @maladrill

**Comment by Dillon-Brown** [comment] 2018-03-09 11:54
@horus68 I've just put a fix up now. We'll look at getting this tested and merged ASAP. Thanks.

**Comment by Mausino** [comment] 2018-03-09 12:06
@horus68  i checked on my slovak version 7.9.14 and this issue doesn't appear

**Comment by likhobory** [comment] 2018-03-09 15:52
Yes, with PR #5449 works as expected, tested with Russian language.

**Comment by Mausino** [comment] 2018-03-12 14:54
@AdminPL we have this issue only on custom modules when we yesterday upgraded to version 7.9.15.. before was everything ok

**Comment by ghermans** [comment] 2018-03-12 15:13
Is this issue still alive after @daniel-samson's fix?

**Comment by Dillon-Brown** [comment] 2018-03-12 15:19
@ghermans Issue should be fixed with now merged #5449 and will be included in the next release.

**Closed** 2018-03-15 14:08 UTC
Labels: Fix Proposed, High Priority, Resolved: Next Release, bug
