### ISSUE TITLE
AOP emails empty messages when cases are updated and no templates are selected

### ISSUE THREAD

**Issue by ChristopherPH** [salesagility/SuiteCRM#576] opened 2015-10-16 22:55 UTC
When AOP is turned on, and no templates are selected, users will get emailed an empty email on case creation and case updates.

The variable $email_template is being initialized to a valid value then checked for null/empty later on. If $aop_config['contact_email_template_id'] or $aop_config['user_email_template_id'] is not set, $email_template holds the original EmailTemplate() object, which is a valid object, and then sends the email which is blank. The check to see if $email_template is valid and email sending code should be moved into the if statement directly above it.

modules/AOP_Case_Updates/AOP_Case_Updates.php:

```
$email_template = new EmailTemplate();
...
if($aop_config['contact_email_template_id']){  
  $email_template = $email_template->retrieve($aop_config['contact_email_template_id']);
  $signature = $current_user->getDefaultSignature();
}
if($email_template) {
  foreach ($this->getContacts() as $contact) {
    $GLOBALS['log']->info("AOPCaseUpdates: Calling send email");
    $emails = array();
    $emails[] = $contact->emailAddress->getPrimaryAddress($contact);
    $res = $this->sendEmail($emails, $email_template, $signature, $this->case_id, $addDelimiter, $c
  }
}
```

**Comment by vladbar** [comment] 2015-10-19 10:49
Hello ChristopherPH,

thank you for raising this issue, but I was unable to reproduce this error. I've checked that Enable AOP was on and made sure that  New Case Auto-Reply Template option had a none option. 

On case creation I received: 
Administrator has assigned a Case to Support Group User.

On case update I received:
You've had an update to your case ... (# 52) on 10/19/2015 11:13:

I would like to ask you a few questions related to this issue:

- are you logged in as administrator or regular user;

- can you see any errors in your suitecrm.log;

- can you see any errors in your apache log file;

Thanks.

**Comment by ChristopherPH** [comment] 2015-10-20 17:24
Hello,

To answer your questions:

I am logged in as an administrator.
There were some email errors saying an invalid address but the logs are 
not available right now.
I can't see anything in the apache logs.

Also, for my AOP settings:
- AOP is turned on
- enable external portal is off
- dist method is single user
- dist user is administrator
- case status changes is empty
- support email from address/from name is blank
- every template is set to -none-

So I do not receive any case updates, but I do get the case creation 
notification via the inbound email setup.

-Chris

**Comment by afatac** [comment] 2017-03-22 02:57
I am using 7.8.2 and have the same issue of sending empty email message and subject to Contact even if the templates are not selected (None) in AOP. My issue is about closing case but found that this issue also happens to updating case. See my posting in the forum https://suitecrm.com/forum/suitecrm-7-0-discussion/6485-how-to-stop-close-cases-and-contact-gets-e-mail#45141

I also tested this issue on a newly installed 7.8.2 and got the same issue.

**Comment by jbrveen** [comment] 2017-05-12 13:47
I'm also having this issue at a 7.8.3 installation. Please look into this and resolve this.

**Closed** 2018-03-07 14:11 UTC
Labels: Fix Proposed, Medium Priority, Resolved: Next Release, bug
