### ISSUE TITLE
Tasks dashboard module not show Related To

### ISSUE THREAD

**Issue by ErMaqui** [salesagility/SuiteCRM#5415] opened 2018-03-06 15:20 UTC
#### Issue
On Dashboard, module Tasks doesn't show the Related to field on some rows.

The first row, show the related to without problems. But second rows and others, show only a space (&nbsp;) and the link to the account or module assigned to the task, and not the name.

#### Expected Behavior
Name of the related to field should be show correctly on all rows.

* SuiteCRM Version used: 7.10.1

**Comment by Dillon-Brown** [comment] 2018-03-07 10:17
Duplicate of #5330

**Closed by Dillon-Brown** 2018-03-07 10:17 UTC
Labels: duplicate
