### ISSUE TITLE
Email pagination buttons hidden

### ISSUE THREAD

**Issue by johnmccuk** [salesagility/SuiteCRM#1546] opened 2016-06-02 14:03 UTC
Email pagination buttons are hidden completely in the the Suite R theme and partially hidden in Suite 7.
`module=Emails&action=index`

This issue effects chrome (50.0.2661) firefox (44.0.2) and safari(9.1.1)

Version 7.6.4
Sugar Version 6.5.23 (Build 1061)
ubuntu 14.4
apache 2.2
php 5.5.34
mysql 5.5

**Comment by Mausino** [comment] 2016-06-02 20:34
@johnmccuk this i reported in #163

**Comment by willrennie** [comment] 2016-06-10 11:08
Duplicate of #163

**Closed by willrennie** 2016-06-10 11:08 UTC
