### ISSUE TITLE
Report Count Functionality is Broken 7.6.6 (and 7.7)

### ISSUE THREAD

**Issue by aarondglover** [salesagility/SuiteCRM#2005] opened 2016-08-22 10:24 UTC
#### Issue
After updating SuiteCRM to 7.6.6 the "COUNT" functionality in Reports is broken. Previous reports which correctly show the "Count" is broken.

![image](https://cloud.githubusercontent.com/assets/8821892/17851633/42bcbcf2-68a6-11e6-9a09-d77719865353.png)

![image](https://cloud.githubusercontent.com/assets/8821892/17851311/ab51a590-68a4-11e6-81c8-b7a156e824b3.png)

#### Expected Behavior
Count Should display correctly

#### Actual Behavior
The Record ID is displayed instead

#### Context
Many reports are now broken and essentially useless. I believe this should be of moderate to high priority.

#### Your Environment
* SuiteCRM Version used: SuiteCRM 7.6.6

This issue is also reported on the SuiteCRM forums: https://suitecrm.com/forum/installation-upgrade-help/10492-7-7-report-count-function-broken

**Comment by shogunpol** [comment] 2016-08-22 11:29
I been able replicate the issue, in SuiteCRM (version 7.7.1), the issue causing "count" field in "Function" drop-down. It appears there is a small difference to the user interface on your version compared to the latest, but the issue is still apparent. 

Thanks for raise this issue, we work on solution.

**Comment by aarondglover** [comment] 2016-08-23 15:28
Actually I just noticed looking at my previously posted image, the "Function" Drop Down Box is completely missing. The Function Drop Down box is appearing 99.9% of the time, but even when it displays, the result of the report is bad.

Here is an image demonstrating the visibility of the Drop Down List

![image](https://cloud.githubusercontent.com/assets/8821892/17898139/fd95bcf6-6999-11e6-91c9-7b4d8ca0d081.png)


Here is an image demonstrating the incorrect results

![image](https://cloud.githubusercontent.com/assets/8821892/17898089/d87cc84c-6999-11e6-8e61-8277001ab7e8.png)

**Comment by aarondglover** [comment] 2016-09-05 05:37
Is a bug fix expected to be released for v7.6.6 - I can't move to 7.7.x because I can't yet update my version of PHP which the newer version requires.

**Comment by aarondglover** [comment] 2016-09-07 12:59
aFTER upgrading to 7.7.4 this is no longer an issue. Not sure what version it was fixed in as none of the release notes seem to address this issue.

**Comment by ijdavie** [comment] 2016-09-22 10:32
Thanks for letting us know that this has been fixed. This could have been fixed within another issue. 
I will close this issue.

**Closed by ijdavie** 2016-09-22 10:32 UTC
Labels: bug
