### ISSUE TITLE
Deleted favorite records still appear in menu 

### ISSUE THREAD

**Issue by lakomaa** [salesagility/SuiteCRM#826] opened 2016-01-04 14:51 UTC
Favorite records that was deteted still appear in menu but without name. There is only icon of the module in which record was created and the edit icon. 

![1](https://cloud.githubusercontent.com/assets/16476017/12092035/04b5b050-b2fb-11e5-9b82-c595c7ebf446.jpg)

**Comment by CaptainChainsaw** [comment] 2016-01-26 10:54
I've tried to reproduce this by favouriting a contact and also a project.  Both of these were successfully added and removed from the list of favourites.  The module and edit icons were also removed.  This may already have been fixed.

**Comment by CaptainChainsaw** [comment] 2016-01-26 11:30
I can reproduce this when deleting the record, I'll have a look.

**Comment by lakomaa** [comment] 2016-01-26 11:54
Exactly - I meant deleting a record, not the unchecking that record is Favorite. 
Thanks for Your answear.

**Comment by CaptainChainsaw** [comment] 2016-01-26 13:33
No problem.  This also affects recently viewed items.  It will show the record id instead and the record has been set to deleted.

**Comment by CaptainChainsaw** [comment] 2016-01-27 17:35
I'm looking into the issue with the recently viewed items.

**Comment by CaptainChainsaw** [comment] 2016-01-28 14:10
In relation to the recently viewed items issue - in the push method in BreadCrumbStack.php I set `$this->stack=[];` to clear the array, I expected that when I commented it out the array would populate again.  It didn't but I've not been able to reproduce this issue since.  It may have been an issue with my instance, so not committing any further changes as currently it seems unnecessary.  The reported issue with the favourites should be working when the fix is merged in.

If the recently viewed items issue does appear to be a problem then one possible solution would be this:

> BreadCrumbStack.php
in getBreadCrumbList():

     /*
      *  only show records that have an item_summary value
      */
       $breadcrumbs=array();
       foreach($s as $item){
           if(isset($item['item_summary']) && !empty($item['item_summary'])){
               $breadcrumbs[]=$item;
           }
       }
       return $breadcrumbs;
     /*
      * end
      */

**Comment by CaptainChainsaw** [comment] 2016-02-25 14:37
Deleting the recently viewed items works for me on my hotfix branch.

**Comment by lakomaa** [comment] 2016-03-08 13:05
We have applied Your fixes and all of them work fine. Many thanks for help.

**Comment by CaptainChainsaw** [comment] 2016-03-28 13:33
@lakomaa you're welcome.  I've submitted a pull request for this so hopefully that will be merged in at some point.

**Comment by pedroresende** [comment] 2016-07-02 20:51
Any idea when will this be fixed/merged ?

**Closed** 2016-12-01 14:25 UTC
Labels: bug, Fix Proposed, Medium Priority, Resolved: Next Release
