### ISSUE TITLE
AOR Date field showing time

### ISSUE THREAD

**Issue by mdemaree99** [salesagility/SuiteCRM#2157] opened 2016-09-07 15:02 UTC
Could not send comment to person who rejected issue.
Please review Issue #2084 

I have added more details to show that Date field in AOR reports is showing time.
Item was closed thinking I was referring to a DateTime field.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by ijdavie** [comment] 2016-09-19 11:04
This appears to be a duplicate of issue #1307, As that issue is older I will close this issue.

**Closed by ijdavie** 2016-09-19 11:04 UTC
Labels: bug, Medium Priority
