### ISSUE TITLE
Role with view = owner doesn't show any records

### ISSUE THREAD

**Issue by ebogaard** [salesagility/SuiteCRM#3354] opened 2017-04-03 21:09 UTC
#### Issue
There seems to be a problem with Roles where listview is set to 'Owner'.
Example: we have a role where Leads listview is set to Owner. When such a role is applied to a User and this user creates a Lead, or a Lead is assigned to this user, the User can't see this Lead. Moreover: the user can't see any Leads at all, even though multiple are assigned to this User.

When removing this role for the user, or when removing the listview=owner setting, the role seems to be working fine. For example, when I keep editing on owner-only, I can only edit those that are assigned to the user.

#### Expected Behavior
When a role is set to "view = owner" and applied to a user, this user should see all records of that module assigned to him/her.

#### Actual Behavior
When a role is set to "view = owner" and applied to a user, this user doesn't see any records of that module.

#### Possible Fix

None known.
More information when Suite is set to debug:

`
Wed Mar 29 09:54:35 2017 [10088][17dcda44-64d2-827e-9eef-58db5f3dcbb9][DEBUG] Retrieve Lead : SELECT leads.*,leads_cstm.* FROM leads  LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c  WHERE leads.id = '[SELECT_ID_LIST]' AND leads.deleted=0
Wed Mar 29 09:54:35 2017 [10088][17dcda44-64d2-827e-9eef-58db5f3dcbb9][DEBUG] Limit Query:SELECT leads.*,leads_cstm.* FROM leads  LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c  WHERE leads.id = '[SELECT_ID_LIST]' AND leads.deleted=0 Start: 0 count: 1
Wed Mar 29 09:54:35 2017 [10088][17dcda44-64d2-827e-9eef-58db5f3dcbb9][INFO] Query:SELECT leads.*,leads_cstm.* FROM leads  LEFT JOIN leads_cstm ON leads.id = leads_cstm.id_c  WHERE leads.id = '[SELECT_ID_LIST]' AND leads.deleted=0 LIMIT 0,1
`

 What strikes me, is the "WHERE leads.id = '[SELECT_ID_LIST]'". That looks to me like some variable isn't filled in properly.

#### Steps to Reproduce

1. Create role for Leads (for example) module with view = owner
2. Apply to user and assign some Leads to this user.
3. Login as this user and see that no Leads are visible.
4. Set view = not set, logout/login as this user and again see all Leads.
5. Set edit = owner and see that you can edit only those Leads assigned to this user (so roles does work in some way, just not for view=owner).

#### Context

Seems to me this is a high priority bug, as it greatly cripples the roles functionality.

#### Your Environment

* SuiteCRM Version used: 7.8.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome and Firefox
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1, PHP 5.6, httpd 2.4
* Operating System and version (e.g Ubuntu 16.04): Centos 7

**Comment by Dillon-Brown** [comment] 2017-04-11 14:31
@ebogaard  I am to be unable to replicate this issue. Do you think you could clarify further or provide screenshots?

With list = owner this is what i'm getting:
![screenshot from 2017-04-11 15-22-40](https://cloud.githubusercontent.com/assets/26431166/24914322/d76a87c2-1ecb-11e7-9146-e8bd04bfa976.png)

**Comment by ebogaard** [comment] 2017-04-11 14:39
@Dillon-Brown last night I found some time to further investigate this.

It seems this only happens with an instance that was upgraded from SugarCRM CE 6.5.24 to 7.6 to 7.8.1, not when using a 'fresh' 7.8.1 install.

I'm not sure why, as the files from both instances (upgraded and fresh) seem to be identical. But I might be missing something.

Hope this helps. Screenshot's won't add much, as I could only show you one screenshot where you can see the Lead which is assigned to user X, and a screenshot when user X is logged in with the role active, who then doesn't see the assigned lead.

**Comment by Dillon-Brown** [comment] 2017-04-11 14:48
Looks like this issue is a duplicate of #3134 which has been fixed #3117 in 7.8.2. Hope this helps :).

**Closed by Dillon-Brown** 2017-04-11 14:48 UTC
Labels: duplicate
