### ISSUE TITLE
Not all variables in Emails processed

### ISSUE THREAD

**Issue by ebogaard** [salesagility/SuiteCRM#6462] opened 2018-11-01 10:07 UTC
#### Issue
When sending an e-mail, you can use variables.
For example, when sending to a Contact, you can select a Contact and then use variables like "$contact_last_name", which will be filled in with thew selected Contact.

In 7.8 (last version we used before upgrading to 7.10), there were also variables like:
* $user_last_name, which was filled in with the last name of the currently logged in User
* $contact_user_last_name, which was filled in with the last name of the Assigned User of the selected Contact/Lead/Target

In 7.10.9, the following doesn't work anymore:
* All "$user_xxx"-variables aren't filled in anymore
* "$contact_user_xxx" only works when associating to a Contact, not to a Lead or Target

Both are really necessary when working properly with Templates and signatures.

#### Expected Behavior
The mentioned variables need to be replaced with the proper information from the logged in user or assigned user.

#### Actual Behavior

See Issue description. No errors in te log files.

#### Steps to Reproduce

1. Create a new e-mail.
2. Associate this e-mail to a Lead (which has an assigned user)
3. Make sure you have your last name filled in in your profile.
4. Use the following variables in the e-mail: $user_last_name and $contact_user_last_name
5. Send the mail
6. See that the variables are still variables, not filled in with respectively your last name and the last name of the assigned user of the selected lead.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Newest Firefox and Chrome
* Environment name and version (e.g. MySQL, PHP 7): MariaDB 10.1 + PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Centos 7

**Comment by samus-aran** [comment] 2018-12-06 12:11
This is a duplicate of https://github.com/salesagility/SuiteCRM/issues/6535 But thank you for raising this.

**Closed by samus-aran** 2018-12-06 12:11 UTC
Labels: Emails:Templates, duplicate
