### ISSUE TITLE
7.11.3 version, Inbound email ,can't auto import to local crm db

### ISSUE THREAD

**Issue by cekowu** [salesagility/SuiteCRM#7179] opened 2019-04-11 08:19 UTC
#### Steps to Reproduce

1. config inbound email account 
2. select "Import Emails Automatically" to "Yes"
3. receive new email
4. the email don't import to local 

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mausino** [comment] 2019-04-11 11:26
I think that your issue is duplicate of #6866

**Closed** 2019-04-25 10:04 UTC
Labels: duplicate
