### ISSUE TITLE
My Pipeline Dashlet drilldown fails when sales stage have a different Display Label and Item Name

### ISSUE THREAD

**Issue by Go2ClassPoorYorick** [salesagility/SuiteCRM#4984] opened 2018-01-18 17:00 UTC
#### Issue
If a user has their "Sales Stage" objects have different Display Labels than Item Names, the My Pipeline drill-down will fail. 

This appears to be because the filter that clicking on the "My Pipeline" links will be created with a sales stage search that doesn't provide any results, as the sales-stage filter doesn't match anything.

#### Expected Behavior
Clicking the drill-down should apply a filter based on the hidden item name, rather than the displayed filter.

#### Actual Behavior
When using a sales stage of 90, but a display label of 90%, my sales stage drill-down filter discloses no results.

#### Possible Fix
It seems that making sure the Display Label and Item Name match fixes the filter, but I believe making it filter by Item name should result in the intended behavior.

#### Steps to Reproduce
1. Create a custom Sales Stage drop-down list. Use different Display labels than item names
2. Create a "My Pipeline" dashlet
3. Create an opportunity that has one of these mismatched fields
4. Attempt a drill through click from the home My Pipeline dashlet. It should not display any results, and the filter will show the display label.

#### Context
This is likely only a minor bug, as it has a simple fix, but it will likely confuse people, as the regular pipeline appears to work fine either way.

My team had used a display label of 90% for a 90, 80% for 80, etc, and it had completely broken the pipeline for our sales team other than for our "Won" field, which was won/won.

#### Your Environment

* SuiteCRM Version used: Version 7.9.5 Sugar Version 6.5.24 (Build 509)
* Browser name and version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 
I don't run the server, but i think these are relevant if this is important.
MySQL Version: 5.1.36 
PHP Version : 5.3.1  
* Operating System and version: Windows 8.1

**Comment by PedroErnst** [comment] 2018-01-19 09:15
Hello @Go2ClassPoorYorick 
Thanks for reporting this issue.

I followed your steps but didn't encounter the same issue.

Upon clicking on the custom label

![screenshot from 2018-01-19 09-11-09](https://user-images.githubusercontent.com/34056696/35143230-de58e40a-fcf8-11e7-9289-4b9f90790b9d.png)

It took me to the correct list view

![screenshot from 2018-01-19 09-11-19](https://user-images.githubusercontent.com/34056696/35143251-ef563668-fcf8-11e7-8b17-2834bf062d28.png)

With the underlying item name being used as the filter

![screenshot from 2018-01-19 09-11-28](https://user-images.githubusercontent.com/34056696/35143283-07b35a38-fcf9-11e7-891f-904a94cc96f2.png)

So I'm thinking possibly this has been fixed since SuiteCRM version 7.9.5?

We'll keep an eye out in any case if this problem comes up again.

PS: You might want to give the person running your server a friendly reminder that PHP 5.3 has been unsupported for over 3 years now.

**Comment by Go2ClassPoorYorick** [comment] 2018-01-19 15:11
Just some screenshots to better show what I was explaining
**With a percent sign:**
![image](https://user-images.githubusercontent.com/33301123/35156735-bb3abd84-fcff-11e7-9042-70b8d34cd159.png)
![image](https://user-images.githubusercontent.com/33301123/35156790-e4622562-fcff-11e7-9e8e-81da3c1e6625.png)
![image](https://user-images.githubusercontent.com/33301123/35157043-c6079b50-fd00-11e7-9f02-28fc80c232fb.png)
**Without the percent sign:**
![image](https://user-images.githubusercontent.com/33301123/35157074-df5d0e3c-fd00-11e7-9167-4203ee9ffc59.png)
![image](https://user-images.githubusercontent.com/33301123/35157091-ecfdd08a-fd00-11e7-96a7-1be4e1921656.png)
![image](https://user-images.githubusercontent.com/33301123/35157111-fee02c76-fd00-11e7-8416-25e3c9ffe84b.png)

As you can see, by removing the percent on the display tag, the filter works correctly.

**Comment by Go2ClassPoorYorick** [comment] 2018-01-19 15:16
@PedroErnst 
By any chance, did you happen to be using the team pipeline, not the "My Pipeline" chart?

**Comment by PedroErnst** [comment] 2018-01-19 15:20
@Go2ClassPoorYorick Yes absolutely, my bad, I did look at the wrong dashlet...

I can reproduce this now, and the fix shouldn't bee too complicated.

**Comment by Go2ClassPoorYorick** [comment] 2018-01-19 15:32
@PedroErnst 
Awesome, glad I'm not going insane!
I'll see about getting the PHP version updated... I didn't realize it was 9 years old!

**Comment by PedroErnst** [comment] 2018-01-19 16:01
@Go2ClassPoorYorick No, you're perfectly sane :+1: 

The PR is made for the 7.8.x branch because the bug needs to be fixed in that version as well. For the next release it will normally be merged into 7.9 as well.

I think the affected files are mostly identical for the two branches, but if you're looking to apply the patch yourself for version 7.9 you want to look at this commit d159f41764dd2b6158c990493a8f5ffa2d4396f7

**Closed** 2018-01-25 18:12 UTC
Labels: Fix Proposed, Low Priority, Resolved: Next Release, bug
