### ISSUE TITLE
Follow on from Bug #3925 duplicate attachments to email templates

### ISSUE THREAD

**Issue by KaKite** [salesagility/SuiteCRM#4645] opened 2017-12-08 20:05 UTC
This behaviour has become apparent after implementing the fix for Bug #3925.That issue has been closed, the behaviour now is different - hence the opening of this bug

#### Issue
When creating an email template with a single or more attachments and using that template as the base for an email communication, the recipient of the email will receive 2 of every attachment in the template. The email that is created from the template, prior to sending, appears to only have a single copy of each attachment

#### Expected Behavior
The recipient should receive a single copy of each attachment

#### Possible Fix
This behaviour has been produced as a side effect of the fix for Bug #3925 where NO attachments were being sent when an email was created from an email attachment

#### Steps to Reproduce
1. Implement the following fix for email templates with NO attachments https://github.com/salesagility/SuiteCRM/issues/3925
2. Create an email template with a single or more file attachments/Suite documents
3. Compose a new email using the template created earlier as the base
4. View the attachments section of your email - how many files are listed there
5. Send the email
6. Check how many attachments are received with the email

#### Context
As a work process/efficiency measure in my business, email templates are extremely important and sending multiple attachments of the same file just makes my business look un-professional, in fact ANYTHING that has to do with communications and my customers is of high value/importance. Not sure why sorting out the problems with emails/the email client aren't given a higher priority
HIGH PRIORITY to fix please

#### Your Environment
SuiteCRM 7.9.7 - have seen the previous bug, no attachments at all reported on v7.9.4 and up
Firefox Developer Edition 58.0b9 - 64 bit
Amazon Light Sail Bitnami stack
Ubuntu

**Comment by Mausino** [comment] 2017-12-12 00:04
We also have same problem... @kakite Great description of issue

**Comment by Mausino** [comment] 2017-12-12 16:58
I think that this issue has something similar with #3818 - same type of issue

@Dillon-Brown  @gymad  

please do you have some plan when will the problem with duplicate of attachment solved ? For example we look as losers if we still send to clients some attachment in email  and this is still duplicated in client inbox :(

**Closed** 2018-01-04 09:14 UTC
Labels: duplicate

**Comment by KaKite** [comment] 2018-01-04 20:19
Try the attached js (in the zip file) - this file was edited from the original EmailsComposeView.js file posted on Github (the one that created the double attachment) The fix is NOT upgrade safe

Rename/backup your existing in SuiteRootFolder/modules/Emails/include/ComposeView/EmailsComposeView.js
Copy the EmailsComposeView.js to the directory
If it doesn't work, may need an Admin -> JS repair

[EmailsComposeView.zip](https://github.com/salesagility/SuiteCRM/files/1604601/EmailsComposeView.zip)

**Comment by markcrobinson55** [comment] 2018-05-11 12:49
This did not appear to have any effect on my Installation of Version 7.10.4. Is there a way to troubleshoot your patch to see why?

**Comment by RiaanBez** [comment] 2020-11-02 09:06
This is still happening in Version 7.11.15
