### ISSUE TITLE
OAuth2Tokens not generated

### ISSUE THREAD

**Issue by dipenpatel235** [salesagility/SuiteCRM#5302] opened 2018-02-21 18:23 UTC
Error: File [modules/OAuth2Tokens/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.

#### Issue
Error: File [modules/OAuth2Tokens/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.
#### Expected Behavior
must be create OAuth2Tokens

#### Actual Behavior
when click on OAuth2 Tokens > create 
getting that error
#### Possible Fix
don't know

#### Steps to Reproduce
1. goto admin
2.click on  OAuth2 Clients and generate new
3.click on OAuth2 Tokens and get error as i have show

#### Context

don't know

medium
#### Your Environment
* SuiteCRM Version used:7.10.0
* Environment name and version : MySQL, PHP 7
* Operating System and version : Centos 7 64 bit

**Comment by Dillon-Brown** [comment] 2018-02-22 16:29
@dipenpatel235 This would be a duplicate of #5291. You are right that you shouldn't be getting this error however OAuth2 Tokens should be generated after you authenticate and not created here.

**Closed** 2018-02-22 16:29 UTC
Labels: duplicate
