### ISSUE TITLE
When editing an existing user you must always reenter (twice) the password

### ISSUE THREAD

**Issue by amariussi** [salesagility/SuiteCRM#6997] opened 2019-02-26 15:54 UTC
SuiteCRM version 7.11.2

#### Issue
When you edit any field of a User you are obliged to re-enter the password (twice) or else the modifications will not be saved.

#### Expected Behavior
The modifications to the User should be saved without having to re-enter the password.
The existing password should be modified only in case a new password is entered otherwise if the password field is empty the User should be saved preverving the existing password

#### Actual Behavior
When you edit any field of a User you are obliged to re-enter the password (twice) or else the modifications will not be saved.
When you click on Save a pop-up appears warning "Please enter your new password."

#### Steps to Reproduce

1. Admin -> Users
2. Edit any of the Users
3. Modify one field (not the password)
4. Click on Save

Result: the User is not saved until you go to the password tab and re-enter the password in both password fields (new and re-enter password)

#### Context

Medium priority. However it is very annoying, specially for new adopters of SuiteCRM and for Administrators (who may not know all Users's passwords!

#### Your Environment

* SuiteCRM Version used: 7.11.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome, latest version
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 7.1
* Operating System and version (e.g Ubuntu 16.04): Linux CentOS

**Comment by willrennie** [comment] 2019-03-01 17:04
Hi @amariussi I've tested this functionality within a fresh 7.11.2 install and I'm not experiencing the issue where the password entry is required on every save of the user. I can make modifications to the users' settings/fields without being prompted to re-enter the password. Is the password field on your CRM set to required or not? I assume this is an upgrade and not a fresh 7.11.2 install?

**Comment by amariussi** [comment] 2019-03-02 11:17
Hi @willrennie I will test it again more thoroughly. For the time being I tried first on an upgrade from 7.11.0 and then on a fresh install of 7.11.2
Please allow me a few days and I will come back with more info.

**Comment by amariussi** [comment] 2019-03-02 11:54
I tested it again on the same fresh install.
Each time the Admin user tries to modify some variable of any existing user I get a pop-up prompting for a new password (see image):
![2019-03-02_124109](https://user-images.githubusercontent.com/8026129/53681356-bfd50a00-3ce8-11e9-97e6-69831bdcdea0.jpg)

> Is the password field on your CRM set to required or not?
I am not sure I understand this question. I can't find any place where to set the password as a required field.
Here is a screenshot of the password management form:
![2019-03-02_124743](https://user-images.githubusercontent.com/8026129/53681419-b5674000-3ce9-11e9-9d7a-b598f3c00fb2.jpg)

Maybe you are referring o the password field definition in Studio. Here is a screenshotof the password field and you can see that it is not a required field:
![2019-03-02_125152](https://user-images.githubusercontent.com/8026129/53681456-30c8f180-3cea-11e9-84f2-d46ddbc0de5b.jpg)

I will try to install another test instance on another machine nd will report back.

**Comment by nelem** [comment] 2019-03-03 14:07
Confirmed in a fresh install of 7.11.1 and now upgraded to 7.11.2. When editing the user profile, the password is always assumed to have been changed in the edit - even when the password tab has not been displayed.

**Comment by apexred** [comment] 2019-03-06 20:12
Can confirm the behaviour on 7.11.2

When I change a setting in my profile, I have to go to Password tab and re-enter my password and then again to confirm.

**Comment by connorshea** [comment] 2019-04-02 20:29
Yep, I can confirm this bug also exists in 7.9.17. (I'm not sure if it existed in 7.9.4). It'd be great to have a fix for this, it's a problem for some of our users (you're not able to edit your own user).

![Screen Shot 2019-04-02 at 2 28 43 PM](https://user-images.githubusercontent.com/2977353/55433935-a9bea180-5553-11e9-8078-f69c07c4e444.png)

**Comment by connorshea** [comment] 2019-04-02 20:32
@willrennie one important detail for reproducing this bug: You need to have your browser (Chrome-specific issue, maybe?) store your user password, otherwise it won't happen. It will then autofill the "Current Password" field without the user knowing, which is what causes this issue.

![Screen Shot 2019-04-02 at 2 31 19 PM](https://user-images.githubusercontent.com/2977353/55434158-28b3da00-5554-11e9-92f5-1fa616c60ab5.png)

**Comment by apexred** [comment] 2019-04-02 20:43
Aha, if I delete the password, after modifying my profile, it saves without the password prompt....   I was today year's old when I learned this trick!

**Comment by connorshea** [comment] 2019-04-02 21:07
This file seems relevant: https://github.com/salesagility/SuiteCRM/blob/27e4e186b645b59dba48b72d0cb78ae045f8f375/jssource/src_files/modules/Users/PasswordRequirementBox.js

This bit in particular is important:

https://github.com/salesagility/SuiteCRM/blob/27e4e186b645b59dba48b72d0cb78ae045f8f375/jssource/src_files/modules/Users/PasswordRequirementBox.js#L55-L59

Which causes the `set_password` function to trigger if the value is set to `true`:

https://github.com/salesagility/SuiteCRM/blob/27e4e186b645b59dba48b72d0cb78ae045f8f375/jssource/src_files/modules/Users/PasswordRequirementBox.js#L61-L62

I guess we need to not set the value for `password_change` to `true` when the tab hasn't been / isn't currently displayed.

**Comment by connorshea** [comment] 2019-04-10 16:52
The change that fixed this for us was [changing this line in `PasswordRequirementBox.js`](https://github.com/salesagility/SuiteCRM/blob/27e4e186b645b59dba48b72d0cb78ae045f8f375/jssource/src_files/modules/Users/PasswordRequirementBox.js#L55):

```diff
- if ((new_pwd != "" || confirm_pwd.value != "" || (document.getElementById('page') && document.getElementById('page').value == "Change"))) {
+ if ((new_pwd != "" || confirm_pwd.value != "" || (document.getElementById('page') && document.getElementById('page').value == "Change")) && old_pwd != "") {
```

**Comment by trainingcity** [comment] 2021-06-28 18:28
Brand new to SuiteCRM. Just installed latest release 7.11.20. Experiencing this problem when system admin (me) attempts to edit own user profile.

**Comment by Dillon-Brown** [comment] 2021-06-28 19:10
Hi @trainingcity, have you checked to see if your user password is being auto-filled when you attempt to save? You should be able to simply delete the auto-fill and re-save as a workaround.

**Comment by trainingcity** [comment] 2021-06-28 19:28
Thanks @Dillon-Brown. That work around solved my issue, much appreciated.

Not sure how the auto fill happened? It is extra confusing for a noobie as the pswd field is on a different UI tab. I guess it is a Chrome issue, but probably still should be addressed as it is very confusing.

**Comment by Dillon-Brown** [comment] 2021-06-29 06:33
@trainingcity No problem, glad to be of help!

As for the root cause of this issue, it's definitely a chrome thing.... They mostly just [ignore](https://bugs.chromium.org/p/chromium/issues/detail?id=370363#c7) requests to not auto-fill unless you happen to get lucky with the ignore request format matching up to specific supported Chrome version specs.

Ideally what we should have here is something like ```autocomplete="new-password"``` to identify that this is a password reset form but I believe that no longer works. I'll see if I can have a play around and find something that will at least work for reasonably modern versions (Chrome 80+).

**Closed** 2021-08-20 10:37 UTC
Labels: Type:Bug, Status:Fix Proposed, Priority:Important
