### ISSUE TITLE
Undefined messages in Compose, select Template, when started from email link

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#4041] opened 2017-07-25 15:54 UTC
#### Steps to Reproduce
1. Go to a contact detail view, click on his email address
2. The Compose window pops-up.
3. Click the arrow to select an Email template, the Template selection pop-up appears
4. Select any template
5. An undefined error appears.

For some users, clicking OK seems to let you work around the issue and send the email.
But others report that they can't complete and send the email, no matter what they click on that "undefined" message box.

Note that the bug only occurs when started from an email link. If you start by entering Email module and clicking Compose, the bug doesn't occur.

#### Expected Behavior
The dialog box should contain these labels

```
/var/www/html/modules/Emails/language/en_us.lang.php:418:    'LBL_CONFIRM_TEMPLATE_TITLE' => 'Apply an Email Template',
/var/www/html/modules/Emails/language/en_us.lang.php:419:    'LBL_CONFIRM_TEMPLATE_BODY' => 'This operation will override the email Body and Subject fields, do you want to continue?',
```

#### Context
High-priority, I think.

#### Actual Behavior
`undefined`, some users can't send email.

#### Your Environment
* SuiteCRM Version used: 7.9.3 and 7.9.4, on SuiteCRM demo, on Softaculous demo, on my test server
* Browser name and version: Firefox latest

**Comment by Dillon-Brown** [comment] 2017-07-26 09:14
Duplicate of #3735 which there is now a fix for #4042. Not sure why some users are unable to send an email as this is only an issue with the displaying of the labels themselves, should be unrelated to any email sending issues.

**Closed by Dillon-Brown** 2017-07-26 09:14 UTC
Labels: duplicate
