### ISSUE TITLE
Error Exporting Products

### ISSUE THREAD

**Issue by mwyres** [salesagility/SuiteCRM#3674] opened 2017-06-08 05:51 UTC
#### Issue

Blank screen when exporting products, the following error thrown in suitecrm.log:

Thu Jun  8 15:02:19 2017 [16044][45653204-0a54-24f7-495e-58e18cb56571][FATAL] Error exporting AOS_Products: <BR>. SELECT  aos_products.* ,aos_products_cstm.aos_products_id_c,aos_products_cstm.estimated_quantity_c , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod, LTRIM(RTRIM(CONCAT(IFNULL(jt3.first_name,''),' ',IFNULL(jt3.last_name,'')))) contact , jt4.name aos_product_category_name , jt5.name products_c  FROM aos_products  LEFT JOIN aos_products_cstm ON aos_products.id = aos_products_cstm.id_c   LEFT JOIN  users jt0 ON aos_products.modified_user_id=jt0.id AND jt0.deleted=0

AND jt0.deleted=0  LEFT JOIN  users jt1 ON aos_products.created_by=jt1.id AND jt1.deleted=0

AND jt1.deleted=0  LEFT JOIN  users jt2 ON aos_products.assigned_user_id=jt2.id AND jt2.deleted=0

AND jt2.deleted=0 LEFT JOIN contacts jt3 ON aos_products.contact_id = jt3.id AND jt3.deleted=0  LEFT JOIN aos_product_categories jt4 ON aos_products.aos_product_category_id = jt4.id AND jt4.deleted=0  LEFT JOIN aos_products jt5 ON aos_products_cstm. = jt5.id AND jt5.deleted=0  where aos_products.deleted=0 Query Failed:  SELECT  aos_products.* ,aos_products_cstm.aos_products_id_c,aos_products_cstm.estimated_quantity_c , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod, LTRIM(RTRIM(CONCAT(IFNULL(jt3.first_name,''),' ',IFNULL(jt3.last_name,'')))) contact , jt4.name aos_product_category_name , jt5.name products_c  FROM aos_products  LEFT JOIN aos_products_cstm ON aos_products.id = aos_products_cstm.id_c   LEFT JOIN  users jt0 ON aos_products.modified_user_id=jt0.id AND jt0.deleted=0

AND jt0.deleted=0  LEFT JOIN  users jt1 ON aos_products.created_by=jt1.id AND jt1.deleted=0

AND jt1.deleted=0  LEFT JOIN  users jt2 ON aos_products.assigned_user_id=jt2.id AND jt2.deleted=0

AND jt2.deleted=0 LEFT JOIN contacts jt3 ON aos_products.contact_id = jt3.id AND jt3.deleted=0  LEFT JOIN aos_product_categories jt4 ON aos_products.aos_product_category_id = jt4.id AND jt4.deleted=0  LEFT JOIN aos_products jt5 ON aos_products_cstm. = jt5.id AND jt5.deleted=0  where aos_products.deleted=0: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= jt5.id AND jt5.deleted=0  where aos_products.deleted=0' at line 7
Thu Jun  8 15:02:19 2017 [16044][45653204-0a54-24f7-495e-58e18cb56571][FATAL] Exception in Controller: Database failure. Please refer to suitecrm.log for details.

* SuiteCRM  7.8.3
* MySQL 5.7.18
* Ubuntu 16.04
* Apache/2.4.18
* PHP 7

**Comment by ChangezKhan** [comment] 2017-06-17 18:31
Not able to recreate on SuiteCRM 7.9.0.

**Comment by mwyres** [comment] 2017-06-19 00:21
Thanks for your effort and feedback, but given 7.8.x is the LTS version of Suite - (and 7.9 is not) - this isn't helpful at this stage.

**Comment by ChangezKhan** [comment] 2017-06-19 06:55
@mwyres it doesn't matter. If the issue is in 7.8.x then it should be in 7.9.x, iff it is not solved already. Still I have checked in 7.8.2, but still couldn't reproduce the error. 

It must be happening due to some specific customization/configuration you did at your end. Kindly provide the details of customization/configuration you did in your CRM, like addition of new fields in product module, addition of relationship between product and other modules.

**Comment by Dillon-Brown** [comment] 2017-09-15 23:52
Closed due to inactivity.

**Closed by Dillon-Brown** 2017-09-15 23:52 UTC
Labels: Pending Input
