### ISSUE TITLE
Cannot edit PDF templates in 7.9.3

### ISSUE THREAD

**Issue by javitoron** [salesagility/SuiteCRM#3916] opened 2017-07-19 12:30 UTC
#### Issue
from list or detail, when you click Edit you get a blank page

#### Expected Behavior
It should display the editForm

#### Actual Behavior
It displays a blank page

#### Steps to Reproduce
1. Go to PDF templates
2. Click edit

#### Context
I can't edit or duplicate PDF templates.
I think it's a high priority.

#### Your Environment
SuiteCRM Version used: 7.9
Browser name and version: Chrome Version 59.0.3071.115 (64-bit)
Environment name and version MySQL, PHP 7
Operating System and version Ubuntu 14.04.5

**Comment by samus-aran** [comment] 2017-07-19 12:36
HI @javitoron 

II'm unable to replicate this issue on the demo instance
https://demo.suiteondemand.com

Is this happening on new PDF templates or existing PDF templates?

When you say a blank page is the Header/Footer of the instance visible or just a white blank screen?

**Comment by javitoron** [comment] 2017-07-19 13:11
I can create new templates, but I can't edit or duplicate.

And yes, Header/Footer of the instance is visible.

I even echoed successfully in function setFields() in modules/AOS_PDF_Templates/views/view.edit.php...

**Comment by javitoron** [comment] 2017-07-20 22:53
Hi @samus-aran, I already answered your questions! but I forgot to mention... is there any more "pending inputs"?

**Comment by samus-aran** [comment] 2017-07-21 08:31
We haven't been able to replicate this so we need to investigate it further.

Have you got any customisations in your instance outside of studio?  What does your suitecrm.log say - anything of interest when you try and open a PDF Template?

**Comment by javitoron** [comment] 2017-07-21 10:55
Well, I only have customised templateParser, that shouldn't affect this.

And the log displays nothing on this... I guess i'm alone on this... :-D

I'll report the solution here if I find it... thanks

**Comment by Pat3920** [comment] 2017-07-24 22:25
Hi javitoron
I have the same issue here V7.9.4. When I create a new PDF template, save it and reopen it for editing, the opened template is empty. I can edit it, but I doesn't see the elements I entered before.

I could replicate it on https://demo.suiteondemand.com
@samus-aran: Try it on https://demo.suiteondemand.com it's the same issue there. Create a new template (for expl. category Contacts) save it and try to edit afterwards. You can open it, but you won't see what you just saved before.

**Comment by horus68** [comment] 2017-07-25 08:21
confirmed in the demo: any text in the body field (just a simple text) is saved and visible but cleared when reediting.
Text in head or footer is not removed

**Comment by Dillon-Brown** [comment] 2017-07-25 08:42
PDF template not saving correctly appears to be resolved in 7.9.4.

**Comment by likhobory** [comment] 2017-07-25 08:58
Confirmed in 7.9.4

Steps to Reproduce
1. Create and save template with some text in body: $accounts_name 
2. Reopen and edit this template: $accounts_name  111
3. Check DetailView - all OK
4. Reopen it in EditView and check the body

**Comment by javitoron** [comment] 2017-07-25 09:19
anyway... this is another bug... my problem is that when I click edit on a PDF template I only see header and sidebar, and the rest of the scree is blank...

**Comment by javitoron** [comment] 2017-08-01 12:54
well, I have tracked down this error to line 108 in "themes/SuiteP/include/EditView/tab_panel_content.tpl" which is `{{sugar_field parentFieldArray='fields' accesskey=$ACCKEY tabindex=$colData.field.tabindex vardef=$fields[$colData.field.name] displayType='EditView' displayParams=$colData.field.displayParams typeOverride=$colData.field.type formName=$form_name module=$module}}` and exactly to `vardef=$fields[$colData.field.name]`

And this is only giving error with the field 5 => array ( 0 => array ( 'name' => 'description', 'label' => 'LBL_DESCRIPTION', ), ),

any idea???

**Comment by javitoron** [comment] 2017-08-01 14:48
In vardefs I changed the type of description field from html to text and now it's working and it displays a tinyMCE editor... I suppose the bug is in class SugarFieldHtml... I don't know why...

**Comment by stancel** [comment] 2017-08-13 23:27
I can confirm that we are experiencing the same bug in version 7.9.4. I created two PDF templates from the samples. All worked as expected, until going back to edit either one of them then nothing is displayed for the body of the PDF template.

**Comment by Dillon-Brown** [comment] 2017-08-14 05:34
@stancel This should be fixed in hotfix. #4009 fixes blank PDF templates due to a caching issue with html fields.

**Comment by stancel** [comment] 2017-08-20 02:10
Thanks @Dillon-Brown. That worked for me.

**Comment by Dillon-Brown** [comment] 2017-09-16 00:04
Closing this as all the core issues mentioned here should be resolved. Please re-open if you are still encountering core issues. Thanks.

**Closed by Dillon-Brown** 2017-09-16 00:04 UTC
Labels: Pending Input
