### ISSUE TITLE
performSetup Error - $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax

### ISSUE THREAD

**Issue by web-sharp** [salesagility/SuiteCRM#9587] opened 2022-05-13 16:15 UTC
It doesn't seem to matter which version I'm using 7.4 is the same.

[Fri May 13 09:07:11.990853 2022] [php:warn] [pid 12121] [client 192.168.12.3:49192] PHP Warning:  Trying to access array offset on value of type null in /Library/WebServer/Documents/include/utils.php on line 1873
[Fri May 13 09:07:11.990873 2022] [php:warn] [pid 12121] [client 192.168.12.3:49192] PHP Warning:  Trying to access array offset on value of type null in /Library/WebServer/Documents/include/utils.php on line 1827
[Fri May 13 09:08:14.271590 2022] [php:error] [pid 12121] [client 192.168.12.3:49204] PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in /Library/WebServer/Documents/install/performSetup.php on line 715, referer: http://crm.websharpstudios.com/install.php

_Originally posted by @web-sharp in https://github.com/salesagility/SuiteCRM/issues/9585#issuecomment-1126225124_

**Comment by pgorod** [comment] 2022-05-13 18:51
I believe this is a duplicate of #9513

Although I can't quite square this issue with your comment that it also breaks in PHP 7.4. 

I will close the issue, but feel free to ask us to reopen if you have some valid reason.

Thanks for reporting

**Closed by pgorod** 2022-05-13 18:51 UTC
