### ISSUE TITLE
AOR - Link does not work

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#1926] opened 2016-08-11 16:41 UTC
At the end of the link the record id is missing. Expample:
.../index.php?module=Contacts&action=DetailView&record=

#### Issue

In a generated report the link to a resulting record will not work.

#### Expected Behavior

The link should work and display the details of the record.

#### Actual Behavior

Blank page.

#### Steps to Reproduce

1. Create a report with a "Link"
2. Save the report.
3. Click on one of the links.

#### Your Environment

* SuiteCRM Version used: 7.7.1, 7.6.6
* Browser name and version (Firefox 48.0):
* Environment name and version (MySQL 5.6.30, PHP 5.6.24):
* Operating System and version (FreeBSD 10.2):

**Comment by samus-aran** [comment] 2016-08-12 08:51
Duplicate of #1558

**Closed by samus-aran** 2016-08-12 08:51 UTC
Labels: duplicate
