### ISSUE TITLE
en_us language code in a value - To be translated?

### ISSUE THREAD

**Issue by horus68** [salesagility/SuiteCRM#1588] opened 2016-06-10 18:13 UTC
In file     
https://github.com/salesagility/SuiteCRM/blob/master/modules/Leads/language/en_us.lang.php

there is this string:
`    'ERR_DELETE_RECORD' => 'en_us A record number must be specified to delete the lead.',`

What is a language code en_us doing here? Is this to be translated or is just an error?

**Comment by JimMackin** [comment] 2016-06-15 14:15
Duplicate of #1512

**Closed by JimMackin** 2016-06-15 14:15 UTC
Labels: bug, duplicate, Low Priority
