### ISSUE TITLE
Strange behavior when changing the layout of a custom module list view

### ISSUE THREAD

**Issue by filev-svt** [salesagility/SuiteCRM#6731] opened 2019-01-07 15:36 UTC
#### Issue

When saving & deploying after editing the layout in Studio in a custom module, the changes are not saved, they get saved after refreshing the page. 
#### Expected Behavior

Changes should be visible right after pressing Save & Deploy
#### Actual Behavior

Changes are rolled back after pressing Save & Deploy, they are committed after refreshing the page.
The logs do not indicate anything wrong.
#### Possible Fix

The problem could be caused by invalid caching, not really sure though.

**Comment by Mausino** [comment] 2019-01-07 19:51
@filev-svt i can confirm this issue in 7.10.11 as you wrote only for custom module. After Save&Deploy need to refresh page to see your configuration.

I must only corect you that after Save&Deploy will show you confirugation before was in listview and after referesh will you see yours which you saved&deployed last.

On fist look it looks like each Save&Deploy load configuration which was before this Save&Deploy. You need only refresh only when you want see your newiest listview configuration.

**Comment by Mausino** [comment] 2019-01-07 22:42
@Dillon-Brown @samus-aran i did litle bit research and i think this is duplicate of #2928 and this fix your @filev-svt issue.

**Comment by filev-svt** [comment] 2019-01-07 22:44
Thanks for the tip, I will definitely take a look at it.

**Comment by Mausino** [comment] 2019-01-08 10:53
@jack7anderson7 i think that is duplicate of #2928 and should be this issue closed and marked with label duplicate.

**Closed** 2019-01-08 14:15 UTC
Labels: duplicate
