### ISSUE TITLE
Portal user - email issue

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#603] opened 2015-10-28 15:17 UTC
If i have Opted Out or  Invalid email in contacts, after create or enable or disable portal user are this emails unchecked in contact :(

**Comment by samus-aran** [comment] 2016-03-14 10:50
@Mausino Can you be abit more clear with your description of issues.  I don't know if this is a question or an issue.

**Comment by Mausino** [comment] 2016-03-22 15:18
Please @samus-aran  look on this videoscreen http://screencast.com/t/N6JGxsrjc4rX

You will see that invalid email after "Enable Portal User" function disapear and the oupted out email was enabled as normal email :(

**Comment by Mausino** [comment] 2016-04-05 13:48
@paulgodley @samus-aran did you test it ? can you replicate this issue ?

**Comment by paulgodley** [comment] 2016-04-05 17:19
Hi there. Excellent screen capture of the issue! I have not been dealing
with this, @samus-aran is there any update on this?

**Comment by Mausino** [comment] 2016-06-16 09:14
@samus-aran @vladbar @mattlorimer could you change the label of this issue ticket from QUESTION to BUG? Thanks

**Comment by cameronblaikie** [comment] 2019-06-13 09:36
Closing as this is a duplicate of this issue (https://github.com/salesagility/SuiteCRM/issues/4145)

**Closed by cameronblaikie** 2019-06-13 09:36 UTC
Labels: Medium Priority, bug
