### ISSUE TITLE
Notes module: Could not populate Name field display blank on UI.

### ISSUE THREAD

**Issue by anhnhatuit** [salesagility/SuiteCRM#5367] opened 2018-03-01 08:35 UTC
#### Issue

I've created new note record. However, when I edit or go to detail record I not see value of Name field.
#### Possible Fix

Because Note Bean extend from File Bean. In retrieve function in File Bean, name value has override by document_name field (document_name current is empty)
Please fix in retrieve function in path: include\SugarObjects\templates\file\File.php

#### Steps to Reproduce

1. Go to Notes module
2. Create new record (must type Name value)
3. Save
4. Edit or Go to Detail -> Name display blank

#### Your Environment

* SuiteCRM Version used: 7.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by pgorod** [comment] 2018-03-01 17:02
Are you using this in English? I can't find a `Name` field in notes. Please check on the [live demo](suitecrm.com/demo) how it is called in English.

If it is the Subject field, then this is probably a duplicate of #5327

Thanks

**Comment by anhnhatuit** [comment] 2018-03-02 02:07
Hi @pgorod,

Ah yes, you're correct. Yes, It's duplicate. I hope you release new version fix this issue ASAP.

Thanks

**Closed** 2018-03-02 05:20 UTC
Labels: duplicate
