### ISSUE TITLE
autocompletion of contact field doesn't work in migration process from lead to contact 

### ISSUE THREAD

**Issue by Lehnerr** [salesagility/SuiteCRM#2031] opened 2016-08-24 16:32 UTC
#### Issue

I've created a lead and than I want to convert it to an contact.
But I dont like to create a new contact  I want to select a contact.
When I type in the first letters of contacts surename or forname nothing is suggested like in other related fields
#### Expected Behavior

Autosuggestion of the existing records would be great like in other relate fields
#### Actual Behavior

nothing is suggested
#### Steps to Reproduce

1.
2.
3.
4.
#### Context

medium
#### Your Environment

- SuiteCRM Version used: 7.7.2
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF(32bit), ie11(32bit)
- Environment name and version (e.g. MySQL, PHP 7): mysql, php5.4
- Operating System and version (e.g Ubuntu 16.04): ubunto 14.04.4

**Comment by shogunpol** [comment] 2016-10-03 10:11
The issue has been tested on recent version of SuiteCRM(7.7.5), and not appear.
@Lehnerr ,can you confirm is this not an issue any longer, if yes can you close this issue?

**Comment by Lehnerr** [comment] 2016-10-03 11:56
I've updated to 775 and the problem is still there.

**Comment by shogunpol** [comment] 2016-10-04 08:00
@Lehnerr , may i ask you about more details about an issue, step by step to reproduce, print-screens, since in my instance everything is correct.
Thanks for help.

**Comment by Lehnerr** [comment] 2016-10-04 10:26
HI.

Created an Doc file whith printscreens.
>>> Jerzy <notifications@github.com> 04.10.2016 10:00 >>>
@Lehnerr
( https://github.com/Lehnerr)  , may i ask you about more details about
an issue, step by step to reproduce, print-screens, since in my instance
everything is correct.
Thanks for help.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
(
https://github.com/salesagility/SuiteCRM/issues/2031#issuecomment-251320375)
, or mute the thread
(

**Closed** 2016-12-31 21:11 UTC
Labels: bug, Fix Proposed, Low Priority
