### ISSUE TITLE
Email duplicated in Contacts List View

### ISSUE THREAD

**Issue by satnav** [salesagility/SuiteCRM#7661] opened 2019-07-30 04:31 UTC
#### Issue

When you look at the list view of contacts, their email address is displayed twice; one with a link and one without. I have looked in custom/modules/Contacts/views to see if something had been overridden but I couldn't find anything.
![Screen Shot 2019-07-30 at 12 20 50 pm](https://user-images.githubusercontent.com/5352436/62100533-af8b8000-b2c4-11e9-9bc3-ac870e637a5f.png)

#### Expected Behavior

There should only be the one with the link

#### Actual Behavior

Both are displayed

#### Steps to Reproduce

1. Go to Contacts module
2. Look at emails column

#### Context

Functionality still works, its just confusing as to why its there in the first place.
Low priority.

#### Your Environment

SuiteCRM Version: 7.11.6
Browser: Chrome: 75.0.3770.142
Environment: MySQL 5.7.22, PHP 7.3
Operating System: Amazon Linux 2 (Cloud hosted)

**Comment by connorshea** [comment] 2019-08-01 20:54
Weird, I can reproduce this on our customized CRM instance running 7.10.19, but not on the demo instance running 7.11.

**Comment by connorshea** [comment] 2019-08-01 21:16
I also can't reproduce it on my local CRM running on hotfix-7.10.x.

I wonder if there's something specific that causes it to occur?

**Comment by connorshea** [comment] 2019-08-01 22:00
Found the source of the issue: https://github.com/salesagility/SuiteCRM/blob/ef1b41965c056937894dd3018d3b149c9c25a9a9/modules/Contacts/metadata/listviewdefs.php#L97

In our `listviewdefs.php`, we had `'customCode' => '{$EMAIL1_LINK}{$EMAIL1}</a>',` and that's what was causing the issue. Changing it to `'customCode' => '{$EMAIL1_LINK}'` in each `listviewdefs.php` file where the old version occurs fixes the problem.

It was fixed in SuiteCRM core with this commit https://github.com/salesagility/SuiteCRM/commit/57912ad71e0ea44c094581127f1a1dcb4e2bced1#diff-b933559f8a6b546e161809842aba79ba

So this isn't an issue with the CRM, just with some customizations that didn't get updated on upgrade. It can be closed.

**Closed** 2019-08-02 09:00 UTC
Labels: Invalid
