### ISSUE TITLE
Calendar module Scheduled Meeting off by one day

### ISSUE THREAD

**Issue by edmondklai** [salesagility/SuiteCRM#5066] opened 2018-01-30 17:16 UTC
#### Issue
When using the Calendar module to create a scheduled meeting, the scheduled meeting is off by one day on the calendar.   The issue resolved itself after refresh.

#### Expected Behavior

When creating the scheduled meeting, the meeting should be displayed on the calendar on the correct day. For example, when creating a meeting on Friday, meeting display on Friday. 

#### Actual Behavior

When creating a meeting on Friday, meeting display on Thursday.

#### Steps to Reproduce

1. Go to Calendar module
2. Click on a timeslot to create a meeting
3. Save the meeting
4. Meeting display is one day off

#### Your Environment

* SuiteCRM Version used: 7.10-RC and 7.8.12. 
* Browsers: Chrome Version 63.0.3239.132 and Firefox 58.0.1

**Comment by horus68** [comment] 2018-01-30 17:38
https://github.com/salesagility/SuiteCRM/pull/3170
https://github.com/salesagility/SuiteCRM/pull/2099
https://github.com/salesagility/SuiteCRM/pull/2099

**Comment by Dillon-Brown** [comment] 2018-02-01 11:01
Hi @edmondklai, I'm unable to replicate this on 7.10-RC or 7.8.12. Can you provide any further info that might help us to replicate? (date settings, etc.). Thanks.

**Comment by edmondklai** [comment] 2018-02-02 15:07
I couldn't find any date/time setting except these in SuiteCRM. 
- Date Format: 12/23/2010
- Time Format: 11:00pm
- Time Zone: America / Chicago (GMT -6:00)

I am running Ubuntu Server 16.04.3, the date is set correctly to the current local time, and the timezone for the server is also set to America/Chicago.  

I tried this on Chrome Version 64.0.3282.140, Firefox 58.0.1, Opera 50.0, and even IE, they all exhibit the same behavior, so it's probably not a browser issue. 

1. Click on 9am on Friday
![picture1](https://user-images.githubusercontent.com/23513440/35739365-fb95f2ca-07f6-11e8-8b78-007ffbad75ed.png)
2. Schedule a meeting, "Friday Meeting", the time is set to 2/2/2018 and 9:00am
3. Save
4. Meeting display on Thursday instead
![picture2](https://user-images.githubusercontent.com/23513440/35739516-739e04a6-07f7-11e8-815b-e6216fe086f7.png)
5. Refresh the browser, the meeting will show up correctly on Calendar
![capture](https://user-images.githubusercontent.com/23513440/35739588-ab1862fa-07f7-11e8-8a53-d4d160af872e.PNG)

Sorry for including so many pictures, but they can probably illustrate better than my words.  The result is produced using 7.10-RC and 7.8.12.  Is there any other information they might be helpful?

**Comment by edmondklai** [comment] 2018-02-06 23:03
@Dillon-Brown , I tried it with my Macbook running MAMP stack and it produces the same result (PHP 7.1).  Can anyone else reproduce the same thing?

**Comment by edmondklai** [comment] 2018-02-16 16:51
Thank you @horus68! The changes in #3170 in Cal.js fixed the issue, thank you.  Is there a reason why this isn't merged?

**Comment by Dillon-Brown** [comment] 2018-03-13 16:40
@edmondklai This should be a duplicate of #2049 which has been fixed here: #5456. Will look at merging asap. Thanks.

**Closed by Dillon-Brown** 2018-03-13 16:40 UTC
Labels: Pending Input
