### ISSUE TITLE
Report Module - Grouping Opportunities by Assigned Users displays user ID instead of Name

### ISSUE THREAD

**Issue by ApatheticCosmos** [salesagility/SuiteCRM#5418] opened 2018-03-06 20:29 UTC
#### Issue

THIS IS AFTER AN UPGRADE FROM 7.8.11 TO 7.10.1
When creating a Report of Opportunities, and setting the 'Main Group' to 'Assigned to', the group header displays the users id instead of their name. It also breaks PDF export, in that the PDF only displays the user ID headers and no content under them.

#### Expected Behavior

The group header should show the User's Name.

#### Actual Behavior

The suitecrm.log file says:
[ERROR] SugarBean.load_relationships, Null relationship name passed.
This error is repeated for each field included.

#### Steps to Reproduce

1. Create Report for the Opportunities Module
2. Select "Opportunity Name" and "Assigned to" fields
3. Set the "Main Group" to "Assigned to"
4.

#### Your Environment

* SuiteCRM Version used: 7.10.1
* Browser name and version: Chrome 64.0.3282.186 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): 10.0.33-MariaDB, PHP 7.0.25-0ubuntu0.16.04.1
* Operating System and version: Ubuntu 16.04

**Comment by ApatheticCosmos** [comment] 2018-03-06 20:30
![image](https://user-images.githubusercontent.com/16560296/37056751-51b6b340-2153-11e8-8f4d-69cdba493920.png)

**Comment by ApatheticCosmos** [comment] 2018-03-06 20:32
Here's a screencast showing the behavior:
[vokoscreen-2018-03-06_15-09-12.mkv.zip](https://github.com/salesagility/SuiteCRM/files/1786624/vokoscreen-2018-03-06_15-09-12.mkv.zip)

**Comment by ApatheticCosmos** [comment] 2018-03-06 20:46
This is what the PDF of the report shows:
![image](https://user-images.githubusercontent.com/16560296/37057464-6d96f7bc-2155-11e8-9a92-c6c53df7c073.png)

**Comment by AdminPL** [comment] 2018-03-07 10:13
I've already reported this bug, no interest from developer site.

**Comment by Dillon-Brown** [comment] 2018-03-07 10:32
Duplicate of #2595

**Closed by Dillon-Brown** 2018-03-07 10:32 UTC
Labels: duplicate

**Comment by ApatheticCosmos** [comment] 2018-03-07 14:15
There is another issue with the PDF export, but I think I'll open a new bug report for that, since the header issue is covered already.

**Comment by anhnhatuit** [comment] 2018-03-12 03:21
Hi @Dillon-Brown ,
Have any someone take care this issue? If not, I'll take care this issue
Thanks,
Nhat

**Comment by Dillon-Brown** [comment] 2018-03-12 12:11
Hi @anhnhatuit, I don't think anyone has made a PR for this issue. A fix would be much appreciated. Thanks.
