### ISSUE TITLE
Inbound auto email fields do not show data

### ISSUE THREAD

**Issue by abrcs** [salesagility/SuiteCRM#3045] opened 2017-02-03 11:26 UTC
#### Issue

When you set up inbound emails and for auto case creation an email is sent to the customer detailing the case details and other variables that have been selected.

> Dear Sir \ Madam,
> 
> Thank you for submitting your query to Support on $acase_date_entered. Your case has been logged under reference number: #$acase_case_number
>  
> Status	$acase_status
> Reference	$acase_case_number
> Description	$acase_description
> 
> We will contact you as soon as possible.

The above is exactly what is sent through the email and the variables do not contain any of the data. The only data that is correct is the case number which is shown on the subject of the email.

#### Expected Behavior
Variables should contain data such as the case number, date created or status etc.

#### Actual Behavior

> Status	$acase_status
> Reference	$acase_case_number
> Description	$acase_description

The variables in the email are shown instead of the actual data.

#### Your Environment
Running version: SuiteCRM-7.6.4

Various reports of this issue:

https://suitecrm.com/forum/suitecrm-7-0-discussion/4145-inbound-email-case-creation
https://www.suitecrm.com/forum/suitecrm-7-0-discussion/1454-case-creation-email
https://community.sugarcrm.com/thread/29357-case-email-template-how-to-include-account-name-variable
**https://suiteforge.org/forum/bug-tracker/714-bug-email-template-issue-variables-not-populating-with-values**

**Comment by ChangezKhan** [comment] 2017-02-03 17:41
Hi team, This issue is also on `SugarCRM 7.7.8`.

**Comment by shogunpol** [comment] 2017-02-08 08:47
(tag and Close issue)

Response - Thank you for highlighting this issue, however, this is a duplicate of issue #1366. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2017-02-08 08:47 UTC

**Comment by boombata** [comment] 2017-03-03 13:23
@shogunpol i have a doubt about the relation between this bug report #3045 and #1366, please excuse me if i'm wrong. 

looking at handleCreateCase() in AOPInboundEmail.php  it is sending the reply with emails send() function without parsing first the description and if i understood correctly email2Send() function in emails.php is the function parsing the template but it is used only when clicking the send button is email2 interface. 

Regards,
BM.
