### ISSUE TITLE
AOR Reports: Date parameter only accepts format 2016-06-20

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM#1624] opened 2016-06-20 10:24 UTC
If the user has a different date format like "20.06.2016" and tries to change a date parameter at the detailview or in a dashlet the report wont work with the new parameters.

If you save a report for the first time, the date format is no issue, so editview seems to handle the date format.
But if you try to edit the parameter "on-the-fly" and click update, or in a dashlet, the date is invalid.

**Comment by gunnicom** [comment] 2016-06-20 12:04
I got these Problems in 7.6 and 7.7beta1 although there is an old bug report it seems not fixed:
https://github.com/salesagility/SuiteCRM/issues/1082

**Comment by daniel-samson** [comment] 2016-06-20 16:27
Seems to be a JavaScript issue. The non-standard Date.prototype.toLocaleFormat() method is being used to achieve the conversion.

We need to change this to Date.prototype.toLocaleFormat() method or use the standard  Intl.DateTimeFormat. We could also use the new mement.js library that I included in the last release.

**Comment by gunnicom** [comment] 2016-06-20 17:02
Why not handling like in the rest of sugar does where the date conversion works (converted server side)?

**Comment by recci** [comment] 2016-07-13 16:04
This issues appears to be caused by the same problem as issue #1700.  Looks like the problem is line 470 in aow_utils.php e.g. $fieldlist[$fieldname]['value'] = $timedate->to_display_date($value);

The to_display_date method is meant to convert a DB date string to local date string, in this case it is not being passed a DB date string but a user formatted string. So when it tries to use the default date format of 'Y-m-d H:i:s' to convert the user formatted date string it fails to convert unless the user's date format is set to 'Y-m-d H:i:s'.  A possible solution would be to convert the date to the db date format before calling  to_display_date() on it.

**Comment by recci** [comment] 2016-08-02 16:50
Disregard my previous comment that is not where the problem lies.

**Comment by vladbar** [comment] 2016-08-15 17:07
There are couple of problems with the current modules/AOR_Reports/tpls/report.tpl: 

- first one is on: fieldInput need to accept value from datepicker by utilising SuiteCRM functions isDate() and getDateObject(fieldInput) from jssource/src_files/include/javascript/sugar_3.js - this will solve the conversion issue.

- Second problem is: there are many ajax requests firing on the background and loadConditionLine() still not ready by the time the code in $(document).ready(function() { is trying to access condition lines.

- third issue is that function fixUpFormatting() in modules/AOW_WorkFlow/aow_utils.php trying to change dates (to previous/next day) if the date does not have any time assigned to it.

**Comment by vladbar** [comment] 2016-08-16 10:12
Another issue here is that Date.prototype.toLocaleFormat() only works for Firefox.

**Comment by vladbar** [comment] 2016-08-22 03:07
Latest commit after some testing by our Support Team.

**Comment by vladbar** [comment] 2016-09-14 09:41
Simeon also added some fixes

**Comment by vladbar** [comment] 2016-09-14 10:13
e736eaa and 782774c were tested by our support team and passed the testing

**Comment by virtualme123** [comment] 2016-10-20 08:57
Might be worth mentioning here that 7.7.5 a report with a date format of 'd/m/Y' doesn't listen to sort in order, you have to select 'none' for full date sorting to work.

**Comment by shogunpol** [comment] 2016-11-24 15:46
@gunnicom ,This issue it appears to be fixed in previous commits, can you confirm this is a case?

**Comment by gunnicom** [comment] 2016-11-24 15:55
Maybe i will update to 7.7.8 on that instance next week and check.

**Comment by clementnadeauludifrance** [comment] 2016-11-30 14:27
Hi, not working in 7.7.8 either.

I have same bug.

My system date format : dd/mm/yyyy

In a report, with date parameter, when i click on date on datepicker, input format is filled with dd/mm/yyyy format. But when i update parameters with button, there is no result.

It works when i manually fill the date input with date formatted yyyy-mm-dd

**Comment by horus68** [comment] 2017-03-06 14:32
@shogunpol Could not confirmed this in the demo version
![2017-03-06 14_28_44-suitecrm](https://cloud.githubusercontent.com/assets/3055443/23613950/4209d368-0279-11e7-8944-4419ecaf3470.png)

![2017-03-06 14_28_03-suitecrm](https://cloud.githubusercontent.com/assets/3055443/23614091/ae5b786e-0279-11e7-8692-88f1e0067cc6.png)

**Comment by gunnicom** [comment] 2017-03-06 15:45
@horus68 Its about the conditions, not about the fields shown.

**Comment by horus68** [comment] 2017-03-06 17:58
Any particular combination on date conditions and modules/fields used?
It works for me on the demo site: Using accounts modules and date to list it worked for me (inline Update and also when editing the report conditions)

![2017-03-06 17_55_13-suitecrm](https://cloud.githubusercontent.com/assets/3055443/23622342/25a1121e-0296-11e7-9f52-bcd47a749b16.png)

**Comment by gunnicom** [comment] 2017-03-08 11:08
@horus68 The bug is still there, in demo, too.
Steps To reproduce in demo site:
1. Create Report for module opportunitites
2. Fields: name, expected close date
3. Conditions: expected close date less than value 01/01/2017, paramater checked
4. Test report, works, shows filtered list
5. change date format in your profile to 23.12.2023
6. Go to report, still seems to work
7. Press "update", parameter field gets empty, result is unfiltered

**Comment by horus68** [comment] 2017-03-08 15:59
For me it works fine several date formats, even with different browsers.
I will test it in other environments or maybe others could confirm this
![2017-03-08 15_57_09-teste 1624 reports suitecrm e mais 1 pagina - microsoft edge](https://cloud.githubusercontent.com/assets/3055443/23711527/1194ca9e-0418-11e7-92a7-cf1bbd51787a.png)
![2017-03-08 15_51_26-teste 1624 reports suitecrm](https://cloud.githubusercontent.com/assets/3055443/23711529/119926fc-0418-11e7-8a6f-3cc4683e0c6f.png)
![2017-03-08 15_51_20-teste 1624 reports suitecrm](https://cloud.githubusercontent.com/assets/3055443/23711528/1195a306-0418-11e7-9f20-0660ca665cc4.png)

**Comment by gunnicom** [comment] 2017-03-08 16:27
You missed the condition as parameter. I see no update button on your screenshots.

**Comment by horus68** [comment] 2017-03-08 16:36
Confirmed now!
![2017-03-08 16_34_00-suitecrm e mais 1 pagina - microsoft edge](https://cloud.githubusercontent.com/assets/3055443/23713269/48c0bfa0-041d-11e7-9fa4-f769f424da99.png)

@gunnicom sorry to take your time (just using my first glasses today!)

**Comment by ChangezKhan** [comment] 2017-06-26 13:45
It is not reflecting in SuiteCRM 7.9.0. I have checked on demo instance also, but couldn't reproduce the error.

**Comment by gunnicom** [comment] 2017-06-26 14:55
@ChangezKhan No. It is still reproducible in demo. Exactly follow my steps provided and you will see.

**Closed** 2017-09-06 20:27 UTC
Labels: bug, Fix Proposed, Medium Priority, Resolved: Next Release

**Comment by karthik5595** [comment] 2017-11-22 06:44
I have a problem in my report parameter..While i'm giving date like 12-11-2017 and press update button the time value can change like 11-12-2017 and once again i press update its changed as usual..

If i'm give date value greater than day 12 ...after update process the date box shows empty result..
