### ISSUE TITLE
Date filter not being saved

### ISSUE THREAD

**Issue by chogori92** [salesagility/SuiteCRM#5936] opened 2018-05-24 15:34 UTC
#### Issue
When using date field as filter, it works but it's not saved. For example filter meetings by date start (ex. today), click on the first record and try to get again to meetings: you'll see no filter applied.

This issue occours when using date formats different from database one. If you use YYYY-mm-dd date format, it works fine.
You can reproduce in the online demo.

#### Expected Behavior
Filter should be saved.

#### Actual Behavior
Missing datetime fields from filter, after moving to record's detail or another module. 

#### Possible Fix
Check date format prior conversion at modules/MySettings/StoreQuery.php:77 
$db_format = $timedate->to_db_date($value, false);
This line causes conversion exception when using d/M/Y format.

#### Steps to Reproduce
1. Go to Meetings module.
2. Apply a filter to date start field (ex. today).
3. Click on a record to get detail view.
4. Come back to Meetings.
5. Filter lost!

#### Your Environment
* SuiteCRM Version used: 7.8.8 LTS
* Browser name and version: Chrome 66.0.3359.181 (64 bit)
* Environment name and version: Apache/2.4.18 + PHP 7 + MySQL 5.7.21
* Operating System and version: Ubuntu Server 16.04 LTS

**Comment by connorshea** [comment] 2019-03-21 21:20
I'm seeing the same thing with a date range filter. SuiteCRM version is 7.9.17, PHP 7.1.

**Comment by connorshea** [comment] 2019-03-21 21:28
It seems like this issue is the same as #3857, which suggests the same fix.

**Comment by Dillon-Brown** [comment] 2019-03-26 06:22
Duplicate of #3857

**Closed by Dillon-Brown** 2019-03-26 06:22 UTC
Labels: duplicate
