### ISSUE TITLE
Fix CSV export € symbol

### ISSUE THREAD

**Issue by holdusback** [salesagility/SuiteCRM#6967] opened 2019-02-19 08:24 UTC
#### Issue
€ symbol is badly exported in csv's report. € became ¬. With UTF16-LE.

#### Expected Behavior
A € symbol not ¬

#### Possible Fix
The CRM just doesnt have the option to encode in UTF-8 WITH BOM.
Take the UTF-8 encodage in user advanced settings.

in file: /modules/AOR_Reports/AOR_Report.php
In build_report_csv(), just before print $csv add this:
$csv = chr(239) . chr(187) . chr(191) . $csv;

#### Your Environment
* SuiteCRM Version used: 7.11.1

**Comment by Dillon-Brown** [comment] 2019-08-02 10:34
Duplicate of #18

**Closed by Dillon-Brown** 2019-08-02 10:34 UTC
Labels: Fix Proposed, Low Priority, bug
