### ISSUE TITLE
Email template content and formatting is lost or ruined when template is edited by different users

### ISSUE THREAD

**Issue by amariussi** [salesagility/SuiteCRM#3670] opened 2017-06-07 10:14 UTC
7.9.0 Has introduced the possibility for each user to choose his own favourite email template editor.

Unfortunately, since the output of the three available editor is incompatible under many circumstances, this creates big problems that end up in ruined templates.

#### Issue

Imagine a company with 30 users (but the issue happens also witho ne single user).

. First a user creates a template for a Marketing campaign with Mozaik.
. Then a second user modifies the template with TinyMCE.
. A third user modifies again the template with the "Html Editor" (I put it in quotes because, since purifying is applied, it cannot be called like that!).

At the end of the process the template is most of the times unusable and most of the changes are lost.

#### Expected Behavior

The content of the template should be preserved.

The selection of the editor should be done at the template level only.

If a user has a different preferred editor than the one of the template, then the template editor should be used.
This selection can be further sophisticated because, in theory:
. a template created with Mozaik could be safely edited by one of TinyMCE or the HTML Editor (but once done, Mozaik can no longer edit the Template otherwise content will be lost)
. a template created with TinyMCE could be safely edited (but not by Mozaik) by the HTML Editor (but once done, TinyMCE can no longer edit the Template otherwise content will be lost)
and so on.

#### Actual Behavior

The choice of the preferred email template editor is made only at a user level.

#### Possible Fix

Add the choice of the editor for an email template at the template level. This editor will be used, no matter what preferred editor has chosen the user.

#### Steps to Reproduce

1. See SuiteCRM Forum: https://suitecrm.com/forum/feedback/14484-bug-email-template-editor-suitecrm-7-9-0
2. Create an email template using Mozaik and save it
3. Log in as a different user (or change your preferred template editor) and edit the same template with TinyMCE and save it
4. Log in as a different user (or change your preferred template editor) and edit the same template with the HTML Editor and save it
5. Depending on the changes and the sequence of email template editors used (but in most circumstances this happens) the template is broken. The breaking can be as severe as getting three times the content of the template or all previous modifications lost

#### Context

High priority
Sending campaigns or any email using templates becomes totally unreliable

#### Your Environment

* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest available Version (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP-Apache-MySql
* Operating System and version (e.g Ubuntu 16.04): tested on both Linux and Windows

**Comment by Dillon-Brown** [comment] 2017-06-07 10:56
@amariussi I cant seem to replicate this issue. Following the steps you listed on the forums, the template correctly updates with each users change and no duplication occurs. Is there any further info you can give that might help with replication?

**Comment by amariussi** [comment] 2017-06-07 13:09
@Dillon-Brown 
Sorry for the delay but I didn't have time to reproduce all the issues.

In any case have a look at the following sequence of edits to see some of the things that can happen:
(to view and get a screenshot of the whole email I modified the size of the editor panel using the inspect feature of Chrome)

1. I created an email template using Mozaik (detail view):
![001_m_detail_view](https://user-images.githubusercontent.com/8026129/26879498-90c554e4-4b91-11e7-95a0-3e9dafd24415.jpg)

2. Then I switched to TinyMCE and added some text (highlighted):
![002_t_detail_view](https://user-images.githubusercontent.com/8026129/26879590-f44cbdb8-4b91-11e7-8408-44bd63481d4d.jpg)

3. Then I switched to DirectHTML and added more text (html edit view):
![003_h_edit_view](https://user-images.githubusercontent.com/8026129/26879686-5afad07c-4b92-11e7-9a56-70df3766593a.jpg)

4. This is the detail view of previous pint resulting edit with DirectHTML:
![004_h_detail_view](https://user-images.githubusercontent.com/8026129/26879718-7385ada6-4b92-11e7-93ba-66d91513ea71.jpg)

5. Then I switched back to Mozaik the detail view was unchanged. But when I entered edit view, the last changes made with DirectHTML disappeared:
![005_m_edit_view](https://user-images.githubusercontent.com/8026129/26879799-b1e4dc02-4b92-11e7-9d3e-0816f7a56db4.jpg)

6. Without doing any edit in Mozaik I saved. This is the resulting detail view where Mozaik removed all my DirectHTML edits:
![006_m_detail_view](https://user-images.githubusercontent.com/8026129/26879871-e33389ca-4b92-11e7-9431-7ce05f042d2b.jpg)

Obviously something is going wrong.

I have done a few othere tests. In all there were some misbehaviours with the code/template being modified upon switching from one editor to the other.

In one occasion the whole template appeared repeated three times in the detail view (so once it had been saved). Now I can't remember the sequence I did to get this strange behaviour but I will try a few more times to replicate it and hopefully document it.

**Comment by amariussi** [comment] 2017-06-10 08:01
@Dillon-Brown 
I just want to make sure that you haven't forgotten to give the bug label to this issue.
The example I provided demonstrates one of the many issues caused by this situation.

In my opinion it's high priority bug because users will inadvertently delete template data if things are not fixed.

**Comment by Dillon-Brown** [comment] 2017-07-06 15:23
@amariussi Upon further review I believe this would actually be a suggestion. It's expected behaviour for editing templates with multiple editors to break the template. Perhaps we should have some way of informing the user which editor has been used to create the template when they attempt to edit it with a different editor?

**Comment by Dillon-Brown** [comment] 2017-07-06 15:27
![](https://github.trello.services/images/mini-trello-icon.png) [Email template content and formatting is lost or ruined when template is edited by different users](https://trello.com/c/rA61wuPy/209-email-template-content-and-formatting-is-lost-or-ruined-when-template-is-edited-by-different-users)

**Comment by amariussi** [comment] 2017-07-06 16:16
@Dillon-Brown Sorry but this is a BUG.

Here is a use case:
. user A creates a template for a campaign. User A has default editor 1
. user B, who has default editor 2, has to make a small modification to the template created by user A
. when user B finalises the template, he has no idea that it was created with Editor 1. When User B edits the template (with Editor 2), the template gets broken and User B cannot be aware that the template is broken.
. Now that the template is supposed to be ready, User B proceeds with sending the campaign

The campaign is sent with a broken template, which is missing some parts and the sender (User B) is unaware.

This is NOT a new feature! IT'S A BUG.

So please review your (wrong) position.

If the campaign module is used in any organisation with more than one user (probably 99% of the cases) this situation is definitely going to happen and make someone really unhappy with SuiteCRM. And if these "someones" know that this bug has been deliberately classified as a feature instead of a BUG, they will be even more unhappy with SuiteCRM!

Thank you.

**Comment by samus-aran** [comment] 2017-07-07 07:51
Hey @amariussi.

Reason why we are stating this as a suggestion is because the three editors are pretty diverse with different audiences in mind intentionally.

Mozaik - Users whom wish to start from scratch with a simple layout and not worry too much about the details and being responsive. This is aimed at users with little or no template experience.

TinyMCE - Aimed at more advanced users that can adapt and perhaps have a template already in place to work on. A note here is that the next release will have the ability to insert the HTML directly via TinyMCE

Direct HTML - Aimed at even more advanced Users that it's just a simple copy and paste job, have a template provided by a third party and is more comfortable using raw HTML.

Now, understandably people use different editors for different areas of the system BUT ultimately these three editors are aimed specifically for those types of users and trans versing between TinyMCE to Mozaki really seems to be the issue but we don't exactly want to remove Mozaki to over come this.

Possible solutions is:
1. Define the Template's Editor for each Template overwriting the User's Preferred Editor. That would be ensure that everyone is using the suitable Editor for the template stated by the template's creator. However, what if the template creator incorrectly created the template and someone chooses to change it and set sit back or to a wrong editor, we are back at square one.

2. Similar to 1 but instead of forcing the user to change editor (overwriting their preferred editor) just alert them that the email uses a particular editor. Again, its still up to the users if they can by pass this and again may include discrepancies.

3. Remove Mozaik - highly discouraged obviously since we did want to make it easier for certain users.

4. Investigate on making the transition as smooth as possible. But as I said earlier these editors are intentionally different and are aimed for those particular audiences in mind.

5. Admin option to define a default Editor so everyone will be forced to use the same editor - again very restricting....

This is my own opinion from working with WYSIWYG editors for years that we will always have some minor issues with users transferring between editors that are complex and are perhaps not suitable for editing in that particular editor.  That is why we have named it as a suggestion as its somewhat expected and perhaps opening it as a suggestions would raise a more thorough discussion.

**Comment by Mausino** [comment] 2017-07-07 10:52
@samus-aran i'm voting for point 2... it's simple to do and it creates for you time to find best solution 👍 wich will love everybody 🥇

**Comment by Dillon-Brown** [comment] 2017-08-16 06:08
![](https://github.trello.services/images/mini-trello-icon.png) [Email template content and formatting is lost or ruined when template is edited by different users](https://trello.com/c/MmahDJgd/214-email-template-content-and-formatting-is-lost-or-ruined-when-template-is-edited-by-different-users)

**Comment by Dillon-Brown** [comment] 2017-08-16 06:08
I have moved this suggestion to Trello. All github issues that are labeled 'suggestion' will be moved to the new system and closed. Thanks for the suggestion!

Announcement of moving Suggestions:
https://suitecrm.com/forum/suggestion-box/13691-moving-suggestions-from-github-to

New SuiteCRM Suggestion Box
https://trello.com/b/Ht7LbMqw/suitecrm-suggestion-box

**Closed by Dillon-Brown** 2017-08-16 06:08 UTC
Labels: suggestion
