### ISSUE TITLE
Bug in pdf export

### ISSUE THREAD

**Issue by SoapJson** [salesagility/SuiteCRM#3666] opened 2017-06-06 18:50 UTC
Problem in pdf, while exporting reports we have got color of table header invisible, we can select it in pdf exectly but we cant see it. 

Screenshot:
<img width="1431" alt="2017-06-06 21 37 58" src="https://user-images.githubusercontent.com/25264089/26846086-5f704236-4b01-11e7-89aa-3829ab596918.png">

#### Expected Behavior
header should be visible

#### Actual Behavior
header invisible

#### Possible Fix
make pdf reports stylefix may be

#### Steps to Reproduce
export in pdf any report in last version of suitCRM (theme SUIT P)

#### Your Environment

* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by RobinHind** [comment] 2017-06-06 21:59
I had the exact same problem but have found a workaround.
I couldn't understand why i could see the images fine in the pdf editor but when i saved as a pdf they were missing.
At first suspected a permissions thing but it didn't seem to be.

My images were loading from a directory that was at the same level as SuiteCRM and could be viewed fine in a browser, and were working fine before upgrading to 7.9.0 what i noticed though was that our company logo was being rendered fine in the PDF and that was located /custom/themes/default/images so i moved my other images there and relinked them and now they output fine on the PDFS

Hope this helps you.

**Comment by Dillon-Brown** [comment] 2017-06-07 09:01
Duplicate of #2144

**Closed by Dillon-Brown** 2017-06-07 09:01 UTC
Labels: duplicate
