### ISSUE TITLE
"Users may send as themselves" broken - Invalid address:  (punyEncode)

### ISSUE THREAD

**Issue by griemser** [salesagility/SuiteCRM#7407] opened 2019-06-17 07:34 UTC
#### Issue
users are not able to send mails, if checkbox "Users may send as themselves:" is activated

![chrome_f1H7uTkFWK](https://user-images.githubusercontent.com/51903816/59585756-85e61300-90e1-11e9-93ff-e2d7c9f24c03.png)

CRM-Settings:

- EMAIL SETTINGS: OUTGOING MAIL CONFIGURATION is configured, "outbound mail" contains only the "system" item (sending test-mails from the admin-backend works)
- checkbox "Users may send as themselves:" is checked as shown above
- test user has two mail addresses set up in his profile

#### Expected Behavior
- click on a contacts mail address opens mailer
- user is able to choose one of his own addresses and add content
- and can send the mail

#### Actual Behavior
- after clicking the "send" icon, an error message appears:

> Error Sending Email. Please contact your administrator for assistance.
![chrome_PASYuvGElf](https://user-images.githubusercontent.com/51903816/59586451-46202b00-90e3-11e9-8d43-cd63ae12942f.png)

- log:
`Mon Jun 17 09:27:55 2019 [16712][1][FATAL] SugarPHPMailer encountered an error: Invalid address:  (punyEncode) Administrator <test.test@test.com`
**- note the missing ">"!**

#### Possible Fix
- I've debugged into it. Found the issue in `\include\phpmailer\class.phpmailer.php`, line 1252 (validateAddress returns false instead of true)
- I changed therefore (only for testing) the condition to
` if (false && !$this->validateAddress($this->$address_kind)) {`
- result: mail is sent. 

- E: var $address in validateAddress() is set to `some.thing@test.org` for all receiving addresses, but the from-address is set to `Administrator <test.test@test.com` and the following preg_match fails

#### Steps to Reproduce
as described above

#### Your Environment
- SuiteCRM Version 7.10.17
Sugar Version 6.5.25 (Build 344)

**Comment by pgorod** [comment] 2019-06-17 09:43
The fix shouldn't be done inside the phpmailer package (include/phpmailer), but in one of the calling functions (probably in https://github.com/salesagility/SuiteCRM/blob/master/include/SugarPHPMailer.php, which is our own SuiteCRM class to deal with phpmailer package, or even further above in the call stack). 

Basically we don't need to disable the validation, we simple shouldn't be passing it an invalid email address.

**Comment by dursuntosun** [comment] 2019-06-17 10:55
Yes, i have same problem.

**Comment by pstevens71** [comment] 2019-06-19 23:56
I'm experiencing this in 7.11.4  it seems to be missing the last ">" to close the email address.

**Comment by pstevens71** [comment] 2019-06-20 00:35
FYI I've also tested with sending as your own SMTP email address vs. the System.  Both do not. Work.  I Think this should be bumped up to high priority as no emails can be sent!

**Comment by pstevens71** [comment] 2019-07-03 18:27
Think this issue is a duplicate of this one...
[https://github.com/salesagility/SuiteCRM/issues/6812](url)

**Comment by MyBlissIT** [comment] 2019-07-11 20:21
> #### Issue
> users are not able to send mails, if checkbox "Users may send as themselves:" is activated
> 
> ![chrome_f1H7uTkFWK](https://user-images.githubusercontent.com/51903816/59585756-85e61300-90e1-11e9-93ff-e2d7c9f24c03.png)
> 
> CRM-Settings:
> 
> * EMAIL SETTINGS: OUTGOING MAIL CONFIGURATION is configured, "outbound mail" contains only the "system" item (sending test-mails from the admin-backend works)
> * checkbox "Users may send as themselves:" is checked as shown above
> * test user has two mail addresses set up in his profile
> 
> #### Expected Behavior
> * click on a contacts mail address opens mailer
> * user is able to choose one of his own addresses and add content
> * and can send the mail
> 
> #### Actual Behavior
> * after clicking the "send" icon, an error message appears:
> 
> > Error Sending Email. Please contact your administrator for assistance.
> > ![chrome_PASYuvGElf](https://user-images.githubusercontent.com/51903816/59586451-46202b00-90e3-11e9-8d43-cd63ae12942f.png)
> 
> * log:
>   `Mon Jun 17 09:27:55 2019 [16712][1][FATAL] SugarPHPMailer encountered an error: Invalid address:  (punyEncode) Administrator <test.test@test.com`
>   **- note the missing ">"!**
> 
> #### Possible Fix
> * I've debugged into it. Found the issue in `\include\phpmailer\class.phpmailer.php`, line 1252 (validateAddress returns false instead of true)
> * I changed therefore (only for testing) the condition to
>   ` if (false && !$this->validateAddress($this->$address_kind)) {`
> * result: mail is sent.
> * E: var $address in validateAddress() is set to `some.thing@test.org` for all receiving addresses, but the from-address is set to `Administrator <test.test@test.com` and the following preg_match fails
> 
> #### Steps to Reproduce
> as described above
> 
> #### Your Environment
> * SuiteCRM Version 7.10.17
>   Sugar Version 6.5.25 (Build 344)

I have applied this fix "* I changed therefore (only for testing) the condition to
>   ` if (false && !$this->validateAddress($this->$address_kind)) {` on line 1252 but I still get the same error message, I also applied all settings on this thread.

But my test user is still ot able to send an email as themselves

**Comment by pstevens71** [comment] 2019-07-11 20:53
@MyBlissIT that's not the fix.  There is a fix for this issue Dillon Brown has linked it above.

**Comment by MyBlissIT** [comment] 2019-07-12 10:21
> @MyBlissIT that's not the fix. There is a fix for this issue Dillon Brown has linked it above.

Thanks, I performed Dillion Brown's fix and it worked

**Closed** 2019-07-31 16:49 UTC
Labels: Emails, Fix Proposed, High Priority, Resolved: Next Release, bug
