### ISSUE TITLE
Cannot add multiple targets to a Target List

### ISSUE THREAD

**Issue by jwkramer61** [salesagility/SuiteCRM#7469] opened 2019-06-25 16:01 UTC
Issue
When attempting to add multiple targets (Contacts, Leads, Accounts) to an existing Target List, the targets can be selected, but clicking "Select" does nothing.

Expected Behavior
Clicking "Select" should add the selected targets to the Target List

Actual Behavior
Clicking "Select" results in no action (click is ignored)

Possible Fix
unknown

Steps to Reproduce
Go to a Target List and select the "Select" option for Accounts, Contacts, or Leads.
Select a few targets from the list by adding "X"s for the items
Click "Select"

Context
Unable to add targets to the list unless you select them one by one.

Your Environment
SuiteCRM Version used: 7.11.5
Browser name and version: Chrome Version 75.0.3770.80 (64-bit)
Environment name and version: MySQL, PHP 7.3.5
Operating System and version: Windows Server 2012 R2 & IIS v8.5.9600.16384

![broken1](https://user-images.githubusercontent.com/50463174/60113994-e8be5680-9740-11e9-8bf3-b382c9dfb595.JPG)

**Comment by pgorod** [comment] 2019-06-25 17:01
Confirmed on live demo (7.11.5)

Javascript error when pressing select:
![image](https://user-images.githubusercontent.com/15945027/60117996-42d80f80-9773-11e9-9414-e11d63d5d007.png)

**Comment by Dillon-Brown** [comment] 2019-06-26 09:23
Should be fixed by #7413 but I'll mark as a bug until I get a chance to confirm.

**Comment by dmcalister** [comment] 2019-06-26 21:38
I also have this problem and fix #7413 does not help.

**Comment by jwkramer61** [comment] 2019-06-27 11:03
this fix worked for me.

**Comment by jwkramer61** [comment] 2019-06-27 11:04
> I also have this problem and fix #7413 does not help.

odd. I applied the fix yesterday, and it took care of it on both my sandbox, and live instance.

**Comment by Lehnerr** [comment] 2019-06-27 13:41
Problem was also in 7.10.17. The Fix works for me. thx

**Comment by Dillon-Brown** [comment] 2019-06-27 16:19
@dmcalister I would try running the JS rebuilds and doing a hard refresh of the browser cache.

**Closed by Dillon-Brown** 2019-06-27 16:19 UTC
Labels: High Priority, bug

**Comment by kikobar** [comment] 2019-07-16 04:02
I upgraded to 7.11.6 and now this works. Thanks.
