### ISSUE TITLE
AOR Reports: Conditions with NULL value Bug

### ISSUE THREAD

**Issue by MikeyJC** [salesagility/SuiteCRM#1812] opened 2016-07-28 15:06 UTC
Any condition that follows after a condition with a NULL or blank value is ignored.
#### Issue

In AOR Reports, when a condition has a NULL or blank value (e.g. an unchecked box), then all of the conditions that come afterwards will not be parsed correctly and do not filter the report data correctly. The condition that causes this issue still works correctly. This is only an issue when the value is empty (a checked box doesn't cause this issue).
#### Expected Behavior

All conditions are taken into account and the data represented is correct.
#### Actual Behavior

Data filtering is correct up until the condition with the NULL/blank value, at which point it fails to filter down any further.

**Comment by Dillon-Brown** [comment] 2017-08-11 09:48
Duplicate of #3375

**Closed by Dillon-Brown** 2017-08-11 09:48 UTC
Labels: duplicate
