### ISSUE TITLE
[DUPLICATE] 7.5.1 - Adding a Dynamic DropDown field does not display a DropDown List or Parent DropDown field

### ISSUE THREAD

**Issue by abeo** [salesagility/SuiteCRM#1015] opened 2016-02-26 13:54 UTC
This resolved in https://github.com/salesagility/SuiteCRM/issues/929
by copying the following files from 7.4.3
custom/modules/DynamicFields/templates/Fields/TemplateDynamicenum.php
custom/modules/DynamicFields/templates/Fields/Forms/dynamicenum.php
custom/modules/DynamicFields/templates/Fields/Forms/dynamicenum.tpl

7.5.1 - Adding a Dynamic DropDown field does not display a DropDown List or Parent DropDown field

Screenshot of 7.5.1 creating a Dynamic DropDown field showing missing fields. 

![suitecrm-missing-fields-in-dynamic-dropdown](https://cloud.githubusercontent.com/assets/1320436/13354062/7e9c0ea2-dc66-11e5-8269-a40b869570a6.PNG)

Screenshot of 7.4.3 (same site prior to upgrade) creating a Dynamic DropDown field with the correct fields.
![suitecrm-correct-fields-in-dynamic-dropdown](https://cloud.githubusercontent.com/assets/1320436/13354108/e438bf9e-dc66-11e5-9ab1-c2f9ef068928.PNG)

**Comment by mattlorimer** [comment] 2016-03-14 15:10
duplicate of #929

**Closed by mattlorimer** 2016-03-14 15:10 UTC
Labels: duplicate
