### ISSUE TITLE
Dashlet menu not working on 7.10.17

### ISSUE THREAD

**Issue by AdminPL** [salesagility/SuiteCRM#7709] opened 2019-08-12 13:25 UTC
#### Issue
Dashlet on main page don't work properly. Buttons next page, edit, refresh, close, etc. are not working. Checked both on my and demo installation.

#### Expected Behavior
Buttons should work

#### Actual Behavior
It doesn't work

#### Steps to Reproduce

1. go to :https://demo.suiteondemand.com/index.php?module=Home&action=index
2. Try making any changes

**Comment by Dillon-Brown** [comment] 2019-08-12 13:55
Hi @AdminPL, closing this as a duplicate of #7696 but thanks for reporting anyway! there's also a proposed fix here: #7697.

**Closed by Dillon-Brown** 2019-08-12 13:55 UTC
