### ISSUE TITLE
Email in 7.9.1: can't select Contacts/Leads/etc in From/CC/BCC field using Search

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#3733] opened 2017-06-16 14:15 UTC
#### Steps to Reproduce
1. Go to Emails, click Compose
2. Click one of the fields where addresses are expected: To, CC, BCC
3. A hovering toolbar appears to help you fill in the field. Click one of the target Types, for example contact or Leads
4. A pop-up appears for you to select a Contact. 
5. **working fine**: just click a Contact from the list, and his email will be added to the original field
6. Instead of doing the step above, you can trigger the **bug** like this: instead of clicking on the list, search for a name. At that very moment when you search, an error shows on the original window below. Note that you don't even have to select a contact, you just click `Search`.

#### Expected Behavior
Search should go on normally, no error given on the window underneath, and then a selection could be made.

#### Actual Behavior
Error shows on Compose Window underneath the pop-up, saying `Invalid email address`.

![invalidemail](https://user-images.githubusercontent.com/15945027/27230267-902e2936-52a6-11e7-833e-a833e8cff880.jpg)

#### Context
From this [forum thread](https://suitecrm.com/forum/suitecrm-7-0-discussion/14659-7-9-1-can-t-select-lead-contact-etc-for-email). Thanks to user `pstevens` for reporting and for the nice screenshot.

I would say this is **High Priority**.

#### Your Environment
* SuiteCRM Version used: both 7.9 and 7.9.1, on my test system and on the online demo
* Browser name and version: Firefox latest

**Comment by Mausino** [comment] 2017-06-18 22:20
Hi @pgorod we had same issue, but i have not time to report it.. here is message from my developer :)

"this is the description of the bug:

Issue:
When compose email and click an icon to select a contact/user/account from popup, if you just select an item from list it works.
But if you do a search first, then select an item from search results, doesn't works anymore.

Cause:
The problem is that when you click search button, the form is submitted and the page is reloaded. This means that the "beforeunload" event for popupWindow is already triggered, and is trying to process returned data, but is too early because there is no returned data from popup at this step.

Fix:
To fix this I've moved processing of returned data in another callback function.
Files changed:
/jssource/src_files/include/javascript/popup_helper.js
/modules/Emails/include/ComposeView/EmailsComposeView.js"

**Comment by oepl** [comment] 2017-07-11 13:23
Can u please explain me solution in detail? I am not getting what exact changes you did. 

Thanks in advance.

**Comment by mruch2** [comment] 2017-08-19 17:57
I am still getting the same error even with a repair rebuild. I have verified that the files are exactly the same as the published fixed ones here. I am on 7.9.3

**Comment by pstevens71** [comment] 2017-10-06 15:45
I can verify that this is still an issue on 7.9.6

**Comment by pgorod** [comment] 2017-10-06 15:48
@pstevens71 do you mean with, or without the fix proposed above?

**Comment by pstevens71** [comment] 2017-10-06 16:00
Without.  I just double checked the files in 7.9.6 and they don't contain the fix.  I'm updating them now to your proposed fix.  I'll post the result.  Thanks for getting back.

**Comment by pstevens71** [comment] 2017-10-06 16:12
So I applied the proposed fix.  It does get rid of the error when selecting a contact to send the email to.  However, the contact that is selected doesn't populate the "To:" field.

**Comment by pstevens71** [comment] 2018-03-14 19:04
This is still or should be an open issue.  Still a problem in 7.9.15

There are various threads for the same issue, but I can' t seem to find a solution.

**Comment by sanchezfauste** [comment] 2018-04-25 10:53
You can not also select a Document if you apply a custom search or navigate to next page. This is caused by:

https://github.com/salesagility/SuiteCRM/blob/a7d82492759dbfd66852a56195207acc913f4cd9/modules/Emails/include/ComposeView/EmailsComposeView.js#L794

As @Mausino has said.

**Closed** 2018-06-06 13:41 UTC
Labels: Medium Priority, Resolved: Next Release, bug, category:emails
