### ISSUE TITLE
More than 10 tabs in a views enters in a loop

### ISSUE THREAD

**Issue by SinergiaCRM** [salesagility/SuiteCRM#9445] opened 2022-01-21 16:13 UTC
If more than 10 tabs are added in a view and the 11th is clicked, the 1st one is showed. If the 12th is clicked, the 2nd one is showed. See the image:
![MoreThan10](https://user-images.githubusercontent.com/61022311/150560779-9caf513e-dbd1-4a44-9e0e-40803b80ee27.gif)

#### Issue
No more than 10 tabs are working in a view

#### Expected Behavior
Any number of tabs should work fine.

#### Actual Behavior
When the 11th is click, the first one is displayed

#### Possible Fix
A fix in the regex that compose the views.

#### Steps to Reproduce
1. Add more than 10 tabs to a view
2. Click on the 11th tab and check that the first one is displayed
3.
4.

#### Context
There are users that need to introduce several tabs for the correct usage of certain module. 

#### Your Environment
SuiteCRM Version used: Version 7.12.2
Browser name and version: Chrome Versión 97.0.4692.71 (Build oficial) (64 bits)
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 18.04

**Comment by johnM2401** [comment] 2022-01-21 16:17
Hey

Thanks for raising this!

I believe this may be a duplicate of: https://github.com/salesagility/SuiteCRM/issues/4122

I'll mark it as such, but please let us know if anything here differs

**Comment by SinergiaCRM** [comment] 2022-01-21 16:42
> Hey
> 
> Thanks for raising this!
> 
> For information's sake, I believe this may be a duplicate of: #4122
> 
> I'll mark it as such, but please let us know if anything here differs

That's right! Same Issue!

**Closed** 2022-03-02 11:06 UTC
Labels: Type:Bug, Type:Duplicate, Priority:Important
