### ISSUE TITLE
Email module very slow every time i open listView

### ISSUE THREAD

**Issue by adamjakab** [salesagility/SuiteCRM#4279] opened 2017-09-19 08:27 UTC
#### Issue
Every time I open listView (action=index) of the Email module (NEW) with a gmail account correctly configured, it takes about 15-25 seconds every time or when refreshing the page. It is as if it was checking for new mails every time. I have 'check E-mails every: 5 min' configuration option.

#### Expected Behavior
I would expect times similar to other modules.

#### Actual Behavior
taking this long to open the list of the email makes the module unusable.

#### Steps to Reproduce

1. fresh install 7.9.5
2. configure mail account
3. open:  index.php?module=Emails&action=index&parentTab=Tutto
4. refresh a few times

#### Your Environment
Versione 7.9.5
Sugar Versione 6.5.24 (Versione 509)

**Comment by thucar** [comment] 2017-09-21 03:36
It seems to be related to the number of e-mails in your mailbox. With 10 000 emails the load time was almost a minute. With 100 emails, it was just couple seconds.

**Comment by adamjakab** [comment] 2017-09-21 08:55
I had around 3000, which is in line with what you @thucar are saying - but the module is doing some extra work because in Accounts module I've got 23 000 records and when listing 150 (with filters) takes 1 second.

**Comment by Dillon-Brown** [comment] 2017-10-09 04:41
Duplicate of #4020

**Closed by Dillon-Brown** 2017-10-09 04:41 UTC
Labels: duplicate
