### ISSUE TITLE
Display html tags in Textfield

### ISSUE THREAD

**Issue by jobvector** [salesagility/SuiteCRM#1006] opened 2016-02-25 12:20 UTC
When I edit a Case, then fill the "Description" field and save, the Html tags <p>  </p> are displayed with.
![capture d ecran 2016-02-25 a 13 14 34](https://cloud.githubusercontent.com/assets/15199551/13319428/d8e53230-dbc1-11e5-9603-199acc48e542.png)
But work normaly with a modification with: "inline edition" option

Tested on SuiteCRM 7.5.1 clean install with Mozilla Firefox 43.0.3

**Comment by willrennie** [comment] 2016-03-01 15:25
Closing as a duplicate of issue #282

**Closed by willrennie** 2016-03-01 15:25 UTC
