### ISSUE TITLE
Pop up Reminder not working after upgrade to 7.4.3 from 7.3.1.

### ISSUE THREAD

**Issue by ecottles** [salesagility/SuiteCRM#811] opened 2015-12-21 23:05 UTC
Performed clean install v7.4.3 on Ubuntu 14.03 lts (LEMP stack) for testing. DB Timestamp is not being converted to user time zone. This problem does not exist  with v7.3.1

I will begin to isolate the problem by installing each version beginning with v7.3.1 and post the results as I progress
12/22 4:25pm
Just installed v7.3.1 on fresh Lemp stack. All is working as expected.
12/24 1:12pm
installed v7.3.2 on fresh Lemp stack. All is working as expected.
12/24 2:04pm
installed v7.4 on fresh Lemp stack. All is working as expected.
12/24 3:011pm
installed v7.4.1 on fresh Lemp stack. All is working as expected.
12/24 3:531pm
Installed v7.4.4 on fresh Lemp stack again. Problem persists with this version.:
          I am In timezone America/Los_Angeles. The popup reminder only works in timexzone UTC.       However, the emails are sent correctly in timezone  America/Los_Angeles

LJC

**Comment by TheFlyinGeek** [comment] 2016-01-29 02:38
Hi I'm also noticing issues regarding the user timezone. Particularly the way how calls are color coded in the Calls activity overview (due date past, due date today), this seems to be based on UTC timezone instead of user timezone.

I've posted an issue here: https://github.com/salesagility/SuiteCRM/issues/755

And also on the forums: https://suitecrm.com/forum/suitecrm-7-0-discussion/7875-tasks-calls-due-date-colors-based-on-gmt-instead-of-user-timezone

It seems like I'm the only one noticing this issue, so wonder if you experiencing the same on your end?

**Comment by KhyberPass** [comment] 2016-02-15 11:33
The original description of this issue is a duplicate of #766. Reminders only work correctly when the users time zone is UTC.

**Closed** 2016-03-16 12:39 UTC
Labels: Resolved: Next Release
