### ISSUE TITLE
Street addresses not showing in Detail View (Accounts, Contacts)

### ISSUE THREAD

**Issue by pgorod** [salesagility/SuiteCRM#4888] opened 2018-01-09 18:43 UTC
#### Issue
From [the forums](https://suitecrm.com/forum/installation-upgrade-help/17212-address-fields-not-displaying).

I tried both in `Accounts` module and `Contacts` module, didn't try anywhere else.

`Primary address` and `Alternative address` don't show in Detail view. The data is there, and you can work with it in Edit view and in inline edit.

#### Environment

* Browser name and version: Firefox 56

* Doesn't work on SuiteCRM 7.9.8 on the live demo

* Does work fine on my test system with 7.10 Beta 3 (I wonder why?).

**Comment by pgorod** [comment] 2018-01-09 18:44
If somebody can test on the latest 7.8 that would be important - this is quite critical and let's hope the bug didn't sneak in to our LTS.

**Comment by Dillon-Brown** [comment] 2018-01-10 09:06
@pgorod Duplicate of #4868

**Closed by Dillon-Brown** 2018-01-10 09:06 UTC
Labels: duplicate
