### ISSUE TITLE
HTML tags not interpreted in quote after update to 7.8.31

### ISSUE THREAD

**Issue by hubyhuby** [salesagility/SuiteCRM#7710] opened 2019-08-12 14:16 UTC
With suite crm 7.8.20 and before I could export my quotation to PDF including HTML fields.

#### Issue
with 7.8.31 the html fields are not interpreted. You get the RAW HTML inside your PDF.

#### Expected Behavior
Get a proper quote as with previous version of suitecrm 7.8.x.

#### Steps to Reproduce
1.Update to 7.8.31
2. Create a quotea custom HTML field; for example the explaination of your quote.
3.Export the quote to PDF
4. See the results :
![image](https://user-images.githubusercontent.com/26340942/62871819-77505c80-bd1c-11e9-9752-e84129d4cfb4.png)

#### Context
Trying to do business with suitecrm ;)
Like sending a quote.

#### Your Environment
* SuiteCRM Version used: 7.8.31 
* Browser name and version Firefox latest
* Environment name and version (e.g. MySQL, PHP 7): PHP 7 mysql 
* Operating System and version (e.g Ubuntu 16.04):Ubuntu 16.04

**Comment by Dillon-Brown** [comment] 2019-08-12 14:24
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Closed by Dillon-Brown** 2019-08-12 14:24 UTC

**Comment by hubyhuby** [comment] 2019-08-12 14:29
Dear @Dillon-Brown ,
Thanks for your prompt answer... 
I understand End Of Life of 7.8.x ... What I don t understand is regression such as this one just for the last update .... It doesn't make me want to go for 7.10 .... But to go back to previous versions .... sadly...

**Comment by hubyhuby** [comment] 2019-08-12 14:31
Moreover this seems to be  a regression, I remember this bug being corrected previously (if it is the same bug).

**Comment by hubyhuby** [comment] 2019-08-12 14:37
Looks like this guy is back:
https://github.com/salesagility/SuiteCRM/issues/241
I ll try the fixe on this version of suitecrm ...

**Comment by Dillon-Brown** [comment] 2019-08-12 14:40
Interestingly enough I couldn't actually replicate this in 7.8.31. Quotes into PDFs seem to work correctly for me. Maybe customisations?

**Comment by hubyhuby** [comment] 2019-08-12 15:09
I have no custom code there, just a custom html field done with the suite crm studio .

Ok I have applied the same patch as explained here and it works aswell on 7.8.31 :
https://github.com/ApatheticCosmos/SuiteCRM/blob/aac97a311ddb4e8fcb24d693c5e
Please include the patch in 7.X

For the next time I update my suitecrm, I copy the code of the file here :  

<?php
/**
 * Products, Quotations & Invoices modules.
 * Extensions to SugarCRM
 * @package Advanced OpenSales for SugarCRM
 * @subpackage Products
 * @copyright SalesAgility Ltd http://www.salesagility.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author Salesagility Ltd <support@salesagility.com>
 */
class templateParser
{
    static function parse_template($string, $bean_arr)
    {
        foreach ($bean_arr as $bean_name => $bean_id) {
            $focus = BeanFactory::getBean($bean_name, $bean_id);
            $string = templateParser::parse_template_bean($string, $focus->table_name, $focus);
            foreach ($focus->field_defs as $focus_name => $focus_arr) {
                if ($focus_arr['type'] == 'relate') {
                    if (isset($focus_arr['module']) && $focus_arr['module'] != '' && $focus_arr['module'] != 'EmailAddress') {
                        $idName = $focus_arr['id_name'];
                        $relate_focus = BeanFactory::getBean($focus_arr['module'], $focus->$idName);
                        $string = templateParser::parse_template_bean($string, $focus_arr['name'], $relate_focus);
                    }
                }
            }
        }
        return $string;
    }
    function parse_template_bean($string, $key, &$focus)
    {
        global $app_strings, $sugar_config;
        $repl_arr = array();
        foreach ($focus->field_defs as $field_def) {
            if (isset($field_def['name']) && $field_def['name'] != '') {
                $fieldName = $field_def['name'];
                if ($field_def['type'] == 'currency') {
                    $repl_arr[$key . "_" . $fieldName] = currency_format_number($focus->$fieldName, $params = array('currency_symbol' => false));
                } else if (($field_def['type'] == 'radioenum' || $field_def['type'] == 'enum' || $field_def['type'] == 'dynamicenum') && isset($field_def['options'])) {
                    $repl_arr[$key . "_" . $fieldName] = translate($field_def['options'], $focus->module_dir, $focus->$fieldName);
                } else if ($field_def['type'] == 'multienum' && isset($field_def['options'])) {
                    $mVals = unencodeMultienum($focus->$fieldName);
                    $translatedVals = array();
                    foreach($mVals as $mVal){
                        $translatedVals[] = translate($field_def['options'], $focus->module_dir, $mVal);
                    }
                    $repl_arr[$key . "_" . $fieldName] = implode(", ", $translatedVals);
                } //Fix for Windows Server as it needed to be converted to a string.
                else if ($field_def['type'] == 'int') {
                    $repl_arr[$key . "_" . $fieldName] = strval($focus->$fieldName);
                } else if ($field_def['type'] == 'image') {
                    $secureLink = $sugar_config['site_url'] . '/' . "public/". $focus->id .  '_' . $fieldName;
                    $file_location = $sugar_config['upload_dir'] . '/'  . $focus->id .  '_' . $fieldName;
                    // create a copy with correct extension by mime type
                    if(!file_exists('public')) {
                        sugar_mkdir('public', 0777);
                    }
                    if(!copy($file_location, "public/{$focus->id}".  '_' . "$fieldName")) {
                        $secureLink = $sugar_config['site_url'] . '/'. $file_location;
                    }
                    $link = $secureLink;
                    $repl_arr[$key . "_" . $fieldName] = '<img src="' . $link . '" width="'.$field_def['width'].'" height="'.$field_def['height'].'"/>';
                } else if ($field_def['type'] == 'wysiwyg') {
                    $repl_arr[$key . "_" . $field_def['name']] = html_entity_decode($focus->$field_def['name'], ENT_COMPAT, 'UTF-8');
                    $repl_arr[$key . "_" . $fieldName] = html_entity_decode($focus->$fieldName, ENT_COMPAT, 'UTF-8');
                } else {
                    $repl_arr[$key . "_" . $fieldName] = $focus->$fieldName;
                }
            }
        } // end foreach()
        krsort($repl_arr);
        reset($repl_arr);
        foreach ($repl_arr as $name => $value) {
            if (strpos($name, 'product_discount') > 0) {
                if ($value != '' && $value != '0.00') {
                    if ($repl_arr['aos_products_quotes_discount'] == 'Percentage') {
                        $sep = get_number_seperators();
                        $value = rtrim(rtrim(format_number($value), '0'), $sep[1]);//.$app_strings['LBL_PERCENTAGE_SYMBOL'];
                    } else {
                        $value = currency_format_number($value, $params = array('currency_symbol' => false));
                    }
                } else {
                    $value = '';
                }
            }
            if ($name === 'aos_products_product_image' && !empty($value)) {
                $value = '<img src="' . $value . '"width="50" height="50"/>';
            }
            if ($name === 'aos_products_quotes_product_qty') {
                $sep = get_number_seperators();
                $value = rtrim(rtrim(format_number($value), '0'), $sep[1]);
            }
            if ($name === 'aos_products_quotes_vat' || strpos($name, 'pct') > 0 || strpos($name, 'percent') > 0 || strpos($name, 'percentage') > 0) {
                $sep = get_number_seperators();
                $value = rtrim(rtrim(format_number($value), '0'), $sep[1]) . $app_strings['LBL_PERCENTAGE_SYMBOL'];
            }
            if ($focus->field_defs[$name][dbType] == 'datetime' &&
                (strpos($name, 'date') > 0 || strpos($name, 'expiration') > 0) ) {
                if ($value != '') {
                    $dt = explode(' ', $value);
                    $value = $dt[0];
                }
            }
            if ($value != '' && is_string($value)) {
                $string = str_replace("\$$name", $value, $string);
            } else if (strpos($name, 'address') > 0) {
                $string = str_replace("\$$name<br />", '', $string);
                $string = str_replace("\$$name <br />", '', $string);
                $string = str_replace("\$$name", '', $string);
            } else {
                $string = str_replace("\$$name", '&nbsp;', $string);
            }
        }
        return $string;
    }
}
?>

**Comment by hubyhuby** [comment] 2019-08-12 15:12
The patch seems to apply a "if wysiwig "
https://github.com/salesagility/SuiteCRM/pull/5989/files
Which I can confirm is not applied in 7.8.31

**Comment by Dillon-Brown** [comment] 2019-08-12 15:14
@hubyhuby Ahhh ok I think I understand this now. So the fix is for a third part WYSIWYG field? that would explain why it was moved to Trello (A suggestion board as opposed to being a core SuiteCRM bug).

It looks like the decision was made not to merge in this fix in on it's own here: https://github.com/salesagility/SuiteCRM/pull/5989#issuecomment-447878750

**Comment by hubyhuby** [comment] 2019-08-13 06:43
Hi @Dillon-Brown ,
Thanks a lot for referring to this bug. It is exactly what I have.
I must say I am not in the code, and I don t understand why it is not merged... You can set custom HTML field in the back office of Suite crm, but you need to apply manually a fix to have it in your quote .... and this fix is not merged .... Whereas ALL other fields in a quote template are HTML and interpreted in the quote...
For example this will be interpreted :
![image](https://user-images.githubusercontent.com/26340942/62920523-53395d80-bda6-11e9-8668-2cfa2782b584.png)

But not my custom field....

**Comment by hubyhuby** [comment] 2019-08-13 06:46
Bottom line the fix as been reported to work with 7.10. So I guess we still have a workaround for now

**Comment by Dillon-Brown** [comment] 2019-08-13 09:58
@hubyhuby I believe the rationale behind not merging this fix is that it requires a core change that checks for a third party addon field 'wysiwyg' when you could instead make a customisation that doesn't require a core change.
