### ISSUE TITLE
Download PDF issue in AOR 

### ISSUE THREAD

**Issue by Mausino** [salesagility/SuiteCRM#1196] opened 2016-04-04 12:46 UTC
When you are using condition as parameter, after filter the records the button Download PFD does not work correctly (we can't download the pdf)

When you load report on detailview first time, it is woking (download pdf) but after used paramerer not.

and many times we have the issue when we edited AOR record and after save button (in editview) the download button again did not work (on detailview)

![reports_crm](https://cloud.githubusercontent.com/assets/5773777/14248310/32505338-fa74-11e5-89d8-c3e63e67f690.png)

**Comment by CaptainChainsaw** [comment] 2016-04-05 15:08
@Mausino What version of SuiteCRM are you experiencing this issue on?

**Comment by Mausino** [comment] 2016-04-06 08:23
Hi, it was latest version of SuiteCRM 7.5.3.  We updated from 7.4.3.  

I want test it on official demo of SuiteCRM but can't (the screenshot from today 6/april/2016)

![suitecrm_demo](https://cloud.githubusercontent.com/assets/5773777/14310300/87025552-fbe1-11e5-870f-a3b49522f853.png)

**Comment by CaptainChainsaw** [comment] 2016-04-06 12:34
This appears to be a regression of this issue:

https://github.com/salesagility/SuiteCRM/issues/201

**Comment by Mausino** [comment] 2016-04-07 09:25
Ok, i tested on SuiteCRM Version 7.5.2 demo official site and same issue occurred

![2016-04-07_1120_github](https://cloud.githubusercontent.com/assets/5773777/14346644/62fae1d8-fcb3-11e5-833b-69688ea12d58.png)

**Comment by mattlorimer** [comment] 2016-04-15 18:52
duplicate of #1056

**Closed by mattlorimer** 2016-04-15 18:52 UTC
Labels: duplicate
