### ISSUE TITLE
Install exists with error - Audit has no table name, mysql query fails

### ISSUE THREAD

**Issue by kentora** [salesagility/SuiteCRM#8820] opened 2020-07-14 21:01 UTC
#### Issue

SuiteCRM cannot install - Mysql query fails. Install log says ```processing table  ``` - i.e. empty table name.
modules/Audit/vardefs.php contains an empty array, so I guess it makes sense that it happens...

#### Expected Behavior

Installation should be succesfull, and I guess a table for audit should be created, although I'm not sure

#### Actual Behavior

Installation fails

#### Possible Fix

Either make sure table is not processed for audit, or fix the definition

#### Steps to Reproduce

1. Install either latest or LTS version (only ones I have checked) of SuiteCRM
2. After putting in details about user and db, view the install.log
3. Everything is fine until an empty table name is processed, and nothing further happens
4.

#### Context

I cannot install

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):
I don't think this is relevant, since the source code reveals the bug.

**Comment by kentora** [comment] 2020-07-14 21:04
Might be fixed with #8689 - but that is only to the hot fix branch. Problem is also present on master

**Comment by chris001** [comment] 2020-07-14 21:19
If this is a bug in the installer, Travis-CI should have detected it...?

**Comment by kentora** [comment] 2020-07-15 05:43
I'm starting to suspect that this might be an issue when running with MySQL instead of MariaDB? I'm getting other errors after implementing a workaround to test...

**Comment by pgorod** [comment] 2020-07-15 09:22
I think this is a duplicate of #8688. 

#8689 probably fixes this, and @kentora whatever goes into `hotfix-7.10.x` will go into `master` also.

**Closed** 2020-07-16 20:14 UTC
