### ISSUE TITLE
Bug in admin panel>outgoing email - with french version

### ISSUE THREAD

**Issue by maverick983** [salesagility/SuiteCRM#4211] opened 2017-09-06 13:15 UTC
#### Issue
I got a javascript error message when I load admin panel, then I choose "outgoing email" menu

#### Expected Behavior
protect the simple quotes

Here is the code with the error

if (f.mail_sendtype.value == "SMTP") {
		addToValidate('ConfigureSettings', 'mail_smtpserver', 'varchar', 'true', 'Serveur de messagerie SMTP :');
		addToValidate('ConfigureSettings', 'mail_smtpport', 'int', 'true', 'Port SMTP :');
		if (f.mail_smtpauth_req.checked) {
			addToValidate('ConfigureSettings', 'mail_smtpuser', 'varchar', 'true', **'Nom d'utilisateur :');**
			addToValidate('ConfigureSettings', 'mail_smtppass', 'varchar', 'true', 'Mot de passe :');
		}
	}

**Comment by pgorod** [comment] 2017-09-07 15:10
Thanks for the bug report, but it would be nicer if you had filled the template... you don't even say something as basic as the SuiteCRM version!...

And in which file did you find that code? Or is it javascript collected from the browser?

**Comment by Dillon-Brown** [comment] 2017-09-07 23:43
@maverick983 Unable to replicate on 7.9.5, please provide SuiteCRM version, browser, etc. Thanks.

**Comment by maverick983** [comment] 2017-09-08 06:25
Hi, 
ok sorry, that was my first message, I'll do better next time.
So, my version 7.9.4, module FR language
Browser : Google Chrome
and I saw this message with Google chrome console.
I don't know the filename

Thanks for your help

**Comment by pgorod** [comment] 2017-09-08 08:24
Thanks @maverick983.

The place in the code seems to be here
https://github.com/salesagility/SuiteCRM/blob/master/modules/EmailMan/Forms.php#L142

**Comment by Dillon-Brown** [comment] 2017-09-15 11:51
Duplicate of #3056.

**Closed by Dillon-Brown** 2017-09-15 11:51 UTC
Labels: duplicate
