### ISSUE TITLE
Printing with theme Suite R shows URL instead of text

### ISSUE THREAD

**Issue by certinet** [salesagility/SuiteCRM#1815] opened 2016-07-28 20:00 UTC
#### Issue
Using the Print button at the bottom, with Suite R gives URL of data instead of data itself

#### Expected Behavior
Should give only data

#### Actual Behavior
Gives URL path

#### Possible Fix
Possible correction in Style.css but wasn't able to make it work

#### Steps to Reproduce
1. Use Print button with any modules
2. Will display URL instead of data
3.
4.

#### Context
Can't print document

#### Your Environment
* SuiteCRM Version used:Version 7.6.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest
* Environment name and version (e.g. MySQL, PHP 7):PHP Version 5.4.42,mysqlnd 5.0.10
* Operating System and version (e.g Ubuntu 16.04): Windows 10 Pro

**Comment by Mausino** [comment] 2016-07-29 07:17
I think, it's duplicate of #1338

**Comment by ijdavie** [comment] 2016-08-12 13:54
This does appear to be a duplicate of this issue.

**Closed by ijdavie** 2016-08-12 13:54 UTC
Labels: duplicate
