### ISSUE TITLE
Issues with test suite 

### ISSUE THREAD

**Issue by dsivam** [salesagility/SuiteCRM#4583] opened 2017-11-24 14:06 UTC
Hi All,

We are running an instance of SuiteCRM (version 7.8.6), and are running the test suite as part of our build pipeline. The output is below:

![tests](https://user-images.githubusercontent.com/33959846/33213546-e5b16aa6-d11f-11e7-8fa5-fc270cb56e1e.png)

This is consistent with the output of the tests that you run on your travis pipeline. 

Are the failures currently occurring known issues, and will they be fixed in later versions?
The suite also errors out at around 85% of the way through the tests - do we know why this might be happening?

**Comment by PedroErnst** [comment] 2017-11-28 08:57
I've experienced the same problem with the suite exiting at the same location, the problem seems to be that in SavedSearchTest.php the following two functions end up calling SugarApplication::redirect(), which in turns echo's that bit of JS and then calls exit(), terminating phpunit. 

SavedSearchTest::returnSavedSearch()
SavedSearchTest::returnSavedSearchContents()

Commenting out those two methods gets the suite to complete.

**Comment by Dillon-Brown** [comment] 2019-08-02 15:22
We haven’t been able to replicate this issue in any newer version of SuiteCRM such as 7.10.x or 7.11.x. This issue has been closed as version 7.8.x of SuiteCRM has reached its end of life and therefore will no longer be receiving updates. If you feel this issue is still present in the supported versions please leave a comment explaining the steps to reproduce and we'll re-open this issue.

For more information about 7.8.x end of life please visit our [blog post](https://suitecrm.com/7-8-x-end-of-life/)

**Closed by Dillon-Brown** 2019-08-02 15:22 UTC
Labels: Low Priority, bug
