### ISSUE TITLE
Problem with Role Permission Update for all modules

### ISSUE THREAD

**Issue by kpcool** [salesagility/SuiteCRM#6928] opened 2019-02-11 06:35 UTC
I am facing problem with Bulk update of the Role Permission.

With standard install of 7.11.1 SuiteCrm, this problem is there.

The Commit for Fixed #3319 
 https://github.com/salesagility/SuiteCRM/commit/b4d3b23f011d076007bc7791a9a4df10feee29dd#diff-87bfc2fbbed017ab9b98568a2ae08001 has introduced this bug.

I have added the comment for line 150. Basically, the update has removed the class name due to which the javascript for bulk update is failing. Please add a fix for this in mainline.

I have tested it locally and it is working fine with this update.

` <select class='{$ACTION_NAME}' name='act_guid{$ACTION.id}' id = 'act_guid{$ACTION.id}' onblur="document.getElementById('{$ACTION.id}link').innerHTML=this.options[this.selectedIndex].text; aclviewer.toggleDisplay('{$ACTION.id}');" >`

Just class='{$ACTION_NAME}' as shown above and bulk update will work fine. For anyone else, if you want to make this change on your server, you will have to update the smarty cache file as well

**Comment by pgorod** [comment] 2019-02-11 11:25
Duplicate of #6778

**Closed** 2019-02-11 17:23 UTC
Labels: duplicate

**Comment by pgorod** [comment] 2019-02-11 17:40
@kpcool thanks for your report anyway - I left a note in the other Issue saying that you have a proposed fix here, that should be useful. Thanks
