### ISSUE TITLE
maxColumn being ignored on front end

### ISSUE THREAD

**Issue by digitalmcgrath** [salesagility/SuiteCRM#6495] opened 2018-11-14 14:09 UTC
#### Issue
When I set maxColumn to 3, the front end of SuiteP is ignoring it. I can drag and drop the 3rd column on the layout in studio, but it just wraps around on the front end.

#### Expected Behavior
The fields should be in 3 columns on the same line.

#### Actual Behavior
The third field wraps around to the next line.

#### Steps to Reproduce
1. Edited custom/modules/Accounts/metadata/detailviewdefs.php and changed maxColumn to 3
2. Added the third column to the widths array and made sure the value was less than 100 for all 3 combined.
3. Quick repair / rebuild
4. Added a third column to the detail view layout in studio.

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 70.0.3538.102 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.2.8, MySQL 5.7.23
* Operating System and version (e.g Ubuntu 16.04): Mojave running MAMP.

**Comment by samus-aran** [comment] 2018-11-30 15:33
Duplicate of https://github.com/salesagility/SuiteCRM/issues/3310

**Closed by samus-aran** 2018-11-30 15:33 UTC
Labels: duplicate
