### ISSUE TITLE
Sending email uses system account even when not desired or configured

### ISSUE THREAD

**Issue by TitaniumCoder477** [salesagility/SuiteCRM#3856] opened 2017-07-09 21:36 UTC
#### Issue
Fresh deployment of version Version 7.9.2 Sugar Version 6.5.24 (Build 509).
Setup system email but did not opt o make available to users.
Setup two user accounts.
Logged into user accounts and setup custom outgoing mail server. Also setup incoming mailboxes and chose custom outgoing mail server.
When users send email, they see expected account. But recipient gets email From system address but Reply to sender.

#### Expected Behavior
The recipient should see the From Address specified for each user.

#### Actual Behavior
No matter what settings I chose, the recipient always sees the system email as the From Address, instead of the From Address specified for each user under the user's Outgoing Email.

All the above are Gmail accounts.

To further test the symptom, I changed the system account to use one of my ISP mailboxes but left the user accounts all Gmail. Now when I test sending email from a user's account, I get an error--possibly because it is trying to send out over the system account (ISP) but using the user's account (Gmail) which obviously will fail.

#### Possible Fix
Not sure

#### Steps to Reproduce
1. Configure system account; Admin > Email Settings > Outgoing Mail Configuration and test OK
2. Create two users and log into their accounts
3. Under each user, configure an Outoing SMTP Mail Server; Profile > Settings > Mail Accounts > Outgoing SMTP Mail Servers > Add
4. Then under each user, configure Mail Account; Profile > Settings > Mail Accounts > Mail Accounts > Add and under Outgoing Email section choose server created in step 3 above
5. From each user, send an email; Activities > Emails > Compose > ... > Send
6. Log into recipient mailbox and confirm; result that I am getting is:

FROM: whatever email I used in step 1 above
REPLY: the user's email in step 4 above

#### Context
This bug unfortunately is a make or break for my deployment.
High priority

#### Your Environment
* SuiteCRM Version used: Version 7.9.2 Sugar Version 6.5.24 (Build 509)
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): apache2 mariadb-server php7.0 php7.0-mysql php7.0-gd php7.0-curl php7.0-imap libapache2-mod-php7.0 php7.0-mcrypt php7.0-xml php7.0-json etc
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

**Comment by sergio91pt** [comment] 2017-07-09 22:52
Seems like a duplicate of #3645

**Comment by TitaniumCoder477** [comment] 2017-07-09 23:27
Yep, that is exactly the issue! I'm sorry that I didn't see that when I
searched for another record of the bug. So glad there's a fix! Thank you!!

**Closed** 2017-07-10 08:50 UTC
Labels: duplicate
