### ISSUE TITLE
Suite P Calendar Dashlet - Scroll function missing in Chrome

### ISSUE THREAD

**Issue by mjrcrm** [salesagility/SuiteCRM#2875] opened 2017-01-09 10:21 UTC
Details:

Browser: Latest version of Chrome
SuiteCRM 7.7.9
Theme: Suite P

Installed calendar dashlet.

The ability to move forward or backward by a day or week is missing. This functionality is present in the other 2 themes.

The above was duplicated in the current SuiteCRM demo.

Please advise of a fix.

**Comment by staganyi** [comment] 2017-01-09 17:54
I believe this is the same issue as #2783

**Comment by mjrcrm** [comment] 2017-01-09 19:51
Correct, the issues are the same.

 

I apologize for the duplication.

 

 

 

Regards,

 

Martin

**Comment by shogunpol** [comment] 2017-01-10 08:31
@mjrcrm  - Thank you for highlighting this issue, however, this is a duplicate of issue #2783. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2017-01-10 08:31 UTC
