### ISSUE TITLE
"Create Person Form" in Suite7 theme is missed up.

### ISSUE THREAD

**Issue by tjaafar** [salesagility/SuiteCRM#2712] opened 2016-11-26 22:46 UTC
#### Issue
When you go to "Create Person Form", the 1st and 2nd columns/boxes do not appear.  Just their labels appear.

#### Expected Behavior
The screen should 2 columns/boxes, where user can drop the field names.

#### Actual Behavior
No boxes appear to drop fields into them.

#### Possible Fix
No sure... but probably there is a missing CSS class for both columns.

#### Steps to Reproduce
Marketing => Campaings => Create Person Form.

#### Context
I was trying to create a web-to-lead form.
High priority

#### Your Environment

* SuiteCRM Version used: 7.7.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): 5.3
* Operating System and version (e.g Ubuntu 16.04):  Windows 8

**Comment by shogunpol** [comment] 2016-11-28 09:43
@tjaafar , the issue has been tested on recent version of SuiteCRM(7.7.8), and not appear,
can you provide screenshots of an issue?

**Comment by tjaafar** [comment] 2016-11-28 12:54
![ss-create-person-form](https://cloud.githubusercontent.com/assets/7531735/20669018/3e8db852-b58b-11e6-9a2e-099830bf4094.png)

Please find a screenshot attached.  I've upgrade it to 7.7.8, but it's still showing the same issue.

**Comment by dursuntosun** [comment] 2016-11-29 05:21
I opened a ticket about this issue before, #2474

**Comment by shogunpol** [comment] 2016-11-29 08:18
(tag and Close issue)
@tjaafar  - Thank you for highlighting this issue, however, this is a duplicate of issue #2474. This is issue will be closed, please follow the original issue.

**Closed by shogunpol** 2016-11-29 08:18 UTC
