### ISSUE TITLE
Outbound Email Accounts, Password don't save

### ISSUE THREAD

**Issue by hilbaONE** [salesagility/SuiteCRM#6797] opened 2019-01-22 12:36 UTC
#### Issue

I cant send eMails with an outbound Email Account, although I can send a test mail without any problems.

#### Expected Behavior

It should be posible to send eMails.

#### Actual Behavior

I can't send an email. See also #4057 and #3841 or https://suitecrm.com/suitecrm/forum/bug-tracker/1266-smtp-not-working

#### Steps to Reproduce

1. ADMIN->EMAIL->Create Outbound Email Account
2. I set a new Account. Send a Testmail and it works fine.
3. Save it and edit it again, now the testmail fails. (An email error occurred:SMTP Error: Could not authenticate.)
4. Also sending eMails from eMail module doesn't work

#### Your Environment

* SuiteCRM Version used: 7.11.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Opera, IE11
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by Mausino** [comment] 2019-01-22 13:42
@hilbaONE is my comment same as you wrote in your issue description?

**Comment by hilbaONE** [comment] 2019-01-22 13:51
@Mausino Yes. I get no error when using the default SMTP account either. (in eMail module)

**Comment by Dillon-Brown** [comment] 2019-01-23 09:39
I think this is a duplicate of #6766 which has a proposed fix.

**Comment by hilbaONE** [comment] 2019-01-23 13:07
@Dillon-Brown I don't think so. In the database the port is stored correct (587 and not 5.87).

**Comment by Dillon-Brown** [comment] 2019-08-02 10:44
I'm unable to replicate this issue on hotfix or latest LTS. Please let me know if this is still an issue you can replicate and we will investigate further. Thanks.

**Closed by Dillon-Brown** 2019-08-02 10:44 UTC
Labels: Medium Priority, bug
