### ISSUE TITLE
Doesn't save email address in the contact in SuiteCRM 7.8.2

### ISSUE THREAD

**Issue by caspervzla** [salesagility/SuiteCRM#3367] opened 2017-04-06 16:17 UTC
When you create a new contact and wrote a email address and click on save, the contact is saving but in the email address is empty

#### Issue

You go: Contacts-->Create Contact.
Complete the field include the email address.
Click on Save.
All fields were saved except email address

I go to the database and I saw the contact in the contacts table but didn't create the email address in the email_addresses table.

#### Steps to Reproduce

1. Contacts-->Create Contact
2. Complete mandatory fields and email address
3. Save the Contact
4. View the Contact and you can see the email address in empty status

#### Context

I can't include new contacts in email campaings

high priority

#### Your Environment

* SuiteCRM Version used: 7.8.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 57.0.2987.133
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.5, PHP 5.3.8
* Operating System and version (e.g Ubuntu 16.04): Windows Server 2008 R2

**Comment by horus68** [comment] 2017-04-06 17:31
Could it be the email is already in use in your suiteCRM?

I had no trouble to create a new contact in the demo site https://suitecrm.com/demo
![contacto](https://cloud.githubusercontent.com/assets/3055443/24767477/01da68ac-1af7-11e7-94f4-75509180d38c.PNG)

**Comment by chris001** [comment] 2017-04-07 01:34
@horus it's not because of duplicate contact.  When you try to Create Contact with the same email as an existing contact, on the demo site, it says this message: 
```
The contact record you are about to create might be a duplicate of a contact record that already exists. Contacts records containing similar names are listed below. Click Save to continue creating this new contact, or click Cancel to return to the module without creating the contact
```
This is obviously a bug.   @caspervzla you should provide the PHP error text from your `sugarcrm.log` around the time you were saved the Contact.

**Comment by samus-aran** [comment] 2017-04-07 09:35
@chris001  Why is that a bug that it looks for duplication of email address?

I went into demo and created a new contact using same email address in the system: sales.vegan@example.it

It took me to the duplication screen (as expected) - I click Save (since I know its a duplication but I don't care) and the Contact saved correctly with the email address.

**Comment by caspervzla** [comment] 2017-04-07 13:03
Hi,

You're right in the demo site work perfectly... I will see in my configuration, Maybe I have a Theme problem... Look the follow captures:

Step 1.- Create the contact with the mandatory fields. 

![picture1](https://cloud.githubusercontent.com/assets/26972559/24800945/33ff3bfe-1b70-11e7-82e3-50132e9c9d23.png)


Step 2.- I wrote the email address. Please look that the email address option (primary, Opted Out & Invalid) is not present.. Maybe a problem with the theme?

![picture2](https://cloud.githubusercontent.com/assets/26972559/24800973/531413c0-1b70-11e7-9d1b-db564b3dbc7a.png)

Step 3.- I saved the contact, and you can see the email address field is empty

![picture3](https://cloud.githubusercontent.com/assets/26972559/24801078/b7263a78-1b70-11e7-92e9-cb92010bb0e1.png)


## **WORKAROUND:**

After create the contact, I edit in-line the email field, see capture:

![picture4](https://cloud.githubusercontent.com/assets/26972559/24801115/dd6b3d1e-1b70-11e7-9397-52f15af0b627.png)

![picture5](https://cloud.githubusercontent.com/assets/26972559/24801121/e1c0f3e0-1b70-11e7-8613-6bc3448bfadd.png)


I'm researching... Thanks for your posts

**Comment by chris001** [comment] 2017-04-07 13:21
@samus-aran I didn't say it clearly, what I meant is, the app's working correctly on the demo system, it warns you of the possible duplicate Contact and asks you to confirm that's what you want to do.  Yet on @caspervzla 's instance, when you enter a non-duplicate Contact, it fails to save the email address, and doesn't tell you that it had a problem saving anything, when it should've given a warning popup.

**Comment by horus68** [comment] 2017-04-07 15:35
@caspervzla "email address option" are not present so it must be an error on your installation.
Maybe this should be in the forum to get personal help.
You should perform a quick rebuild, verify your permissions, clean up chache from browser and suiteCRM.

**Comment by caspervzla** [comment] 2017-04-07 15:45
Thanks @horus68 ... Resolve it with the clean up cache. You're right my mistake include this issue here, I should have tried the demo site first, and then use the forum.... My apologies!

**Comment by samus-aran** [comment] 2017-04-07 16:29
@chris001 - I may have misread your comment also. No worries.

@caspervzla - Great that you have got it resolved.  I will close this issue.

**Closed by samus-aran** 2017-04-07 16:29 UTC
Labels: Pending Input

**Comment by chris001** [comment] 2017-04-07 19:53
Personally I, and most others, still consider this an unresolved bug. The app needs to popup an onscreen error message to the user admitting that it had a problem saving the record.

Better yet, the app should realize that an error occurred while saving the record, and attempt to fix the situation by silently triggering a clear of the cache quick rebuild, and attempt to save the record again.

Silently failing and then blaming the user saying they should have known better for not clearing the cache and doing a quick rebuild, is unsatisfactory in this day and age, when the software can and should auto detect and fix its environment by itself.

**Comment by horus68** [comment] 2017-04-08 17:07
@chris001 You got a point here. Now the thing is, how to reproduce this and what checks need to be implemented in the different forms when saving fields?

**Comment by chris001** [comment] 2017-04-08 23:17
@horus68 It's not having to do with implementing checks, or different forms, or while saving.  The entire application is wrong, it doesn't handle errors.  Whenever it hits an error, it silently stops.  This is wrong, it should never just silently stop!  I've designed a code module to fix this.

**Comment by horus68** [comment] 2017-04-10 12:27
@chris001 hope to see it implemented. Is it ready yet to be tested?

**Comment by chris001** [comment] 2017-04-10 23:37
@horus68  Not yet, should be soon.  The way errors are being handled in Sugar 6.5 is solidly stuck in 2004 and hasn't been updated to better software in about 13 years - about 100 human years.  Sugar 7.x has adopted the latest and greatest open source system wide upgrades 5 years ago, now it's time for SuiteCRM to do the same.  Users and customers will be delighted.
